"""Shared GateContext fixtures for orchestrator and dispatch tests."""

from __future__ import annotations

from agentic_core.L5_safety.runtime_gates import GateContext


def clean_ctx() -> GateContext:
    """A GateContext that is ALLOW-clean across the full mesh.

    Tuned against the actual gate implementations in this package; see each
    ``gNN_*.py`` for the exact fields read.
    """
    return GateContext(
        request_id="req-1",
        session_id="sess-1",
        trace_root="trace-1",
        tenant_id="tenant-A",
        policy_hash="pol::v1",
        compliance_hash="comp::v1",
        blueprint_hash="bp::v1",
        risk_tier="low",
        impact_class="read",
        reversible=True,
        intent={
            "objective": "summarize doc",
            "deliverable": "1-page summary",
            "ask_form": "answer_only",
            "raw_text": "please summarize this document",
            "payload_bytes": 1024,
            "safety_risk_class": "low",
            "impact_class": "read",
        },
        caller_scope_baseline={"tenant_id": "tenant-A", "session_id": "sess-1"},
        hitl={"review_requested": True, "verdict": "approve", "latency_ms": 100},
        route_contract={
            "id": "R3",
            "signed": True,
            "complete": True,
            "confidence": 0.95,
            "known": True,
            "deterministic": True,
        },
        retrieval_plan={
            "required": False,
            "mode": "answer_only",
            "blocked_sources": [],
            "k": 5,
            "results_count": 0,
        },
        evidence={
            "required": False,
            "sources": ["doc-1"],
            "source_ids": ["doc-1"],
            "source_resolution_ok": True,
            "contradictions": 0,
            "support_score": 1.0,
            "coverage": 1.0,
            "cited_spans": ["doc-1#p1"],
            "all_sources_resolvable": True,
        },
        prompt_packet={
            "slot_order_valid": True,
            "unknown_slots": [],
            "token_count": 100,
            "budget": 4000,
            "schema_bound": True,
            "manifest_hash": "mh::v1",
            "hmac_valid": True,
        },
        tool_call={
            "tool_name": "noop",
            "tool_approved": True,
            "model_id": "m1",
            "model_approved": True,
            "registry_digest": "rd::v1",
            "args_valid": True,
            "args_schema_ok": True,
            "is_mutating": False,
            "trusted_origin": True,
            "output": "",
            "output_text": "",
            "approved_provider": True,
            "secrets_redacted": True,
            "in_sandbox": True,
            "path_traversal": False,
            "destructive_command": False,
        },
        memory_op={"is_proposed_mutation": False},
        workflow_state={
            "attempt_count": 1,
            "retry_count": 0,
            "max_iterations": 10,
            "max_retry": 3,
            "deps_satisfied": True,
            "handoff_ok": True,
            "branches_independent": True,
            "trajectory_class_drift": False,
        },
        budget={
            "used_tokens": 0,
            "max_tokens": 1000,
            "cost_usd": 0.0,
            "max_cost_usd": 1.0,
            "elapsed_ms": 100,
            "slo_ms": 30000,
            "used_tool_calls": 0,
            "max_tool_calls": 50,
            "used_model_calls": 0,
            "max_model_calls": 30,
        },
        output={
            "text": "Paris is the capital of France.",
            "schema_required": False,
            "schema_valid": True,
            "groundedness": 0.95,
            "faithfulness": 0.95,
            "citation_support": 0.95,
            "completeness": 0.95,
            "task_fit": 0.95,
            "confidence": 0.5,
            "format_fit": True,
            "sealed": True,
            "sub_results": {
                "policy": "pass",
                "schema": "pass",
                "support": "pass",
                "safety": "pass",
                "sandbox": "pass",
                "mutation_authorization": "pass",
            },
        },
        baseline={},
        observed={},
        trace_artifacts={
            "replay_required": False,
            "replay_key": "rk-1",
            "snapshot_id": "snap-1",
            "digest_match": True,
            "spans": {
                "trace_root": "t1",
                "route_contract": "rc1",
                "tool_invocations": ["i1"],
                "evidence_contracts": ["e1"],
                "step_outputs": ["s1"],
                "exit_disposition": "ALLOW",
            },
            "audit_hash_chain_ok": True,
        },
        learning_signal={"run_status": "in_progress"},
    )
