# hops/hop_7_rendering.py
"""
Hop 7: Document Rendering - HIGH-SIGNAL OVERWRITE

This is a spec-driven, context-aware renderer.
1. It loads a "render_spec" (mocked inline) to define document
   structure, order, and content sourcing.
2. It dynamically sources content from the HOP-4 staging buffer
   (for LLM content) AND the HOP-0 thematic analysis (for
   guaranteed-alignment data like keywords).
3. It generates a "High-Signal App Tracker" entry, which serves
   as a performance snapshot of the run, including RAG signal
   quality and final alignment scores from HOP-5.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Any, List

# Add project root to path
project_root = Path(__file__).resolve().parent.parent
sys.path.append(str(project_root))

# Import necessary components
from helpers import (
    setup_workflow_logging, HopExecutionError, default_serializer,
    ImmutableStagingBuffer, ThematicAnalysis, ValidationResult
)

# --- Mock Render Spec ---
# In a real system, this would be loaded from artist_specs_path or config_path
MOCK_RENDER_SPEC = {
    "document_order": [
        "HEADER_TITLE",
        "K1_SUMMARY",
        "DYNAMIC_KEYWORDS",
        "K2_EXPERIENCE",
        "K3_EXPERIENCE",
        "FOOTER"
    ],
    "sections": {
        "HEADER_TITLE": {
            "type": "template",
            "template": "# {company_name} - {job_title}\n\n"
        },
        "K1_SUMMARY": {
            "type": "buffer_content",
            "source_key": "K.1_Executive_Summary",
            "template": "## Executive Summary\n\n{content}\n\n",
            "if_exists": True
        },
        "DYNAMIC_KEYWORDS": {
            "type": "dynamic_hop0",
            "source_key": "primary_theme.keywords",
            "template": "## Core Thematic Competencies\n\n- {content}\n\n",
            "list_delimiter": "\n- "
        },
        "K2_EXPERIENCE": {
            "type": "buffer_content",
            "source_key": "K.2_Unify_Overview",
            "template": "## Professional Experience\n\n### Recent Experience (Overview)\n\n{content}\n\n",
            "if_exists": True
        },
        "K3_EXPERIENCE": {
            "type": "buffer_content",
            "source_key": "K.2_Unify_Bullets", # Note: K.2 bullets
            "template": "### Key Achievements\n\n- {content}\n\n",
            "list_delimiter": "\n- ",
            "if_exists": True
        },
        "FOOTER": {
            "type": "template",
            "template": "\n---\n*Generated by resume-pipeline v2.0*"
        }
    }
}

# --- End Mock Render Spec ---

class DynamicMarkdownRenderer:
    """Renders a markdown resume based on a render spec."""
    
    def __init__(self, render_spec: Dict, staging_buffer: ImmutableStagingBuffer,
                 thematic_analysis: ThematicAnalysis, base_metadata: Dict):
        self.logger = logging.getLogger(__name__)
        self.spec = render_spec
        self.buffer = staging_buffer
        self.thematic_analysis = thematic_analysis
        self.base_metadata = base_metadata # For {company_name} etc.
        self.output_lines = []
        
        # Simple regex for hyphenation (mock)
        self.hyphen_rules = {
            "data base": "database",
            "back end": "backend",
            "front end": "frontend"
        }
        self.hyphen_pattern = re.compile(
            r'\b(' + '|'.join(re.escape(k) for k in self.hyphen_rules.keys()) + r')\b',
            re.IGNORECASE
        )

    def _apply_formatting(self, text: str) -> str:
        """Applies final typography and hyphenation rules."""
        # Fix hyphenation
        text = self.hyphen_pattern.sub(
            lambda m: self.hyphen_rules[m.group(0).lower()], text
        )
        # Fix smart quotes (simple version)
        text = text.replace("'", "’").replace('"', '”')
        return text.strip()

    def _get_dynamic_content(self, source_key: str) -> Any:
        """Fetches data from HOP-0 ThematicAnalysis."""
        if source_key == "primary_theme.keywords":
            return self.thematic_analysis.primary_theme.get("keywords", [])
        # Add more dynamic keys here
        return None

    def render(self) -> str:
        """Iterates the spec and builds the markdown string."""
        self.logger.info("Starting spec-driven markdown rendering...")
        
        for section_id in self.spec.get("document_order", []):
            section = self.spec["sections"].get(section_id)
            if not section:
                self.logger.warning(f"Section '{section_id}' in order, but not defined in spec. Skipping.")
                continue

            content = None
            template = section.get("template", "{content}")
            
            if section["type"] == "template":
                content = "" # Content is just the template
            
            elif section["type"] == "buffer_content":
                content = self.buffer.get(section["source_key"])
                if not content and section.get("if_exists", False):
                    continue # Skip optional, empty sections
                content = content or f"[CONTENT NOT FOUND: {section['source_key']}]"

            elif section["type"] == "dynamic_hop0":
                content = self._get_dynamic_content(section["source_key"])
                if not content and section.get("if_exists", False):
                    continue
                content = content or f"[DYNAMIC CONTENT NOT FOUND: {section['source_key']}]"

            # Format content (list or string)
            if isinstance(content, list):
                delimiter = section.get("list_delimiter", "\n")
                content_str = delimiter.join(str(item) for item in content)
            else:
                content_str = str(content)

            # Inject content into template, and template into base metadata
            try:
                formatted_section = template.format(content=content_str, **self.base_metadata)
            except KeyError as e:
                self.logger.error(f"Failed to format template for {section_id}. Missing key: {e}")
                formatted_section = f"[TEMPLATE ERROR: {e}]"
                
            self.output_lines.append(self._apply_formatting(formatted_section))

        self.logger.info(f"Rendering complete. {len(self.output_lines)} sections rendered.")
        return "\n".join(self.output_lines)


class HighSignalAppTracker:
    """Generates a rich app tracker entry with performance data."""
    
    def __init__(self, base_metadata: Dict, thematic_analysis: ThematicAnalysis,
                 validation_results: List[ValidationResult], gate_decision: Dict):
        self.logger = logging.getLogger(__name__)
        self.base_metadata = base_metadata
        self.thematic_analysis = thematic_analysis
        self.validation_results = validation_results
        self.gate_decision = gate_decision.get("decision_metadata", {})

    def _find_validation_detail(self, rule_id: str) -> Dict:
        """Helper to find specific validation results."""
        for vr in self.validation_results:
            if vr.rule_id == rule_id:
                return vr.details
        return {}

    def build_entry(self) -> str:
        """Builds the app tracker JSON string."""
        self.logger.info("Building high-signal app tracker entry...")
        
        # 1. Find key performance metrics
        alignment_details = self._find_validation_detail("THEMATIC_ALIGNMENT_SUMMARY")
        keyword_details = self._find_validation_detail("KEYWORD_COVERAGE")
        
        # 2. Build the rich dictionary
        entry_data = {
            "company_name": self.base_metadata.get("company_name"),
            "job_title": self.base_metadata.get("job_title"),
            "jd_url": self.base_metadata.get("jd_url"),
            "date_applied": datetime.now().isoformat(),
            "status": "Applied" if "PROCEED" in self.gate_decision.get("decision", "HALT") else "Generated (HALTED)",
            
            "performance_snapshot": {
                "gate_decision": self.gate_decision.get("decision"),
                "gate_reason": self.gate_decision.get("reason"),
                "rag_signal_quality": self.thematic_analysis.signal_quality_score,
                "rag_primary_theme": self.thematic_analysis.primary_theme.get("name", "N/A"),
                "final_thematic_alignment": alignment_details.get("actual_similarity", 0.0),
                "final_keyword_coverage": keyword_details.get("found", 0) / (len(keyword_details.get("found", [])) + len(keyword_details.get("missing", [1]))),
                "final_risk_score": self.gate_decision.get("total_risk_score", 0),
            },
            
            "pipeline_metadata": {
                "workflow_id": self.base_metadata.get("workflow_id"),
                "run_dir": self.base_metadata.get("run_dir")
            }
        }
        
        return json.dumps(entry_data, indent=2, default=default_serializer)

def run_hop_7(args: argparse.Namespace):
    """Executes the HOP-7 rendering logic."""
    logger, _ = setup_workflow_logging(args.workflow_id, log_file_dir=args.run_dir)
    logger.info("--- Starting HOP-7: Spec-Driven Rendering [v-HighSignal] ---")
    start_time = datetime.now()

    try:
        # Load inputs
        try:
            with open(args.input_path_staging_buffer, 'r', encoding='utf-8') as f:
                staging_buffer = ImmutableStagingBuffer.from_dict(
                    json.load(f).get("staging_buffer_data", {}), locked=True
                )
            
            with open(args.input_path_thematic_analysis, 'r', encoding='utf-8') as f:
                thematic_analysis = ThematicAnalysis.from_dict(json.load(f))
            
            with open(args.input_path_validation_results, 'r', encoding='utf-8') as f:
                validation_results = [
                    ValidationResult.from_dict(vr) for vr in
                    json.load(f).get("validation_results", [])
                ]
            
            with open(args.input_path_gate_decision, 'r', encoding='utf-8') as f:
                gate_decision = json.load(f)
            
            # Load render spec (using mock)
            render_spec = MOCK_RENDER_SPEC
            logger.info("Loaded MOCK render spec.")
            
        except Exception as e:
            raise HopExecutionError(f"Failed to load input files: {e}") from e

        # Base metadata for templates
        base_metadata = {
            "company_name": args.company_name,
            "job_title": args.job_title,
            "jd_url": args.jd_url,
            "workflow_id": args.workflow_id,
            "run_dir": args.run_dir,
            "date": datetime.now().strftime('%Y-%m-%d')
        }

        # 1. Render Resume
        renderer = DynamicMarkdownRenderer(render_spec, staging_buffer, thematic_analysis, base_metadata)
        resume_markdown = renderer.render()
        
        # 2. Render App Tracker Entry
        app_tracker_builder = HighSignalAppTracker(
            base_metadata, thematic_analysis, validation_results, gate_decision
        )
        app_tracker_json = app_tracker_builder.build_entry()
        
        logger.info(f"Rendering complete. Resume length: {len(resume_markdown)} chars")

        # Write outputs
        try:
            resume_path = Path(args.output_path_resume_md)
            resume_path.write_text(resume_markdown, encoding='utf-8')
            logger.info(f"Successfully wrote resume to {resume_path}")
            
            tracker_path = Path(args.output_path_app_tracker)
            tracker_path.write_text(app_tracker_json, encoding='utf-8')
            logger.info(f"Successfully wrote high-signal app tracker to {tracker_path}")
            
        except Exception as e:
            raise HopExecutionError(f"Failed to write output files: {e}") from e

        duration = (datetime.now() - start_time).total_seconds()
        logger.info(f"--- HOP-7 Finished Successfully ({duration:.2f}s) ---")
        print("API Calls Made: 0")

    except HopExecutionError as he:
        logger.error(f"HOP-7 HALTED: {he}", exc_info=False)
        duration = (datetime.now() - start_time).total_seconds()
        logger.info(f"--- HOP-7 Finished with HALT ({duration:.2f}s) ---")
        print("API Calls Made: 0")
        exit(1)
    except Exception as e:
        logger.error(f"HOP-7 FAILED with unexpected error: {e}", exc_info=True)
        duration = (datetime.now() - start_time).total_seconds()
        logger.info(f"--- HOP-7 Finished with FAILURE ({duration:.2f}s) ---")
        print("API Calls Made: 0")
        exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="HOP-7: Spec-Driven Rendering [v-HighSignal]")
    parser.add_argument("--workflow-id", required=True, help="Unique ID for the workflow run")
    parser.add_argument("--run-dir", required=True, help="Directory for the workflow run artifacts")
    parser.add_argument("--config-path", required=True, help="Path to the config file snapshot")
    # Note: In a real impl, render_spec_path, hyphenation_rules, etc.
    # would be passed here from the orchestrator.
    parser.add_argument("--input-path-staging-buffer", required=True, help="Path to the staging buffer JSON")
    parser.add_argument("--input-path-thematic-analysis", required=True, help="Path to the thematic analysis JSON")
    parser.add_argument("--input-path-validation-results", required=True, help="Path to the validation results JSON")
    parser.add_argument("--input-path-gate-decision", required=True, help="Path to the gate decision JSON")
    parser.add_argument("--company-name", required=True, help="Target company name")
    parser.add_argument("--job-title", required=True, help="Target job title")
    parser.add_argument("--jd-url", required=True, help="Job description URL")
    parser.add_argument("--output-path-resume-md", required=True, help="Path to write the resume markdown file")
    parser.add_argument("--output-path-app-tracker", required=True, help="Path to write the app tracker entry JSON")

    args = parser.parse_args()
    run_hop_7(args)