import logging
#!/usr/bin/env python3
"""
PHASE 4 FREEZE AGGREGATOR — GLOBAL MERKLE-ROOT FREEZE (Pre-Flight 0.5)

Implements:
  - Read all per-domain freeze reports generated by Phase 4
  - Construct a deterministic ordering of domain + path entries
  - Compute a Merkle tree over (domain, path, hash) tuples
  - Emit: global_freeze_aggregate.json containing:
      - Merkle root
      - per-domain digests
      - metadata (timestamp, tool version)

Aggregator must be fully deterministic (no random ordering).

Version: 1.0
Created: SUPER-PROMPT v3.2 Pre-Flight 0.5
"""

from __future__ import annotations

import hashlib
import json
import sys
from dataclasses import dataclass, asdict
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

# =====================================================================
# ROOTS
# =====================================================================

PROJECT_ROOT = Path(r"C:/Git/Agentic-Workflow").resolve()
DATA_ROOT = PROJECT_ROOT / "06_data"
OUTPUT_PATH = DATA_ROOT / "global_freeze_aggregate.json"

# Per-domain freeze report naming convention
FREEZE_REPORT_PATTERN = "*_freeze_report.json"

# Target domains for freeze aggregation
TARGET_DOMAINS = [
    "01_agentic_core",
    "02_schemas",
    "03_runtime",
    "04_prompt_governance",
    "05_config",
    "06_data",
    "07_observability",
    "08_scripts",
    "09_apps",
    "10_tests",
]

# =====================================================================
# MERKLE TREE IMPLEMENTATION
# =====================================================================

def sha256_hash(data: str) -> str:
    """Compute SHA256 hash of a string."""
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def compute_merkle_root(hashes: List[str]) -> str:
    """
    Compute Merkle root from a list of hashes.
    
    Uses a deterministic binary tree construction:
    - If odd number of leaves, duplicate the last one
    - Combine pairs by concatenating and hashing
    - Repeat until single root remains
    """
    if not hashes:
        return sha256_hash("EMPTY_TREE")
    
    if len(hashes) == 1:
        return hashes[0]
    
    # Ensure even number of leaves
    current_level = list(hashes)
    if len(current_level) % 2 == 1:
        current_level.append(current_level[-1])
    
    while len(current_level) > 1:
        next_level = []
        for i in range(0, len(current_level), 2):
            left = current_level[i]
            right = current_level[i + 1] if i + 1 < len(current_level) else left
            combined = sha256_hash(left + right)
            next_level.append(combined)
        current_level = next_level
        
        # Ensure even number for next iteration
        if len(current_level) > 1 and len(current_level) % 2 == 1:
            current_level.append(current_level[-1])
    
    return current_level[0]


# =====================================================================
# FREEZE REPORT LOADING
# =====================================================================

@dataclass
class FreezeEntry:
    """Single file entry from a freeze report."""
    domain: str
    relative_path: str
    file_hash: str
    size: int


@dataclass
class DomainFreezeReport:
    """Loaded freeze report for a single domain."""
    domain: str
    timestamp: str
    file_count: int
    entries: List[FreezeEntry]
    domain_digest: str


def load_freeze_report(path: Path) -> Optional[DomainFreezeReport]:
    """Load a single freeze report JSON file."""
    try:
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        
        # Extract domain from filename
        domain = path.stem.replace("_freeze_report", "")
        timestamp = data.get("timestamp", "unknown") if isinstance(data, dict) else "unknown"
        
        entries = []
        
        # Handle different freeze report formats
        if isinstance(data, dict):
            files_data = data.get("files", data.get("entries", {}))
            
            # Format 1: {"files": {"path": {"sha256": "...", "size_bytes": N}}}
            if isinstance(files_data, dict):
                for rel_path, file_info in files_data.items():
                    if isinstance(file_info, dict):
                        entries.append(FreezeEntry(
                            domain=domain,
                            relative_path=rel_path,
                            file_hash=file_info.get("sha256", file_info.get("hash", "")),
                            size=file_info.get("size_bytes", file_info.get("size", 0)),
                        ))
            # Format 2: {"files": [{"path": "...", "hash": "...", "size": N}]}
            elif isinstance(files_data, list):
                for entry in files_data:
                    if isinstance(entry, dict):
                        entries.append(FreezeEntry(
                            domain=domain,
                            relative_path=entry.get("relative_path", entry.get("path", "")),
                            file_hash=entry.get("hash", entry.get("sha256", entry.get("file_hash", ""))),
                            size=entry.get("size", entry.get("size_bytes", 0)),
                        ))
        
        # Compute domain digest
        entry_hashes = [
            sha256_hash(f"{e.relative_path}:{e.file_hash}:{e.size}")
            for e in sorted(entries, key=lambda x: x.relative_path)
        ]
        domain_digest = compute_merkle_root(entry_hashes) if entry_hashes else sha256_hash(f"EMPTY_{domain}")
        
        return DomainFreezeReport(
            domain=domain,
            timestamp=timestamp,
            file_count=len(entries),
            entries=entries,
            domain_digest=domain_digest,
        )
    except Exception as e:
        logging.debug(f"[WARN] Failed to load freeze report {path}: {e}")
        import traceback
        traceback.print_exc()
        return None


def find_freeze_reports() -> List[Path]:
    """Find all per-domain freeze reports in the data directory."""
    reports = []
    
    # Look for freeze reports in 06_data and domain roots
    search_paths = [DATA_ROOT, PROJECT_ROOT]
    
    for search_path in search_paths:
        if not search_path.exists():
            continue
        
        for report_path in search_path.glob(FREEZE_REPORT_PATTERN):
            if report_path.is_file():
                reports.append(report_path)
        
        # Also check domain-specific locations
        for domain in TARGET_DOMAINS:
            domain_path = search_path / domain
            if domain_path.exists():
                for report_path in domain_path.glob(FREEZE_REPORT_PATTERN):
                    if report_path.is_file():
                        reports.append(report_path)
    
    # Deduplicate and sort for determinism
    unique_reports = sorted(set(reports), key=lambda p: str(p))
    return unique_reports


# =====================================================================
# GLOBAL AGGREGATE
# =====================================================================

@dataclass
class GlobalFreezeAggregate:
    """Global freeze aggregate with Merkle root."""
    timestamp: str
    tool_version: str
    schema_version: str
    merkle_root: str
    total_file_count: int
    domain_count: int
    per_domain_digests: Dict[str, str]
    per_domain_file_counts: Dict[str, int]
    validation_keys: Dict[str, str]


def compute_global_aggregate(reports: List[DomainFreezeReport]) -> GlobalFreezeAggregate:
    """Compute global Merkle-root aggregate from domain reports."""
    
    # Collect all entries across domains
    all_entries: List[Tuple[str, str, str, int]] = []
    per_domain_digests: Dict[str, str] = {}
    per_domain_file_counts: Dict[str, int] = {}
    
    for report in reports:
        per_domain_digests[report.domain] = report.domain_digest
        per_domain_file_counts[report.domain] = report.file_count
        
        for entry in report.entries:
            all_entries.append((
                entry.domain,
                entry.relative_path,
                entry.file_hash,
                entry.size,
            ))
    
    # Sort entries deterministically: by domain, then path
    all_entries.sort(key=lambda x: (x[0], x[1]))
    
    # Compute leaf hashes for Merkle tree
    leaf_hashes = [
        sha256_hash(f"{domain}:{path}:{file_hash}:{size}")
        for domain, path, file_hash, size in all_entries
    ]
    
    # Compute Merkle root
    merkle_root = compute_merkle_root(leaf_hashes)
    
    # Validation keys
    validation_keys = {
        "K1": "PASS" if merkle_root else "FAIL",
        "K2": "PASS" if len(reports) > 0 else "FAIL",
        "K3": "PASS",  # Aggregator completed
    }
    
    return GlobalFreezeAggregate(
        timestamp=datetime.now().isoformat(),
        tool_version="1.0",
        schema_version="v3.2",
        merkle_root=merkle_root,
        total_file_count=len(all_entries),
        domain_count=len(reports),
        per_domain_digests=per_domain_digests,
        per_domain_file_counts=per_domain_file_counts,
        validation_keys=validation_keys,
    )


# =====================================================================
# MAIN
# =====================================================================

def run_freeze_aggregator() -> GlobalFreezeAggregate:
    """Run the freeze aggregator."""
    logging.debug("=== PHASE 4 FREEZE AGGREGATOR — GLOBAL MERKLE-ROOT ===")
    logging.debug(f"Project root: {PROJECT_ROOT}")
    logging.debug(f"Output path: {OUTPUT_PATH}")
    
    # Find freeze reports
    report_paths = find_freeze_reports()
    logging.debug(f"Found {len(report_paths)} freeze reports")
    
    # Load reports
    reports: List[DomainFreezeReport] = []
    for path in report_paths:
        report = load_freeze_report(path)
        if report:
            reports.append(report)
            logging.debug(f"  Loaded: {report.domain} ({report.file_count} files)")
    
    # If no reports found, create empty aggregate
    if not reports:
        logging.debug("[WARN] No freeze reports found. Creating empty aggregate.")
    
    # Compute global aggregate
    aggregate = compute_global_aggregate(reports)
    
    # Write output
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        json.dump(asdict(aggregate), f, indent=2, sort_keys=True)
    
    logging.debug(f"\n=== GLOBAL FREEZE AGGREGATE ===")
    logging.debug(f"Merkle root: {aggregate.merkle_root}")
    logging.debug(f"Total files: {aggregate.total_file_count}")
    logging.debug(f"Domains: {aggregate.domain_count}")
    
    logging.debug(f"\n=== PER-DOMAIN DIGESTS ===")
    for domain, digest in sorted(aggregate.per_domain_digests.items()):
        count = aggregate.per_domain_file_counts.get(domain, 0)
        logging.debug(f"  {domain}: {digest[:16]}... ({count} files)")
    
    logging.debug(f"\n=== VALIDATION KEYS ===")
    for key, status in aggregate.validation_keys.items():
        logging.debug(f"{key} = {status}")
    
    return aggregate


def main() -> int:
    """Main entry point."""
    try:
        aggregate = run_freeze_aggregator()
        
        # Check validation keys
        all_pass = all(v == "PASS" for v in aggregate.validation_keys.values())
        
        if all_pass:
            logging.debug("\n[PASS] Global freeze aggregate computed successfully")
            return 0
        else:
            logging.debug("\n[FAIL] Some validation keys failed")
            return 1
    
    except Exception as e:
        logging.debug(f"[ERROR] Freeze aggregator failed: {e}")
        import traceback
        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
