"""K1 Research Executor - First hop in the sequential K1-K7 execution pipeline.

Incorporated from L2 lic_k1_research.py to execute research queries generated
by the L1 research planner, perform HyDE enrichment, hybrid recall, and
produce structured research output for K2 insights generation.

This is the first execution phase in the hop-based architecture that follows:
L1 Planning → K1 Research → K2 Insights → K3 Draft → K4 Regeneration → K5 Validation → K6 CTA → K7 Assembly
"""

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import logging

logger = logging.getLogger(__name__)


@dataclass
class ResearchOutput:
    """Output from K1 research execution phase."""
    hyde_profile: Optional[str]
    rag_sources: List[Dict[str, Any]]
    enriched_context: Dict[str, Any]
    signal_score: float
    query_results: List[Dict[str, Any]]
    execution_metadata: Dict[str, Any] = field(default_factory=dict)
    confidence_score: float = 0.0


class K1ResearchExecutor:
    """K1 research executor - first hop in sequential execution pipeline.
    
    Executes research queries generated by L1 research planner, performs
    HyDE enrichment, hybrid recall, and prepares data for K2 insights.
    """
    
    def __init__(self, research_plan: Optional[Any] = None, telemetry_bus: Optional[Any] = None) -> None:
        """Initialize K1 research executor."""
        self.research_plan = research_plan
        self.telemetry_bus = telemetry_bus
        
        # Default research configuration
        self.default_config = {
            "hyde_enabled": True,
            "hyde_trigger": "missing_about_or_short",
            "web_search_calls": 6,
            "internal_sources": 10,
            "reranking_enabled": True,
            "reranking_threshold": 0.7,
            "max_hops": 3
        }


# Alias for backward compatibility with tests
LIC_K1_Research = K1ResearchExecutor
        
        # Research query templates
        self.query_templates = {
            "company_initiatives": "{company} recent initiatives strategic projects",
            "role_challenges": "{role} challenges industry trends",
            "company_news": "{company} recent news press releases",
            "technology_stack": "{company} technology stack infrastructure",
            "competitive_landscape": "{company} competitors market position",
            "strategic_alignment": "{company} {role} strategic alignment opportunities"
        }
    
    def execute(
        self,
        *,
        research_plan: Optional[Any] = None,
        recipient_profile: Dict[str, Any],
        outreach_context: Dict[str, Any] = None,
    ) -> ResearchOutput:
        """Execute K1 research phase.
        
        Args:
            research_plan: Research plan from L1 research planner
            recipient_profile: Target recipient profile data
            outreach_context: Additional context for research
            
        Returns:
            Complete research output with sources and enriched context
        """
        outreach_context = outreach_context or {}
        
        # Use provided plan or fall back to default
        plan = research_plan or self.research_plan
        
        # 1. Execute HyDE enrichment if needed
        hyde_profile = self._execute_hyde_enrichment(recipient_profile, plan)
        
        # 2. Execute hybrid recall research
        rag_sources = self._execute_hybrid_recall(recipient_profile, hyde_profile, plan)
        
        # 3. Generate query results
        query_results = self._execute_query_research(recipient_profile, plan)
        
        # 4. Create enriched context
        enriched_context = self._create_enriched_context(recipient_profile, hyde_profile, rag_sources)
        
        # 5. Calculate signal score
        signal_score = self._calculate_signal_score(rag_sources, query_results)
        
        # 6. Calculate confidence score
        confidence_score = self._calculate_confidence_score(hyde_profile, rag_sources, signal_score)
        
        # 7. Build execution metadata
        execution_metadata = {
            "hyde_generated": hyde_profile is not None,
            "source_count": len(rag_sources),
            "query_count": len(query_results),
            "research_strategy": getattr(plan, 'primary_strategy', 'vector_first') if plan else 'default'
        }
        
        # 8. Create research output
        output = ResearchOutput(
            hyde_profile=hyde_profile,
            rag_sources=rag_sources,
            enriched_context=enriched_context,
            signal_score=signal_score,
            query_results=query_results,
            execution_metadata=execution_metadata,
            confidence_score=confidence_score
        )
        
        # 9. Record telemetry (best-effort)
        self._safe_record_telemetry(output)
        
        return output
    
    def _execute_hyde_enrichment(self, recipient_profile: Dict[str, Any], plan: Optional[Any]) -> Optional[str]:
        """Execute HyDE profile enrichment if triggered."""
        # Get HyDE configuration
        if plan and hasattr(plan, 'vector_params'):
            hyde_enabled = getattr(plan.vector_params, 'hyde_enabled', self.default_config["hyde_enabled"])
            hyde_trigger = getattr(plan.vector_params, 'hyde_trigger', self.default_config["hyde_trigger"])
        else:
            hyde_enabled = self.default_config["hyde_enabled"]
            hyde_trigger = self.default_config["hyde_trigger"]
        
        if not hyde_enabled:
            return None
        
        # Check if trigger conditions are met
        trigger_met = self._check_hyde_trigger(recipient_profile, hyde_trigger)
        if not trigger_met:
            return None
        
        # Generate HyDE profile
        return self._generate_hyde_profile(recipient_profile)
    
    def _check_hyde_trigger(self, recipient_profile: Dict[str, Any], trigger: str) -> bool:
        """Check if HyDE enrichment should be triggered."""
        if trigger == "missing_about_or_short":
            about = recipient_profile.get("about", "")
            return about is None or len(about) < 50
        elif trigger == "limited_profile":
            required_fields = ["title", "company", "experience"]
            return any(not recipient_profile.get(field) for field in required_fields)
        elif trigger == "always":
            return True
        else:
            return False
    
    def _generate_hyde_profile(self, recipient_profile: Dict[str, Any]) -> str:
        """Generate HyDE profile from recipient data."""
        title = recipient_profile.get("title", "professional")
        company = recipient_profile.get("company", "organization")
        industry = recipient_profile.get("industry", "sector")
        
        profile = f"Professional with expertise in {title} at {company}. "
        
        if industry:
            profile += f"Works in the {industry} sector. "
        
        profile += "Focuses on strategic initiatives and team leadership. "
        profile += "Experienced in driving business outcomes and technical innovation. "
        profile += "Demonstrates strong problem-solving skills and collaborative approach."
        
        return profile
    
    def _execute_hybrid_recall(self, recipient_profile: Dict[str, Any], hyde_profile: Optional[str], plan: Optional[Any]) -> List[Dict[str, Any]]:
        """Execute hybrid recall research combining multiple sources."""
        sources = []
        
        # Generate research queries
        queries = self._generate_research_queries(recipient_profile, hyde_profile, plan)
        
        # Execute web search simulation
        web_sources = self._simulate_web_search(queries)
        sources.extend(web_sources)
        
        # Execute internal knowledge base search
        internal_sources = self._simulate_internal_search(recipient_profile, plan)
        sources.extend(internal_sources)
        
        # Execute company-specific research
        company_sources = self._simulate_company_research(recipient_profile, plan)
        sources.extend(company_sources)
        
        # Rank and filter sources
        ranked_sources = self._rank_and_filter_sources(sources, plan)
        
        return ranked_sources[:20]  # Limit to top 20 sources
    
    def _generate_research_queries(self, recipient_profile: Dict[str, Any], hyde_profile: Optional[str], plan: Optional[Any]) -> List[str]:
        """Generate research queries based on profile and plan."""
        title = recipient_profile.get("title", "")
        company = recipient_profile.get("company", "")
        archetype = recipient_profile.get("archetype", "")
        
        queries = []
        
        # Use plan queries if available
        if plan and hasattr(plan, 'queries'):
            for query in plan.queries:
                queries.extend(query.expanded_queries)
        else:
            # Generate default queries
            for template_name, template in self.query_templates.items():
                query = template.format(company=company, role=title)
                queries.append(query)
        
        # Add archetype-specific queries
        if archetype == "EXECUTIVE":
            queries.extend([
                f"{company} executive leadership team",
                f"{company} business strategy financial performance",
                f"{title} strategic decision making authority"
            ])
        elif archetype == "SENIOR_TA":
            queries.extend([
                f"{company} engineering culture technical stack",
                f"{title} technical leadership architecture decisions",
                f"{company} innovation initiatives R&D"
            ])
        
        return queries[:10]  # Limit to 10 queries
    
    def _simulate_web_search(self, queries: List[str]) -> List[Dict[str, Any]]:
        """Simulate web search execution (placeholder for actual search)."""
        sources = []
        
        for i, query in enumerate(queries):
            # Simulate search result
            source = {
                "source_type": "web",
                "query": query,
                "title": f"Research result for: {query[:50]}...",
                "content": f"Simulated web search content for {query}. Contains relevant information about the topic.",
                "url": f"https://example.com/search/{i}",
                "relevance_score": 0.8 + (i % 3) * 0.05,
                "timestamp": "2024-01-01T00:00:00Z",
                "metadata": {"search_method": "web_search"}
            }
            sources.append(source)
        
        return sources
    
    def _simulate_internal_search(self, recipient_profile: Dict[str, Any], plan: Optional[Any]) -> List[Dict[str, Any]]:
        """Simulate internal knowledge base search."""
        company = recipient_profile.get("company", "")
        title = recipient_profile.get("title", "")
        
        sources = [
            {
                "source_type": "internal",
                "title": f"Internal profile: {title} at {company}",
                "content": f"Internal knowledge base entry for {title} role at {company}. Contains role responsibilities and team structure.",
                "relevance_score": 0.9,
                "timestamp": "2024-01-01T00:00:00Z",
                "metadata": {"source": "internal_kb", "category": "profile"}
            },
            {
                "source_type": "internal",
                "title": f"Company overview: {company}",
                "content": f"Internal company overview for {company}. Includes business model, market position, and strategic initiatives.",
                "relevance_score": 0.85,
                "timestamp": "2024-01-01T00:00:00Z",
                "metadata": {"source": "internal_kb", "category": "company"}
            }
        ]
        
        return sources
    
    def _simulate_company_research(self, recipient_profile: Dict[str, Any], plan: Optional[Any]) -> List[Dict[str, Any]]:
        """Simulate company-specific research."""
        company = recipient_profile.get("company", "")
        
        sources = [
            {
                "source_type": "company",
                "title": f"{company} official information",
                "content": f"Official company information for {company}. Includes company size, industry, and key personnel.",
                "relevance_score": 0.95,
                "timestamp": "2024-01-01T00:00:00Z",
                "metadata": {"source": "company_official", "verified": True}
            },
            {
                "source_type": "company",
                "title": f"{company} recent activities",
                "content": f"Recent activities and announcements from {company}. Includes product launches, partnerships, and strategic changes.",
                "relevance_score": 0.88,
                "timestamp": "2024-01-01T00:00:00Z",
                "metadata": {"source": "company_activities", "verified": True}
            }
        ]
        
        return sources
    
    def _rank_and_filter_sources(self, sources: List[Dict[str, Any]], plan: Optional[Any]) -> List[Dict[str, Any]]:
        """Rank and filter research sources."""
        # Get threshold from plan or use default
        if plan and hasattr(plan, 'vector_params'):
            threshold = getattr(plan.vector_params, 'similarity_threshold', 0.7)
        else:
            threshold = 0.7
        
        # Filter by relevance threshold
        filtered_sources = [s for s in sources if s.get("relevance_score", 0) >= threshold]
        
        # Sort by relevance score (descending)
        ranked_sources = sorted(filtered_sources, key=lambda x: x.get("relevance_score", 0), reverse=True)
        
        return ranked_sources
    
    def _execute_query_research(self, recipient_profile: Dict[str, Any], plan: Optional[Any]) -> List[Dict[str, Any]]:
        """Execute specific research queries from plan."""
        results = []
        
        if plan and hasattr(plan, 'queries'):
            for query in plan.queries:
                result = {
                    "query_id": query.query_id,
                    "query_type": query.query_type,
                    "base_query": query.base_query,
                    "expanded_queries": query.expanded_queries,
                    "results_found": len(query.expanded_queries),
                    "priority": query.priority,
                    "status": "completed"
                }
                results.append(result)
        
        return results
    
    def _create_enriched_context(self, recipient_profile: Dict[str, Any], hyde_profile: Optional[str], rag_sources: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Create enriched context combining profile and research data."""
        context = {
            "recipient_profile": recipient_profile,
            "research_summary": {
                "total_sources": len(rag_sources),
                "source_types": list(set(s.get("source_type", "unknown") for s in rag_sources)),
                "average_relevance": sum(s.get("relevance_score", 0) for s in rag_sources) / len(rag_sources) if rag_sources else 0,
                "high_quality_sources": len([s for s in rag_sources if s.get("relevance_score", 0) >= 0.8])
            },
            "key_insights": self._extract_key_insights(rag_sources),
            "company_signals": self._extract_company_signals(rag_sources),
            "role_signals": self._extract_role_signals(rag_sources)
        }
        
        if hyde_profile:
            context["hyde_profile"] = hyde_profile
        
        return context
    
    def _extract_key_insights(self, sources: List[Dict[str, Any]]) -> List[str]:
        """Extract key insights from research sources."""
        insights = []
        
        # Get top sources by relevance
        top_sources = sorted(sources, key=lambda x: x.get("relevance_score", 0), reverse=True)[:5]
        
        for source in top_sources:
            content = source.get("content", "")
            if len(content) > 100:
                insight = content[:100] + "..."
            else:
                insight = content
            insights.append(insight)
        
        return insights
    
    def _extract_company_signals(self, sources: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Extract company-specific signals from sources."""
        company_sources = [s for s in sources if s.get("source_type") == "company"]
        
        return {
            "company_sources_count": len(company_sources),
            "verified_sources": len([s for s in company_sources if s.get("metadata", {}).get("verified", False)]),
            "recent_activities": any("activities" in s.get("title", "").lower() for s in company_sources)
        }
    
    def _extract_role_signals(self, sources: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Extract role-specific signals from sources."""
        role_sources = [s for s in sources if "role" in s.get("title", "").lower() or "profile" in s.get("title", "").lower()]
        
        return {
            "role_sources_count": len(role_sources),
            "internal_profiles": len([s for s in role_sources if s.get("source_type") == "internal"]),
            "responsibility_signals": len([s for s in role_sources if "responsibilities" in s.get("content", "").lower()])
        }
    
    def _calculate_signal_score(self, rag_sources: List[Dict[str, Any]], query_results: List[Dict[str, Any]]) -> float:
        """Calculate overall signal score from research results."""
        if not rag_sources:
            return 0.0
        
        # Average relevance score
        avg_relevance = sum(s.get("relevance_score", 0) for s in rag_sources) / len(rag_sources)
        
        # Source diversity bonus
        source_types = len(set(s.get("source_type", "unknown") for s in rag_sources))
        diversity_bonus = min(source_types / 5.0, 0.2)  # Max 0.2 bonus
        
        # Query completion bonus
        completion_bonus = min(len(query_results) / 10.0, 0.1)  # Max 0.1 bonus
        
        signal_score = avg_relevance + diversity_bonus + completion_bonus
        return round(min(signal_score, 1.0), 3)
    
    def _calculate_confidence_score(self, hyde_profile: Optional[str], rag_sources: List[Dict[str, Any]], signal_score: float) -> float:
        """Calculate confidence score for research execution."""
        base_score = 0.6
        
        # HyDE profile bonus
        if hyde_profile:
            base_score += 0.1
        
        # Signal score contribution
        base_score += signal_score * 0.3
        
        return round(min(base_score, 1.0), 3)
    
    def _safe_record_telemetry(self, output: ResearchOutput) -> None:
        """Record telemetry data (best-effort)."""
        try:
            if self.telemetry_bus:
                self.telemetry_bus.record("k1_research_executed", {
                    "hyde_generated": output.hyde_profile is not None,
                    "source_count": len(output.rag_sources),
                    "signal_score": output.signal_score,
                    "confidence_score": output.confidence_score
                })
        except Exception as e:
            logger.debug(f"Failed to record telemetry: {e}")
    
    def get_research_summary(self, output: ResearchOutput) -> Dict[str, Any]:
        """Get a summary of the research execution for debugging/telemetry."""
        return {
            "execution_id": "k1_research",
            "hyde_generated": output.hyde_profile is not None,
            "source_count": len(output.rag_sources),
            "query_count": len(output.query_results),
            "signal_score": output.signal_score,
            "confidence_score": output.confidence_score,
            "source_types": list(set(s.get("source_type", "unknown") for s in output.rag_sources)),
            "average_relevance": sum(s.get("relevance_score", 0) for s in output.rag_sources) / len(output.rag_sources) if output.rag_sources else 0
        }
