"""Auto-generated flattened view for core/test_cost_tracker_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "core/test_cost_tracker_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """from core_v10_7 import CostTracker


def test_cost_tracker_records_calls_and_sums():
    tracker = CostTracker()
    tracker.record_call("wf1", "google", "gemini-2.5-pro", input_tokens=1000, output_tokens=500)
    summary = tracker.get_cost_summary("wf1")
    assert abs(summary["total_workflow_cost"] - 0.005) < 1e-9
    assert summary["calls"]


def test_unknown_provider_no_cost():
    tracker = CostTracker()
    tracker.record_call("wf2", "unknown", "mystery-model", input_tokens=1000, output_tokens=1000)
    summary = tracker.get_cost_summary("wf2")
    assert summary["total_workflow_cost"] == 0


def test_multiple_calls_aggregated():
    tracker = CostTracker()
    tracker.record_call("wf3", "google", "gemini-2.5-flash", input_tokens=500, output_tokens=500)
    tracker.record_call("wf3", "google", "gemini-2.5-pro", input_tokens=500, output_tokens=500)
    summary = tracker.get_cost_summary("wf3")
    assert summary["total_workflow_cost"] > 0
    assert len(summary["calls"]) == 2
"""
}

ORIGINAL_MODULE_NAME = "tests.core.test_cost_tracker_v10_7"
FLAT_MODULE_NAME = "tests_flat.core__test_cost_tracker_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
