from __future__ import annotations

from agentic_core.runtime.contracts import lifecycle_trace_contract as trace_contract

trace_contract.emit_replay_key("p0", "filesystem_mcp")
trace_contract.emit_determinism_digest("p0", "filesystem_mcp")

trace_contract._emit_dispatches_healing_run("p1", "filesystem_mcp", "L2")
trace_contract._emit_routes_through("p1", "filesystem_mcp", "L2")
trace_contract._emit_checks_agent_registry("p1", "filesystem_mcp", "agent_registry")
trace_contract._emit_validates_agent_capability("p1", "filesystem_mcp", "capability")
trace_contract._emit_dispatches_execution_plan("p1", "filesystem_mcp", "exec_plan")
trace_contract._emit_agent_executes_agent("p1", "filesystem_mcp", "sub_agent")
trace_contract._emit_routes_to_agent("p1", "filesystem_mcp", "target_agent")
trace_contract._emit_verifies_policy("p1", "filesystem_mcp", "policy_check")
trace_contract._emit_observes_runtime_state("p1", "filesystem_mcp", "runtime_state")
trace_contract._emit_verifies_boundary("p1", "filesystem_mcp", "boundary_check")
trace_contract._emit_transcripts_response("p1", "filesystem_mcp", "transcript")
trace_contract._emit_hard_fails_untranscripted("p1", "filesystem_mcp")
trace_contract._emit_gated_by_confidence("p1", "filesystem_mcp", "confidence_gate")
trace_contract._emit_escalates_to_human("p1", "filesystem_mcp", "L2")
trace_contract._emit_reads_policy_state("p1", "filesystem_mcp", "L2")

trace_contract._emit_signs_execution_trace("p0", "p0hash", "p0_trace", 0)
trace_contract._emit_records_execution_trace("p0", "evidence", "filesystem_mcp")
trace_contract._emit_applies_guardrail("p0", "filesystem_mcp", "p0_governance")
trace_contract._emit_snapshots_state("p0", "filesystem_mcp", "state_snapshot")
trace_contract._emit_authorize_and_execute("p2", "filesystem_mcp", "execution_auth")
trace_contract._emit_validates_capability("p2", "filesystem_mcp", "capability_check")
trace_contract._emit_routes_to_capability("p2", "filesystem_mcp", "capability_route")
trace_contract._emit_writes_via_uwg("p2", "filesystem_mcp", "uwg_write")
trace_contract._emit_blocks_direct_write("p2", "filesystem_mcp", "direct_write_block")
trace_contract._emit_records_tool_invocation("p2", "filesystem_mcp", "tool_invocation")
trace_contract._emit_captures_execution_output("p2", "filesystem_mcp", "exec_output")
trace_contract._emit_dispatches_agent("p3", "filesystem_mcp", "agent_dispatch")
trace_contract._emit_coordinates_agents("p3", "filesystem_mcp", "agent_coordination")
trace_contract._emit_records_workflow_lineage("p3", "filesystem_mcp", "workflow_lineage")
trace_contract._emit_records_healing_outcome("p3", "filesystem_mcp", "healing_outcome")
trace_contract._emit_escalates_failure("p3", "filesystem_mcp", "failure_escalation")
trace_contract._emit_orchestrates_workflow("p3", "filesystem_mcp", "workflow_orchestration")
trace_contract._emit_dispatches_healing_run("p3", "filesystem_mcp", "healing_dispatch")
trace_contract._emit_invokes_evaluation("p3", "filesystem_mcp", "evaluation_signal")
trace_contract._emit_records_telemetry_event("p4", "filesystem_mcp", "telemetry_event")
trace_contract._emit_captures_evaluation_metric("p4", "filesystem_mcp", "eval_metric")
trace_contract._emit_stores_embedding("p4", "filesystem_mcp", "embedding_store")
trace_contract._emit_updates_meta_learning_state("p4", "filesystem_mcp", "meta_learning")
trace_contract._emit_links_execution_to_snapshot("p4", "filesystem_mcp", "exec_snapshot_link")

trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_1")
trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_2")
trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_3")
trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_4")
trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_5")
trace_contract._emit_emits_metric_event("filesystem_mcp", "p4obs", "metric_6")
trace_contract._emit_records_incident_event("filesystem_mcp", "p4obs", "incident")
trace_contract._emit_captures_runtime_anomaly("filesystem_mcp", "p4obs", "anomaly")
trace_contract._emit_writes_observability_log("filesystem_mcp", "p4obs", "obs_log")
trace_contract._emit_updates_monitoring_state("filesystem_mcp", "p4obs", "mon_state")
trace_contract._emit_triggers_alert("filesystem_mcp", "p4obs", "alert")
trace_contract._emit_links_incident_trace("filesystem_mcp", "p4obs", "trace_link")
trace_contract._emit_captures_pattern("filesystem_mcp", "p3lm", "pattern")
trace_contract._emit_records_learning_event("filesystem_mcp", "p3lm", "learning_event")
trace_contract._emit_writes_learning_snapshot("filesystem_mcp", "p3lm", "snapshot")
trace_contract._emit_feeds_meta_learning("filesystem_mcp", "p3lm", "meta_feed")
trace_contract._emit_updates_routing_strategy("filesystem_mcp", "p3lm", "routing")
trace_contract._emit_improves_agent_policy("filesystem_mcp", "p3lm", "policy")
trace_contract._emit_stores_learning_state("filesystem_mcp", "p3lm", "state")
trace_contract._emit_records_execution_trace("filesystem_mcp", "L0_ROUTING", "p2_trace_1")
trace_contract._emit_records_execution_trace("filesystem_mcp", "L1_REASONING", "p2_trace_2")
trace_contract._emit_records_execution_trace("filesystem_mcp", "L2_EXECUTION", "p2_trace_3")
trace_contract._emit_records_execution_trace("filesystem_mcp", "L3_ORCHESTRATION", "p2_trace_4")
trace_contract._emit_records_execution_trace("filesystem_mcp", "L4_STATE", "p2_trace_5")
trace_contract._emit_reads_environ("filesystem_mcp", "env_read", "p2_env_1")
trace_contract._emit_reads_environ("filesystem_mcp", "env_read", "p2_env_2")
trace_contract._emit_reads_runtime_state("filesystem_mcp", "runtime_state", "p2_rt_1")
trace_contract._emit_reads_runtime_state("filesystem_mcp", "runtime_state", "p2_rt_2")
trace_contract._emit_pulls_context("p1", "filesystem_mcp", "context_pull")
trace_contract._emit_pulls_context("p1", "filesystem_mcp", "context_pull_2")
trace_contract._emit_execution_terminates_at_uwg("p1", "filesystem_mcp", "uwg_term")
trace_contract._emit_execution_terminates_at_uwg("p1", "filesystem_mcp", "uwg_term_2")
trace_contract._emit_writes_through("p1", "filesystem_mcp", "write_through")
trace_contract._emit_writes_through("p1", "filesystem_mcp", "write_through_2")
trace_contract._emit_validated_by_safety_plane("p1", "filesystem_mcp", "safety_validation")
trace_contract._emit_invokes_eval("p1", "filesystem_mcp", "eval_call")
trace_contract._emit_proposal_commits_routing("p1", "filesystem_mcp", "routing_commit")

try:
    from .filesystem_mcp import FilesystemMCP
except ImportError as e:
    raise ImportError(f"Required dependency missing: {e}")  # guardian: allow-silent-swallow


print("   [OK] agentic_core.L4_state.memory package initialized (stub mode)")
