"""QwenContextGateway - local-GPU gateway adapter for ContextualChunkBuilder.

Implements the ``_GatewayProtocol`` declared in
``tools.ingestion.contextual_chunk_builder`` and routes contextualization
requests through the local Qwen 2.5 vLLM server at ``VLLM_BASE_URL`` via the
sanctioned ``QwenInferenceGateway`` at L3.

Purpose
-------
Replaces the paid Anthropic contextualization path (``claude-haiku-4-5`` via
``AnthropicContextGateway``) with a free local-GPU equivalent. Closes the cost
blocker on ADR-045 W1.2 (gateway A/B measurement) without changing the
contextualization technique - same Anthropic-style 50-100 token narrative
prepended to each chunk, but generated by Qwen2.5-14B-Instruct-AWQ locally.

V1 scope
--------
* Route each contextualization request through ``QwenInferenceGateway.infer``.
* Default model resolved from L0 ``model_registry`` SSOT
  (``QWEN_LOCAL_MODEL_ID``, override via ``VLLM_MODEL_NAME`` env var).
* Default endpoint resolved from L0 ``model_registry`` SSOT
  (``VLLM_BASE_URL``, override via ``VLLM_BASE_URL`` env var).
* Module-level singleton gateway + single shared event loop per process
  (avoids spawning an event loop per chunk and re-initializing the vLLM HTTP
  pool on every call).
* Precise exception handling. On any transport/import/inference failure,
  ``generate`` re-raises ``RuntimeError`` so ``ContextualChunkBuilder`` falls
  back to its heuristic path per its own contract.

Factory contract
----------------
``build_from_env`` returns ``None`` when the local vLLM server is not
reachable - matching the ``AnthropicContextGateway.build_from_env`` shape so
ingestion scripts can chain: prefer Qwen, then Anthropic (if
``ANTHROPIC_API_KEY`` is set and explicitly opted in), else heuristic.

Out of scope (tracked separately)
---------------------------------
* Prompt-cache markers on the <document> prefix - Qwen vLLM supports prefix
  caching natively when the same document prefix repeats across chunks;
  ``OptimizedVLLMClient`` already enables response caching for identical
  prompts, so per-document prefix reuse happens when chunks from the same
  doc arrive in sequence.
* Late chunking integration (Jina-style long-document pooling) - orthogonal
  improvement tracked in a separate backlog item.

Determinism
-----------
* Defaults ``temperature=0.0``.
* ``OptimizedVLLMClient`` emits its own replay key and telemetry via the
  lifecycle-trace contract; no additional instrumentation required here.

Failure modes
-------------
* vLLM server not running / unreachable: factory returns ``None``; caller
  treats absence as "no gateway" and ``ContextualChunkBuilder`` falls back to
  heuristic.
* ``QwenInferenceGateway`` import failure: ``generate`` raises ``RuntimeError``
  (builder catches it).
* Inference-time error (timeout, model error, malformed response): ``generate``
  raises ``RuntimeError`` (builder catches it).
"""

from __future__ import annotations

import asyncio
import logging
import os
import threading
from typing import Any

import urllib.request
import urllib.error

Logger = logging.getLogger(__name__)


# Module-level singletons. Initialized lazily on first generate() call to keep
# import cost zero for ingestion runs that never contextualize.
_GATEWAY_LOCK = threading.Lock()
_GATEWAY_INSTANCE: Any = None  # QwenInferenceGateway once initialized
_EVENT_LOOP: asyncio.AbstractEventLoop | None = None


def _resolve_defaults() -> tuple[str, str]:
    """Resolve (model_id, base_url) from the L0 SSOT registry.

    Delegates to ``agentic_core.L0_routing.config.model_registry`` so the
    ingestion path uses the same SSOT as the rest of the system. Keeps this
    adapter free of hardcoded defaults.
    """
    try:
        from agentic_core.L0_routing.config.model_registry import (  # noqa: PLC0415
            QWEN_LOCAL_MODEL_ID,
            VLLM_BASE_URL,
        )
    except ImportError as exc:
        raise RuntimeError(
            f"QwenContextGateway could not import L0 model_registry SSOT: {exc}"
        ) from exc
    return QWEN_LOCAL_MODEL_ID, VLLM_BASE_URL


def _vllm_server_reachable(base_url: str, timeout_s: float = 2.0) -> bool:
    """Probe the vLLM server with a short GET on /models.

    Returns True iff the server responds with HTTP 200 to the OpenAI-compatible
    models endpoint. Used by ``build_from_env`` to decide whether to construct
    a gateway at all, matching the ``AnthropicContextGateway`` contract where
    absence of the key yields a None gateway and clean heuristic fallback.
    """
    # base_url is "http://localhost:8000/v1"; probe /v1/models directly.
    probe_url = base_url.rstrip("/") + "/models"
    try:
        with urllib.request.urlopen(probe_url, timeout=timeout_s) as resp:
            status: int = int(resp.status)
            return 200 <= status < 300
    except (urllib.error.URLError, OSError, ValueError) as exc:
        Logger.debug("vLLM reachability probe failed at %s: %s", probe_url, exc)
        return False


def _get_or_create_loop() -> asyncio.AbstractEventLoop:
    """Return a process-lifetime event loop for sync->async bridging.

    ``QwenInferenceGateway.infer`` is async; the ``_GatewayProtocol.generate``
    contract is sync. Creating a new loop per call is expensive and would
    reinitialize the vLLM HTTP pool every time; we keep one loop for the
    module lifetime and run coroutines on it via ``run_until_complete``.
    """
    global _EVENT_LOOP
    if _EVENT_LOOP is None or _EVENT_LOOP.is_closed():
        _EVENT_LOOP = asyncio.new_event_loop()
    return _EVENT_LOOP


def _get_or_create_gateway() -> Any:
    """Lazy-init the singleton ``QwenInferenceGateway`` instance.

    Import is delayed to first call so that importing this module doesn't drag
    the L3 qwen_vllm subtree into every ingestion run. Thread-safe via a
    module-level lock; safe for concurrent contextualization (builder is
    currently sequential per-chunk, but future batching will need this).
    """
    global _GATEWAY_INSTANCE
    if _GATEWAY_INSTANCE is not None:
        return _GATEWAY_INSTANCE
    with _GATEWAY_LOCK:
        if _GATEWAY_INSTANCE is not None:
            return _GATEWAY_INSTANCE
        try:
            from agentic_core.L3_orchestration.inference.qwen_vllm.reasoning.qwen_inference_gateway import (  # noqa: PLC0415, E501
                QwenInferenceGateway,
            )
        except ImportError as exc:
            raise RuntimeError(
                f"QwenContextGateway could not import QwenInferenceGateway: {exc}"
            ) from exc
        model_id, base_url = _resolve_defaults()
        _GATEWAY_INSTANCE = QwenInferenceGateway(
            model_id=model_id,
            base_url=base_url,
            # Low concurrency for contextualization: per-chunk calls are
            # sequential from the builder today; raise to 4-8 when the builder
            # adopts batch submission.
            max_concurrent=2,
            batch_size=1,
        )
        Logger.info(
            "QwenContextGateway initialized: model=%s, url=%s",
            model_id,
            base_url,
        )
        return _GATEWAY_INSTANCE


class QwenContextGateway:
    """Minimal ``_GatewayProtocol`` adapter routing through QwenInferenceGateway.

    Thread-safety: uses a module-level event loop + lock so concurrent
    ``generate`` calls serialize through the shared gateway; suitable for the
    current sequential per-chunk builder. A future batch-mode builder should
    bypass this adapter and call ``QwenInferenceGateway.infer_batch`` directly.
    """

    def __init__(self, *, default_model: str | None = None) -> None:
        self._default_model = default_model

    def generate(
        self,
        prompt: str,
        *,
        model: str,
        max_tokens: int,
        temperature: float,
        timeout_s: int,
    ) -> str:
        """Generate a contextualization narrative via the local Qwen vLLM server.

        Args:
            prompt: Flat prompt string. ``ContextualChunkBuilder`` inlines the
                ``<document>`` / ``<chunk>`` tags into this string.
            model: Model id passed by the builder. Ignored in favor of the
                L0-registry SSOT model (Qwen vLLM serves exactly one model per
                running server instance; picking a different model at call
                time is a no-op).
            max_tokens: Upper bound on generated context. Builder default is
                150; sufficient for 50-100 token contexts.
            temperature: Sampling temperature. Builder passes 0.0 for
                determinism; forwarded as-is.
            timeout_s: Per-call timeout. Note: ``QwenInferenceRequest`` does
                not currently expose a per-request timeout; the underlying
                ``OptimizedVLLMClient`` enforces its own request timeout. If
                the vLLM server hangs, the builder's own catch of
                ``RuntimeError`` covers it.

        Returns:
            Generated text. Empty string on empty response.

        Raises:
            RuntimeError: Any transport, import, or inference failure.
                ``ContextualChunkBuilder.build`` catches this and falls back
                to the heuristic path.
        """
        # Import locally to avoid L3 subtree load at module import time.
        try:
            from agentic_core.L3_orchestration.inference.qwen_vllm.reasoning.qwen_inference_gateway import (  # noqa: PLC0415, E501
                QwenInferenceRequest,
            )
        except ImportError as exc:
            raise RuntimeError(
                f"QwenContextGateway could not import QwenInferenceRequest: {exc}"
            ) from exc

        try:
            gateway = _get_or_create_gateway()
        except RuntimeError:
            raise  # propagate import/init failures verbatim
        except (ValueError, OSError) as exc:
            raise RuntimeError(
                f"QwenContextGateway failed to initialize gateway: {exc}"
            ) from exc

        request = QwenInferenceRequest(
            app_name="contextual_chunk_builder",
            prompt=prompt,
            # ``confidence_threshold`` is ignored by ``infer()`` for routing;
            # 0.0 signals "accept any non-empty response" which matches our
            # builder contract (empty string on refusal, not an exception).
            confidence_threshold=0.0,
            max_tokens=max_tokens,
            temperature=temperature,
            use_cache=True,
        )

        loop = _get_or_create_loop()
        try:
            response = loop.run_until_complete(gateway.infer(request))
        except (RuntimeError, ValueError, OSError, asyncio.TimeoutError) as exc:
            Logger.warning(
                "QwenContextGateway.generate failed (model=%s, timeout=%ds): %s",
                model or self._default_model or "<registry-default>",
                timeout_s,
                exc,
            )
            raise RuntimeError(f"Qwen gateway generation failed: {exc}") from exc

        if not response.success:
            raise RuntimeError(
                f"Qwen gateway inference unsuccessful: {response.error_message}"
            )
        return response.response or ""


def build_from_env() -> QwenContextGateway | None:
    """Construct a gateway iff the local vLLM server is reachable, else None.

    Honors two opt-out knobs for CI / offline scenarios:
      * ``QWEN_CONTEXT_GATEWAY_DISABLED=1`` - skip probe, return None.
      * ``VLLM_BASE_URL`` unset/invalid - probe will fail, return None.

    The server-reachability probe is a 2-second GET against ``/models`` on the
    configured base URL. This avoids constructing a gateway (and failing
    noisily later) when the vLLM server is simply not running - mirroring the
    ``AnthropicContextGateway.build_from_env`` behavior where a missing API
    key yields a None gateway and clean heuristic fallback.

    Canonical usage in ingestion scripts:

        from tools.ingestion.qwen_context_gateway import build_from_env as build_qwen
        from tools.ingestion.contextual_chunk_builder import ContextualChunkBuilder

        gateway = build_qwen()  # or fall back to heuristic when None
        builder = ContextualChunkBuilder(gateway=gateway)
    """
    if os.environ.get("QWEN_CONTEXT_GATEWAY_DISABLED") == "1":
        Logger.info("QwenContextGateway disabled by QWEN_CONTEXT_GATEWAY_DISABLED=1")
        return None
    try:
        _, base_url = _resolve_defaults()
    except RuntimeError as exc:
        Logger.info("QwenContextGateway unavailable (SSOT resolve failed): %s", exc)
        return None
    if not _vllm_server_reachable(base_url):
        Logger.info(
            "QwenContextGateway unavailable: vLLM server not reachable at %s",
            base_url,
        )
        return None
    return QwenContextGateway()


__all__ = ["QwenContextGateway", "build_from_env"]


# Note: _GatewayProtocol in contextual_chunk_builder is a structural Protocol
# (not @runtime_checkable), so isinstance() is not available. Static type
# compatibility is verified by mypy on the generate() signature.
