"""Canonical apps_lic research terminal reason codes."""

from __future__ import annotations

from enum import Enum

APPS_RESEARCH_DEPRECATED = "APPS_RESEARCH_DEPRECATED"
APPS_RESEARCH_FAILED = "APPS_RESEARCH_FAILED"
APPS_RESEARCH_EMPTY = "APPS_RESEARCH_EMPTY"
APPS_RESEARCH_BLOCKED = "APPS_RESEARCH_BLOCKED"
APPS_RESEARCH_STALE = "APPS_RESEARCH_STALE"
APPS_RESEARCH_WEAK_SUPPORT = "APPS_RESEARCH_WEAK_SUPPORT"

RESEARCH_FAILURE_REASON_CODES = frozenset(
    {
        APPS_RESEARCH_FAILED,
        APPS_RESEARCH_EMPTY,
        APPS_RESEARCH_BLOCKED,
        APPS_RESEARCH_STALE,
        APPS_RESEARCH_WEAK_SUPPORT,
    }
)


class ResearchFailureReason(str, Enum):
    """Terminal research reason emitted by apps_lic research compatibility paths."""

    APPS_RESEARCH_DEPRECATED = APPS_RESEARCH_DEPRECATED
    APPS_RESEARCH_FAILED = APPS_RESEARCH_FAILED
    APPS_RESEARCH_EMPTY = APPS_RESEARCH_EMPTY
    APPS_RESEARCH_BLOCKED = APPS_RESEARCH_BLOCKED
    APPS_RESEARCH_STALE = APPS_RESEARCH_STALE
    APPS_RESEARCH_WEAK_SUPPORT = APPS_RESEARCH_WEAK_SUPPORT


__all__ = [
    "APPS_RESEARCH_BLOCKED",
    "APPS_RESEARCH_DEPRECATED",
    "APPS_RESEARCH_EMPTY",
    "APPS_RESEARCH_FAILED",
    "APPS_RESEARCH_STALE",
    "APPS_RESEARCH_WEAK_SUPPORT",
    "RESEARCH_FAILURE_REASON_CODES",
    "ResearchFailureReason",
]
