"""Proof-evidence test for 10C-REQ-175 (04_L2_Execute).

Severity      : CRITICAL
Surface       : 04_L2_Execute
Layer owner   : L2 execution
Artifact      : ExecutionResult
OTEL span     : l2.execution.prep
Source        : agentic_process_mapping_v38.md + best-practice gap analysis 2026-04-29 :: HITL-NEW-B pre-execution approval gate at L2 E2

Canonical requirement (paraphrased): L2 E2 Work-Order Check MUST refuse to admit a step into E3 execution when L1PlanContract.risk_tier in {T2_approve, T3_hard_stop} OR capabili...

Negative control text (from ledger row, paraphrased): Row-specific [10C-REQ-175]: ExecutionResult emitted without satisfying 'L2 E2 Work-Order Check MUST refuse to admit a step into E3 execution...

Generated by tools/requirements/generate_wave1_tests.py from
artifacts/requirements/wave1_critical_specs.json. Re-run the generator to
regenerate; do NOT hand-edit the rows that match the ledger spec.
"""

from __future__ import annotations

import pytest

from tests.fixtures.proof_evidence.otel_span_receipt import (
    BASE_REQUIRED_ATTRS,
    SpanAssertionError,
    assert_owner_surface_matches,
    assert_span_shape,
    make_receipt,
)
from tests.fixtures.proof_evidence.replay_digest import (
    assert_replay_drift_detected,
    assert_replay_stable,
)
from tests.fixtures.proof_evidence.runtime_artifact_validators import (
    ArtifactShapeError,
    assert_l2_execution_sealed,
    validate_artifact_shape,
)

REQ_ID = "10C-REQ-175"
OWNER_SURFACE = "04_L2_Execute"
EXPECTED_SPAN = "l2.execution.prep"
ARTIFACT_TYPE = "ExecutionResult"

# OTEL required attributes from the ledger row's otel_required_attributes
# column (pipe-delimited). BASE_REQUIRED_ATTRS already covers req_id, run_id,
# trace_id, request_id, owner_surface, policy_hash, blueprint_hash, replay_key.
EXTRA_SPAN_ATTRS = tuple(
    a for a in 'req_id|run_id|trace_id|request_id|owner_surface|policy_hash|blueprint_hash|replay_key|artifact_id'.split("|")
    if a and a not in BASE_REQUIRED_ATTRS
)
REQUIRED_ATTRS = BASE_REQUIRED_ATTRS + EXTRA_SPAN_ATTRS

def _valid_artifact() -> dict:
    return {
        "execution_id": "exec-175-001",
        "blueprint_hash": "blueprint-175-h",
        "policy_hash": "policy-175-h",
        "tool_calls": [],
        "side_effects_proposed": [],
        "replay_key": "replay-175-k",
        "owner_surface": OWNER_SURFACE,
        "no_durable_commit_assertion": True,
        "no_hitl_invocation_assertion": True,
        "no_routing_assertion": True,
    }

def _valid_span_attrs() -> dict:
    attrs = {
        "req_id": REQ_ID,
        "run_id": "run-175-001",
        "trace_id": "trace-175-001",
        "request_id": "req-175-001",
        "owner_surface": OWNER_SURFACE,
        "policy_hash": "policy-175-h",
        "blueprint_hash": "blueprint-175-h",
        "replay_key": "replay-175-k",
    }
    # Add any extra row-required span attrs with deterministic placeholders.
    for a in EXTRA_SPAN_ATTRS:
        attrs.setdefault(a, f"{a}-175-v")
    return attrs


# ---------------------------------------------------------------------------
# Positive controls
# ---------------------------------------------------------------------------

def test_artifact_shape_positive() -> None:
    """A well-formed ExecutionResult must validate cleanly + satisfy boundary invariant."""
    record = _valid_artifact()
    validate_artifact_shape(ARTIFACT_TYPE, record)
    assert_l2_execution_sealed(record)


def test_span_shape_positive() -> None:
    """The l2.execution.prep span must carry all required attrs."""
    receipt = make_receipt(EXPECTED_SPAN, _valid_span_attrs())
    assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)
    assert_owner_surface_matches(receipt, OWNER_SURFACE)


def test_replay_digest_stability_positive() -> None:
    """Same artifact yields the same digest across runs."""
    digest = assert_replay_stable(_valid_artifact())
    assert len(digest) == 64  # sha256 hex


# ---------------------------------------------------------------------------
# Negative controls (matches negative_control_specific from the ledger row)
# ---------------------------------------------------------------------------

def test_negative_control_specific_violation() -> None:
    """10C-REQ-175: per ledger row, a ExecutionResult that violates the canonical
    requirement MUST raise. Drift inducer: no_durable_commit_assertion.
    """
    record = _valid_artifact()
    record["no_durable_commit_assertion"] = False
    with pytest.raises(ArtifactShapeError):
        assert_l2_execution_sealed(record)


def test_negative_control_missing_required_field() -> None:
    """A ExecutionResult missing the required field 'execution_id' MUST fail shape validation."""
    record = _valid_artifact()
    del record['execution_id']
    with pytest.raises(ArtifactShapeError) as excinfo:
        validate_artifact_shape(ARTIFACT_TYPE, record)
    assert 'execution_id' in str(excinfo.value)


def test_negative_control_span_missing_owner_surface() -> None:
    """Span without owner_surface MUST fail shape assertion."""
    attrs = _valid_span_attrs()
    del attrs["owner_surface"]
    receipt = make_receipt(EXPECTED_SPAN, attrs)
    with pytest.raises(SpanAssertionError):
        assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)


def test_negative_control_replay_drift() -> None:
    """Two semantically different artifacts MUST produce different digests."""
    a = _valid_artifact()
    b = _valid_artifact()
    # Mutate a deterministic field that participates in the digest.
    if "owner_surface" in b:
        b["owner_surface"] = OWNER_SURFACE + "-DRIFTED"
    assert_replay_drift_detected(a, b)
