# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

import pytest


from workflow.runner import run_workflow


def test_latency_smoke(benchmark, case):
    out = benchmark(lambda: run_workflow({"resume": case, "jd":"perf"}))
    assert out is not None
