"""
01_agentic_core/L2_execution/P3_aggregate/execute-actions/use/perform.py
AUTO-HARDENED BY ZERO-LOSS MERGE ENGINE
L5 CANONICAL — WINDSURF Ω — 2025-12-07
MERKLE-INTENDED: d0b6da530118f776fe8fb6ea4e9a0f2ea15ac24353fb0a6d3fd3cd5692d77588
"""


from __future__ import annotations
# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

import pytest


from workflow.runner import run_workflow


def test_latency_smoke(benchmark, case):
    out = benchmark(lambda: run_workflow({"resume": case, "jd":"perf"}))
    assert out is not None
