# canon_keys.py

def get_keys_as_prompt() -> str:
    """Returns the 50 Keys of the Subatomic Canon."""
    KEYS = [
        "1. COGNITIVE SEPARATION: The Cognitive Plane (Thinking) must be isolated from the Action Plane (Doing).",
        "2. NO IMPLICIT STATE: All function arguments must be explicit. No global state.",
        "3. TOOL WHITELIST: Actions must only use approved tools defined in ActionNode.",
        "4. NO HALLUCINATION: Plans must reference specific Canon IDs.",
        "5. JSON STRICTNESS: Inter-node communication must strictly adhere to JSON schemas.",
        "6. IDEMPOTENCY: All Action Tools must be idempotent.",
        "7. OBSERVABILITY: Every execution step must log start, end, and status.",
        "8. FAILURE ATOMICITY: If a step fails, the system must fail safe.",
        "9. NO INFINITE LOOPS: Recursive self-calls are forbidden.",
        "10. SECURITY SANDBOX: File operations are restricted to the workspace.",
        "11. EXPLICIT DEPENDENCIES: All imports and dependencies must be declared explicitly.",
        "12. NO SIDE EFFECTS: Functions must not modify external state without explicit declaration.",
        "13. IMMUTABLE CONFIGURATION: Configuration values must be immutable after initialization.",
        "14. ATOMIC TRANSACTIONS: Multi-step operations must be atomic - all succeed or all fail.",
        "15. TIMEOUT PROTECTION: All operations must have reasonable timeouts.",
        "16. RATE LIMITING: API calls must be rate-limited to prevent abuse.",
        "17. ERROR PROPAGATION: Errors must be explicitly handled and propagated.",
        "18. RESOURCE CLEANUP: All resources must be cleaned up after use.",
        "19. TYPE SAFETY: All function signatures must specify types.",
        "20. NULL SAFETY: Null/None values must be explicitly handled.",
        "21. IMMUTABLE LOG: Audit logs must be append-only and immutable.",
        "22. SECURE CREDENTIALS: API keys and secrets must never be logged or exposed.",
        "23. MINIMAL PRIVILEGE: Operations must request only necessary permissions.",
        "24. DETERMINISTIC OUTPUT: Same inputs must produce same outputs.",
        "25. VERSIONED INTERFACES: All APIs must be versioned.",
        "26. BACKWARD COMPATIBILITY: New versions must support old interfaces.",
        "27. GRACEFUL DEGRADATION: Systems must degrade gracefully when components fail.",
        "28. CIRCUIT BREAKER: Failing services must be isolated with circuit breakers.",
        "29. CACHE CONSISTENCY: Cache invalidation must be consistent across nodes.",
        "30. EVENTUAL CONSISTENCY: Distributed state must converge to consistency.",
        "31. IMMUTABLE HISTORY: Historical data must never be modified.",
        "32. ENCRYPTED TRANSIT: All network communication must be encrypted.",
        "33. ENCRYPTED AT REST: Sensitive data must be encrypted at rest.",
        "34. AUDIT TRAIL: All actions must have an immutable audit trail.",
        "35. SINGLE RESPONSIBILITY: Each module must have one clear responsibility.",
        "36. LOOSE COUPLING: Modules must depend on abstractions, not implementations.",
        "37. HIGH COHESION: Related functionality must be grouped together.",
        "38. DEPENDENCY INJECTION: Dependencies must be injected, not hard-coded.",
        "39. INTERFACE SEGREGATION: Interfaces must be small and specific.",
        "40. LISKOV SUBSTITUTION: Subtypes must be substitutable for base types.",
        "41. OPEN/CLOSED PRINCIPLE: Modules must be open for extension, closed for modification.",
        "42. COMPOSITION OVER INHERITANCE: Prefer composition to inheritance.",
        "43. DON'T REPEAT YOURSELF: No duplicated logic.",
        "44. YOU AREN'T GONNA NEED IT: Don't implement features until needed.",
        "45. KEEP IT SIMPLE: Simple solutions are preferred over complex ones.",
        "46. EARLY RETURN: Return early from functions to reduce nesting.",
        "47. AVOID MAGIC NUMBERS: All constants must be named and documented.",
        "48. DOCUMENTED CODE: All non-obvious code must have comments.",
        "49. TESTED CODE: All code must have corresponding tests.",
        "50. HUMAN IN THE LOOP: High-risk actions require confirmation."
    ]
    return "\n".join(KEYS)

