#!/usr/bin/env python3
"""
canon_validator.py — SUBATOMIC CANON 2026 — 50/50 STRICT ENFORCEMENT

This file implements a *non-destructive*, internally consistent, 50-key
validation canon for the Agentic-Workflow repo.

STATUS: STRICT MODE
- All 50 Keys Active.
- No Deprecations.
- No Skipped Checks.
- Zero Tolerance for Stubs, Debt, or Sprawl.
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import sys
import time
from collections import defaultdict, deque
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Set, Tuple

# =====================================================================
# CORE CONFIGURATION
# =====================================================================

def _find_project_root() -> Path:
    """Robust root finding via marker files."""
    current = Path(__file__).resolve().parent
    for _ in range(4):
        if (current / ".git").is_dir() or (current / "data").is_dir():
            return current
        if current.parent == current:
            break
        current = current.parent
    return Path(__file__).resolve().parent

ROOT: Path = _find_project_root()
DATA_FOLDER_NAME = "data"

# Sovereign domains – full canon applies
SOVEREIGN_DIRS: Set[str] = {
    "agentic_core",
    "apps_lic",
    "apps_rg",
    "apps_shared",
    "schemas",
    "prompt_governance",
    "observability",
    "config",
    "shared",
    "scripts",
}

# Directories excluded from ALL canon checks
EXCLUDED_DIRS: Set[str] = {"data", "archives"}

# "Layered" sovereign domains that must obey L1/L2/L3 structure
LAYERED_SOVEREIGN_DIRS: Set[str] = {"agentic_core", "apps_lic", "apps_rg"}

# Allowed layers in layered sovereign domains
ALLOWED_LAYERS: Tuple[str, ...] = ("L1_cognition", "L2_execution", "L3_orchestration")

# Forbidden directory names anywhere under sovereign dirs
FORBIDDEN_FOLDER_NAMES: Set[str] = {
    "utils", "helpers", "common", "misc", "lib", "libs", "modules",
    "inner", "wrapper", "base", "abstract", "legacy", "old", "temp",
    "tmp", "backup", "archive", "v1", "v2", "v3", "final", "new",
    "test", "tests", "testing", "__pycache__",
}

# Banned filename tokens (Strict Key 09)
BANNED_FILENAME_TOKENS: Set[str] = {
    "ops", "utils", "helper", "common", "misc", "general", "base",
    "abstract", "legacy", "module", "unit", "dedup_pointer",
}

# Banned symbol prefixes (Key 10)
BANNED_SYMBOL_PREFIXES: Set[str] = {
    "tmp_", "temp_", "helper_", "misc_", "util_", "do_", "my_",
}

# Banned vocabulary in comments/strings (Strict Key 11)
BANNED_VOCABULARY: Set[str] = {
    "utility", "util", "misc", "magic", "wrapper", "base", "common",
    "general", "abstract", "manager", "handler", "processor", "service",
    "controller", "factory", "monolith", "legacy", "old", "temp", "tmp",
}

# Poison markers for stub / placeholder content (Strict Key 17)
POISON_MARKERS: List[str] = [
    "auto-generated", "auto generated", "ssot",
    "stub file", "stub module", "to satisfy", "generated by ai",
    "not implemented", "insert logic here", "skeleton",
    "boilerplate", "empty implementation", "needs implementation",
]

# TODO/FIXME/HACK etc (Strict Key 12)
TODO_PATTERN = re.compile(r"\b(TODO|FIXME|HACK|XXX|STUB|WIP)\b", re.IGNORECASE)

# === ETERNAL CANON CONSTANTS ===
MIN_SOVEREIGN_BYTES = 50 
MAX_SOVEREIGN_BYTES = 60_000
MAX_FUNCTION_LINES = 150
MAX_NESTING_DEPTH = 5
MAX_ANY_FILE_DEPTH = 5
MAX_TOP_LEVEL_DEFS = 5  # Cognitive Density Limit

# Strict Magic Number Allowlist (Key 14)
ALLOWED_MAGIC_NUMBERS: Set[int] = {
    0, 1, -1, 100, 200, 400, 401, 403, 404, 500,  # HTTP/Common
    60, 300, 600, 3600, 86400,                    # Time
    1024, 2048, 4096, 8192, 16384,                # Bytes
    80, 443, 8000, 8080, 3000, 5000,              # Ports
    1536, 512, 768,                               # Embeddings
}

# Allowed .py files at project root
ALLOWED_ROOT_SCRIPTS = {
    "canon_validator.py", "run_agent.py", "dev_runner.py", "install.py",
    "setup.py", "docstring_debt.py", "verify_installation.py",
    "fix_canon_violations.py", "__init__.py",
}

MAX_BINARY_BYTES = 10 * 1024 * 1024
results: Dict[str, Tuple[bool, str]] = {}
DELETED_SOVEREIGN_FILES: Set[Path] = set()
RENAMED_SOVEREIGN_FILES: Set[Tuple[Path, Path]] = set()

# =====================================================================
# SINGLE-PASS REPOSITORY CONTEXT
# =====================================================================

@dataclass
class FileData:
    path: Path
    rel_path: str
    content: str
    lines: List[str]
    tree: Optional[ast.AST]
    size: int
    depth: int
    semantic_depth: int
    is_generated: bool = False

SOV_FILES: List[FileData] = []
SOV_INIT_FILES: List[FileData] = []
LIGHT_FILES: List[FileData] = []
ALL_PY_FILES: List[FileData] = []
ALL_DIRS: List[Path] = []
_REPO_HYDRATED: bool = False

def _is_generated_content(content: str) -> bool:
    lower = content[:2000].lower()
    markers = [
        "auto-generated", "generated by", "hydrated via",
        "do not edit", "autogenerated", "machine generated",
        "auto-hardened", "auto-populated",
    ]
    return any(m in lower for m in markers)

def hydrate_repo_data() -> None:
    global SOV_FILES, SOV_INIT_FILES, LIGHT_FILES, ALL_PY_FILES, ALL_DIRS, _REPO_HYDRATED
    if _REPO_HYDRATED: return
    
    SOV_FILES.clear(); SOV_INIT_FILES.clear(); LIGHT_FILES.clear(); ALL_PY_FILES.clear(); ALL_DIRS.clear()
    sov_roots = {d for d in SOVEREIGN_DIRS if (ROOT / d).is_dir()}
    excluded = {".git", "__pycache__", "node_modules", ".venv"} | EXCLUDED_DIRS
    
    for item in ROOT.rglob("*"):
        if any(ex in item.parts for ex in excluded): continue
        if item.is_dir():
            ALL_DIRS.append(item)
            continue
        if not item.is_file() or item.suffix != ".py": continue
        
        try: content = item.read_bytes().decode("utf-8", errors="replace")
        except: content = ""
        try: tree = ast.parse(content)
        except SyntaxError: tree = None
        
        rel = item.relative_to(ROOT)
        parts = rel.parts
        file_data = FileData(
            path=item, rel_path=str(rel), content=content, lines=content.splitlines(),
            tree=tree, size=len(content.encode("utf-8")), depth=len(parts),
            semantic_depth=semantic_depth(parts), is_generated=_is_generated_content(content),
        )
        ALL_PY_FILES.append(file_data)
        is_sov = parts and parts[0] in sov_roots
        if is_sov:
            if item.name == "__init__.py": SOV_INIT_FILES.append(file_data)
            else: SOV_FILES.append(file_data)
        else:
            if item.name != "__init__.py": LIGHT_FILES.append(file_data)
    _REPO_HYDRATED = True

def get_file_data(path: Path) -> Optional[FileData]:
    for fd in ALL_PY_FILES:
        if fd.path == path: return fd
    return None

# =====================================================================
# HELPERS
# =====================================================================

def success(key: str, msg: str = "PASS") -> None: results[key] = (True, msg)
def fail(key: str, msg: str) -> None: results[key] = (False, msg)

def semantic_depth(parts: Tuple[str, ...]) -> int:
    """Calculate semantic depth, ignoring virtual namespace prefixes."""
    # Strip virtual namespace prefixes like L1_, L2_, L3_, P1_, P2_, etc.
    cleaned = []
    for part in parts:
        # Remove common namespace prefixes
        if re.match(r"^[LPT]\d+_.*", part):
            # Keep the part after the prefix
            cleaned.append(part.split('_', 1)[1])
        else:
            cleaned.append(part)
    return len(cleaned) - 1  # depth is parts-1

def is_globally_excluded(rel_path: Path) -> bool:
    """Check if a path is in the global exclusion list."""
    parts = rel_path.parts
    return any(ex in parts for ex in EXCLUDED_DIRS | {".git", "__pycache__", "node_modules", ".venv"})

def is_sovereign_path(path: Path) -> bool:
    """Check if path is under a sovereign directory."""
    rel = path.relative_to(ROOT)
    return rel.parts and rel.parts[0] in SOVEREIGN_DIRS

def sovereign_roots() -> Iterable[Path]:
    """Get all sovereign directory roots that exist."""
    for d in SOVEREIGN_DIRS:
        root = ROOT / d
        if root.is_dir():
            yield root

def iter_sovereign_py_files() -> Iterable[Path]:
    """Iterate over all Python files in sovereign directories."""
    for root in sovereign_roots():
        for f in root.rglob("*.py"):
            if f.is_file():
                yield f

def parse_ast(file_path: Path) -> Optional[ast.AST]:
    """Parse AST from file path with error handling."""
    try:
        return ast.parse(read_file(file_path))
    except (SyntaxError, OSError):
        return None

def read_file(path: Path) -> str:
    """Read file content with error handling."""
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""

def load_change_tracker_from_env() -> None:
    """Load pre-commit deletion/rename tracking from environment."""
    global DELETED_SOVEREIGN_FILES, RENAMED_SOVEREIGN_FILES
    tracker_path = os.environ.get("CANON_CHANGE_TRACKER")
    if not tracker_path or not Path(tracker_path).is_file():
        return
    
    try:
        import json
        with open(tracker_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        DELETED_SOVEREIGN_FILES = {Path(p) for p in data.get("deleted", [])}
        RENAMED_SOVEREIGN_FILES = {(Path(s), Path(t)) for s, t in data.get("renamed", [])}
    except Exception:
        pass  # Silently ignore tracking errors

# ---------------------------------------------------------------------
# KEYS 01–08 : SOVEREIGN IMMUTABILITY & FOUNDATIONS
# ---------------------------------------------------------------------

def check_key_01_no_sovereign_deletions() -> None:
    """
    Key 01 – No sovereign files deleted since last commit.
    
    Uses pre-commit hook environment variable CANON_CHANGE_TRACKER
    to track deleted sovereign files.
    """
    if not DELETED_SOVEREIGN_FILES:
        success("01", "No sovereign file deletions detected")
        return
    
    violations = [str(f.relative_to(ROOT)) for f in DELETED_SOVEREIGN_FILES]
    fail(
        "01",
        "SOVEREIGN FILE DELETIONS DETECTED:\n"
        + "\n".join(f"  - {v}" for v in violations[:20])
        + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
    )

def check_key_02_no_sovereign_renames() -> None:
    """
    Key 02 – No sovereign files renamed since last commit.
    
    Uses pre-commit hook environment variable CANON_CHANGE_TRACKER
    to track renamed sovereign files.
    """
    if not RENAMED_SOVEREIGN_FILES:
        success("02", "No sovereign file renames detected")
        return
    
    violations = [f"{src.relative_to(ROOT)} -> {dst.relative_to(ROOT)}" 
                  for src, dst in RENAMED_SOVEREIGN_FILES]
    fail(
        "02",
        "SOVEREIGN FILE RENAMES DETECTED:\n"
        + "\n".join(f"  - {v}" for v in violations[:20])
        + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
    )

def check_key_03_data_folder_exists() -> None:
    """Key 03 – data/ folder must exist at project root."""
    data_folder = ROOT / DATA_FOLDER_NAME
    if data_folder.is_dir():
        success("03", f"data/ folder exists at root")
    else:
        fail("03", f"data/ folder missing at project root")

def check_key_04_no_zombie_archive_singular_root() -> None:
    """
    Key 04 – No stray 'archive' (singular) directories at root or anywhere.
    
    Only 'archives/' (plural) is allowed as the official archive location.
    """
    violations: List[str] = []
    
    # Check root level first
    root_archive = ROOT / "archive"
    if root_archive.is_dir():
        violations.append("archive/ at project root")
    
    # Check anywhere in tree (but not inside archives/)
    for d in ROOT.rglob("archive"):
        if d.is_dir():
            rel_path = d.relative_to(ROOT)
            # Skip if it's inside the archives/ directory
            if "archives" in rel_path.parts:
                continue
            violations.append(f"archive/ directory: {rel_path}")
    
    if violations:
        fail("04", "UNAUTHORIZED ARCHIVE DIRECTORIES:\n" + "\n".join(f"  - {v}" for v in violations))
    else:
        success("04", "No unauthorized 'archive' directories")

def check_key_05_layered_structure_sane() -> None:
    """
    Key 05 – Layered sovereign domains must obey L1/L2/L3 structure.
    
    Only agentic_core, apps_lic, and apps_rg are layered domains.
    They may only contain L1_cognition, L2_execution, L3_orchestration.
    """
    violations: List[str] = []
    
    for domain in LAYERED_SOVEREIGN_DIRS:
        domain_path = ROOT / domain
        if not domain_path.is_dir():
            continue
        
        # Get immediate children
        for child in domain_path.iterdir():
            if not child.is_dir():
                continue
            name = child.name
            
            # Skip __pycache__ and other non-layer dirs
            if name in FORBIDDEN_FOLDER_NAMES or name.startswith("."):
                continue
            
            # Check if it's an allowed layer
            if name not in ALLOWED_LAYERS:
                violations.append(f"{domain}/{name} -> invalid layer (must be one of {ALLOWED_LAYERS})")
    
    if violations:
        fail("05", "LAYERED STRUCTURE VIOLATIONS:\n" + "\n".join(f"  - {v}" for v in violations))
    else:
        success("05", "Layered sovereign domains obey L1/L2/L3 structure")

def check_key_06_no_forbidden_folder_names() -> None:
    """
    Key 06 – Forbidden folder names not allowed under sovereign dirs.
    
    Generic utility folders like 'utils', 'helpers', 'common' etc.
    are forbidden to prevent architectural debt.
    """
    violations: List[str] = []
    
    for root in sovereign_roots():
        for folder in root.rglob("*"):
            if not folder.is_dir():
                continue
            name = folder.name
            if name in FORBIDDEN_FOLDER_NAMES:
                violations.append(str(folder.relative_to(ROOT)))
    
    if violations:
        fail(
            "06",
            "FORBIDDEN FOLDER NAMES IN SOVEREIGN DOMAINS:\n"
            + "\n".join(f"  - {v}" for v in violations[:40])
            + (f"\n  ... and {len(violations) - 40} more" if len(violations) > 40 else ""),
        )
    else:
        success("06", "No forbidden folder names in sovereign domains")

def check_key_07_required_root_folders() -> None:
    """
    Key 07 – Required sovereign directories must exist.
    
    These are the core architectural pillars of the system.
    """
    missing: List[str] = []
    
    for req_dir in SOVEREIGN_DIRS:
        if not (ROOT / req_dir).is_dir():
            missing.append(req_dir)
    
    if missing:
        fail("07", f"Missing required sovereign directories: {', '.join(missing)}")
    else:
        success("07", "All required sovereign directories present")

def check_key_08_no_empty_sov_roots() -> None:
    """
    Key 08 – No empty sovereign root directories.
    
    Each sovereign domain must contain at least one file or subdirectory.
    """
    empty: List[str] = []
    
    for root in sovereign_roots():
        try:
            items = list(root.iterdir())
            # Filter out dotfiles and __pycache__
            real_items = [i for i in items if not i.name.startswith(".") and i.name != "__pycache__"]
            if not real_items:
                empty.append(root.name)
        except OSError:
            empty.append(root.name)
    
    if empty:
        fail("08", f"Empty sovereign root directories: {', '.join(empty)}")
    else:
        success("08", "All sovereign root directories contain content")

# ---------------------------------------------------------------------
# KEYS 09–18 : SOVEREIGN NAMING, VOCABULARY & COMMENTS
# ---------------------------------------------------------------------

def check_key_09_banned_tokens_in_filenames() -> None:
    """
    Key 09 – Banned tokens in sovereign filenames (STRICT).
    
    Filenames may not contain generic utility tokens like 'utils', 'helper', etc.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        if f.name == "__init__.py":
            continue
        
        stem_tokens = f.stem.lower().split('_')
        found = [t for t in stem_tokens if t in BANNED_FILENAME_TOKENS]
        if found:
            violations.append(f"{f.relative_to(ROOT)} ({', '.join(found)})")
    
    if violations:
        fail(
            "09",
            "BANNED FILENAME TOKENS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("09", "No banned filename tokens")

def check_key_10_banned_symbol_prefixes() -> None:
    """
    Key 10 – Banned prefixes for symbols in sovereign code.
    
    Symbols may not start with generic prefixes like 'tmp_', 'util_', etc.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Name)):
                name = node.name if isinstance(node, ast.Name) else node.name
                for prefix in BANNED_SYMBOL_PREFIXES:
                    if name.startswith(prefix):
                        violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – {name}")
                        break
    
    if violations:
        fail(
            "10",
            "BANNED SYMBOL PREFIXES:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("10", "No banned symbol prefixes")

def check_key_11_banned_vocabulary() -> None:
    """
    Key 11 – Banned vocabulary in sovereign comments/strings (STRICT).
    
    Generic architectural debt terms are forbidden in comments and strings.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        lower = content.lower()
        found = []
        
        for word in BANNED_VOCABULARY:
            if word in lower:
                # Find line numbers
                for i, line in enumerate(content.splitlines(), 1):
                    if word in line.lower():
                        found.append(f"{word} (line {i})")
                        break
        
        if found:
            violations.append(f"{f.relative_to(ROOT)} – {', '.join(found)}")
    
    if violations:
        fail(
            "11",
            "BANNED VOCABULARY IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("11", "No banned vocabulary")

def check_key_12_todo_fixme_comments() -> None:
    """
    Key 12 – No TODO/FIXME/HACK comments in sovereign code (STRICT).
    
    All technical debt must be tracked externally, not in code comments.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        matches = TODO_PATTERN.finditer(content)
        
        for match in matches:
            line_num = content[:match.start()].count('\n') + 1
            violations.append(f"{f.relative_to(ROOT)}:{line_num} – {match.group()}")
    
    if violations:
        fail(
            "12",
            "TODO/FIXME/HACK COMMENTS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("12", "No TODO/FIXME/HACK comments")

def check_key_13_hardcoded_paths() -> None:
    """
    Key 13 – No hardcoded absolute paths in sovereign code.
    
    All paths must be relative or derived from configuration.
    """
    violations: List[str] = []
    # Pattern matches Windows and Unix absolute paths
    path_pattern = re.compile(r'["\']([A-Za-z]:[/\\]|/)[^"\']+\.(py|json|yaml|txt|csv)["\']')
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        matches = path_pattern.finditer(content)
        
        for match in matches:
            line_num = content[:match.start()].count('\n') + 1
            violations.append(f"{f.relative_to(ROOT)}:{line_num} – {match.group()}")
    
    if violations:
        fail(
            "13",
            "HARDCODED ABSOLUTE PATHS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("13", "No hardcoded absolute paths")

def check_key_14_magic_numbers() -> None:
    """
    Key 14 – Magic numbers must be on allowlist (STRICT).
    
    Unnamed numeric literals must be from the allowed set.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
                # Skip if it's a known allowed value
                if node.value in ALLOWED_MAGIC_NUMBERS:
                    continue
                # Skip if it's 0 or 1 (commonly used)
                if node.value in (0, 1, -1):
                    continue
                
                line_num = getattr(node, 'lineno', 0)
                violations.append(f"{f.relative_to(ROOT)}:{line_num} – {node.value}")
    
    if violations:
        fail(
            "14",
            "MAGIC NUMBERS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("14", "No magic numbers outside allowlist")

def check_key_15_bare_except() -> None:
    """
    Key 15 – No bare except clauses in sovereign code.
    
    All except clauses must specify exception types.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler) and node.type is None:
                violations.append(f"{f.relative_to(ROOT)}:{node.lineno}")
    
    if violations:
        fail(
            "15",
            "BARE EXCEPT CLAUSES IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("15", "No bare except clauses")

def check_key_16_eval_exec_usage() -> None:
    """
    Key 16 – No eval() or exec() in sovereign code.
    
    Dynamic code execution is forbidden for security.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name):
                if node.func.id in ('eval', 'exec'):
                    violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – {node.func.id}()")
    
    if violations:
        fail(
            "16",
            "EVAL/EXEC USAGE IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("16", "No eval() or exec() usage")

def check_key_17_poison_markers_and_stubs() -> None:
    """
    Key 17 – No poison markers or stub content in sovereign code (STRICT).
    
    Markers like 'auto-generated', 'stub', 'not implemented' are forbidden.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f).lower()
        found = []
        
        for marker in POISON_MARKERS:
            if marker in content:
                # Find line numbers
                for i, line in enumerate(content.splitlines(), 1):
                    if marker in line:
                        found.append(f"{marker} (line {i})")
                        break
        
        if found:
            violations.append(f"{f.relative_to(ROOT)} – {', '.join(found)}")
    
    if violations:
        fail(
            "17",
            "POISON MARKERS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("17", "No poison markers or stub content")

def check_key_18_sovereign_debug_statements() -> None:
    """
    Key 18 – No debug statements in sovereign code.
    
    print(), pdb, breakpoint() etc. are forbidden in production code.
    """
    debug_patterns = [
        r"\bprint\s*\(",
        r"\bpdb\.",
        r"\bipdb\.",
        r"\bbreakpoint\s*\(",
        r"\bset_trace\s*\(",
    ]
    compiled = [re.compile(p) for p in debug_patterns]
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        if any(p.search(content) for p in compiled):
            violations.append(str(f.relative_to(ROOT)))
    
    if violations:
        fail(
            "18",
            "DEBUG STATEMENTS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("18", "No debug statements in sovereign code")

# ---------------------------------------------------------------------
# KEYS 19–26 : SOVEREIGN AST / IMPORT HYGIENE
# ---------------------------------------------------------------------

def check_key_19_duplicate_functions() -> None:
    """
    Key 19 – No duplicate function names in sovereign directories.
    
    Each sovereign directory must have unique function names.
    """
    violations: List[str] = []
    func_map: Dict[str, List[Tuple[Path, int]]] = defaultdict(list)
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                func_map[node.name].append((f, getattr(node, 'lineno', 0)))
    
    for func_name, locations in func_map.items():
        if len(locations) > 1:
            # Skip __init__ and other dunder methods
            if func_name.startswith('__') and func_name.endswith('__'):
                continue
            loc_strs = [f"{loc[0].relative_to(ROOT)}:{loc[1]}" for loc in locations]
            violations.append(f"{func_name} – {', '.join(loc_strs)}")
    
    if violations:
        fail(
            "19",
            "DUPLICATE FUNCTION NAMES IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("19", "No duplicate function names")

def check_key_20_duplicate_classes() -> None:
    """
    Key 20 – No duplicate class names in sovereign directories.
    
    Each sovereign directory must have unique class names.
    """
    violations: List[str] = []
    class_map: Dict[str, List[Tuple[Path, int]]] = defaultdict(list)
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef):
                class_map[node.name].append((f, getattr(node, 'lineno', 0)))
    
    for class_name, locations in class_map.items():
        if len(locations) > 1:
            loc_strs = [f"{loc[0].relative_to(ROOT)}:{loc[1]}" for loc in locations]
            violations.append(f"{class_name} – {', '.join(loc_strs)}")
    
    if violations:
        fail(
            "20",
            "DUPLICATE CLASS NAMES IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("20", "No duplicate class names")

def check_key_21_circular_imports() -> None:
    """
    Key 21 – No circular imports in sovereign code.
    
    Circular dependencies are forbidden for architectural clarity.
    """
    violations: List[str] = []
    import_graph: Dict[str, Set[str]] = defaultdict(set)
    
    # Build import graph
    for f in iter_sovereign_py_files():
        rel_path = str(f.relative_to(ROOT))
        module_name = rel_path.replace('/', '.').replace('.py', '')
        
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name.startswith('agentic_workflow'):
                        import_graph[module_name].add(alias.name)
            elif isinstance(node, ast.ImportFrom):
                if node.module and node.module.startswith('agentic_workflow'):
                    import_graph[module_name].add(node.module)
    
    # Detect cycles
    visited = set()
    rec_stack = set()
    
    def dfs(node: str, path: List[str]) -> bool:
        if node in rec_stack:
            # Found cycle
            cycle_start = path.index(node)
            cycle = path[cycle_start:] + [node]
            violations.append(f"{' -> '.join(cycle)}")
            return True
        if node in visited:
            return False
        
        visited.add(node)
        rec_stack.add(node)
        
        for neighbor in import_graph.get(node, []):
            if dfs(neighbor, path + [node]):
                return True
        
        rec_stack.remove(node)
        return False
    
    for module in import_graph:
        if module not in visited:
            dfs(module, [])
    
    if violations:
        fail(
            "21",
            "CIRCULAR IMPORTS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:10])
            + (f"\n  ... and {len(violations) - 10} more" if len(violations) > 10 else ""),
        )
    else:
        success("21", "No circular imports")

def check_key_22_import_hygiene() -> None:
    """
    Key 22 – Import hygiene in sovereign code (STRICT).
    
    - No wildcard imports (from module import *)
    - No relative imports beyond one level
    - No imports from non-sovereign domains
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                # Check wildcard imports
                if node.names and any(alias.name == '*' for alias in node.names):
                    violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – wildcard import")
                
                # Check relative import depth
                if node.level > 1:
                    violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – deep relative import")
                
                # Check imports from non-sovereign domains
                if node.module and not node.module.startswith('agentic_workflow'):
                    # Skip standard library and common third-party
                    common_modules = {'os', 'sys', 'json', 're', 'pathlib', 'dataclasses', 
                                    'typing', 'collections', 'time', 'argparse', 'ast'}
                    if node.module.split('.')[0] not in common_modules:
                        violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – import from non-sovereign domain")
    
    if violations:
        fail(
            "22",
            "IMPORT HYGIENE VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("22", "Import hygiene satisfied")

def check_key_23_hardcoded_credentials() -> None:
    """
    Key 23 – No hardcoded credentials in sovereign code.
    
    Passwords, API keys, tokens must be in environment or config.
    """
    cred_patterns = [
        r'password\s*=\s*["\'][^"\']{8,}["\']',
        r'api_key\s*=\s*["\']sk-[A-Za-z0-9]{20,}["\']',
        r'secret\s*=\s*["\'][A-Za-z0-9]{16,}["\']',
        r'token\s*=\s*["\'][A-Za-z0-9]{20,}["\']',
    ]
    compiled = [re.compile(p, re.IGNORECASE) for p in cred_patterns]
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        if any(p.search(content) for p in compiled):
            violations.append(str(f.relative_to(ROOT)))
    
    if violations:
        fail(
            "23",
            "HARDCODED CREDENTIALS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("23", "No hardcoded credentials")

def check_key_24_sql_injection_patterns() -> None:
    """
    Key 24 – No SQL injection vulnerabilities in sovereign code.
    
    String formatting in SQL queries must use parameterized queries.
    """
    violations: List[str] = []
    sql_pattern = re.compile(r'(execute|query|select|insert|update|delete)\s*\(\s*["\'].*%.*["\']')
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        content = read_file(f)
        if sql_pattern.search(content):
            violations.append(str(f.relative_to(ROOT)))
    
    if violations:
        fail(
            "24",
            "POTENTIAL SQL INJECTION PATTERNS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("24", "No SQL injection patterns")

def check_key_25_hardcoded_urls() -> None:
    """
    Key 25 – No hardcoded URLs in sovereign code.
    
    URLs must be in configuration or environment variables.
    """
    url_pattern = re.compile(r'["\']https?://[^"\']+["\']')
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        content = read_file(f)
        matches = url_pattern.finditer(content)
        
        for match in matches:
            line_num = content[:match.start()].count('\n') + 1
            violations.append(f"{f.relative_to(ROOT)}:{line_num} – {match.group()}")
    
    if violations:
        fail(
            "25",
            "HARDCODED URLS IN SOVEREIGN CODE:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("25", "No hardcoded URLs")

def check_key_26_syntax_and_strict_typing() -> None:
    """
    Key 26 – All sovereign files must parse cleanly and use type hints (STRICT).
    
    - No syntax errors
    - Public functions must have type hints
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        # Check syntax
        try:
            tree = ast.parse(read_file(f))
        except SyntaxError as e:
            violations.append(f"{f.relative_to(ROOT)} – Syntax error: {e.msg}")
            continue
        
        # Check type hints for public functions
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                if not node.name.startswith('_'):
                    # Check return type annotation
                    if node.returns is None:
                        violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – {node.name}() missing return type")
                    
                    # Check argument type annotations
                    for arg in node.args.args:
                        if arg.annotation is None and arg.arg != 'self':
                            violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – {node.name}() arg {arg.arg} missing type")
    
    if violations:
        fail(
            "26",
            "SYNTAX OR TYPING VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("26", "All sovereign files parse cleanly with type hints")

# ---------------------------------------------------------------------
# KEYS 27–34 : SOVEREIGN SIZE, NESTING, PACKAGES
# ---------------------------------------------------------------------

def check_key_27_no_empty_sov_files() -> None:
    """
    Key 27 – No empty sovereign Python files.
    
    Every .py file in sovereign domains must contain actual code.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        if f.name == "__init__.py":
            continue
        
        content = read_file(f).strip()
        if len(content) < MIN_SOVEREIGN_BYTES:
            violations.append(f"{f.relative_to(ROOT)} – {len(content)} bytes")
    
    if violations:
        fail(
            "27",
            "EMPTY SOVEREIGN FILES:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("27", "No empty sovereign files")

def check_key_28_subatomic_file_size_law() -> None:
    """
    Key 28 – Sovereign files must respect size limits.
    
    Min 50 bytes, max 60KB per file.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        size = f.stat().st_size
        if size < MIN_SOVEREIGN_BYTES or size > MAX_SOVEREIGN_BYTES:
            violations.append(f"{f.relative_to(ROOT)} – {size} bytes")
    
    if violations:
        fail(
            "28",
            "SOVEREIGN FILE SIZE VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("28", "All sovereign files within size limits")

def check_key_29_function_length_limits() -> None:
    """
    Key 29 – Functions in sovereign code must not exceed 150 lines.
    
    Long functions indicate complexity that should be refactored.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                # Count lines excluding decorators and docstrings
                start_line = node.end_lineno if hasattr(node, 'end_lineno') else node.lineno
                if hasattr(node, 'end_lineno'):
                    length = node.end_lineno - node.lineno + 1
                else:
                    # Fallback: count lines in source
                    source = ast.get_source_segment(read_file(f), node) or ""
                    length = len(source.splitlines())
                
                if length > MAX_FUNCTION_LINES:
                    violations.append(f"{f.relative_to(ROOT)}:{node.lineno} – {node.name}() {length} lines")
    
    if violations:
        fail(
            "29",
            "FUNCTION LENGTH VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("29", "All functions within length limits")

def check_key_30_nesting_depth_limits() -> None:
    """
    Key 30 – Nesting depth must not exceed 5 levels in sovereign code.
    
    Deep nesting indicates complex control flow.
    """
    violations: List[str] = []
    
    def get_nesting_depth(node: ast.AST, current: int = 0) -> int:
        """Recursively calculate maximum nesting depth."""
        if isinstance(node, (ast.If, ast.While, ast.For, ast.With, ast.Try)):
            current += 1
            if current > MAX_NESTING_DEPTH:
                return current
        
        max_child = current
        for child in ast.iter_child_nodes(node):
            child_depth = get_nesting_depth(child, current)
            max_child = max(max_child, child_depth)
        
        return max_child
    
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        
        max_depth = get_nesting_depth(tree)
        if max_depth > MAX_NESTING_DEPTH:
            violations.append(f"{f.relative_to(ROOT)} – max depth {max_depth}")
    
    if violations:
        fail(
            "30",
            "NESTING DEPTH VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("30", "All code within nesting depth limits")

def check_key_31_max_path_depth_sov() -> None:
    """
    Key 31 – Sovereign path depth limit (STRICT).
    
    No sovereign file may exceed semantic depth 5.
    """
    violations: List[str] = []
    
    for f in iter_sovereign_py_files():
        depth = semantic_depth(f.relative_to(ROOT).parts)
        if depth > MAX_ANY_FILE_DEPTH:
            violations.append(f"{f.relative_to(ROOT)} – depth {depth}")
    
    if violations:
        fail(
            "31",
            "SOVEREIGN PATH DEPTH VIOLATIONS:\n"
            + "\n".join(f"  - {v}" for v in violations[:20])
            + (f"\n  ... and {len(violations) - 20} more" if len(violations) > 20 else ""),
        )
    else:
        success("31", "All sovereign files within depth limits")

def check_key_32_fake_nesting_names() -> None:
    """
    Key 32 – No fake nesting via smashed directory names.
    
    Directory names like 'utils_helpers_common' are forbidden.
    """
    violations: List[str] = []
    
    for root in sovereign_roots():
        for d in root.rglob("*"):
            if not d.is_dir():
                continue
            
            # Check for smashed names with multiple underscores
            if d.name.count('_') >= 2:
                # Skip legitimate layered directories
                if d.name in ALLOWED_LAYERS:
                    continue
                
                violations.append(str(d.relative_to(ROOT)))
    
    if violations:
        fail(
            "32",
            "Directory hygiene violations (fake nesting or smashed names):\n"
            + "\n".join(f"  - {v}" for v in violations[:40])
            + (f"\n  ... and {len(violations) - 40} more" if len(violations) > 40 else ""),
        )
    else:
        success("32", "No fake nesting directory names under sovereign roots")

def check_key_33_missing_init_files() -> None:
    """
    Key 33 – Every sovereign directory that contains any .py file
    must have an __init__.py to form a proper package.
    """
    violations: List[str] = []
    for root in sovereign_roots():
        for d in root.rglob("*"):
            if not d.is_dir():
                continue
            # Does this dir contain any .py file?
            has_py = any(child.suffix == ".py" for child in d.iterdir() if child.is_file())
            if has_py and not (d / "__init__.py").is_file():
                violations.append(str(d.relative_to(ROOT)))
    if violations:
        fail(
            "33",
            "Sovereign directories missing __init__.py:\n"
            + "\n".join(f"  - {v}" for v in violations[:40])
            + (f"\n  ... and {len(violations) - 40} more" if len(violations) > 40 else ""),
        )
    else:
        success("33", "All sovereign directories with .py files have __init__.py")

def check_key_34_empty_sov_directories() -> None:
    """Key 34 – HARDENED: No Ghost Packages (folders with only init/cache)."""
    violations = []
    # Exclude legitimate runtime infrastructure directories (handle both path separators)
    exempt_ghosts = {"shared/cache", "shared/data", "shared/logs", "shared/output"}
    
    for root in sovereign_roots():
        for d in root.rglob("*"):
            if not d.is_dir() or d.name == "__pycache__": continue
            
            # Skip exempt ghost packages (normalize path separators)
            rel_path = str(d.relative_to(ROOT)).replace("\\", "/")
            if rel_path in exempt_ghosts:
                continue
            
            # Check for "Ghost" status: Only contains __init__.py and/or __pycache__
            children = list(d.iterdir())
            real_files = [c for c in children if c.name != "__pycache__" and c.name != "__init__.py"]
            
            if not real_files:
                violations.append(f"{d.relative_to(ROOT)} -> GHOST PACKAGE (Contains only init/cache)")

    if violations:
        fail("34", "GHOST PACKAGES DETECTED:\n" + "\n".join(f"  - {v}" for v in violations))
    else:
        success("34", "No empty directories or ghost packages")

# ---------------------------------------------------------------------
# KEYS 35–40 : REPO-LEVEL INVARIANTS & DOCSTRINGS
# ---------------------------------------------------------------------

def check_key_35_gitignore_exists_and_patterns() -> None:
    """Key 35 – .gitignore exists and contains minimal patterns."""
    gitignore = ROOT / ".gitignore"
    if not gitignore.is_file():
        fail("35", ".gitignore missing at project root")
        return
    content = read_file(gitignore)
    required = ["__pycache__", "*.pyc"]
    missing = [p for p in required if p not in content]
    if missing:
        fail("35", f".gitignore missing patterns: {', '.join(missing)}")
    else:
        success("35", ".gitignore present with minimal patterns")

def check_key_36_no_git_submodules() -> None:
    """Key 36 – No git submodules (.gitmodules must not exist)."""
    if (ROOT / ".gitmodules").is_file():
        fail("36", ".gitmodules present – git submodules are forbidden")
    else:
        success("36", "No git submodules detected")

def check_key_37_large_binaries_in_sov() -> None:
    """Key 37 – No large binary blobs in sovereign directories."""
    binary_ext = {".exe", ".dll", ".so", ".dylib", ".bin", ".pkl", ".model", ".h5", ".pt"}
    violations: List[str] = []
    for root in sovereign_roots():
        for f in root.rglob("*"):
            if f.is_file() and f.suffix in binary_ext:
                try:
                    size = f.stat().st_size
                except OSError:
                    continue
                if size > MAX_BINARY_BYTES:
                    violations.append(f"{f.relative_to(ROOT)} – {size} B")
    if violations:
        fail(
            "37",
            f"Large binary files (> {MAX_BINARY_BYTES} B) in sovereign directories:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("37", "No large binary files in sovereign directories")

def check_key_38_readme_canon_badge() -> None:
    """Key 38 – README.md must exist and advertise 50/50 Canon."""
    readme = ROOT / "README.md"
    if not readme.is_file():
        fail("38", "README.md missing at project root")
        return
    content = read_file(readme)
    if "50/50" in content or "50-KEY CANON" in content.upper():
        success("38", "README.md present with 50-key canon badge/reference")
    else:
        fail("38", "README.md present but missing 50-key canon badge/reference")

def check_key_39_docstring_requirements() -> None:
    """
    Key 39 – Docstrings required for public functions/classes with
    substantial bodies in sovereign code.
    """
    violations: List[str] = []
    for f in iter_sovereign_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                if node.name.startswith("_"):
                    # private symbol
                    continue
                # Compute body length via source reconstruction
                try:
                    source = ast.get_source_segment(read_file(f), node)
                except Exception:
                    source = None
                if not source:
                    continue
                # Count lines excluding decorators and blanks
                lines = [
                    ln for ln in source.splitlines()
                    if ln.strip() and not ln.strip().startswith("@")
                ]
                if len(lines) <= 10:
                    continue  # small symbol exempt
                if not ast.get_docstring(node):
                    violations.append(
                        f"{f.relative_to(ROOT)}:{node.lineno} – {node.name}() missing docstring"
                    )
    if violations:
        fail(
            "39",
            "Docstrings missing on non-trivial public symbols in sovereign code:\n"
            + "\n".join(f"  - {v}" for v in violations[:40])
            + (f"\n  ... and {len(violations) - 40} more" if len(violations) > 40 else ""),
        )
    else:
        success("39", "Docstring requirements satisfied for sovereign code")

def check_key_40_validator_self_sanity() -> None:
    """
    Key 40 – Validator self-integrity check.
    
    Verifies that the validator is being run from the project root directory.
    This ensures correct path resolution for all other checks.
    """
    current_script = Path(__file__).resolve()
    script_name = current_script.name
    
    if not current_script.is_file():
        fail("40", f"Validator cannot resolve its own path: {current_script}")
        return
    
    # Verify that os.getcwd() matches ROOT (validator run from project root)
    cwd = Path(os.getcwd()).resolve()
    if cwd != ROOT:
        fail("40", f"Validator must be run from project root. CWD: {cwd}, ROOT: {ROOT}")
        return
    
    try:
        ast.parse(read_file(current_script))
    except SyntaxError as e:
        fail("40", f"{script_name} has syntax error: {e.msg}")
        return
    
    success("40", f"{script_name} syntactically valid and run from project root")

# ---------------------------------------------------------------------
# KEYS 41–50 : LIGHT CANON (NON-SOVEREIGN PYTHON)
# ---------------------------------------------------------------------

def _iter_light_py_files() -> Iterable[Path]:
    """
    Non-sovereign Python files under project root (uses cache).
    Strictly excludes sovereign dirs AND global excludes (data/archives/.git/.venv).
    """
    if _REPO_HYDRATED:
        for fd in LIGHT_FILES:
            # Additional .venv filter even when using cache
            # fd.rel_path is a string, convert to Path to check parts
            rel_path = Path(fd.rel_path)
            if any(part == ".venv" for part in rel_path.parts):
                continue
            yield fd.path
    else:
        sov_roots = set(SOVEREIGN_DIRS)
        for f in ROOT.rglob("*.py"):
            rel = f.relative_to(ROOT)
            # Check 1: Global Excludes (data, archives, .git, .venv, etc.)
            if is_globally_excluded(rel):
                continue
            # Check 2: Explicit .venv exclusion (Windows path issue)
            if any(part == ".venv" for part in rel.parts):
                continue
            # Check 3: Sovereign Directories (not light)
            if rel.parts and rel.parts[0] in sov_roots:
                continue
            yield f

def _iter_light_file_data() -> Iterable[FileData]:
    """Iterate FileData for light (non-sovereign) .py files (cache-only, fast)."""
    return iter(LIGHT_FILES)

def check_key_41_light_no_debug() -> None:
    """Key 41 – Light Canon: STRICT no debug statements in non-sovereign code."""
    debug_patterns = [
        r"\bprint\s*\(",
        r"\bpdb\.",
        r"\bipdb\.",
        r"\bbreakpoint\s*\(",
        r"\bset_trace\s*\(",
    ]
    compiled = [re.compile(p) for p in debug_patterns]
    violations: List[str] = []
    # Scripts and CLI tools are exempt (they need print for output)
    exempt_files = {"canon_validator.py", "fix_canon_violations.py", "verify_installation.py"}
    exempt_dirs = {"scripts", "runtime", "examples", "tests"}  # Added examples and tests to exempt dirs
    
    for f in _iter_light_py_files():
        if f.name in exempt_files:
            continue
        if any(d in f.parts for d in exempt_dirs):
            continue
        text = read_file(f)
        if any(p.search(text) for p in compiled):
            violations.append(str(f.relative_to(ROOT)))
    
    if violations:
        fail(
            "41",
            "Debug statements found in non-sovereign Python code:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("41", "No debug statements in non-sovereign Python code")

def check_key_42_light_todo_fixme() -> None:
    """Key 42 – Light Canon: no TODO/FIXME/HACK in non-sovereign code."""
    violations: List[str] = []
    # Exclude the validator itself (contains TODO_PATTERN definition)
    exclude_files = {"canon_validator.py"}
    for f in _iter_light_py_files():
        if f.name in exclude_files:
            continue
        text = read_file(f)
        if TODO_PATTERN.search(text):
            violations.append(str(f.relative_to(ROOT)))
    if violations:
        fail(
            "42",
            "TODO/FIXME/HACK/XXX/STUB/WIP found in non-sovereign Python code:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("42", "No TODO/FIXME/HACK annotations in non-sovereign code")

def check_key_43_light_no_tiny_files() -> None:
    """Key 43 – Light Canon: no micro-files (<150 bytes) except __init__.py."""
    violations: List[str] = []
    for f in _iter_light_py_files():
        size = f.stat().st_size
        if f.name == "__init__.py" and size < 100:
            continue
        if size < 150:
            violations.append(f"{f.relative_to(ROOT)} – {size} B")
    if violations:
        fail(
            "43",
            "Tiny non-sovereign Python files (<150 B) detected:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("43", "No micro-files in non-sovereign Python code")

def check_key_44_light_no_pass_only_defs() -> None:
    """Key 44 – Light Canon: no pass-only functions/classes in non-sovereign code."""
    violations: List[str] = []
    for f in _iter_light_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
                if len(node.body) == 1 and isinstance(node.body[0], ast.Pass):
                    violations.append(
                        f"{f.relative_to(ROOT)}:{node.lineno} – {node.name} pass-only definition"
                    )
    if violations:
        fail(
            "44",
            "Pass-only function/class definitions in non-sovereign code:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("44", "No pass-only definitions in non-sovereign Python code")

def check_key_45_light_no_bare_except() -> None:
    """Key 45 – Light Canon: no bare 'except:' in non-sovereign code."""
    violations: List[str] = []
    for f in _iter_light_py_files():
        tree = parse_ast(f)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.ExceptHandler):
                if node.type is None:
                    violations.append(f"{f.relative_to(ROOT)}:{node.lineno}")
                    break

    if violations:
        fail(
            "45",
            "Bare 'except:' in non-sovereign Python code:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("45", "No bare 'except:' in non-sovereign Python code")

def check_key_46_light_no_secrets() -> None:
    """Key 46 – Light Canon: no obvious secrets in non-sovereign code."""
    cred_patterns = [
        r'password\s*=\s*["\'][^"\']{8,}["\']',
        r'api_key\s*=\s*["\']sk-[A-Za-z0-9]{20,}["\']',
        r'secret\s*=\s*["\'][A-Za-z0-9]{16,}["\']',
    ]
    compiled = [re.compile(p, re.IGNORECASE) for p in cred_patterns]
    violations: List[str] = []
    for f in _iter_light_py_files():
        text = read_file(f)
        if any(p.search(text) for p in compiled):
            violations.append(str(f.relative_to(ROOT)))
    if violations:
        fail(
            "46",
            "Potential secrets in non-sovereign Python code:\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("46", "No obvious secrets in non-sovereign Python code")

def check_key_47_no_zombie_archive_anywhere() -> None:
    """Key 47 – No stray archive/ directories or residual compiled files/metadata."""
    violations: List[str] = []
    
    # 1. Check for zombie archive directories (original check)
    for d in ROOT.rglob("archive"):
        if d.is_dir():
            rel_path = d.relative_to(ROOT)
            # Skip archive directories that are inside the archives/ directory
            if "archives" in rel_path.parts:
                continue
            violations.append(f"archive/ directory: {rel_path}")

    # 2. Check for residual compiled files and metadata (Hole 1 fix)
    residual_extensions = {".pyc", ".bak", ".tmp", ".swp", ".orig", "~", ".DS_Store", "Thumbs.db"}
    
    # Iterate all files in the repository (excluding .git)
    for f in ROOT.rglob("*"):
        if not f.is_file():
            continue
        if is_globally_excluded(f.relative_to(ROOT)):
            continue

        if f.suffix in residual_extensions or f.name.endswith("~"):
            violations.append(f"Residual file: {f.relative_to(ROOT)}")
            
    if violations:
        fail(
            "47",
            "Cleanup violations (archive/ directories or residual files):\n"
            + "\n".join(f"  - {v}" for v in violations[:30])
            + (f"\n  ... and {len(violations) - 30} more" if len(violations) > 30 else ""),
        )
    else:
        success("47", "Cleanup is pristine (archives/ only, no residual files)")

def check_key_48_final_depth_canon() -> None:
    """
    Key 48 – HARDENED: The One True Depth Law (Max 5).

    - No CODE file in ANY directory (Sovereign or Light) may exceed depth 5
    - Exception: tests/ directory files may go to depth 7 (to mirror source structure)
    - No .py file at root except whitelisted scripts
    - Uses is_globally_excluded() for consistent exclusion policy
    """
    violations: List[str] = []
    MAX_DEPTH = 5
    
    # Code file extensions to check (not all files)
    CODE_EXTENSIONS = {".py", ".yaml", ".yml", ".json", ".toml", ".cfg", ".ini"}
    
    # Relaxed depth for tests/ directory
    MAX_TESTS_DEPTH = 7

    for f in ROOT.rglob("*"):
        if not f.is_file():
            continue
        
        rel = f.relative_to(ROOT)
        parts = rel.parts
        
        # UNIVERSAL EXCLUSION CHECK
        if is_globally_excluded(rel):
            continue
        
        if f.suffix not in CODE_EXTENSIONS:
            continue

        # Use SEMANTIC depth (ignores L1_*, P2_*, etc. virtual namespaces)
        depth = semantic_depth(parts)
        
        # Determine max depth based on directory
        is_tests = parts and parts[0] == "tests"
        limit = MAX_TESTS_DEPTH if is_tests else MAX_DEPTH

        if depth > limit:
            violations.append(f"{rel} (Depth {depth} > {limit})")

        if depth == 1 and f.suffix == ".py":
            if f.name not in ALLOWED_ROOT_SCRIPTS:
                violations.append(f"{rel} -> illegal .py file at project root")

    if violations:
        fail("48", "DEPTH CANON VIOLATIONS:\n" + "\n".join(f"  - {v}" for v in violations))
    else:
        success("48", "Depth Canon Enforced (Max 5)")

def check_key_49_no_smashed_filenames() -> None:
    """
    Key 49 – Depth-Aware Signal-to-Noise Filename Strictness.
    1. Signal-to-Noise: Max 4 high-signal words.
    2. Universal Underscore Limit: Max 5 underscores in any filename. (Hole 5 Fix)
    """
    LOW_SIGNAL_WORDS: Set[str] = {
        "config", "cache", "utils", "test", "spec", "impl",
        "manager", "service", "handler", "controller", "base", "common",
        "data", "info", "get", "set", "load", "save", "read", "write",
        "process", "execute", "run", "init",
        "create", "delete", "find", "fetch", "store",
        "input", "output", "result", "context", "status",
        "check", "update", "manage", "perform", "task",
    }
    
    violations: List[str] = []
    
    for f in ROOT.rglob("*.py"):
        if f.name == "__init__.py":
            continue
        
        rel = f.relative_to(ROOT)
        if is_globally_excluded(rel):
            continue
        
        stem = f.stem
        issues: List[str] = []

        # Rule 1: Max filename length
        if len(f.name) > 60:
            issues.append(f"{len(f.name)} chars (max 60)")
        
        # Rule 2: Universal Underscore Limit (Hole 5 Fix)
        # Apply this universally for readability, regardless of sovereign status
        if stem.count("_") > 5:
            issues.append(f"{stem.count('_')} underscores (max 5)")

        # Rule 3: Signal-to-Noise word count (applied only to Sovereign files for strictness)
        if is_sovereign_path(f):
            words = stem.lower().split("_")
            high_signal_words = [w for w in words if w and w not in LOW_SIGNAL_WORDS]
            signal_count = len(high_signal_words)
            max_signal = 4
            
            if signal_count > max_signal:
                issues.append(
                    f"{signal_count} high-signal words (max {max_signal})"
                )

        if issues:
            violations.append(
                f"{f.relative_to(ROOT)} – " + ", ".join(issues)
            )

    if violations:
        fail(
            "49",
            "Filename hygiene violations (Too complex / Word Salad / Underscore Smashes):\n"
            + "\n".join(f"  - {v}" for v in violations[:40])
            + (f"\n  ... and {len(violations) - 40} more" if len(violations) > 40 else ""),
        )
    else:
        success("49", "No smashed filenames – signal-to-noise ratio and universal underscore limits OK")

def check_key_50_canon_meta_integrity() -> None:
    """
    Key 50 – Meta: exactly 50 keys executed and reported.

    This does not perform additional repo checks; it verifies that the
    validator itself behaved as a 50-key canon.
    """
    # Keys 01-49 should already be registered at this point (50 is this check)
    expected_keys = {f"{i:02d}" for i in range(1, 50)}  # 01-49
    actual_keys = set(results.keys())
    missing = sorted(expected_keys - actual_keys)
    extra = sorted(actual_keys - expected_keys)
    if missing or extra:
        fail(
            "50",
            f"Canon meta-integrity failure: missing keys={missing}, extra keys={extra}",
        )
    else:
        success("50", "Canon meta-integrity OK — all 49 prerequisite keys executed")

# =====================================================================
# TOP-LEVEL CHECK RUNNER
# =====================================================================

def run_all_checks() -> None:
    """Run all 50 validation keys in a deterministic order."""
    results.clear()
    
    # PERFORMANCE: Single-pass hydration before any key runs
    hydrate_repo_data()

    # Sovereign immutability & foundations
    check_key_01_no_sovereign_deletions()
    check_key_02_no_sovereign_renames()
    check_key_03_data_folder_exists()
    check_key_04_no_zombie_archive_singular_root()
    check_key_05_layered_structure_sane()
    check_key_06_no_forbidden_folder_names()
    check_key_07_required_root_folders()
    check_key_08_no_empty_sov_roots()

    # Sovereign naming, vocabulary & comments
    check_key_09_banned_tokens_in_filenames()
    check_key_10_banned_symbol_prefixes()
    check_key_11_banned_vocabulary()
    check_key_12_todo_fixme_comments()
    check_key_13_hardcoded_paths()
    check_key_14_magic_numbers()
    check_key_15_bare_except()
    check_key_16_eval_exec_usage()
    check_key_17_poison_markers_and_stubs()
    check_key_18_sovereign_debug_statements()

    # Sovereign AST / import hygiene
    check_key_19_duplicate_functions()
    check_key_20_duplicate_classes()
    check_key_21_circular_imports()
    check_key_22_import_hygiene()          # <--- FIXED (was unused_imports)
    check_key_23_hardcoded_credentials()
    check_key_24_sql_injection_patterns()
    check_key_25_hardcoded_urls()
    check_key_26_syntax_and_strict_typing() # <--- FIXED (was syntax_parses_clean)

    # Sovereign size, nesting, packages
    check_key_27_no_empty_sov_files()
    check_key_28_subatomic_file_size_law()
    check_key_29_function_length_limits()
    check_key_30_nesting_depth_limits()
    check_key_31_max_path_depth_sov()
    check_key_32_fake_nesting_names()
    check_key_33_missing_init_files()
    check_key_34_empty_sov_directories()

    # Repo-level invariants & docstrings
    check_key_35_gitignore_exists_and_patterns()
    check_key_36_no_git_submodules()
    check_key_37_large_binaries_in_sov()
    check_key_38_readme_canon_badge()
    check_key_39_docstring_requirements()
    check_key_40_validator_self_sanity()

    # Light Canon
    check_key_41_light_no_debug()
    check_key_42_light_todo_fixme()
    check_key_43_light_no_tiny_files()
    check_key_44_light_no_pass_only_defs()
    check_key_45_light_no_bare_except()
    check_key_46_light_no_secrets()
    check_key_47_no_zombie_archive_anywhere()     # ← stays at 47
    check_key_48_final_depth_canon()           # ← NEW: replaces 31 + 48
    check_key_49_no_smashed_filenames()        # ← stays at 49

    # Meta key (must be last, checks keys present in results)
    check_key_50_canon_meta_integrity()

# =====================================================================
# CLI
# =====================================================================

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="SUBATOMIC CANON 2026 — 50-key validator (non-destructive)."
    )
    parser.add_argument(
        "--check-50",
        action="store_true",
        dest="check_50",
        help="Run all 50 canonical keys (default)",
    )
    parser.add_argument(
        "--only",
        type=str,
        help="Run a specific key only (e.g., --only 49) or comma-separated (e.g., --only 48,49)",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="Output results in JSON format (context-efficient for AI parsing)",
    )
    parser.add_argument(
        "--silent",
        action="store_true",
        help="Suppress console output; rely on exit code only",
    )
    parser.add_argument(
        "extra",
        nargs="*",
        help="Extra positional arguments (ignored)",
    )
    return parser.parse_args()

def main() -> None:
    args = parse_args()
    import json

    # Force rehydration to pick up .venv exclusion changes
    global _REPO_HYDRATED
    _REPO_HYDRATED = False

    # Load pre-commit change tracker if available
    load_change_tracker_from_env()

    if not args.silent and not args.json:
        print("=" * 80)
        print("SUBATOMIC CANON VALIDATOR — 50/50 KEYS")
        print("=" * 80)

    # 1. Hydrate (Always required)
    hydrate_repo_data()

    # 2. Map keys to functions
    key_map = {
        "01": check_key_01_no_sovereign_deletions,
        "02": check_key_02_no_sovereign_renames,
        "03": check_key_03_data_folder_exists,
        "04": check_key_04_no_zombie_archive_singular_root,
        "05": check_key_05_layered_structure_sane,
        "06": check_key_06_no_forbidden_folder_names,
        "07": check_key_07_required_root_folders,
        "08": check_key_08_no_empty_sov_roots,
        "09": check_key_09_banned_tokens_in_filenames,
        "10": check_key_10_banned_symbol_prefixes,
        "11": check_key_11_banned_vocabulary,
        "12": check_key_12_todo_fixme_comments,
        "13": check_key_13_hardcoded_paths,
        "14": check_key_14_magic_numbers,
        "15": check_key_15_bare_except,
        "16": check_key_16_eval_exec_usage,
        "17": check_key_17_poison_markers_and_stubs,
        "18": check_key_18_sovereign_debug_statements,
        "19": check_key_19_duplicate_functions,
        "20": check_key_20_duplicate_classes,
        "21": check_key_21_circular_imports,
        "22": check_key_22_import_hygiene,
        "23": check_key_23_hardcoded_credentials,
        "24": check_key_24_sql_injection_patterns,
        "25": check_key_25_hardcoded_urls,
        "26": check_key_26_syntax_and_strict_typing,
        "27": check_key_27_no_empty_sov_files,
        "28": check_key_28_subatomic_file_size_law,
        "29": check_key_29_function_length_limits,
        "30": check_key_30_nesting_depth_limits,
        "31": check_key_31_max_path_depth_sov,
        "32": check_key_32_fake_nesting_names,
        "33": check_key_33_missing_init_files,
        "34": check_key_34_empty_sov_directories,
        "35": check_key_35_gitignore_exists_and_patterns,
        "36": check_key_36_no_git_submodules,
        "37": check_key_37_large_binaries_in_sov,
        "38": check_key_38_readme_canon_badge,
        "39": check_key_39_docstring_requirements,
        "40": check_key_40_validator_self_sanity,
        "41": check_key_41_light_no_debug,
        "42": check_key_42_light_todo_fixme,
        "43": check_key_43_light_no_tiny_files,
        "44": check_key_44_light_no_pass_only_defs,
        "45": check_key_45_light_no_bare_except,
        "46": check_key_46_light_no_secrets,
        "47": check_key_47_no_zombie_archive_anywhere,
        "48": check_key_48_final_depth_canon,
        "49": check_key_49_no_smashed_filenames,
        "50": check_key_50_canon_meta_integrity,
    }

    # 3. Determine Execution Scope
    keys_to_run = []
    if args.only:
        targets = [k.strip() for k in args.only.split(",")]
        keys_to_run = [k if len(k) == 2 else f"0{k}" for k in targets]
        for k in keys_to_run:
            if k not in key_map:
                if not args.json: print(f"Unknown key: {k}")
    else:
        keys_to_run = sorted(key_map.keys())

    # 4. Execute
    for k in keys_to_run:
        if k in key_map:
            key_map[k]()

    # 5. Output Handling
    if args.json:
        output = {
            "summary": {"total": len(keys_to_run), "passed": 0, "failed": 0},
            "failures": {}
        }
        for k in keys_to_run:
            passed, msg = results.get(k, (False, "Not Run"))
            if passed:
                output["summary"]["passed"] += 1
            else:
                output["summary"]["failed"] += 1
                lines = msg.split('\n')
                header = lines[0]
                # Extract file paths from bullet points
                files = [l.strip().replace("- ", "").replace("• ", "") for l in lines[1:] if l.strip()]
                # If bullet points are complex (contain reason), split them
                clean_files = []
                for f in files:
                    if " – " in f: clean_files.append(f.split(" – ")[0])
                    elif " -> " in f: clean_files.append(f.split(" -> ")[0])
                    else: clean_files.append(f)
                
                output["failures"][k] = {"error": header, "files": clean_files}

        sys.exit(1 if output["summary"]["failed"] > 0 else 0)

    else:
        fails = [k for k in keys_to_run if not results.get(k, (False, ""))[0]]
        passed = [k for k in keys_to_run if results.get(k, (False, ""))[0]]
        if not args.silent:
            print(f"\n{'=' * 80}")
            print(f"VALIDATION COMPLETE: {len(passed)}/{len(keys_to_run)} KEYS PASSED")
            print(f"{'=' * 80}\n")
            
            for k in keys_to_run:
                if k in results:
                    p, m = results[k]
                    icon = "[PASS]" if p else "[FAIL]"
                    print(f"{icon} Key {k}: {m}")

        sys.exit(1 if fails else 0)

if __name__ == "__main__":
    main()
