#!/bin/bash
# Flatten single-file packages
set -e

git mv "apps_shared\api\__init__.py" "apps_shared\api.py"
rmdir "apps_shared\api"
git mv "apps_shared\safety\__init__.py" "apps_shared\safety.py"
rmdir "apps_shared\safety"
git mv "apps_shared\shared_utilities\__init__.py" "apps_shared\shared_utilities.py"
rmdir "apps_shared\shared_utilities"
git mv "runtime\validation\__init__.py" "runtime\validation.py"
rmdir "runtime\validation"
git mv "scripts\runtime\guardrails\__init__.py" "scripts\runtime\guardrails.py"
rmdir "scripts\runtime\guardrails"
git mv "scripts\runtime\validation\__init__.py" "scripts\runtime\validation.py"
rmdir "scripts\runtime\validation"
git mv "scripts\security\guardrails\check_rules\__init__.py" "scripts\security\guardrails\check_rules.py"
rmdir "scripts\security\guardrails\check_rules"
git mv "scripts\runtime\synthesis\use_tools\__init__.py" "scripts\runtime\synthesis\use_tools.py"
rmdir "scripts\runtime\synthesis\use_tools"
git mv "scripts\pipeline\data_access\get_info\__init__.py" "scripts\pipeline\data_access\get_info.py"
rmdir "scripts\pipeline\data_access\get_info"
git mv "scripts\pipeline\guardrails\check_rules\__init__.py" "scripts\pipeline\guardrails\check_rules.py"
rmdir "scripts\pipeline\guardrails\check_rules"
git mv "scripts\pipeline\synthesis\use_tools\__init__.py" "scripts\pipeline\synthesis\use_tools.py"
rmdir "scripts\pipeline\synthesis\use_tools"
git mv "scripts\logic\data_access\check_rules\__init__.py" "scripts\logic\data_access\check_rules.py"
rmdir "scripts\logic\data_access\check_rules"
git mv "scripts\logic\data_access\get_info\__init__.py" "scripts\logic\data_access\get_info.py"
rmdir "scripts\logic\data_access\get_info"
git mv "scripts\logic\guardrails\check_rules\__init__.py" "scripts\logic\guardrails\check_rules.py"
rmdir "scripts\logic\guardrails\check_rules"
git mv "scripts\logic\guardrails\manage_costs\__init__.py" "scripts\logic\guardrails\manage_costs.py"
rmdir "scripts\logic\guardrails\manage_costs"
git mv "scripts\logic\synthesis\pick_best_result\__init__.py" "scripts\logic\synthesis\pick_best_result.py"
rmdir "scripts\logic\synthesis\pick_best_result"
git mv "scripts\logic\synthesis\use_tools\__init__.py" "scripts\logic\synthesis\use_tools.py"
rmdir "scripts\logic\synthesis\use_tools"
git mv "scripts\logic\validation\check_structure\__init__.py" "scripts\logic\validation\check_structure.py"
rmdir "scripts\logic\validation\check_structure"
git mv "scripts\logic\validation\convert_content\__init__.py" "scripts\logic\validation\convert_content.py"
rmdir "scripts\logic\validation\convert_content"
git mv "scripts\cache\data_access\get_info\__init__.py" "scripts\cache\data_access\get_info.py"
rmdir "scripts\cache\data_access\get_info"
git mv "scripts\cache\guardrails\check_rules\__init__.py" "scripts\cache\guardrails\check_rules.py"
rmdir "scripts\cache\guardrails\check_rules"
git mv "schemas\templates\injection_patterns\__init__.py" "schemas\templates\injection_patterns.py"
rmdir "schemas\templates\injection_patterns"
git mv "schemas\security_controls\guardrails\check_schema_rules\__init__.py" "schemas\security_controls\guardrails\check_schema_rules.py"
rmdir "schemas\security_controls\guardrails\check_schema_rules"
git mv "schemas\runtime\guardrails\check_schema_rules\__init__.py" "schemas\runtime\guardrails\check_schema_rules.py"
rmdir "schemas\runtime\guardrails\check_schema_rules"
git mv "schemas\runtime\guardrails\check_schema_safety\__init__.py" "schemas\runtime\guardrails\check_schema_safety.py"
rmdir "schemas\runtime\guardrails\check_schema_safety"
git mv "schemas\runtime\synthesis\use_schema_tools\__init__.py" "schemas\runtime\synthesis\use_schema_tools.py"
rmdir "schemas\runtime\synthesis\use_schema_tools"
git mv "schemas\runtime\synthesis\use_schema_utility\__init__.py" "schemas\runtime\synthesis\use_schema_utility.py"
rmdir "schemas\runtime\synthesis\use_schema_utility"
git mv "schemas\runtime\validation\check_schema_safety\__init__.py" "schemas\runtime\validation\check_schema_safety.py"
rmdir "schemas\runtime\validation\check_schema_safety"
git mv "schemas\runtime\validation\check_schema_structure\__init__.py" "schemas\runtime\validation\check_schema_structure.py"
rmdir "schemas\runtime\validation\check_schema_structure"
git mv "schemas\pipeline\data_access\get_schema_info\__init__.py" "schemas\pipeline\data_access\get_schema_info.py"
rmdir "schemas\pipeline\data_access\get_schema_info"
git mv "schemas\pipeline\guardrails\check_schema_rules\__init__.py" "schemas\pipeline\guardrails\check_schema_rules.py"
rmdir "schemas\pipeline\guardrails\check_schema_rules"
git mv "schemas\pipeline\synthesis\use_schema_tools\__init__.py" "schemas\pipeline\synthesis\use_schema_tools.py"
rmdir "schemas\pipeline\synthesis\use_schema_tools"
git mv "schemas\logic\data_access\check_schema_rules\__init__.py" "schemas\logic\data_access\check_schema_rules.py"
rmdir "schemas\logic\data_access\check_schema_rules"
git mv "schemas\logic\data_access\get_schema_info\__init__.py" "schemas\logic\data_access\get_schema_info.py"
rmdir "schemas\logic\data_access\get_schema_info"
git mv "schemas\logic\guardrails\check_schema_rules\__init__.py" "schemas\logic\guardrails\check_schema_rules.py"
rmdir "schemas\logic\guardrails\check_schema_rules"
git mv "schemas\logic\guardrails\manage_schema_costs\__init__.py" "schemas\logic\guardrails\manage_schema_costs.py"
rmdir "schemas\logic\guardrails\manage_schema_costs"
git mv "schemas\logic\synthesis\pick_best_result\__init__.py" "schemas\logic\synthesis\pick_best_result.py"
rmdir "schemas\logic\synthesis\pick_best_result"
git mv "schemas\logic\synthesis\state_update\__init__.py" "schemas\logic\synthesis\state_update.py"
rmdir "schemas\logic\synthesis\state_update"
git mv "schemas\logic\synthesis\use_schema_retry\__init__.py" "schemas\logic\synthesis\use_schema_retry.py"
rmdir "schemas\logic\synthesis\use_schema_retry"
git mv "schemas\logic\synthesis\use_schema_tools\__init__.py" "schemas\logic\synthesis\use_schema_tools.py"
rmdir "schemas\logic\synthesis\use_schema_tools"
git mv "schemas\logic\validation\check_schema_structure\__init__.py" "schemas\logic\validation\check_schema_structure.py"
rmdir "schemas\logic\validation\check_schema_structure"
git mv "schemas\logic\validation\convert_schema_content\__init__.py" "schemas\logic\validation\convert_schema_content.py"
rmdir "schemas\logic\validation\convert_schema_content"
git mv "schemas\logic\validation\find_schema_diagnostics\__init__.py" "schemas\logic\validation\find_schema_diagnostics.py"
rmdir "schemas\logic\validation\find_schema_diagnostics"
git mv "schemas\logic\validation\find_schema_problems\__init__.py" "schemas\logic\validation\find_schema_problems.py"
rmdir "schemas\logic\validation\find_schema_problems"
git mv "schemas\cache\data_access\get_schema_info\__init__.py" "schemas\cache\data_access\get_schema_info.py"
rmdir "schemas\cache\data_access\get_schema_info"
git mv "schemas\cache\guardrails\check_schema_rules\__init__.py" "schemas\cache\guardrails\check_schema_rules.py"
rmdir "schemas\cache\guardrails\check_schema_rules"
git mv "runtime\guardrails\check_rules\policy_check_safety\__init__.py" "runtime\guardrails\check_rules\policy_check_safety.py"
rmdir "runtime\guardrails\check_rules\policy_check_safety"
git mv "prompt_governance\templates\budget-manager-layer\refine-phase-group\__init__.py" "prompt_governance\templates\budget-manager-layer\refine-phase-group.py"
rmdir "prompt_governance\templates\budget-manager-layer\refine-phase-group"
git mv "prompt_governance\templates\budget-manager-layer\refine-phase-group_constraint-check-ops\__init__.py" "prompt_governance\templates\budget-manager-layer\refine-phase-group_constraint-check-ops.py"
rmdir "prompt_governance\templates\budget-manager-layer\refine-phase-group_constraint-check-ops"
git mv "prompt_governance\templates\resume\executor-microagent-layer\__init__.py" "prompt_governance\templates\resume\executor-microagent-layer.py"
rmdir "prompt_governance\templates\resume\executor-microagent-layer"
git mv "prompt_governance\templates\resume\executor-microagent-layer_retry-phase-group\__init__.py" "prompt_governance\templates\resume\executor-microagent-layer_retry-phase-group.py"
rmdir "prompt_governance\templates\resume\executor-microagent-layer_retry-phase-group"
git mv "prompt_governance\templates\resume\observer-microagent-layer\__init__.py" "prompt_governance\templates\resume\observer-microagent-layer.py"
rmdir "prompt_governance\templates\resume\observer-microagent-layer"
git mv "prompt_governance\templates\resume\observer-microagent-layer_inspect-phase-group\__init__.py" "prompt_governance\templates\resume\observer-microagent-layer_inspect-phase-group.py"
rmdir "prompt_governance\templates\resume\observer-microagent-layer_inspect-phase-group"
git mv "prompt_governance\templates\resume\planner-microagent-layer\__init__.py" "prompt_governance\templates\resume\planner-microagent-layer.py"
rmdir "prompt_governance\templates\resume\planner-microagent-layer"
git mv "prompt_governance\templates\resume\planner-microagent-layer_act-phase-group\__init__.py" "prompt_governance\templates\resume\planner-microagent-layer_act-phase-group.py"
rmdir "prompt_governance\templates\resume\planner-microagent-layer_act-phase-group"
git mv "prompt_governance\templates\router-microagent-layer\expand-phase-group\__init__.py" "prompt_governance\templates\router-microagent-layer\expand-phase-group.py"
rmdir "prompt_governance\templates\router-microagent-layer\expand-phase-group"
git mv "prompt_governance\templates\router-microagent-layer\expand-phase-group_vectorization-ops\__init__.py" "prompt_governance\templates\router-microagent-layer\expand-phase-group_vectorization-ops.py"
rmdir "prompt_governance\templates\router-microagent-layer\expand-phase-group_vectorization-ops"
git mv "prompt_governance\templates\safety-guard-layer\validate-phase-group\__init__.py" "prompt_governance\templates\safety-guard-layer\validate-phase-group.py"
rmdir "prompt_governance\templates\safety-guard-layer\validate-phase-group"
git mv "prompt_governance\templates\safety-guard-layer\validate-phase-group_retrieval-ops\__init__.py" "prompt_governance\templates\safety-guard-layer\validate-phase-group_retrieval-ops.py"
rmdir "prompt_governance\templates\safety-guard-layer\validate-phase-group_retrieval-ops"
git mv "prompt_governance\security_controls\guardrails\check_prompt_rules\__init__.py" "prompt_governance\security_controls\guardrails\check_prompt_rules.py"
rmdir "prompt_governance\security_controls\guardrails\check_prompt_rules"
git mv "prompt_governance\security_controls\guardrails\check_prompt_rules_manage_costs_state_update\__init__.py" "prompt_governance\security_controls\guardrails\check_prompt_rules_manage_costs_state_update.py"
rmdir "prompt_governance\security_controls\guardrails\check_prompt_rules_manage_costs_state_update"
git mv "prompt_governance\security_controls\guardrails\check_prompt_rules_policy_check_safety\__init__.py" "prompt_governance\security_controls\guardrails\check_prompt_rules_policy_check_safety.py"
rmdir "prompt_governance\security_controls\guardrails\check_prompt_rules_policy_check_safety"
git mv "prompt_governance\runtime\guardrails\check_prompt_rules\__init__.py" "prompt_governance\runtime\guardrails\check_prompt_rules.py"
rmdir "prompt_governance\runtime\guardrails\check_prompt_rules"
git mv "prompt_governance\runtime\synthesis\use_prompt_tools\__init__.py" "prompt_governance\runtime\synthesis\use_prompt_tools.py"
rmdir "prompt_governance\runtime\synthesis\use_prompt_tools"
git mv "prompt_governance\runtime\synthesis\use_prompt_tools_utility_prepare_information\__init__.py" "prompt_governance\runtime\synthesis\use_prompt_tools_utility_prepare_information.py"
rmdir "prompt_governance\runtime\synthesis\use_prompt_tools_utility_prepare_information"
git mv "prompt_governance\runtime\validation\check_prompt_structure\__init__.py" "prompt_governance\runtime\validation\check_prompt_structure.py"
rmdir "prompt_governance\runtime\validation\check_prompt_structure"
git mv "prompt_governance\pipeline\data_access\get_prompt_info\__init__.py" "prompt_governance\pipeline\data_access\get_prompt_info.py"
rmdir "prompt_governance\pipeline\data_access\get_prompt_info"
git mv "prompt_governance\pipeline\guardrails\check_prompt_rules\__init__.py" "prompt_governance\pipeline\guardrails\check_prompt_rules.py"
rmdir "prompt_governance\pipeline\guardrails\check_prompt_rules"
git mv "prompt_governance\pipeline\synthesis\use_prompt_tools\__init__.py" "prompt_governance\pipeline\synthesis\use_prompt_tools.py"
rmdir "prompt_governance\pipeline\synthesis\use_prompt_tools"
git mv "prompt_governance\pipeline\synthesis\use_prompt_tools_use_a_tool\__init__.py" "prompt_governance\pipeline\synthesis\use_prompt_tools_use_a_tool.py"
rmdir "prompt_governance\pipeline\synthesis\use_prompt_tools_use_a_tool"
git mv "prompt_governance\logic\data_access\check_prompt_rules\__init__.py" "prompt_governance\logic\data_access\check_prompt_rules.py"
rmdir "prompt_governance\logic\data_access\check_prompt_rules"
git mv "prompt_governance\logic\data_access\get_prompt_info\__init__.py" "prompt_governance\logic\data_access\get_prompt_info.py"
rmdir "prompt_governance\logic\data_access\get_prompt_info"
git mv "prompt_governance\logic\data_access\get_prompt_info_understand_request\__init__.py" "prompt_governance\logic\data_access\get_prompt_info_understand_request.py"
rmdir "prompt_governance\logic\data_access\get_prompt_info_understand_request"
git mv "prompt_governance\logic\data_access\get_prompt_info_utility_prepare_information\__init__.py" "prompt_governance\logic\data_access\get_prompt_info_utility_prepare_information.py"
rmdir "prompt_governance\logic\data_access\get_prompt_info_utility_prepare_information"
git mv "prompt_governance\logic\guardrails\check_prompt_rules\__init__.py" "prompt_governance\logic\guardrails\check_prompt_rules.py"
rmdir "prompt_governance\logic\guardrails\check_prompt_rules"
git mv "prompt_governance\logic\guardrails\manage_prompt_costs\__init__.py" "prompt_governance\logic\guardrails\manage_prompt_costs.py"
rmdir "prompt_governance\logic\guardrails\manage_prompt_costs"
git mv "prompt_governance\logic\synthesis\pick_best_result\__init__.py" "prompt_governance\logic\synthesis\pick_best_result.py"
rmdir "prompt_governance\logic\synthesis\pick_best_result"
git mv "prompt_governance\logic\synthesis\pick_best_result_understand_request\__init__.py" "prompt_governance\logic\synthesis\pick_best_result_understand_request.py"
rmdir "prompt_governance\logic\synthesis\pick_best_result_understand_request"
git mv "prompt_governance\logic\synthesis\state_update\__init__.py" "prompt_governance\logic\synthesis\state_update.py"
rmdir "prompt_governance\logic\synthesis\state_update"
git mv "prompt_governance\logic\synthesis\use_prompt_tools\__init__.py" "prompt_governance\logic\synthesis\use_prompt_tools.py"
rmdir "prompt_governance\logic\synthesis\use_prompt_tools"
git mv "prompt_governance\logic\synthesis\use_prompt_tools_use_a_tool\__init__.py" "prompt_governance\logic\synthesis\use_prompt_tools_use_a_tool.py"
rmdir "prompt_governance\logic\synthesis\use_prompt_tools_use_a_tool"
git mv "prompt_governance\logic\validation\check_prompt_structure\__init__.py" "prompt_governance\logic\validation\check_prompt_structure.py"
rmdir "prompt_governance\logic\validation\check_prompt_structure"
git mv "prompt_governance\logic\validation\convert_prompt_content\__init__.py" "prompt_governance\logic\validation\convert_prompt_content.py"
rmdir "prompt_governance\logic\validation\convert_prompt_content"
git mv "prompt_governance\logic\validation\find_prompt_problems\__init__.py" "prompt_governance\logic\validation\find_prompt_problems.py"
rmdir "prompt_governance\logic\validation\find_prompt_problems"
git mv "prompt_governance\config\logic\data_access_check_rules\__init__.py" "prompt_governance\config\logic\data_access_check_rules.py"
rmdir "prompt_governance\config\logic\data_access_check_rules"
git mv "prompt_governance\config\logic\data_access_get_info\__init__.py" "prompt_governance\config\logic\data_access_get_info.py"
rmdir "prompt_governance\config\logic\data_access_get_info"
git mv "prompt_governance\config\logic\guardrails\__init__.py" "prompt_governance\config\logic\guardrails.py"
rmdir "prompt_governance\config\logic\guardrails"
git mv "prompt_governance\config\logic\settings\__init__.py" "prompt_governance\config\logic\settings.py"
rmdir "prompt_governance\config\logic\settings"
git mv "prompt_governance\config\logic\synthesis\__init__.py" "prompt_governance\config\logic\synthesis.py"
rmdir "prompt_governance\config\logic\synthesis"
git mv "prompt_governance\config\logic\validation\__init__.py" "prompt_governance\config\logic\validation.py"
rmdir "prompt_governance\config\logic\validation"
git mv "prompt_governance\config\pipeline\data_access_get_info\__init__.py" "prompt_governance\config\pipeline\data_access_get_info.py"
rmdir "prompt_governance\config\pipeline\data_access_get_info"
git mv "prompt_governance\config\pipeline\guardrails\__init__.py" "prompt_governance\config\pipeline\guardrails.py"
rmdir "prompt_governance\config\pipeline\guardrails"
git mv "prompt_governance\config\pipeline\synthesis\__init__.py" "prompt_governance\config\pipeline\synthesis.py"
rmdir "prompt_governance\config\pipeline\synthesis"
git mv "prompt_governance\config\runtime\synthesis\__init__.py" "prompt_governance\config\runtime\synthesis.py"
rmdir "prompt_governance\config\runtime\synthesis"
git mv "prompt_governance\config\security_controls\guardrails\__init__.py" "prompt_governance\config\security_controls\guardrails.py"
rmdir "prompt_governance\config\security_controls\guardrails"
git mv "prompt_governance\cache\data_access\get_prompt_info\__init__.py" "prompt_governance\cache\data_access\get_prompt_info.py"
rmdir "prompt_governance\cache\data_access\get_prompt_info"
git mv "prompt_governance\cache\data_access\get_prompt_info_understand_request\__init__.py" "prompt_governance\cache\data_access\get_prompt_info_understand_request.py"
rmdir "prompt_governance\cache\data_access\get_prompt_info_understand_request"
git mv "prompt_governance\cache\guardrails\check_prompt_rules\__init__.py" "prompt_governance\cache\guardrails\check_prompt_rules.py"
rmdir "prompt_governance\cache\guardrails\check_prompt_rules"
git mv "observability\runtime\guardrails\check_rules_policy_check_safety\__init__.py" "observability\runtime\guardrails\check_rules_policy_check_safety.py"
rmdir "observability\runtime\guardrails\check_rules_policy_check_safety"
git mv "observability\runtime\synthesis\use_tools_use_a_tool\__init__.py" "observability\runtime\synthesis\use_tools_use_a_tool.py"
rmdir "observability\runtime\synthesis\use_tools_use_a_tool"
git mv "observability\runtime\synthesis\use_tools_utility_prepare_information\__init__.py" "observability\runtime\synthesis\use_tools_utility_prepare_information.py"
rmdir "observability\runtime\synthesis\use_tools_utility_prepare_information"
git mv "observability\runtime\validation\check_structure_policy_check_safety\__init__.py" "observability\runtime\validation\check_structure_policy_check_safety.py"
rmdir "observability\runtime\validation\check_structure_policy_check_safety"
git mv "observability\pipeline\data_access\get_info_understand_request\__init__.py" "observability\pipeline\data_access\get_info_understand_request.py"
rmdir "observability\pipeline\data_access\get_info_understand_request"
git mv "observability\pipeline\guardrails\check_rules_policy_check_safety\__init__.py" "observability\pipeline\guardrails\check_rules_policy_check_safety.py"
rmdir "observability\pipeline\guardrails\check_rules_policy_check_safety"
git mv "observability\pipeline\synthesis\use_tools_routing_retry_task\__init__.py" "observability\pipeline\synthesis\use_tools_routing_retry_task.py"
rmdir "observability\pipeline\synthesis\use_tools_routing_retry_task"
git mv "observability\pipeline\synthesis\use_tools_use_a_tool\__init__.py" "observability\pipeline\synthesis\use_tools_use_a_tool.py"
rmdir "observability\pipeline\synthesis\use_tools_use_a_tool"
git mv "observability\logic\data_access\check_rules_policy_check_safety\__init__.py" "observability\logic\data_access\check_rules_policy_check_safety.py"
rmdir "observability\logic\data_access\check_rules_policy_check_safety"
git mv "observability\logic\data_access\get_info_embedding_compare_meaning\__init__.py" "observability\logic\data_access\get_info_embedding_compare_meaning.py"
rmdir "observability\logic\data_access\get_info_embedding_compare_meaning"
git mv "observability\logic\data_access\get_info_understand_request\__init__.py" "observability\logic\data_access\get_info_understand_request.py"
rmdir "observability\logic\data_access\get_info_understand_request"
git mv "observability\logic\data_access\get_info_utility_prepare_information\__init__.py" "observability\logic\data_access\get_info_utility_prepare_information.py"
rmdir "observability\logic\data_access\get_info_utility_prepare_information"
git mv "observability\logic\guardrails\check_rules_policy_check_safety\__init__.py" "observability\logic\guardrails\check_rules_policy_check_safety.py"
rmdir "observability\logic\guardrails\check_rules_policy_check_safety"
git mv "observability\logic\guardrails\manage_costs_state_update\__init__.py" "observability\logic\guardrails\manage_costs_state_update.py"
rmdir "observability\logic\guardrails\manage_costs_state_update"
git mv "observability\logic\synthesis\pick_best_result\__init__.py" "observability\logic\synthesis\pick_best_result.py"
rmdir "observability\logic\synthesis\pick_best_result"
git mv "observability\logic\synthesis\pick_best_result_understand_request\__init__.py" "observability\logic\synthesis\pick_best_result_understand_request.py"
rmdir "observability\logic\synthesis\pick_best_result_understand_request"
git mv "observability\logic\synthesis\state_update\__init__.py" "observability\logic\synthesis\state_update.py"
rmdir "observability\logic\synthesis\state_update"
git mv "observability\logic\synthesis\use_tools_routing_retry_task\__init__.py" "observability\logic\synthesis\use_tools_routing_retry_task.py"
rmdir "observability\logic\synthesis\use_tools_routing_retry_task"
git mv "observability\logic\synthesis\use_tools_use_a_tool\__init__.py" "observability\logic\synthesis\use_tools_use_a_tool.py"
rmdir "observability\logic\synthesis\use_tools_use_a_tool"
git mv "observability\logic\validation\check_structure_policy_check_safety\__init__.py" "observability\logic\validation\check_structure_policy_check_safety.py"
rmdir "observability\logic\validation\check_structure_policy_check_safety"
git mv "observability\logic\validation\convert_content_embedding_compare_meaning\__init__.py" "observability\logic\validation\convert_content_embedding_compare_meaning.py"
rmdir "observability\logic\validation\convert_content_embedding_compare_meaning"
git mv "observability\logic\validation\find_problems\__init__.py" "observability\logic\validation\find_problems.py"
rmdir "observability\logic\validation\find_problems"
git mv "observability\logic\validation\find_problems_diagnostics\__init__.py" "observability\logic\validation\find_problems_diagnostics.py"
rmdir "observability\logic\validation\find_problems_diagnostics"
git mv "observability\cache\data_access\get_info_embedding_compare_meaning\__init__.py" "observability\cache\data_access\get_info_embedding_compare_meaning.py"
rmdir "observability\cache\data_access\get_info_embedding_compare_meaning"
git mv "observability\cache\data_access\get_info_understand_request\__init__.py" "observability\cache\data_access\get_info_understand_request.py"
rmdir "observability\cache\data_access\get_info_understand_request"
git mv "observability\cache\guardrails\check_rules_policy_check_safety\__init__.py" "observability\cache\guardrails\check_rules_policy_check_safety.py"
rmdir "observability\cache\guardrails\check_rules_policy_check_safety"
git mv "config\logic\settings\__init__.py" "config\logic\settings.py"
rmdir "config\logic\settings"
git mv "config\pipeline\data_access\get_info_understand_request\__init__.py" "config\pipeline\data_access\get_info_understand_request.py"
rmdir "config\pipeline\data_access\get_info_understand_request"
git mv "config\pipeline\guardrails\check_rules_policy_check_safety\__init__.py" "config\pipeline\guardrails\check_rules_policy_check_safety.py"
rmdir "config\pipeline\guardrails\check_rules_policy_check_safety"
git mv "config\pipeline\synthesis\use_tools_routing_retry_task\__init__.py" "config\pipeline\synthesis\use_tools_routing_retry_task.py"
rmdir "config\pipeline\synthesis\use_tools_routing_retry_task"
git mv "config\pipeline\synthesis\use_tools_use_a_tool\__init__.py" "config\pipeline\synthesis\use_tools_use_a_tool.py"
rmdir "config\pipeline\synthesis\use_tools_use_a_tool"
git mv "config\logic\data_access\check_rules_policy_check_safety\__init__.py" "config\logic\data_access\check_rules_policy_check_safety.py"
rmdir "config\logic\data_access\check_rules_policy_check_safety"
git mv "config\logic\data_access\get_info_embedding_compare_meaning\__init__.py" "config\logic\data_access\get_info_embedding_compare_meaning.py"
rmdir "config\logic\data_access\get_info_embedding_compare_meaning"
git mv "config\logic\data_access\get_info_understand_request\__init__.py" "config\logic\data_access\get_info_understand_request.py"
rmdir "config\logic\data_access\get_info_understand_request"
git mv "config\logic\data_access\get_info_utility_prepare_information\__init__.py" "config\logic\data_access\get_info_utility_prepare_information.py"
rmdir "config\logic\data_access\get_info_utility_prepare_information"
git mv "config\logic\guardrails\check_rules_policy_check_safety\__init__.py" "config\logic\guardrails\check_rules_policy_check_safety.py"
rmdir "config\logic\guardrails\check_rules_policy_check_safety"
git mv "config\logic\guardrails\manage_costs_state_update\__init__.py" "config\logic\guardrails\manage_costs_state_update.py"
rmdir "config\logic\guardrails\manage_costs_state_update"
git mv "config\logic\synthesis\pick_best_result\__init__.py" "config\logic\synthesis\pick_best_result.py"
rmdir "config\logic\synthesis\pick_best_result"
git mv "config\logic\synthesis\use_tools_use_a_tool\__init__.py" "config\logic\synthesis\use_tools_use_a_tool.py"
rmdir "config\logic\synthesis\use_tools_use_a_tool"
git mv "config\logic\validation\check_structure_policy_check_safety\__init__.py" "config\logic\validation\check_structure_policy_check_safety.py"
rmdir "config\logic\validation\check_structure_policy_check_safety"
git mv "config\logic\validation\convert_content_embedding_compare_meaning\__init__.py" "config\logic\validation\convert_content_embedding_compare_meaning.py"
rmdir "config\logic\validation\convert_content_embedding_compare_meaning"
git mv "config\cache\data_access\get_info_embedding_compare_meaning\__init__.py" "config\cache\data_access\get_info_embedding_compare_meaning.py"
rmdir "config\cache\data_access\get_info_embedding_compare_meaning"
git mv "config\cache\data_access\get_info_understand_request\__init__.py" "config\cache\data_access\get_info_understand_request.py"
rmdir "config\cache\data_access\get_info_understand_request"
git mv "config\cache\guardrails\check_rules_policy_check_safety\__init__.py" "config\cache\guardrails\check_rules_policy_check_safety.py"
rmdir "config\cache\guardrails\check_rules_policy_check_safety"
git mv "archives\legacy_root_folders\orchestration\control_plane\__init__.py" "archives\legacy_root_folders\orchestration\control_plane.py"
rmdir "archives\legacy_root_folders\orchestration\control_plane"
git mv "archives\legacy_root_folders\orchestration\dag_engine\__init__.py" "archives\legacy_root_folders\orchestration\dag_engine.py"
rmdir "archives\legacy_root_folders\orchestration\dag_engine"
git mv "archives\legacy_root_folders\orchestration\model_routing\__init__.py" "archives\legacy_root_folders\orchestration\model_routing.py"
rmdir "archives\legacy_root_folders\orchestration\model_routing"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\pydantic_stub"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\schema\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\schema.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\schema"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.6\openai\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.6\openai.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.6\openai"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\agents\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\agents.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\agents"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\anthropic\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\anthropic.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\anthropic"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\config\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\config.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\config"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\mcp\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\mcp.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\mcp"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\openai\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\openai.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\openai"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\pytest_benchmark\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\pytest_benchmark.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\pytest_benchmark"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\schema\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\schema.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\schema"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\agents\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\agents.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\agents"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\anthropic\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\anthropic.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\anthropic"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\config\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\config.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\config"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\mcp\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\mcp.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\mcp"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\openai\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\openai.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\openai"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\pytest_benchmark\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\pytest_benchmark.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\pytest_benchmark"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\schema\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\schema.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\schema"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\chromadb\utils\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\chromadb\utils.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\chromadb\utils"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\google\generativeai\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\google\generativeai.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\google\generativeai"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\vendor\langchain\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\vendor\langchain.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\vendor\langchain"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\chromadb\utils\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\chromadb\utils.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\chromadb\utils"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\google\generativeai\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\google\generativeai.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\google\generativeai"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\vendor\langchain\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\vendor\langchain.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.7\Agentic-Workflow\vendor\langchain"
git mv "archives\legacy_resume_gen\Older Microservices Models\v10.6\chromadb\utils\__init__.py" "archives\legacy_resume_gen\Older Microservices Models\v10.6\chromadb\utils.py"
rmdir "archives\legacy_resume_gen\Older Microservices Models\v10.6\chromadb\utils"
git mv "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\control_plane\__init__.py" "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\control_plane.py"
rmdir "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\control_plane"
git mv "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\dag_engine\__init__.py" "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\dag_engine.py"
rmdir "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\dag_engine"
git mv "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\model_routing\__init__.py" "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\model_routing.py"
rmdir "archives\legacy_resume_gen\Agentic_Workflow-10_10\orchestration\model_routing"
git mv "archives\legacy_resume_gen\Agentic_Workflow-10_10\tests\vector\__init__.py" "archives\legacy_resume_gen\Agentic_Workflow-10_10\tests\vector.py"
rmdir "archives\legacy_resume_gen\Agentic_Workflow-10_10\tests\vector"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agentic_workflow\workflow_v10_7\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agentic_workflow\workflow_v10_7.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agentic_workflow\workflow_v10_7"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agent_stacks_v10_8\components\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agent_stacks_v10_8\components.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\agent_stacks_v10_8\components"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\chromadb\utils\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\chromadb\utils.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\chromadb\utils"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\engines\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\engines.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\engines"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\models\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\models.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\simulations\models"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\anthropic_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\anthropic_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\anthropic_stub"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\chromadb_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\chromadb_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\chromadb_stub"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\google_generativeai_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\google_generativeai_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\google_generativeai_stub"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\langchain\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\langchain.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\langchain"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\openai_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\openai_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\openai_stub"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pydantic\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pydantic.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pydantic"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pytest_benchmark\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pytest_benchmark.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\pytest_benchmark"
git mv "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\redis_stub\__init__.py" "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\redis_stub.py"
rmdir "archives\legacy_resume_gen\Agentic-Workflow-10_7_main\vendor\redis_stub"
git mv "apps_shared\security\guardrails\check_rules_manage_costs\__init__.py" "apps_shared\security\guardrails\check_rules_manage_costs.py"
rmdir "apps_shared\security\guardrails\check_rules_manage_costs"
git mv "apps_shared\security\guardrails\check_rules_policy_check_safety\__init__.py" "apps_shared\security\guardrails\check_rules_policy_check_safety.py"
rmdir "apps_shared\security\guardrails\check_rules_policy_check_safety"
git mv "apps_shared\runtime\data_access\get_info_understand_request\__init__.py" "apps_shared\runtime\data_access\get_info_understand_request.py"
rmdir "apps_shared\runtime\data_access\get_info_understand_request"
git mv "apps_shared\runtime\synthesis\use_tools_use_a_tool\__init__.py" "apps_shared\runtime\synthesis\use_tools_use_a_tool.py"
rmdir "apps_shared\runtime\synthesis\use_tools_use_a_tool"
git mv "apps_shared\runtime\synthesis\use_tools_utility_prepare_information\__init__.py" "apps_shared\runtime\synthesis\use_tools_utility_prepare_information.py"
rmdir "apps_shared\runtime\synthesis\use_tools_utility_prepare_information"
git mv "apps_shared\runtime\validation\check_format_policy_check_safety\__init__.py" "apps_shared\runtime\validation\check_format_policy_check_safety.py"
rmdir "apps_shared\runtime\validation\check_format_policy_check_safety"
git mv "apps_shared\rag\hardening\content\__init__.py" "apps_shared\rag\hardening\content.py"
rmdir "apps_shared\rag\hardening\content"
git mv "apps_shared\rag\hardening\diagnostics\__init__.py" "apps_shared\rag\hardening\diagnostics.py"
rmdir "apps_shared\rag\hardening\diagnostics"
git mv "apps_shared\rag\hardening\diagnostics_diagnostics\__init__.py" "apps_shared\rag\hardening\diagnostics_diagnostics.py"
rmdir "apps_shared\rag\hardening\diagnostics_diagnostics"
git mv "apps_shared\rag\hardening\guardrails\__init__.py" "apps_shared\rag\hardening\guardrails.py"
rmdir "apps_shared\rag\hardening\guardrails"
git mv "apps_shared\rag\hardening\guardrails_check_rules\__init__.py" "apps_shared\rag\hardening\guardrails_check_rules.py"
rmdir "apps_shared\rag\hardening\guardrails_check_rules"
git mv "apps_shared\rag\hardening\structure\__init__.py" "apps_shared\rag\hardening\structure.py"
rmdir "apps_shared\rag\hardening\structure"
git mv "apps_shared\rag\hardening\validation\__init__.py" "apps_shared\rag\hardening\validation.py"
rmdir "apps_shared\rag\hardening\validation"
git mv "apps_shared\rag\retrieval\check_rules_policy_check_safety\__init__.py" "apps_shared\rag\retrieval\check_rules_policy_check_safety.py"
rmdir "apps_shared\rag\retrieval\check_rules_policy_check_safety"
git mv "apps_shared\rag\retrieval\get_info_embedding_compare_meaning\__init__.py" "apps_shared\rag\retrieval\get_info_embedding_compare_meaning.py"
rmdir "apps_shared\rag\retrieval\get_info_embedding_compare_meaning"
git mv "apps_shared\rag\retrieval\get_info_understand_request\__init__.py" "apps_shared\rag\retrieval\get_info_understand_request.py"
rmdir "apps_shared\rag\retrieval\get_info_understand_request"
git mv "apps_shared\rag\retrieval\get_info_utility_prepare_information\__init__.py" "apps_shared\rag\retrieval\get_info_utility_prepare_information.py"
rmdir "apps_shared\rag\retrieval\get_info_utility_prepare_information"
git mv "apps_shared\pipeline\data_access\get_info_understand_request\__init__.py" "apps_shared\pipeline\data_access\get_info_understand_request.py"
rmdir "apps_shared\pipeline\data_access\get_info_understand_request"
git mv "apps_shared\pipeline\guardrails\check_rules_policy_check_safety\__init__.py" "apps_shared\pipeline\guardrails\check_rules_policy_check_safety.py"
rmdir "apps_shared\pipeline\guardrails\check_rules_policy_check_safety"
git mv "apps_shared\pipeline\synthesis\use_tools_routing_retry_task\__init__.py" "apps_shared\pipeline\synthesis\use_tools_routing_retry_task.py"
rmdir "apps_shared\pipeline\synthesis\use_tools_routing_retry_task"
git mv "apps_shared\pipeline\synthesis\use_tools_use_a_tool\__init__.py" "apps_shared\pipeline\synthesis\use_tools_use_a_tool.py"
rmdir "apps_shared\pipeline\synthesis\use_tools_use_a_tool"
git mv "apps_shared\logic\data_access\check_rules_policy_check_safety\__init__.py" "apps_shared\logic\data_access\check_rules_policy_check_safety.py"
rmdir "apps_shared\logic\data_access\check_rules_policy_check_safety"
git mv "apps_shared\logic\data_access\get_info_embedding_compare_meaning\__init__.py" "apps_shared\logic\data_access\get_info_embedding_compare_meaning.py"
rmdir "apps_shared\logic\data_access\get_info_embedding_compare_meaning"
git mv "apps_shared\logic\data_access\get_info_understand_request\__init__.py" "apps_shared\logic\data_access\get_info_understand_request.py"
rmdir "apps_shared\logic\data_access\get_info_understand_request"
git mv "apps_shared\logic\data_access\get_info_utility_prepare_information\__init__.py" "apps_shared\logic\data_access\get_info_utility_prepare_information.py"
rmdir "apps_shared\logic\data_access\get_info_utility_prepare_information"
git mv "apps_shared\logic\guardrails\check_rules_policy_check_safety\__init__.py" "apps_shared\logic\guardrails\check_rules_policy_check_safety.py"
rmdir "apps_shared\logic\guardrails\check_rules_policy_check_safety"
git mv "apps_shared\logic\guardrails\manage_costs_state_update\__init__.py" "apps_shared\logic\guardrails\manage_costs_state_update.py"
rmdir "apps_shared\logic\guardrails\manage_costs_state_update"
git mv "apps_shared\logic\synthesis\check_format_policy_check_safety\__init__.py" "apps_shared\logic\synthesis\check_format_policy_check_safety.py"
rmdir "apps_shared\logic\synthesis\check_format_policy_check_safety"
git mv "apps_shared\logic\synthesis\pick_best_result\__init__.py" "apps_shared\logic\synthesis\pick_best_result.py"
rmdir "apps_shared\logic\synthesis\pick_best_result"
git mv "apps_shared\logic\synthesis\use_tools_routing_retry_task\__init__.py" "apps_shared\logic\synthesis\use_tools_routing_retry_task.py"
rmdir "apps_shared\logic\synthesis\use_tools_routing_retry_task"
git mv "apps_shared\logic\synthesis\use_tools_use_a_tool\__init__.py" "apps_shared\logic\synthesis\use_tools_use_a_tool.py"
rmdir "apps_shared\logic\synthesis\use_tools_use_a_tool"
git mv "apps_shared\logic\validation\check_format_policy_check_safety\__init__.py" "apps_shared\logic\validation\check_format_policy_check_safety.py"
rmdir "apps_shared\logic\validation\check_format_policy_check_safety"
git mv "apps_shared\logic\validation\convert\__init__.py" "apps_shared\logic\validation\convert.py"
rmdir "apps_shared\logic\validation\convert"
git mv "apps_shared\logic\validation\find_problems\__init__.py" "apps_shared\logic\validation\find_problems.py"
rmdir "apps_shared\logic\validation\find_problems"
git mv "apps_shared\logic\validation\pick_best_result\__init__.py" "apps_shared\logic\validation\pick_best_result.py"
rmdir "apps_shared\logic\validation\pick_best_result"
git mv "apps_shared\cache\data_access\get_info_embedding_compare_meaning\__init__.py" "apps_shared\cache\data_access\get_info_embedding_compare_meaning.py"
rmdir "apps_shared\cache\data_access\get_info_embedding_compare_meaning"
git mv "apps_shared\cache\data_access\get_info_understand_request\__init__.py" "apps_shared\cache\data_access\get_info_understand_request.py"
rmdir "apps_shared\cache\data_access\get_info_understand_request"
git mv "apps_shared\cache\guardrails\check_rules_policy_check_safety\__init__.py" "apps_shared\cache\guardrails\check_rules_policy_check_safety.py"
rmdir "apps_shared\cache\guardrails\check_rules_policy_check_safety"
git mv "apps_rg\L1_cognition\P1_retrieve\check_resume_rules\__init__.py" "apps_rg\L1_cognition\P1_retrieve\check_resume_rules.py"
rmdir "apps_rg\L1_cognition\P1_retrieve\check_resume_rules"
git mv "apps_rg\L1_cognition\P3_aggregate\use_tools_use_a_tool\__init__.py" "apps_rg\L1_cognition\P3_aggregate\use_tools_use_a_tool.py"
rmdir "apps_rg\L1_cognition\P3_aggregate\use_tools_use_a_tool"
git mv "apps_rg\L1_cognition\P4_safety\check_resume_rules\__init__.py" "apps_rg\L1_cognition\P4_safety\check_resume_rules.py"
rmdir "apps_rg\L1_cognition\P4_safety\check_resume_rules"
git mv "apps_lic\L1_cognition\P1_retrieve\check_outreach_rules\__init__.py" "apps_lic\L1_cognition\P1_retrieve\check_outreach_rules.py"
rmdir "apps_lic\L1_cognition\P1_retrieve\check_outreach_rules"
git mv "apps_lic\L1_cognition\P1_retrieve\get_info_embedding_compare_meaning\__init__.py" "apps_lic\L1_cognition\P1_retrieve\get_info_embedding_compare_meaning.py"
rmdir "apps_lic\L1_cognition\P1_retrieve\get_info_embedding_compare_meaning"
git mv "apps_lic\L1_cognition\P1_retrieve\get_info_understand_request\__init__.py" "apps_lic\L1_cognition\P1_retrieve\get_info_understand_request.py"
rmdir "apps_lic\L1_cognition\P1_retrieve\get_info_understand_request"
git mv "apps_lic\L1_cognition\P1_retrieve\get_info_utility_prepare_information\__init__.py" "apps_lic\L1_cognition\P1_retrieve\get_info_utility_prepare_information.py"
rmdir "apps_lic\L1_cognition\P1_retrieve\get_info_utility_prepare_information"
git mv "apps_lic\L1_cognition\P3_aggregate\pick_message_refinement_adjust_scores\__init__.py" "apps_lic\L1_cognition\P3_aggregate\pick_message_refinement_adjust_scores.py"
rmdir "apps_lic\L1_cognition\P3_aggregate\pick_message_refinement_adjust_scores"
git mv "apps_lic\L1_cognition\P3_aggregate\use_tools_routing_retry_task\__init__.py" "apps_lic\L1_cognition\P3_aggregate\use_tools_routing_retry_task.py"
rmdir "apps_lic\L1_cognition\P3_aggregate\use_tools_routing_retry_task"
git mv "apps_lic\L1_cognition\P3_aggregate\use_tools_use_a_tool\__init__.py" "apps_lic\L1_cognition\P3_aggregate\use_tools_use_a_tool.py"
rmdir "apps_lic\L1_cognition\P3_aggregate\use_tools_use_a_tool"
git mv "apps_lic\L1_cognition\P4_safety\check_outreach_rules\__init__.py" "apps_lic\L1_cognition\P4_safety\check_outreach_rules.py"
rmdir "apps_lic\L1_cognition\P4_safety\check_outreach_rules"
git mv "agentic_core\L3_orchestration\data_access\get_info_understand_request\__init__.py" "agentic_core\L3_orchestration\data_access\get_info_understand_request.py"
rmdir "agentic_core\L3_orchestration\data_access\get_info_understand_request"
git mv "agentic_core\L3_orchestration\guardrails\check_rules_policy_check_safety\__init__.py" "agentic_core\L3_orchestration\guardrails\check_rules_policy_check_safety.py"
rmdir "agentic_core\L3_orchestration\guardrails\check_rules_policy_check_safety"
git mv "agentic_core\L3_orchestration\synthesis\use_tools_routing_retry_task\__init__.py" "agentic_core\L3_orchestration\synthesis\use_tools_routing_retry_task.py"
rmdir "agentic_core\L3_orchestration\synthesis\use_tools_routing_retry_task"
git mv "agentic_core\L3_orchestration\synthesis\use_tools_use_a_tool\__init__.py" "agentic_core\L3_orchestration\synthesis\use_tools_use_a_tool.py"
rmdir "agentic_core\L3_orchestration\synthesis\use_tools_use_a_tool"
git mv "agentic_core\L2_execution\tools\routing_retry_task\__init__.py" "agentic_core\L2_execution\tools\routing_retry_task.py"
rmdir "agentic_core\L2_execution\tools\routing_retry_task"
git mv "agentic_core\L1_cognition\P1_retrieve\check_rules_policy_check_safety\__init__.py" "agentic_core\L1_cognition\P1_retrieve\check_rules_policy_check_safety.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\check_rules_policy_check_safety"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_embedding_embedding_compare_meaning\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_embedding_embedding_compare_meaning.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_embedding_embedding_compare_meaning"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals_understand_request\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals_understand_request.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_integrate_source_signals_understand_request"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_understand\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_understand.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_understand"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility"
git mv "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility_utility_prepare_information\__init__.py" "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility_utility_prepare_information.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\gather_context_inputs_utility_utility_prepare_information"
git mv "agentic_core\L1_cognition\P1_retrieve\get_info_understand_request\__init__.py" "agentic_core\L1_cognition\P1_retrieve\get_info_understand_request.py"
rmdir "agentic_core\L1_cognition\P1_retrieve\get_info_understand_request"
git mv "agentic_core\L1_cognition\P2_inspect\check_structure_policy\__init__.py" "agentic_core\L1_cognition\P2_inspect\check_structure_policy.py"
rmdir "agentic_core\L1_cognition\P2_inspect\check_structure_policy"
git mv "agentic_core\L1_cognition\P2_inspect\check_structure_policy_check_safety\__init__.py" "agentic_core\L1_cognition\P2_inspect\check_structure_policy_check_safety.py"
rmdir "agentic_core\L1_cognition\P2_inspect\check_structure_policy_check_safety"
git mv "agentic_core\L1_cognition\P2_inspect\check_structure_semantic_semantic_adjust_scores\__init__.py" "agentic_core\L1_cognition\P2_inspect\check_structure_semantic_semantic_adjust_scores.py"
rmdir "agentic_core\L1_cognition\P2_inspect\check_structure_semantic_semantic_adjust_scores"
git mv "agentic_core\L1_cognition\P2_inspect\convert_content\__init__.py" "agentic_core\L1_cognition\P2_inspect\convert_content.py"
rmdir "agentic_core\L1_cognition\P2_inspect\convert_content"
git mv "agentic_core\L1_cognition\P2_inspect\convert_core_content\__init__.py" "agentic_core\L1_cognition\P2_inspect\convert_core_content.py"
rmdir "agentic_core\L1_cognition\P2_inspect\convert_core_content"
git mv "agentic_core\L1_cognition\P2_inspect\convert_core_content_embedding_embedding_compare_meaning\__init__.py" "agentic_core\L1_cognition\P2_inspect\convert_core_content_embedding_embedding_compare_meaning.py"
rmdir "agentic_core\L1_cognition\P2_inspect\convert_core_content_embedding_embedding_compare_meaning"
git mv "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic\__init__.py" "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic.py"
rmdir "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic"
git mv "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic_semantic_adjust_scores\__init__.py" "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic_semantic_adjust_scores.py"
rmdir "agentic_core\L1_cognition\P2_inspect\convert_core_content_semantic_semantic_adjust_scores"
git mv "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms\__init__.py" "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms.py"
rmdir "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms"
git mv "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms_update_memory\__init__.py" "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms_update_memory.py"
rmdir "agentic_core\L1_cognition\P2_inspect\detect_anomalies_analyze_symptoms_update_memory"
git mv "agentic_core\L1_cognition\P3_aggregate\pick_best_result\__init__.py" "agentic_core\L1_cognition\P3_aggregate\pick_best_result.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\pick_best_result"
git mv "agentic_core\L1_cognition\P3_aggregate\pick_best_result_understand_request\__init__.py" "agentic_core\L1_cognition\P3_aggregate\pick_best_result_understand_request.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\pick_best_result_understand_request"
git mv "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options\__init__.py" "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options"
git mv "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options_understand_request\__init__.py" "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options_understand_request.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\select_optimal_evaluate_options_understand_request"
git mv "agentic_core\L1_cognition\P3_aggregate\select_optimal_refinement_semantic_adjust_scores\__init__.py" "agentic_core\L1_cognition\P3_aggregate\select_optimal_refinement_semantic_adjust_scores.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\select_optimal_refinement_semantic_adjust_scores"
git mv "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory\__init__.py" "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory"
git mv "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory_update_memory\__init__.py" "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory_update_memory.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\sync_status_update_memory_update_memory"
git mv "agentic_core\L1_cognition\P3_aggregate\sync_status_utility\__init__.py" "agentic_core\L1_cognition\P3_aggregate\sync_status_utility.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\sync_status_utility"
git mv "agentic_core\L1_cognition\P3_aggregate\sync_status_utility_utility_prepare_information\__init__.py" "agentic_core\L1_cognition\P3_aggregate\sync_status_utility_utility_prepare_information.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\sync_status_utility_utility_prepare_information"
git mv "agentic_core\L1_cognition\P3_aggregate\use_tools_routing_retry_task\__init__.py" "agentic_core\L1_cognition\P3_aggregate\use_tools_routing_retry_task.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\use_tools_routing_retry_task"
git mv "agentic_core\L1_cognition\P3_aggregate\use_tools_use_a_tool\__init__.py" "agentic_core\L1_cognition\P3_aggregate\use_tools_use_a_tool.py"
rmdir "agentic_core\L1_cognition\P3_aggregate\use_tools_use_a_tool"
git mv "agentic_core\L1_cognition\P4_safety\check_rules_policy_check_safety\__init__.py" "agentic_core\L1_cognition\P4_safety\check_rules_policy_check_safety.py"
rmdir "agentic_core\L1_cognition\P4_safety\check_rules_policy_check_safety"
git mv "agentic_core\L1_cognition\P4_safety\control_resources_track_usage\__init__.py" "agentic_core\L1_cognition\P4_safety\control_resources_track_usage.py"
rmdir "agentic_core\L1_cognition\P4_safety\control_resources_track_usage"
git mv "agentic_core\L1_cognition\P4_safety\control_resources_track_usage_update_memory\__init__.py" "agentic_core\L1_cognition\P4_safety\control_resources_track_usage_update_memory.py"
rmdir "agentic_core\L1_cognition\P4_safety\control_resources_track_usage_update_memory"
