"""
01_agentic_core/L1_cognition/P3_aggregate/select-optimal/refinement/refine.py
AUTO-HARDENED BY ZERO-LOSS MERGE ENGINE
L5 CANONICAL — WINDSURF Ω — 2025-12-07
MERKLE-INTENDED: a5e4ded0a371d9bafce3b5ff6efa7dce8c70bb532ff68f939b847f8e56c8f457
"""


from __future__ import annotations
# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

from meta.metacognition.models import Hypothesis


from meta.metacognition.refinement import refine_low_confidence


def test_refine_marks_very_low_confidence_as_discarded():
    hs = [
        Hypothesis(id="h1", agent_id="a1", content="c1", confidence=0.1),
        Hypothesis(id="h2", agent_id="a1", content="c2", confidence=0.5),
    ]

    refined = refine_low_confidence(hs, threshold=0.4)
    assert refined[0].content.startswith("[DISCARDED_CANDIDATE]")
    assert "needs further evidence" in refined[1].content
