# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

"""Append signature information to the outreach draft."""


from __future__ import annotations


class SignatureAgent:
    def attach(self, draft: str, route_decision) -> str:
        signature = "Best regards,\nLIC Outreach Bot"
        return f"{draft}\n\n{signature}"
