"""
07_observability\_unassigned\support_nomatch\token_budget_inspector.py
Auto-hardened by WINDSURF v2
"""

from __future__ import annotations
# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

from types import SimpleNamespace


from src.lic_agentic.reasoning.toggles import ReasoningToggles


from src.lic_agentic.stacks.outreach_stack import OutreachStack


def test_token_drift_guard():
    stack = OutreachStack(ReasoningToggles())
    sample = SimpleNamespace(prompt="Checking drift bounds", company_id="ACME", contact_id="C1")
    outcome = stack.run(sample)
    verdict = outcome["verdict"]
    assert verdict.passed
    drift = stack.validator.metrics.token_drift()
    assert drift <= 0.1
