"""Auto-generated flattened view for simulations/test_safety_sim.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "simulations/test_safety_sim.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: '''"""Tests for safety simulator."""

import pytest

from simulations.engines.safety_sim import SafetySimulator
from simulations.models import SafetySimRequest


@pytest.mark.asyncio
async def test_safety_simulator_returns_result():
    simulator = SafetySimulator()
    request = SafetySimRequest(
        simulation_id="sim-safety",
        payload={},
        text="Some text that might contain pii.",
    )
    result = await simulator.run(request)
    assert result.success is True
    assert 0.0 <= result.metrics["pii_risk"] <= 1.0
    assert 0.0 <= result.metrics["injection_risk"] <= 1.0
    assert 0.0 <= result.metrics["bias_risk"] <= 1.0
    assert "text_snippet" in result.details


def test_safety_request_validation():
    request = SafetySimRequest(
        simulation_id="sim-safety-validate",
        payload={},
        text="abc",
    )
    assert request.text == "abc"
'''
}

ORIGINAL_MODULE_NAME = "tests.simulations.test_safety_sim"
FLAT_MODULE_NAME = "tests_flat.simulations__test_safety_sim"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
