"""Auto-generated flattened view for stacks/test_bullet_execution_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "stacks/test_bullet_execution_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import pytest

from stacks_v10_8.bullet_execution import BulletExecutionStack


@pytest.mark.asyncio
async def test_generate_from_state_async_builds_expected_patch(workflow_context):
    state = {
        "metadata": {"workflow_id": "wf-bullets"},
        "prompts": {"prompts": {"bullet_generation_prompt": "Write impact bullets."}},
        "strategy": {
            "strategy_plan": {
                "strategy_name": "default",
                "focus_areas": ["impact"],
                "key_achievements_to_highlight": ["growth"],
                "tone": "Bold",
            }
        },
        "resume": {
            "experience_bullets": [
                {"id": "exp-1", "text": "Improved retention"},
                {"id": "exp-2", "text": "Cut churn"},
            ]
        },
    }
    stack = BulletExecutionStack(workflow_context)
    captured = {}

    async def fake_generate_async(prompt, experiences, strategy, workflow_id):
        captured["prompt"] = prompt
        captured["experiences"] = experiences
        captured["workflow_id"] = workflow_id
        captured["strategy_tone"] = strategy.tone if hasattr(strategy, "tone") else None
        return {"bullets": {"generated_bullets": experiences}}

    stack.generate_async = fake_generate_async  # type: ignore[assignment]
    patch = await stack.generate_from_state_async(state, "wf-bullets")

    assert captured["prompt"] == "Write impact bullets."
    assert captured["workflow_id"] == "wf-bullets"
    assert captured["strategy_tone"] == "Bold"
    assert patch["bullets"]["generated_bullets"] == state["resume"]["experience_bullets"][:3]


@pytest.mark.asyncio
async def test_critique_from_state_async_uses_generated_bullets(workflow_context):
    state = {
        "metadata": {"workflow_id": "wf-critique"},
        "prompts": {"prompts": {"critique_prompt": "Score bullets"}},
        "bullets": {
            "generated_bullets": [
                {"id": "b-1", "text": "Shipped features"},
                {"id": "b-2", "text": "Optimized ops"},
            ]
        },
    }
    stack = BulletExecutionStack(workflow_context)
    captured = {}

    async def fake_critique_async(bullets, critique_prompt, workflow_id):
        captured["bullets"] = bullets
        captured["prompt"] = critique_prompt
        captured["workflow_id"] = workflow_id
        return {"bullets": {"critiqued_bullets": bullets}}

    stack.critique_async = fake_critique_async  # type: ignore[assignment]
    patch = await stack.critique_from_state_async(state, None)

    assert captured["prompt"] == "Score bullets"
    assert captured["workflow_id"] == "wf-critique"
    assert patch["bullets"]["critiqued_bullets"] == state["bullets"]["generated_bullets"]
"""
}

ORIGINAL_MODULE_NAME = "tests.stacks.test_bullet_execution_v10_7"
FLAT_MODULE_NAME = "tests_flat.stacks__test_bullet_execution_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
