"""Auto-generated flattened view for integration/test_safety_pipeline_e2e.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "integration/test_safety_pipeline_e2e.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import pytest

from models import MainGraphState

try:  # Optional depending on build exposure
    from agent_orchestration_v10_7 import build_workflow

    HAS_WORKFLOW = True
except ImportError:  # pragma: no cover - guard until workflow factory is available
    HAS_WORKFLOW = False


@pytest.mark.skipif(not HAS_WORKFLOW, reason="Workflow builder not available")
def test_safety_fields_populate_in_simple_run():
    initial = MainGraphState()
    workflow = build_workflow(debug_mode=False)

    result_state = workflow.invoke(initial)

    assert hasattr(result_state, "safety_report")
    assert hasattr(result_state, "policy_decision")
    assert hasattr(result_state, "constitutional_review")
"""
}

ORIGINAL_MODULE_NAME = "tests.integration.test_safety_pipeline_e2e"
FLAT_MODULE_NAME = "tests_flat.integration__test_safety_pipeline_e2e"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
