"""Proof-evidence test for 10C-REQ-052 (01_U0_Request_Intake).

Severity      : CRITICAL
Surface       : 01_U0_Request_Intake
Layer owner   : L5/gateway
Artifact      : ValidatedRequest
OTEL span     : u0.intake.quota_checked
Source        : 01_request_intake.md :: E3 CHECKING DAILY LIMITS

Canonical requirement (paraphrased): Quota validation MUST: Enforce quota burst/abuse control suppress duplicates guard same-ask spam deny early before load

Negative control text (from ledger row, paraphrased): Row-specific [10C-REQ-052]: ValidatedRequest emitted without satisfying 'Quota validation MUST: Enforce quota burst/abuse control suppress d...

Generated by tools/requirements/generate_wave1_tests.py from
artifacts/requirements/wave1_critical_specs.json. Re-run the generator to
regenerate; do NOT hand-edit the rows that match the ledger spec.
"""

from __future__ import annotations

import pytest

from tests.fixtures.proof_evidence.otel_span_receipt import (
    BASE_REQUIRED_ATTRS,
    SpanAssertionError,
    assert_owner_surface_matches,
    assert_span_shape,
    make_receipt,
)
from tests.fixtures.proof_evidence.replay_digest import (
    assert_replay_drift_detected,
    assert_replay_stable,
)
from tests.fixtures.proof_evidence.runtime_artifact_validators import (
    ArtifactShapeError,
    assert_u0_no_authority_leak,
    validate_artifact_shape,
)

REQ_ID = "10C-REQ-052"
OWNER_SURFACE = "01_U0_Request_Intake"
EXPECTED_SPAN = "u0.intake.quota_checked"
ARTIFACT_TYPE = "ValidatedRequest"

# OTEL required attributes from the ledger row's otel_required_attributes
# column (pipe-delimited). BASE_REQUIRED_ATTRS already covers req_id, run_id,
# trace_id, request_id, owner_surface, policy_hash, blueprint_hash, replay_key.
EXTRA_SPAN_ATTRS = tuple(
    a for a in 'req_id|run_id|trace_id|request_id|owner_surface|policy_hash|blueprint_hash|replay_key|tenant|identity|session_id'.split("|")
    if a and a not in BASE_REQUIRED_ATTRS
)
REQUIRED_ATTRS = BASE_REQUIRED_ATTRS + EXTRA_SPAN_ATTRS

def _valid_artifact() -> dict:
    return {
        "request_id": "req-52-001",
        "session_id": "sess-52-001",
        "trace_root": "trace-52-001",
        "tenant": "tenant-A",
        "transport": "https",
        "ingress_envelope": {"schema_version": "v1", "method": "POST"},
        "caller_scope_baseline": {"role": "user", "scopes": ["read"]},
        "ingress_time_utc": "2026-04-30T12:00:00+00:00",
        "owner_surface": OWNER_SURFACE,
    }

def _valid_span_attrs() -> dict:
    attrs = {
        "req_id": REQ_ID,
        "run_id": "run-52-001",
        "trace_id": "trace-52-001",
        "request_id": "req-52-001",
        "owner_surface": OWNER_SURFACE,
        "policy_hash": "policy-52-h",
        "blueprint_hash": "blueprint-52-h",
        "replay_key": "replay-52-k",
    }
    # Add any extra row-required span attrs with deterministic placeholders.
    for a in EXTRA_SPAN_ATTRS:
        attrs.setdefault(a, f"{a}-52-v")
    return attrs


# ---------------------------------------------------------------------------
# Positive controls
# ---------------------------------------------------------------------------

def test_artifact_shape_positive() -> None:
    """A well-formed ValidatedRequest must validate cleanly + satisfy boundary invariant."""
    record = _valid_artifact()
    validate_artifact_shape(ARTIFACT_TYPE, record)
    assert_u0_no_authority_leak(record)


def test_span_shape_positive() -> None:
    """The u0.intake.quota_checked span must carry all required attrs."""
    receipt = make_receipt(EXPECTED_SPAN, _valid_span_attrs())
    assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)
    assert_owner_surface_matches(receipt, OWNER_SURFACE)


def test_replay_digest_stability_positive() -> None:
    """Same artifact yields the same digest across runs."""
    digest = assert_replay_stable(_valid_artifact())
    assert len(digest) == 64  # sha256 hex


# ---------------------------------------------------------------------------
# Negative controls (matches negative_control_specific from the ledger row)
# ---------------------------------------------------------------------------

def test_negative_control_specific_violation() -> None:
    """10C-REQ-052: per ledger row, a ValidatedRequest that violates the canonical
    requirement MUST raise. Drift inducer: route_id_leak.
    """
    record = _valid_artifact()
    record["route_id"] = "R-LEAK"  # U0 must not carry route_id
    with pytest.raises(ArtifactShapeError):
        assert_u0_no_authority_leak(record)


def test_negative_control_missing_required_field() -> None:
    """A ValidatedRequest missing the required field 'tenant' MUST fail shape validation."""
    record = _valid_artifact()
    del record['tenant']
    with pytest.raises(ArtifactShapeError) as excinfo:
        validate_artifact_shape(ARTIFACT_TYPE, record)
    assert 'tenant' in str(excinfo.value)


def test_negative_control_span_missing_owner_surface() -> None:
    """Span without owner_surface MUST fail shape assertion."""
    attrs = _valid_span_attrs()
    del attrs["owner_surface"]
    receipt = make_receipt(EXPECTED_SPAN, attrs)
    with pytest.raises(SpanAssertionError):
        assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)


def test_negative_control_replay_drift() -> None:
    """Two semantically different artifacts MUST produce different digests."""
    a = _valid_artifact()
    b = _valid_artifact()
    # Mutate a deterministic field that participates in the digest.
    if "owner_surface" in b:
        b["owner_surface"] = OWNER_SURFACE + "-DRIFTED"
    assert_replay_drift_detected(a, b)
