# AUTO-GENERATED BY PHASE A — DO NOT EDIT
# Canonical regenerated LIC capability registry derived solely from LIC hash-index.

LIC_CAPABILITIES = {
    "routing_rules": {
        "CONNECTION_REQ": {
            "conditions": {
                "connection_status": "not_connected",
                "prior_message_count": 0
            },
            "constraints": {
                "word_range": [40, 60],
                "char_limit": 300,
                "subject_required": False
            }
        },
        "INMAIL": {
            "conditions": {
                "connection_status": "not_connected",
                "prior_message_count_gte": 0
            },
            "constraints": {
                "word_range": [180, 250],
                "char_limit": 1900,
                "subject_required": True
            }
        },
        "EMAIL": {
            "conditions": {
                "connection_status": "connected"
            },
            "constraints": {
                "word_range": [200, 350],
                "char_limit": 2500,
                "subject_required": True
            }
        },
        "FOLLOW_UP": {
            "conditions": {
                "prior_message_count_gt": 0
            },
            "constraints": {
                "word_range": [150, 220],
                "char_limit": 1600,
                "subject_required": True
            }
        }
    },
    
    "parameter_presets": {
        "circuit_breaker": {
            "failure_threshold": 3,
            "timeout_seconds": 60
        },
        "context_manager": {
            "section_priorities": {
                "job_description": 100,
                "recipient_profile": 90,
                "company_context": 80,
                "sender_profile": 70,
                "rag_recent": 60,
                "rag_historical": 40,
                "examples": 30
            },
            "max_context_tokens": 180000,
            "chars_per_token": 4,
            "min_truncated_section_chars": 100
        },
        "adaptive_temperature_controller": {
            "base_temperatures": {
                "C_LEVEL": 0.45,
                "EXECUTIVE": 0.5,
                "SENIOR_TA": 0.55,
                "RECRUITER": 0.65
            },
            "escalation_step": 0.15,
            "max_temperature": 0.95,
            "max_creative_retries": 3
        }
    },
    
    "insight_patterns": {
        "signal_quality_scorer": {
            "source_weights": {
                "STRATEGIC_BRIEF": 2.5,
                "RECIPIENT_LINKEDIN_ABOUT": 2.0,
                "RECIPIENT_RECENT_POST": 1.8,
                "COMPANY_BLOG_ANNOUNCEMENT": 1.5,
                "COMPANY_LINKEDIN_PAGE": 1.3,
                "NEWS_ARTICLE_COMPANY": 1.2,
                "COMPETITOR_COMPARISON": 0.9,
                "GENERIC_INDUSTRY_TREND": 0.6,
                "SENDER_PROFILE_ONLY": 0.3,
                "MASTER_RESUME": 2.0,
                "SENDER_KNOWLEDGE_BASE": 1.8
            },
            "minimum_signal_threshold": 0.7
        },
        "claim_confidence_scorer": {
            "min_per_claim_confidence": 0.7,
            "min_aggregate_confidence": 0.75,
            "min_word_overlap": 3,
            "confidence_calculation": {
                "supporting_source_weight": 0.3,
                "avg_source_weight": 0.7,
                "source_boost_per_additional": 0.1,
                "max_confidence": 1.0
            }
        }
    },
    
    "message_templates": {
        "cta_templates": {
            "CONNECTION_REQ": {
                "default": None
            },
            "INMAIL": {
                "C_LEVEL": "Would you be open to a brief conversation about how [TOPIC] might align with your strategic priorities?",
                "EXECUTIVE": "I'd welcome the chance to discuss how [TOPIC] could support your team's objectives.",
                "SENIOR_TA": {
                    "direct": "Would you have 15 minutes to discuss [TECHNICAL_TOPIC]?",
                    "deferential": "If this aligns with your team's direction, I'd appreciate any guidance you could share."
                },
                "RECRUITER": "Would you be open to a conversation about roles that might match your team's needs?"
            },
            "EMAIL": {
                "C_LEVEL": "I'd value the opportunity to explore how [TOPIC] aligns with your vision for [COMPANY].",
                "EXECUTIVE": "Would you be open to a brief call to discuss [TOPIC]?",
                "SENIOR_TA": {
                    "direct": "Could we schedule 20 minutes to dive into [TECHNICAL_TOPIC]?",
                    "deferential": "If this resonates with your team's roadmap, I'd be grateful for any insights you could offer."
                },
                "RECRUITER": "I'd welcome a conversation about potential opportunities that could benefit your team."
            },
            "FOLLOW_UP": {
                "default": "Following up on my previous message - would you have time for a brief conversation this week?"
            }
        },
        "generation_system_prompt": {
            "core_identity": "You are an expert at crafting personalized, high-signal professional outreach messages.",
            "core_principles": [
                "Every word must count - no filler, no generic statements",
                "Ground all claims in research evidence",
                "Write as a peer, not a supplicant",
                "Lead with value, not need",
                "Be specific and concrete, never vague",
                "Use active voice and confident phrasing"
            ],
            "forbidden_patterns": [
                "Placeholder text like [TOPIC], [COMPANY], etc.",
                "Weak phrases: 'I hope', 'I wanted to', 'just reaching out'",
                "Corporate clichés: 'spearheaded', 'leveraged', 'synergized'",
                "Generic statements that could apply to anyone",
                "Unsupported claims about sender capabilities"
            ],
            "required_patterns": [
                "Specific references to recipient's work, role, or recent activity",
                "Clear connection between sender experience and recipient needs",
                "Concrete value proposition",
                "Natural, conversational tone",
                "Perfect grammar and professional formatting"
            ]
        }
    },
    
    "cta_patterns": {
        "archetype_specific": {
            "C_LEVEL": {
                "style": "strategic_alignment",
                "verbs": ["discuss", "align", "explore", "advance"],
                "focus": "business_impact"
            },
            "EXECUTIVE": {
                "style": "collaborative_value",
                "verbs": ["collaborate", "discuss", "connect", "share"],
                "focus": "team_objectives"
            },
            "SENIOR_TA": {
                "style": "technical_peer",
                "verbs": ["build", "implement", "architect", "optimize"],
                "focus": "technical_challenges"
            },
            "RECRUITER": {
                "style": "warm_professional",
                "verbs": ["match", "connect", "support", "assist"],
                "focus": "role_alignment"
            }
        }
    },
    
    "tone_rules": {
        "archetype_tone_mappings": {
            "C_LEVEL": {
                "message_tone": "strategic",
                "verb_preference": ["discuss", "align", "explore", "advance"],
                "jargon_level": "strategic",
                "formality": "very high"
            },
            "EXECUTIVE": {
                "message_tone": "professional",
                "verb_preference": ["collaborate", "discuss", "connect", "share"],
                "jargon_level": "professional",
                "formality": "high"
            },
            "SENIOR_TA": {
                "message_tone": "technical_peer",
                "verb_preference": ["build", "implement", "architect", "optimize"],
                "jargon_level": "technical",
                "formality": "moderate"
            },
            "RECRUITER": {
                "message_tone": "warm_professional",
                "verb_preference": ["match", "connect", "support", "assist"],
                "jargon_level": "minimal",
                "formality": "moderate"
            }
        }
    },
    
    "constraints": {
        "content_cleanliness": {
            "forbidden_verbs": [
                "spearheaded", "leveraged", "utilized", "facilitated", "orchestrated",
                "championed", "pioneered", "revolutionized", "transformed", "optimized",
                "enhanced", "streamlined", "synergized", "enabled", "empowered", "drove", "drive"
            ],
            "max_violations": 1,
            "filler_patterns": [
                "(?i)\\bi hope\\b", "(?i)\\bhope (this|you) (finds|are|don't)",
                "(?i)\\bi (wanted|would like) to (reach|connect|discuss|share)",
                "(?i)\\bi was wondering if", "(?i)\\bperhaps (we|you) could",
                "(?i)\\bif you('re| are) interested", "(?i)\\bjust (wanted|reaching|following)"
            ],
            "placeholder_patterns": [
                "\\[.*?\\]", "\\{.*?\\}", "<.*?>", "PLACEHOLDER", "TODO", "XXX"
            ]
        },
        "structural_validation": {
            "word_count_tolerance": 0.1,
            "char_limit_enforcement": "strict",
            "subject_line_requirements": {
                "min_words": 4,
                "max_words": 10
            }
        }
    },
    
    "scenario_rules": {
        "rag_agent_config": {
            "archetype_params": {
                "C_LEVEL": {
                    "total_calls": 24,
                    "retrievers": ["linkedin", "company_blog", "news", "industry_reports"],
                    "recency_weight": 0.85,
                    "depth_priority": "maximum"
                },
                "EXECUTIVE": {
                    "total_calls": 18,
                    "retrievers": ["linkedin", "company_blog", "news"],
                    "recency_weight": 0.75,
                    "depth_priority": "high"
                },
                "SENIOR_TA": {
                    "total_calls": 16,
                    "retrievers": ["linkedin", "github", "tech_blogs", "conference_talks"],
                    "recency_weight": 0.7,
                    "depth_priority": "technical"
                },
                "RECRUITER": {
                    "total_calls": 8,
                    "retrievers": ["linkedin", "company_careers"],
                    "recency_weight": 0.6,
                    "depth_priority": "efficient"
                }
            },
            "max_rag_reflexion_loops": 2,
            "min_signal_for_proceed": 0.7,
            "adversarial_critique_enabled": True
        },
        "reasoning_agent_config": {
            "archetype_params": {
                "C_LEVEL": {
                    "max_hops": 6,
                    "temperature": 0.45,
                    "self_consistency_runs": 12,
                    "tot_branches": 16,
                    "reasoning_depth": "maximum",
                    "synthesis_enabled": True
                },
                "EXECUTIVE": {
                    "max_hops": 4,
                    "temperature": 0.5,
                    "self_consistency_runs": 5,
                    "tot_branches": 6,
                    "reasoning_depth": "high",
                    "synthesis_enabled": True
                },
                "SENIOR_TA": {
                    "max_hops": 4,
                    "temperature": 0.55,
                    "self_consistency_runs": 4,
                    "tot_branches": 4,
                    "reasoning_depth": "technical",
                    "synthesis_enabled": False
                },
                "RECRUITER": {
                    "max_hops": 2,
                    "temperature": 0.65,
                    "self_consistency_runs": 3,
                    "tot_branches": 0,
                    "reasoning_depth": "efficient",
                    "synthesis_enabled": False
                }
            }
        }
    },
    
    "seniority_rules": {
        "archetype_classification": {
            "C_LEVEL": {
                "keywords": ["ceo", "cto", "cfo", "coo", "chief", "president", "founder"],
                "confidence": 0.95
            },
            "EXECUTIVE": {
                "keywords": ["vp", "vice president", "director", "head of", "lead"],
                "confidence": 0.9
            },
            "RECRUITER": {
                "keywords": ["recruiter", "talent", "hiring", "hr"],
                "confidence": 0.92
            },
            "SENIOR_TA": {
                "keywords": ["principal", "staff", "senior", "architect", "tech lead", "engineering manager"],
                "confidence": 0.88
            }
        },
        "default_archetype": "EXECUTIVE",
        "default_confidence": 0.6,
        "manual_override_threshold": 0.75
    },
    
    "validator_rules": {
        "error_code_registry": {
            "LIC-E001": {
                "severity": "CRITICAL",
                "description": "Placeholder detected in generated message",
                "remediation": "Regenerate with explicit anti-placeholder constraint"
            },
            "LIC-E002": {
                "severity": "CRITICAL",
                "description": "Per-claim confidence below threshold (0.70)",
                "remediation": "Add more RAG sources or remove low-confidence claim"
            },
            "LIC-E003": {
                "severity": "CRITICAL",
                "description": "Hallucinated claim without supporting evidence",
                "remediation": "Remove claim or add supporting RAG evidence"
            },
            "LIC-E004": {
                "severity": "HIGH",
                "description": "Message too similar to previous message (>0.85)",
                "remediation": "Increase temperature or add diversity constraint"
            },
            "LIC-E005": {
                "severity": "HIGH",
                "description": "Job title not in first 50 words",
                "remediation": "Regenerate with job title positioning constraint"
            },
            "LIC-E006": {
                "severity": "HIGH",
                "description": "Company name misspelled",
                "remediation": "Use exact company name from profile"
            },
            "LIC-E007": {
                "severity": "HIGH",
                "description": "Non-ASCII characters detected",
                "remediation": "Replace Unicode with ASCII equivalents"
            },
            "LIC-E008": {
                "severity": "MEDIUM",
                "description": "Forbidden corporate verbs detected",
                "remediation": "Regenerate avoiding: spearheaded, leveraged, etc."
            },
            "LIC-E009": {
                "severity": "MEDIUM",
                "description": "Weak filler phrases detected",
                "remediation": "Remove: 'I hope', 'I wanted to', 'just reaching out'"
            },
            "LIC-E010": {
                "severity": "HIGH",
                "description": "Metric lacks supporting keyword context from RAG",
                "remediation": "Add RAG evidence keywords around metric or remove metric"
            },
            "LIC-E011": {
                "severity": "HIGH",
                "description": "Signal quality score below threshold (0.70)",
                "remediation": "Trigger RAG reflexion for more research"
            },
            "LIC-E012": {
                "severity": "CRITICAL",
                "description": "Circuit breaker OPEN - API unavailable",
                "remediation": "Wait for circuit breaker timeout or check API"
            },
            "LIC-E013": {
                "severity": "CRITICAL",
                "description": "Constraint pre-flight check failed",
                "remediation": "Adjust constraints or change route"
            },
            "LIC-E014": {
                "severity": "CRITICAL",
                "description": "Forbidden voice phrase detected",
                "remediation": "Regenerate avoiding sender_voice_profile forbidden phrases"
            },
            "LIC-E015": {
                "severity": "CRITICAL",
                "description": "Strategic alignment failure - no keyword overlap with strategic brief",
                "remediation": "Trigger S6->S2 meta-loop to re-research strategic brief alignment"
            }
        },
        "validation_severity_thresholds": {
            "critical_halt": True,
            "high_halt": True,
            "medium_regenerate": True,
            "info_log_only": True
        }
    },
    
    "message_families": {
        "archetype_generation_templates": {
            "C_LEVEL": {
                "system_instructions": "You are crafting an executive-level message that demonstrates thought leadership and strategic alignment.",
                "tone": "Strategic, confident, focused on business impact and organizational transformation.",
                "approach": "Lead with macro trends, demonstrate understanding of strategic challenges, position yourself as a peer with complementary expertise.",
                "avoid": "Tactical details, overt sales language, assumptions about their specific pain points.",
                "key_principles": [
                    "Speak to business outcomes, not features",
                    "Use industry context and market trends",
                    "Demonstrate strategic thinking",
                    "Position as a peer conversation, not a pitch",
                    "Reference organizational transformation and competitive advantage"
                ]
            },
            "EXECUTIVE": {
                "system_instructions": "You are crafting a professional message that emphasizes collaboration and mutual value.",
                "tone": "Professional, collaborative, focused on team objectives and operational excellence.",
                "approach": "Reference their role and responsibilities, demonstrate understanding of their team's challenges, offer concrete value.",
                "avoid": "Overly formal language, generic value propositions, excessive deference.",
                "key_principles": [
                    "Focus on team impact and operational outcomes",
                    "Demonstrate understanding of their domain",
                    "Offer specific, actionable value",
                    "Balance professionalism with warmth",
                    "Show respect for their time and priorities"
                ]
            },
            "SENIOR_TA": {
                "system_instructions": "You are crafting a technical message for a senior technical authority (architect, principal engineer, tech lead).",
                "tone": "Technical peer, respectful but confident, focused on architectural decisions and technical excellence.",
                "approach": "Reference specific technologies or patterns, demonstrate technical credibility, respect their authority on technical direction.",
                "avoid": "Marketing language, oversimplification of technical concepts, challenging their technical decisions.",
                "key_principles": [
                    "Use appropriate technical terminology",
                    "Reference specific technologies, frameworks, or patterns",
                    "Demonstrate deep technical understanding",
                    "Position as a technical peer, not a subordinate",
                    "Show respect for their architectural decisions",
                    "Focus on technical challenges and solutions"
                ]
            },
            "RECRUITER": {
                "system_instructions": "You are crafting a job-focused message that centers on role fit and candidate qualifications.",
                "tone": "Warm, professional, focused on alignment between candidate skills and role requirements.",
                "approach": "Lead with relevant experience, highlight specific skills that match job description, emphasize career growth potential.",
                "avoid": "Generic qualifications, vague interest statements, over-selling unrelated experience.",
                "key_principles": [
                    "Lead with most relevant experience",
                    "Connect specific skills to job requirements",
                    "Show enthusiasm for the role and company",
                    "Demonstrate understanding of the position",
                    "Focus on mutual fit, not just interest",
                    "Be concise and scannable"
                ]
            }
        }
    },
    
    "k_node_behaviors": {
        "hop_execution_order": [
            {
                "hop_id": "HOP-1",
                "agent": "ProfileAnalysisAgent",
                "input_files": ["mission_input_LIC.json"],
                "output_file": "1_profile_analysis.json"
            },
            {
                "hop_id": "HOP-2",
                "agent": "ResearchAgent",
                "input_files": ["1_profile_analysis.json"],
                "output_file": "2_research_context.json"
            },
            {
                "hop_id": "HOP-3",
                "agent": "SenderGroundingAgent",
                "input_files": ["master_resume.json", "sender_knowledge_base.json"],
                "output_file": "3_sender_grounding.json"
            },
            {
                "hop_id": "HOP-4",
                "agent": "RoutingAgent",
                "input_files": ["1_profile_analysis.json", "mission_input_LIC.json"],
                "output_file": "4_routing_decision.json"
            },
            {
                "hop_id": "HOP-4.5",
                "agent": "ScaffoldAgent",
                "input_files": ["4_routing_decision.json", "1_profile_analysis.json"],
                "output_file": "4.5_scaffold.json"
            },
            {
                "hop_id": "HOP-5",
                "agent": "GenerationAgent",
                "input_files": ["2_research_context.json", "3_sender_grounding.json", "4.5_scaffold.json"],
                "output_file": "5_generated_drafts.json"
            },
            {
                "hop_id": "HOP-6",
                "agent": "ValidationAgent",
                "input_files": ["5_generated_drafts.json", "2_research_context.json"],
                "output_file": "6_validation_report.json"
            },
            {
                "hop_id": "HOP-7",
                "agent": "GateDecisionAgent",
                "input_files": ["6_validation_report.json"],
                "output_file": "7_gate_decision.json"
            },
            {
                "hop_id": "HOP-8",
                "agent": "QAReportAgent",
                "input_files": ["state/*"],
                "output_file": "QA_Report.md"
            }
        ],
        "gate_decision_logic": {
            "FACTUAL_FAILURE": "raise FactualGapError -> trigger S6->S2 meta-loop",
            "CREATIVE_FAILURE": "raise CreativeFailureError -> HALT workflow",
            "PASS": "return True -> proceed to output"
        }
    },
    
    "mission_fields": {
        "sender_profile_structure": {
            "name": "string",
            "title": "string", 
            "company": "string",
            "linkedin_url": "string",
            "about_section": "string",
            "teams": "array"
        },
        "recipient_profile_structure": {
            "name": "string",
            "title": "string",
            "company": "string", 
            "linkedin_url": "string",
            "connection_status": "string",
            "prior_message_count": "integer"
        },
        "job_description_structure": {
            "title": "string",
            "company": "string",
            "location": "string",
            "requirements": "string"
        }
    }
}
