"""ADG R6 Backlog Enricher — 5 remaining low-effort detectors.

Sibling to debt_overlay_enricher (R1-R4) and truth_expansion_enricher (R5).
Implements the remaining low-effort detectors from the R5 backlog.

Detectors:

  A13  async_fire_and_forget
       `asyncio.create_task(...)` / `loop.create_task(...)` whose return
       value is discarded (not assigned, awaited, or stored)
  A14  external_call_no_timeout
       requests.X() / httpx.X() / aiohttp.X() without `timeout=` kwarg
  A15  snapshot_metadata
       Record git SHA, dirty status, generation time, newest indexed
       file mtime — so downstream tools can detect stale snapshots
  A16  boundary_strings_unresolved
       String literals in .py code that LOOK like module paths
       ("agentic_core.foo.Bar") but don't resolve on disk
  A17  rename_shim_consumer_risk (view-only; joins existing shim data)
       WHO still imports the rename shims? (join shim modules × fan-in)
  A19  mcp_tool_contract_drift
       Compare .cursor/mcp.json servers vs tools/*/mcp_*_server.py
       @tool declarations

Bonus:
  A18  source_origin tagging
       handwritten (default) | generated | vendored | archived
       Feeds into severity calibration — generated code should not raise
       violations as loudly as handwritten code.

All findings land in sibling tables + `overlay_violations`.
Canonical tables untouched.

Entry point: `enrich_r6(sqlite_path: Path) -> dict[str, int]`
"""

from __future__ import annotations

import ast
import json
import os
import re
import sqlite3
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

EXCLUDE_DIRS = {
    "archives",
    "tools_graveyard_w5.12",
    ".venv",
    "venv",
    "node_modules",
    "__pycache__",
    "_smoke_v1_coerce_e9aa09",
    ".backup",
    ".git",
    "site-packages",
    "build",
    "dist",
}

# A14 — libraries whose HTTP calls require `timeout=`
HTTP_LIBS_STRICT: set[str] = {"requests", "httpx", "aiohttp"}
HTTP_METHODS: set[str] = {"get", "post", "put", "patch", "delete", "head", "options", "request"}

# A13 — task creation patterns (function names that create async tasks)
ASYNC_TASK_CREATORS: set[str] = {
    "create_task",
    "ensure_future",
    "async_task",
}

# A16 — boundary string heuristic: look for module-looking dotted names
BOUNDARY_STRING_RE = re.compile(
    r"^(?:apps_rg|apps_shared|apps_underwriting_ai|system_learning|tools|"
    r"ops_scripts|infrastructure)"
    r"(?:\.[A-Za-z_][A-Za-z0-9_]*){2,}$"
)

# A18 — generated-code markers
GENERATED_HEADER_RE = re.compile(
    r"(?:# *)?(?:@generated|DO NOT EDIT|auto-generated|automatically generated|"
    r"generated by [\w\s]+)",
    re.IGNORECASE,
)
VENDOR_PATH_PREFIXES = ("vendor/", "third_party/", "_vendor/")


# ----------------------------------------------------------- progress reporter
class _Progress:
    def __init__(self, total: int, label: str) -> None:
        self.total = max(total, 1)
        self.n = 0
        self.label = label
        self.t0 = time.time()
        self.last = 0.0

    def tick(self, by: int = 1) -> None:
        self.n += by
        now = time.time()
        if now - self.last < 1.0 and self.n < self.total:
            return
        self.last = now
        pct = 100 * self.n / self.total
        fill = int(pct * 40 / 100)
        bar = "\u2588" * fill + "\u2591" * (40 - fill)
        elapsed = now - self.t0
        eta = (elapsed / max(self.n, 1)) * (self.total - self.n)
        if pct >= 90:
            color = "\033[92m"
        elif pct >= 70:
            color = "\033[94m"
        elif pct >= 40:
            color = "\033[93m"
        else:
            color = "\033[91m"
        sys.stderr.write(
            f"\r{color}[{bar}]\033[0m {pct:5.1f}% ({self.n}/{self.total}) - ETA: {eta:5.0f}s - {self.label}"
        )
        sys.stderr.flush()

    def done(self) -> None:
        sys.stderr.write(
            f"\r\033[92m[{'\u2588' * 40}]\033[0m 100.0% ({self.total}/{self.total}) - {self.label} done\n"
        )


# ---------------------------------------------------- file walking
def _iter_py_files() -> list[Path]:
    out: list[Path] = []
    for py in ROOT.rglob("*.py"):
        rel_parts = py.relative_to(ROOT).parts
        if set(rel_parts) & EXCLUDE_DIRS:
            continue
        out.append(py)
    return out


def _safe_read(p: Path) -> str | None:
    try:
        return p.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _safe_parse(txt: str) -> ast.Module | None:
    try:
        return ast.parse(txt)
    except SyntaxError:
        return None


# ---------------------------------------------------- A13 + A14 + A16 visitor
class _R6Visitor(ast.NodeVisitor):
    """Single-pass collector for A13, A14, A16."""

    def __init__(self) -> None:
        self.async_fire_and_forget: list[dict] = []
        self.timeout_gaps: list[dict] = []
        self.boundary_strings: list[dict] = []

    # A13 — create_task whose result is discarded
    # We recognize discarded-return by parent context: `ast.Expr(value=Call)`.
    # Traverse via generic_visit and check parent in visit_Expr.
    def visit_Expr(self, node: ast.Expr) -> None:
        if isinstance(node.value, ast.Call):
            self._maybe_record_fire_forget(node.value, is_discarded=True)
        self.generic_visit(node)

    def visit_Call(self, node: ast.Call) -> None:
        self._maybe_record_fire_forget(node, is_discarded=False)
        self._maybe_record_timeout_gap(node)
        self.generic_visit(node)

    def _maybe_record_fire_forget(self, call: ast.Call, *, is_discarded: bool) -> None:
        fn = call.func
        # Resolve attribute form: module.create_task(...)
        name = None
        mod = None
        if isinstance(fn, ast.Attribute):
            name = fn.attr
            if isinstance(fn.value, ast.Name):
                mod = fn.value.id
        elif isinstance(fn, ast.Name):
            name = fn.id
        if name not in ASYNC_TASK_CREATORS:
            return
        # Heuristic: asyncio.create_task or loop.create_task — require
        # asyncio/loop context OR bare `create_task` import.
        acceptable_mods = {"asyncio", "loop", "_loop", "self"}
        if mod is not None and mod not in acceptable_mods and mod != "None":
            # Unlikely to be asyncio — skip
            return
        # Record only if discarded (called in Expr statement context)
        if is_discarded:
            self.async_fire_and_forget.append(
                {
                    "line": call.lineno,
                    "callee": f"{mod or ''}.{name}".lstrip("."),
                }
            )

    def _maybe_record_timeout_gap(self, call: ast.Call) -> None:
        fn = call.func
        if not isinstance(fn, ast.Attribute):
            return
        if not isinstance(fn.value, ast.Name):
            return
        lib = fn.value.id
        method = fn.attr
        if lib not in HTTP_LIBS_STRICT:
            return
        if method not in HTTP_METHODS:
            return
        # Check for timeout= kwarg
        has_timeout = any(kw.arg == "timeout" for kw in call.keywords)
        if not has_timeout:
            self.timeout_gaps.append(
                {
                    "line": call.lineno,
                    "lib": lib,
                    "method": method,
                }
            )

    # A16 — boundary strings (module-looking dotted names in string literals)
    def visit_Constant(self, node: ast.Constant) -> None:
        if not isinstance(node.value, str):
            return
        v = node.value.strip()
        if len(v) < 10 or len(v) > 120:
            return
        m = BOUNDARY_STRING_RE.match(v)
        if not m:
            return
        self.boundary_strings.append(
            {
                "line": node.lineno,
                "target": v,
            }
        )


# ---------------------------------------------------- A16 resolution helper
def _resolve_module_path(target: str) -> bool:
    as_path = target.replace(".", "/")
    py_file = ROOT / f"{as_path}.py"
    pkg_init = ROOT / as_path / "__init__.py"
    pkg_dir = ROOT / as_path
    return py_file.exists() or pkg_init.exists() or pkg_dir.is_dir()


# ---------------------------------------------------- A18 source origin
def _source_origin(rel: str, txt: str) -> str:
    if any(p in rel for p in VENDOR_PATH_PREFIXES):
        return "vendored"
    if "archives/" in rel or "tools_graveyard" in rel:
        return "archived"
    # Check first ~20 lines for generated header
    head = "\n".join(txt.splitlines()[:20])
    if GENERATED_HEADER_RE.search(head):
        return "generated"
    return "handwritten"


# ---------------------------------------------------- A15 snapshot freshness
def _collect_snapshot_metadata() -> dict[str, str]:
    meta: dict[str, str] = {}
    # Git SHA
    try:
        sha = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        meta["git_head_sha"] = sha.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        meta["git_head_sha"] = "unavailable"
    # Dirty status
    try:
        st = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        meta["git_dirty"] = "1" if st.stdout.strip() else "0"
        meta["git_dirty_files"] = str(len(st.stdout.strip().splitlines()))
    except (OSError, subprocess.SubprocessError):
        meta["git_dirty"] = "unknown"
        meta["git_dirty_files"] = "0"
    # Branch
    try:
        br = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
        meta["git_branch"] = br.stdout.strip() or "unknown"
    except (OSError, subprocess.SubprocessError):
        meta["git_branch"] = "unavailable"
    # Timestamp
    meta["generated_at_utc"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    meta["generated_at_epoch"] = str(int(time.time()))
    return meta


# ---------------------------------------------------- A19 MCP contract drift
MCP_TOOL_DECORATOR_RE = re.compile(r"@(?:mcp\.)?tool\b")
MCP_CONFIG_PATH = ROOT / "docs/archive/windsurf/legacy-tree" / "mcp_config.json"


def _collect_mcp_declarations() -> list[dict]:
    """Find @tool / @mcp.tool / @app.tool decorated functions across tools/.

    Returns [{file, tool_name, decorator}].
    """
    decls: list[dict] = []
    # Broad search across tools/ — narrower filtering happens at decorator level
    search_roots = [ROOT / "tools"]
    mcp_files: set[Path] = set()
    for root in search_roots:
        if not root.is_dir():
            continue
        for py in root.rglob("*.py"):
            rel_parts = py.relative_to(ROOT).parts
            if set(rel_parts) & EXCLUDE_DIRS:
                continue
            mcp_files.add(py)

    for py in sorted(mcp_files):
        rel = str(py.relative_to(ROOT)).replace("\\", "/")
        txt = _safe_read(py)
        if txt is None:
            continue
        tree = _safe_parse(txt)
        if tree is None:
            continue
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                for deco in node.decorator_list:
                    deco_src = ast.unparse(deco) if sys.version_info >= (3, 9) else ""
                    deco_l = deco_src.lower()
                    # Match @tool, @mcp.tool, @app.tool, @server.tool
                    is_tool_deco = (
                        deco_l == "tool"
                        or deco_l.startswith("tool(")
                        or ".tool" in deco_l
                        or "@mcp" in f"@{deco_l}"
                    )
                    if is_tool_deco:
                        decls.append(
                            {
                                "file": rel,
                                "tool_name": node.name,
                                "decorator": deco_src[:120],
                            }
                        )
                        break
    return decls


def _normalize_arg_path(args: list) -> str | None:
    """Extract the python script path from MCP args, normalize to repo-relative.

    Examples:
      ["-u", "-m", "tools.adg.mcp.server"] -> "tools/adg/mcp/server.py"
      ["-u", "${env:AGENTIC_REPO_ROOT}/tools/mcp/redis_mcp_server.py"]
        -> "tools/mcp/redis_mcp_server.py"
    """
    for i, arg in enumerate(args):
        s = str(arg)
        # `-m module.path`
        if s == "-m" and i + 1 < len(args):
            modpath = str(args[i + 1]).strip()
            return modpath.replace(".", "/") + ".py"
        # path-like
        if s.endswith(".py"):
            # Strip env var prefix
            if "tools/" in s:
                return s[s.index("tools/") :].replace("\\", "/")
            if "tools\\" in s:
                return s[s.index("tools\\") :].replace("\\", "/")
    return None


def _collect_mcp_config_servers() -> list[dict]:
    """Return list of MCP servers from mcp_config.json.

    Each entry includes `is_internal` — True if the command runs a local
    Python module (and we therefore expect a matching @tool file in-repo),
    False if it's an external package (npx/uvx/docker — no local file
    expected).
    """
    if not MCP_CONFIG_PATH.exists():
        return []
    try:
        data = json.loads(MCP_CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return []
    servers = []
    for name, cfg in (data.get("mcpServers") or {}).items():
        cmd = (cfg.get("command") or "").lower()
        args = cfg.get("args") or []
        # Internal = python/python.exe + a script path, OR cmd contains
        # tools/ already.
        is_internal = (
            "python" in cmd
            or "py " in cmd
            or any("tools/" in str(a) or "tools\\" in str(a) or str(a).endswith(".py") for a in args)
        )
        script_path = _normalize_arg_path(args) if is_internal else None
        # If script ends in .py but the file doesn't exist on disk, also
        # check the `.py` from a `-m` module path
        if script_path:
            disk = ROOT / script_path
            if not disk.exists():
                # Try as package: script.replace('.py','/__init__.py')
                pkg_init = ROOT / script_path.replace(".py", "/__init__.py")
                if pkg_init.exists():
                    script_path = str(pkg_init.relative_to(ROOT)).replace("\\", "/")
        # Compute script_dir for sibling-tool matching
        script_dir = ""
        if script_path:
            parts = script_path.rsplit("/", 1)
            script_dir = parts[0] if len(parts) > 1 else ""
        servers.append(
            {
                "name": name,
                "args": args,
                "disabled": cfg.get("disabled", False),
                "is_internal": is_internal,
                "script_path": script_path or "",
                "script_dir": script_dir,
            }
        )
    return servers


# ---------------------------------------------------- A17 shim consumer risk
# Implemented as a view against overlay_violations + edges — no new data.


# ---------------------------------------------------- schema
SCHEMA_STATEMENTS = [
    """
    CREATE TABLE IF NOT EXISTS async_fire_and_forget (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT NOT NULL,
        line_no INTEGER NOT NULL,
        callee TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS external_calls (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT NOT NULL,
        line_no INTEGER NOT NULL,
        lib TEXT NOT NULL,
        method TEXT NOT NULL,
        has_timeout INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS boundary_strings (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT NOT NULL,
        line_no INTEGER NOT NULL,
        target TEXT NOT NULL,
        resolved INTEGER NOT NULL DEFAULT 0
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS snapshot_metadata (
        key TEXT PRIMARY KEY,
        value TEXT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS mcp_tool_declarations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        file_path TEXT NOT NULL,
        tool_name TEXT NOT NULL,
        decorator TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS mcp_config_servers (
        name TEXT PRIMARY KEY,
        disabled INTEGER NOT NULL DEFAULT 0,
        is_internal INTEGER NOT NULL DEFAULT 0,
        script_path TEXT NOT NULL DEFAULT '',
        script_dir TEXT NOT NULL DEFAULT '',
        args TEXT
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS module_origins (
        file_path TEXT PRIMARY KEY,
        origin TEXT NOT NULL DEFAULT 'handwritten'
    )
    """,
]

INDEX_STATEMENTS = [
    "CREATE INDEX IF NOT EXISTS ix_aff_file ON async_fire_and_forget(file_path)",
    "CREATE INDEX IF NOT EXISTS ix_ec_file ON external_calls(file_path)",
    "CREATE INDEX IF NOT EXISTS ix_ec_notimeout ON external_calls(has_timeout)",
    "CREATE INDEX IF NOT EXISTS ix_bs_resolved ON boundary_strings(resolved)",
    "CREATE INDEX IF NOT EXISTS ix_mo_origin ON module_origins(origin)",
]

VIEW_STATEMENTS = [
    """
    CREATE VIEW IF NOT EXISTS mv_async_fire_and_forget_hotspots AS
    SELECT file_path, COUNT(*) AS n
    FROM async_fire_and_forget
    GROUP BY file_path
    ORDER BY n DESC
    """,
    """
    CREATE VIEW IF NOT EXISTS mv_external_calls_no_timeout AS
    SELECT file_path, line_no, lib, method
    FROM external_calls
    WHERE has_timeout = 0
    ORDER BY file_path, line_no
    """,
    """
    CREATE VIEW IF NOT EXISTS mv_boundary_string_unresolved AS
    SELECT file_path, line_no, target
    FROM boundary_strings
    WHERE resolved = 0
    ORDER BY file_path, line_no
    """,
    """
    CREATE VIEW IF NOT EXISTS mv_mcp_contract_drift AS
    -- Internal server with no @tool files anywhere under its script_dir
    -- (the server file may delegate to sibling/child @tool files — that's fine)
    SELECT 'script_missing' AS drift_kind, s.name AS server_or_tool,
           'no @tool files under ' || s.script_dir
           || ' (config points to ' || s.script_path || ')' AS note
    FROM mcp_config_servers s
    WHERE s.disabled = 0
      AND s.is_internal = 1
      AND s.script_path != ''
      AND NOT EXISTS (
          SELECT 1 FROM mcp_tool_declarations d
          WHERE d.file_path = s.script_path
             OR d.file_path LIKE s.script_dir || '/%'
      )
    UNION ALL
    -- @tool file that doesn't live under any configured server's directory
    SELECT 'orphan_tool_file' AS drift_kind, d.file_path AS server_or_tool,
           'has @tool decorators but is outside every configured '
           || 'mcp_config.json server directory' AS note
    FROM (SELECT DISTINCT file_path FROM mcp_tool_declarations) d
    WHERE d.file_path NOT LIKE '%/archive/%'
      AND d.file_path NOT LIKE 'tools/archive/%'
      AND NOT EXISTS (
          SELECT 1 FROM mcp_config_servers s
          WHERE s.disabled = 0
            AND s.is_internal = 1
            AND s.script_path != ''
            AND (d.file_path = s.script_path
                 OR d.file_path LIKE s.script_dir || '/%')
      )
    """,
    """
    CREATE VIEW IF NOT EXISTS mv_rename_shim_consumers AS
    SELECT ov.file_path AS shim_file,
           COUNT(DISTINCT e.src_id) AS import_fanin
    FROM overlay_violations ov
    LEFT JOIN nodes n ON n.resolved_path = ov.file_path
    LEFT JOIN edges e ON e.dst_id = n.id AND e.relation_type = 'imports'
    WHERE ov.category = 'rename_shim_module'
    GROUP BY ov.file_path
    ORDER BY import_fanin DESC
    """,
    """
    CREATE VIEW IF NOT EXISTS mv_r6_summary AS
    SELECT
        (SELECT COUNT(*) FROM async_fire_and_forget) AS async_fire_and_forget,
        (SELECT COUNT(*) FROM external_calls) AS external_calls_total,
        (SELECT COUNT(*) FROM external_calls WHERE has_timeout = 0)
            AS external_calls_no_timeout,
        (SELECT COUNT(*) FROM boundary_strings) AS boundary_strings_total,
        (SELECT COUNT(*) FROM boundary_strings WHERE resolved = 0)
            AS boundary_strings_unresolved,
        (SELECT COUNT(*) FROM mcp_tool_declarations) AS mcp_tool_declarations,
        (SELECT COUNT(*) FROM mcp_config_servers) AS mcp_config_servers,
        (SELECT COUNT(*) FROM mv_mcp_contract_drift) AS mcp_contract_drift,
        (SELECT COUNT(*) FROM module_origins WHERE origin = 'generated')
            AS generated_modules,
        (SELECT COUNT(*) FROM module_origins WHERE origin = 'vendored')
            AS vendored_modules,
        (SELECT value FROM snapshot_metadata WHERE key = 'git_head_sha')
            AS git_head_sha,
        (SELECT value FROM snapshot_metadata WHERE key = 'git_dirty')
            AS git_dirty,
        (SELECT value FROM snapshot_metadata WHERE key = 'generated_at_utc')
            AS generated_at_utc
    """,
]


def _ensure_schema(con: sqlite3.Connection) -> None:
    cur = con.cursor()
    # Idempotent migration: drop tables that may have evolved schema since
    # the last enrichment run. CREATE IF NOT EXISTS won't update them.
    for legacy in ("mcp_config_servers",):
        try:
            cur.execute(f"DROP TABLE IF EXISTS {legacy}")
        except sqlite3.Error:
            pass
    # overlay_violations may not exist if running standalone
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS overlay_violations (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            category        TEXT NOT NULL,
            severity        TEXT NOT NULL DEFAULT 'MEDIUM',
            file_path       TEXT NOT NULL DEFAULT '',
            line_no         INTEGER,
            evidence        TEXT NOT NULL DEFAULT '',
            violation_class TEXT NOT NULL DEFAULT 'overlay_enrichment',
            disposition     TEXT NOT NULL DEFAULT 'untriaged'
        )
        """
    )
    for stmt in SCHEMA_STATEMENTS:
        cur.execute(stmt)
    for stmt in INDEX_STATEMENTS:
        cur.execute(stmt)
    con.commit()


def _ensure_views(con: sqlite3.Connection) -> None:
    cur = con.cursor()
    for name in (
        "mv_async_fire_and_forget_hotspots",
        "mv_external_calls_no_timeout",
        "mv_boundary_string_unresolved",
        "mv_mcp_contract_drift",
        "mv_rename_shim_consumers",
        "mv_r6_summary",
    ):
        cur.execute(f"DROP VIEW IF EXISTS {name}")
    for stmt in VIEW_STATEMENTS:
        cur.execute(stmt)
    con.commit()


# ---------------------------------------------------- main entrypoint
def enrich_r6(sqlite_path: Path) -> dict[str, int]:
    if not sqlite_path.exists():
        raise FileNotFoundError(sqlite_path)

    con = sqlite3.connect(str(sqlite_path))
    try:
        _ensure_schema(con)
        cur = con.cursor()

        # --- Pass 1: Python files for A13/A14/A16/A18
        py_files = _iter_py_files()
        pr = _Progress(len(py_files), label="r6-backlog (.py pass)")
        aff_rows: list[tuple[str, int, str]] = []
        ec_rows: list[tuple[str, int, str, str, int]] = []
        bs_rows: list[tuple[str, int, str, int]] = []
        origin_rows: list[tuple[str, str]] = []
        v_rows: list[tuple] = []

        for py in py_files:
            rel = str(py.relative_to(ROOT)).replace("\\", "/")
            txt = _safe_read(py)
            if txt is None:
                pr.tick()
                continue
            # A18 source origin
            origin = _source_origin(rel, txt)
            origin_rows.append((rel, origin))
            tree = _safe_parse(txt)
            pr.tick()
            if tree is None:
                continue
            v = _R6Visitor()
            v.visit(tree)
            # A13
            for a in v.async_fire_and_forget:
                aff_rows.append((rel, a["line"], a["callee"]))
                v_rows.append(
                    (
                        "async_fire_and_forget",
                        "MEDIUM",
                        rel,
                        a["line"],
                        f"{a['callee']}() return value discarded — exceptions will be lost",
                        "overlay_enrichment",
                    )
                )
            # A14
            # First gather all HTTP-lib calls to derive the has_timeout stat
            # (visitor only records the NO-timeout gaps). For full external_calls
            # table, we'd need both. Keeping minimal: store no-timeout as gaps.
            for g in v.timeout_gaps:
                ec_rows.append((rel, g["line"], g["lib"], g["method"], 0))
                v_rows.append(
                    (
                        "external_call_no_timeout",
                        "MEDIUM",
                        rel,
                        g["line"],
                        f"{g['lib']}.{g['method']}(...) without timeout=",
                        "overlay_enrichment",
                    )
                )
            # A16
            for bs in v.boundary_strings:
                resolved = _resolve_module_path(bs["target"])
                bs_rows.append(
                    (
                        rel,
                        bs["line"],
                        bs["target"],
                        1 if resolved else 0,
                    )
                )
                if not resolved:
                    v_rows.append(
                        (
                            "boundary_string_unresolved",
                            "LOW",
                            rel,
                            bs["line"],
                            f'"{bs["target"]}" — string looks like a module path '
                            "but does not resolve on disk",
                            "overlay_enrichment",
                        )
                    )
        pr.done()

        # --- Pass 2: A15 snapshot metadata
        print("# r6: collecting snapshot metadata", file=sys.stderr)
        meta = _collect_snapshot_metadata()

        # --- Pass 3: A19 MCP contract
        print("# r6: collecting MCP declarations", file=sys.stderr)
        mcp_decls = _collect_mcp_declarations()
        mcp_servers = _collect_mcp_config_servers()

        # --- Write all rows
        cur.execute("DELETE FROM async_fire_and_forget")
        cur.executemany(
            "INSERT INTO async_fire_and_forget (file_path, line_no, callee) VALUES (?, ?, ?)",
            aff_rows,
        )
        cur.execute("DELETE FROM external_calls")
        cur.executemany(
            "INSERT INTO external_calls "
            "(file_path, line_no, lib, method, has_timeout) "
            "VALUES (?, ?, ?, ?, ?)",
            ec_rows,
        )
        cur.execute("DELETE FROM boundary_strings")
        cur.executemany(
            "INSERT INTO boundary_strings (file_path, line_no, target, resolved) VALUES (?, ?, ?, ?)",
            bs_rows,
        )
        cur.execute("DELETE FROM module_origins")
        cur.executemany(
            "INSERT OR REPLACE INTO module_origins (file_path, origin) VALUES (?, ?)",
            origin_rows,
        )
        cur.execute("DELETE FROM snapshot_metadata")
        cur.executemany(
            "INSERT OR REPLACE INTO snapshot_metadata (key, value) VALUES (?, ?)",
            list(meta.items()),
        )
        cur.execute("DELETE FROM mcp_tool_declarations")
        cur.executemany(
            "INSERT INTO mcp_tool_declarations (file_path, tool_name, decorator) VALUES (?, ?, ?)",
            [(d["file"], d["tool_name"], d["decorator"]) for d in mcp_decls],
        )
        cur.execute("DELETE FROM mcp_config_servers")
        cur.executemany(
            "INSERT INTO mcp_config_servers "
            "(name, disabled, is_internal, script_path, script_dir, args) "
            "VALUES (?, ?, ?, ?, ?, ?)",
            [
                (
                    s["name"],
                    1 if s["disabled"] else 0,
                    1 if s.get("is_internal") else 0,
                    s.get("script_path", ""),
                    s.get("script_dir", ""),
                    json.dumps(s["args"]),
                )
                for s in mcp_servers
            ],
        )

        # A17/A19 — violations derived from view results
        # Delete prior R6 overlay rows before inserting fresh
        cur.execute(
            """
            DELETE FROM overlay_violations
            WHERE category IN (
                'async_fire_and_forget', 'external_call_no_timeout',
                'boundary_string_unresolved', 'snapshot_dirty',
                'mcp_contract_drift', 'rename_shim_consumer_risk'
            )
            """
        )
        cur.executemany(
            "INSERT INTO overlay_violations "
            "(category, severity, file_path, line_no, evidence, "
            "violation_class) VALUES (?, ?, ?, ?, ?, ?)",
            v_rows,
        )
        # A15: snapshot_dirty as ADVISORY (not an error — just signal)
        if meta.get("git_dirty") == "1":
            cur.execute(
                "INSERT INTO overlay_violations "
                "(category, severity, file_path, line_no, evidence, "
                "violation_class) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "snapshot_dirty",
                    "ADVISORY",
                    "",
                    None,
                    f"working tree is dirty at generation "
                    f"({meta.get('git_dirty_files', '?')} files) — snapshot "
                    "reflects uncommitted state",
                    "overlay_enrichment",
                ),
            )
        con.commit()
        _ensure_views(con)

        # A19 drift — materialize view rows into overlay_violations
        drift_rows = cur.execute(
            "SELECT drift_kind, server_or_tool, note FROM mv_mcp_contract_drift"
        ).fetchall()
        for drift_kind, target, note in drift_rows:
            severity = "MEDIUM" if drift_kind == "orphan_server" else "LOW"
            cur.execute(
                "INSERT INTO overlay_violations "
                "(category, severity, file_path, line_no, evidence, "
                "violation_class) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "mcp_contract_drift",
                    severity,
                    target,
                    None,
                    f"[{drift_kind}] {note}",
                    "overlay_enrichment",
                ),
            )

        # A17 — rename_shim_consumer_risk: any shim with fan-in > 0
        shim_consumer_rows = cur.execute(
            "SELECT shim_file, import_fanin FROM mv_rename_shim_consumers WHERE import_fanin > 0"
        ).fetchall()
        for shim_file, fanin in shim_consumer_rows:
            cur.execute(
                "INSERT INTO overlay_violations "
                "(category, severity, file_path, line_no, evidence, "
                "violation_class) VALUES (?, ?, ?, ?, ?, ?)",
                (
                    "rename_shim_consumer_risk",
                    "MEDIUM",
                    shim_file,
                    None,
                    f"shim has {fanin} import(s) — cannot delete until consumers migrate",
                    "overlay_enrichment",
                ),
            )
        con.commit()

        # --- Summary
        summary: dict[str, int] = {
            "async_fire_and_forget": len(aff_rows),
            "external_calls_no_timeout": len(ec_rows),
            "boundary_strings_total": len(bs_rows),
            "boundary_strings_unresolved": sum(1 for r in bs_rows if r[3] == 0),
            "module_origins_recorded": len(origin_rows),
            "generated_modules": sum(1 for r in origin_rows if r[1] == "generated"),
            "vendored_modules": sum(1 for r in origin_rows if r[1] == "vendored"),
            "archived_modules": sum(1 for r in origin_rows if r[1] == "archived"),
            "mcp_tool_declarations": len(mcp_decls),
            "mcp_config_servers": len(mcp_servers),
            "mcp_contract_drift": len(drift_rows),
            "rename_shim_consumer_risk": len(shim_consumer_rows),
            "snapshot_dirty": 1 if meta.get("git_dirty") == "1" else 0,
        }
        summary["git_head_sha"] = meta.get("git_head_sha", "")  # type: ignore[assignment]
        summary["generated_at_utc"] = meta.get("generated_at_utc", "")  # type: ignore[assignment]
        return summary
    finally:
        con.close()


# ----------------------------------------------------------- CLI
def main() -> int:
    import argparse
    import glob

    parser = argparse.ArgumentParser()
    parser.add_argument("--sqlite")
    args = parser.parse_args()

    if args.sqlite:
        path = Path(args.sqlite)
    else:
        snaps = sorted(
            glob.glob(str(ROOT / "artifacts/adg/adg_indexed_*.sqlite")),
            key=os.path.getmtime,
        )
        if not snaps:
            tmps = sorted(
                glob.glob(str(ROOT / "artifacts/adg/adg_indexed_*.sqlite.tmp")),
                key=os.path.getmtime,
            )
            if not tmps:
                print("FATAL: no snapshot", file=sys.stderr)
                return 2
            path = Path(tmps[-1])
        else:
            path = Path(snaps[-1])

    print(f"# r6 enrichment: {path.name}", file=sys.stderr)
    summary = enrich_r6(path)
    print(json.dumps(summary, indent=2, default=str))
    return 0


if __name__ == "__main__":
    sys.exit(main())
