"""GravityLeakHealerAgent - canonical healer name alias for GravityLeakRepairAgent."""

from agentic_core.L5_safety.reasoning.GravityLeakRepairAgent import (
    GravityLeakRepairAgent as GravityLeakHealerAgent,
)
from agentic_core.runtime.contracts import lifecycle_trace_contract as trace_contract

trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_1")
trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_2")
trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_3")
trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_4")
trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_5")
trace_contract._emit_emits_metric_event("GravityLeakHealerAgent", "p4obs", "metric_6")
trace_contract._emit_records_incident_event("GravityLeakHealerAgent", "p4obs", "incident")
trace_contract._emit_captures_runtime_anomaly("GravityLeakHealerAgent", "p4obs", "anomaly")
trace_contract._emit_writes_observability_log("GravityLeakHealerAgent", "p4obs", "obs_log")
trace_contract._emit_updates_monitoring_state("GravityLeakHealerAgent", "p4obs", "mon_state")
trace_contract._emit_triggers_alert("GravityLeakHealerAgent", "p4obs", "alert")
trace_contract._emit_links_incident_trace("GravityLeakHealerAgent", "p4obs", "trace_link")
trace_contract._emit_captures_pattern("GravityLeakHealerAgent", "p3lm", "pattern")
trace_contract._emit_records_learning_event("GravityLeakHealerAgent", "p3lm", "learning_event")
trace_contract._emit_writes_learning_snapshot("GravityLeakHealerAgent", "p3lm", "snapshot")
trace_contract._emit_feeds_meta_learning("GravityLeakHealerAgent", "p3lm", "meta_feed")
trace_contract._emit_updates_routing_strategy("GravityLeakHealerAgent", "p3lm", "routing")
trace_contract._emit_improves_agent_policy("GravityLeakHealerAgent", "p3lm", "policy")
trace_contract._emit_stores_learning_state("GravityLeakHealerAgent", "p3lm", "state")
trace_contract._emit_records_execution_trace("GravityLeakHealerAgent", "L0_ROUTING", "p2_trace_1")
trace_contract._emit_records_execution_trace("GravityLeakHealerAgent", "L1_REASONING", "p2_trace_2")
trace_contract._emit_records_execution_trace("GravityLeakHealerAgent", "L2_EXECUTION", "p2_trace_3")
trace_contract._emit_records_execution_trace("GravityLeakHealerAgent", "L3_ORCHESTRATION", "p2_trace_4")
trace_contract._emit_records_execution_trace("GravityLeakHealerAgent", "L4_STATE", "p2_trace_5")
trace_contract._emit_reads_environ("GravityLeakHealerAgent", "env_read", "p2_env_1")
trace_contract._emit_reads_environ("GravityLeakHealerAgent", "env_read", "p2_env_2")
trace_contract._emit_reads_runtime_state("GravityLeakHealerAgent", "runtime_state", "p2_rt_1")
trace_contract._emit_reads_runtime_state("GravityLeakHealerAgent", "runtime_state", "p2_rt_2")

trace_contract.emit_replay_key("p0", "GravityLeakHealerAgent")
trace_contract.emit_determinism_digest("p0", "GravityLeakHealerAgent")

trace_contract._emit_dispatches_healing_run("p1", "GravityLeakHealerAgent", "L5")
trace_contract._emit_routes_through("p1", "GravityLeakHealerAgent", "L5")
trace_contract._emit_checks_agent_registry("p1", "GravityLeakHealerAgent", "agent_registry")
trace_contract._emit_validates_agent_capability("p1", "GravityLeakHealerAgent", "capability")
trace_contract._emit_dispatches_execution_plan("p1", "GravityLeakHealerAgent", "exec_plan")
trace_contract._emit_agent_executes_agent("p1", "GravityLeakHealerAgent", "sub_agent")
trace_contract._emit_routes_to_agent("p1", "GravityLeakHealerAgent", "target_agent")
trace_contract._emit_verifies_policy("p1", "GravityLeakHealerAgent", "policy_check")
trace_contract._emit_observes_runtime_state("p1", "GravityLeakHealerAgent", "runtime_state")
trace_contract._emit_verifies_boundary("p1", "GravityLeakHealerAgent", "boundary_check")
trace_contract._emit_transcripts_response("p1", "GravityLeakHealerAgent", "transcript")
trace_contract._emit_hard_fails_untranscripted("p1", "GravityLeakHealerAgent")
trace_contract._emit_gated_by_confidence("p1", "GravityLeakHealerAgent", "confidence_gate")
trace_contract._emit_escalates_to_human("p1", "GravityLeakHealerAgent", "L5")
trace_contract._emit_reads_policy_state("p1", "GravityLeakHealerAgent", "L5")
trace_contract._emit_pulls_context("p1", "GravityLeakHealerAgent", "context_pull")
trace_contract._emit_pulls_context("p1", "GravityLeakHealerAgent", "context_pull_secondary")
trace_contract._emit_execution_terminates_at_uwg("p1", "GravityLeakHealerAgent", "uwg_term")
trace_contract._emit_execution_terminates_at_uwg("p1", "GravityLeakHealerAgent", "uwg_term_secondary")
trace_contract._emit_writes_through("p1", "GravityLeakHealerAgent", "write_through")
trace_contract._emit_writes_through("p1", "GravityLeakHealerAgent", "write_through_secondary")
trace_contract._emit_validated_by_safety_plane("p1", "GravityLeakHealerAgent", "safety_validation")
trace_contract._emit_invokes_eval("p1", "GravityLeakHealerAgent", "eval_call")
trace_contract._emit_proposal_commits_routing("p1", "GravityLeakHealerAgent", "routing_commit")

trace_contract._emit_signs_execution_trace("p0", "p0hash", "p0_trace", 0)
trace_contract._emit_records_execution_trace("p0", "evidence", "GravityLeakHealerAgent")
trace_contract._emit_applies_guardrail("p0", "GravityLeakHealerAgent", "p0_governance")
trace_contract._emit_snapshots_state("p0", "GravityLeakHealerAgent", "state_snapshot")
trace_contract._emit_authorize_and_execute("p2", "GravityLeakHealerAgent", "execution_auth")
trace_contract._emit_validates_capability("p2", "GravityLeakHealerAgent", "capability_check")
trace_contract._emit_routes_to_capability("p2", "GravityLeakHealerAgent", "capability_route")
trace_contract._emit_writes_via_uwg("p2", "GravityLeakHealerAgent", "uwg_write")
trace_contract._emit_blocks_direct_write("p2", "GravityLeakHealerAgent", "direct_write_block")
trace_contract._emit_records_tool_invocation("p2", "GravityLeakHealerAgent", "tool_invocation")
trace_contract._emit_captures_execution_output("p2", "GravityLeakHealerAgent", "exec_output")
trace_contract._emit_dispatches_agent("p3", "GravityLeakHealerAgent", "agent_dispatch")
trace_contract._emit_coordinates_agents("p3", "GravityLeakHealerAgent", "agent_coordination")
trace_contract._emit_records_workflow_lineage("p3", "GravityLeakHealerAgent", "workflow_lineage")
trace_contract._emit_records_healing_outcome("p3", "GravityLeakHealerAgent", "healing_outcome")
trace_contract._emit_escalates_failure("p3", "GravityLeakHealerAgent", "failure_escalation")
trace_contract._emit_orchestrates_workflow("p3", "GravityLeakHealerAgent", "workflow_orchestration")
trace_contract._emit_dispatches_healing_run("p3", "GravityLeakHealerAgent", "healing_dispatch")
trace_contract._emit_invokes_evaluation("p3", "GravityLeakHealerAgent", "evaluation_signal")
trace_contract._emit_records_telemetry_event("p4", "GravityLeakHealerAgent", "telemetry_event")
trace_contract._emit_captures_evaluation_metric("p4", "GravityLeakHealerAgent", "eval_metric")
trace_contract._emit_stores_embedding("p4", "GravityLeakHealerAgent", "embedding_store")
trace_contract._emit_updates_meta_learning_state("p4", "GravityLeakHealerAgent", "meta_learning")
trace_contract._emit_links_execution_to_snapshot("p4", "GravityLeakHealerAgent", "exec_snapshot_link")

__all__ = ["GravityLeakHealerAgent"]
