"""
Install a pre-commit hook that runs the pre-commit framework and sovereignty validation.
"""

from __future__ import annotations

import argparse
import os
import stat
import sys
from pathlib import Path

HOOK_FILENAME = "pre-commit"
HOOK_CONTENT = """#!/bin/sh
# Pascal Sovereignty Pre-Commit Hook
# Auto-generated by ops_scripts/install_git_hooks.py
# Updated 2026-01-30: Now invokes pre-commit framework for full hook execution

echo "[SOVEREIGNTY] Auditing architectural compliance..."

pre-commit run --hook-stage commit
PRECOMMIT_EXIT=$?

if [ $PRECOMMIT_EXIT -ne 0 ]; then
    echo "================================================================"
    echo " [BLOCK] PRE-COMMIT HOOKS FAILED"
    echo "================================================================"
    echo " One or more pre-commit hooks failed."
    echo " Review the output above and fix the issues."
    echo "================================================================"
    exit 1
fi

python agentic_core/L0_routing/scripts/PascalSovereigntyFixer.py --validate
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "================================================================"
    echo " [BLOCK] SOVEREIGNTY VIOLATION DETECTED"
    echo "================================================================"
    echo " Your commit introduces file naming violations."
    echo " Please run: python agentic_core/L0_routing/scripts/PascalSovereigntyFixer.py"
    echo "================================================================"
    exit 1
fi

echo "[PASS] Architecture compliant."
exit 0
"""


def _resolve_repo_root(explicit_root: str | None = None) -> Path:
    if explicit_root:
        return Path(explicit_root).expanduser().resolve()
    env_root = os.getenv("AGENTIC_WORKFLOW_ROOT")
    if env_root:
        return Path(env_root).expanduser().resolve()
    for candidate in Path(__file__).resolve().parents:
        if (candidate / ".git").exists():
            return candidate
    return Path.cwd().resolve()


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp_path = path.with_suffix(path.suffix + ".tmp")
    tmp_path.write_text(content, encoding="utf-8", newline="\n")
    tmp_path.replace(path)


def install_hook(repo_root: Path, execute: bool = False, force: bool = False) -> int:
    hooks_dir = repo_root / ".git" / "hooks"
    pre_commit_file = hooks_dir / HOOK_FILENAME

    print(f"[INSTALL] Target: {pre_commit_file}")
    if not hooks_dir.exists():
        print(f"[ERROR] .git/hooks directory not found at {hooks_dir}")
        print("        Are you in a valid git repository?")
        return 1

    existing = (
        pre_commit_file.read_text(encoding="utf-8", errors="replace") if pre_commit_file.exists() else None
    )
    if existing == HOOK_CONTENT:
        print("[INFO] Pre-commit hook is already up to date.")
        return 0
    if existing is not None and not force:
        print("[ERROR] A pre-commit hook already exists. Re-run with --force to overwrite it.")
        return 1

    if not execute:
        print("[DRY RUN] Hook content validated. Re-run with --execute to install.")
        return 0

    if existing is not None:
        backup_path = pre_commit_file.with_suffix(".bak")
        _atomic_write(backup_path, existing)
        print(f"[BACKUP] Existing hook backed up to {backup_path}")

    _atomic_write(pre_commit_file, HOOK_CONTENT)
    current_mode = os.stat(pre_commit_file).st_mode
    os.chmod(pre_commit_file, current_mode | stat.S_IEXEC)
    print("[SUCCESS] Pre-commit hook installed.")
    print("          Pascal Sovereignty will now protect this repo from regression.")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Install the repo's sovereignty pre-commit hook.")
    parser.add_argument("--repo-root", help="Override automatic repository root detection.")
    parser.add_argument(
        "--execute", action="store_true", help="Actually install the hook. Default is dry-run."
    )
    parser.add_argument("--force", action="store_true", help="Overwrite an existing pre-commit hook.")
    args = parser.parse_args(argv)

    repo_root = _resolve_repo_root(args.repo_root)
    return install_hook(repo_root, execute=args.execute, force=args.force)


if __name__ == "__main__":
    raise SystemExit(main())
