"""
File: scripts/install_git_hooks.py
Path: C:\\Git\\Agentic-Workflow\\scripts\\install_git_hooks.py
Status: New "Day 2" Sovereignty Enforcer
Rationale:
    Now that the migration is complete/ready, we must prevent regression.
    This script installs a git pre-commit hook that runs the sovereignty validator
    before every commit, ensuring 'The 3 Laws' are never broken again.
"""
import os
import stat
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.resolve()
HOOKS_DIR = REPO_ROOT / '.git' / 'hooks'
PRE_COMMIT_FILE = HOOKS_DIR / 'pre-commit'
HOOK_CONTENT = '#!/bin/sh\n# Pascal Sovereignty Pre-Commit Hook\n# Auto-generated by ops_scripts/install_git_hooks.py\n# Updated 2026-01-30: Now invokes pre-commit framework for full hook execution\n\necho "[SOVEREIGNTY] Auditing architectural compliance..."\n\n# Git guarantees the CWD is the top-level of the working tree.\n\n# Step 1: Run the pre-commit framework (executes .pre-commit-config.yaml)\n# This includes: ruff, trailing-whitespace, purge-cache, validate-ssot-structure, etc.\npre-commit run --hook-stage commit\nPRECOMMIT_EXIT=$?\n\nif [ $PRECOMMIT_EXIT -ne 0 ]; then\n    echo "================================================================"\n    echo " [BLOCK] PRE-COMMIT HOOKS FAILED"\n    echo "================================================================"\n    echo " One or more pre-commit hooks failed."\n    echo " Review the output above and fix the issues."\n    echo "================================================================"\n    exit 1\nfi\n\n# Step 2: Run Pascal Sovereignty validation (legacy check)\npython agentic_core/L0_routing/scripts/PascalSovereigntyFixer.py --validate\nEXIT_CODE=$?\n\nif [ $EXIT_CODE -ne 0 ]; then\n    echo "================================================================"\n    echo " [BLOCK] SOVEREIGNTY VIOLATION DETECTED"\n    echo "================================================================"\n    echo " Your commit introduces file naming violations."\n    echo " Please run: python agentic_core/L0_routing/scripts/PascalSovereigntyFixer.py"\n    echo "================================================================"\n    exit 1\nfi\n\necho "[PASS] Architecture compliant."\nexit 0\n'

def install_hook():
    print(f'[INSTALL] Target: {PRE_COMMIT_FILE}')
    if not HOOKS_DIR.exists():
        print(f'[ERROR] .git/hooks directory not found at {HOOKS_DIR}')
        print('        Are you in a valid git repository?')
        sys.exit(1)
    try:
        with open(PRE_COMMIT_FILE, 'w', encoding='utf-8', newline='\n') as f:
            f.write(HOOK_CONTENT)
        st = os.stat(PRE_COMMIT_FILE)
        os.chmod(PRE_COMMIT_FILE, st.st_mode | stat.S_IEXEC)
        print('[SUCCESS] Pre-commit hook installed.')
        print('          Pascal Sovereignty will now protect this repo from regression.')
    # guardian: allow-silent-swallow
    except Exception as e:
        print(f'[ERROR] Failed to install hook: {e}')
        sys.exit(1)
if __name__ == '__main__':
    install_hook()
