"""
LIC CTA Patterns - Call-to-action patterns and date window engine.

Ported from: archives/LIC_capabilities/reconstructed_capabilities.py
"""

from datetime import datetime, timedelta


class RecipientArchetype(Enum):
    """Recipient Archetype classifications."""

    C_LEVEL = "C_LEVEL"
    EXECUTIVE = "EXECUTIVE"
    SENIOR_TA = "SENIOR_TA"
    RECRUITER = "RECRUITER"


class CTAStyle(Enum):
    """CTA style types."""

    STRATEGIC_ALIGNMENT = "strategic_alignment"
    COLLABORATIVE_VALUE = "collaborative_value"
    TECHNICAL_PEER = "technical_peer"
    WARM_PROFESSIONAL = "warm_professional"


@dataclass
class CTAPattern:
    """Pattern for call-to-action generation."""

    style: CTAStyle
    verbs: list[str]
    focus: str
    tone: str
    formality: str
    example: str


# CTA patterns by Archetype
CTA_PATTERNS: dict[RecipientArchetype, CTAPattern] = {
    RecipientArchetype.C_LEVEL: CTAPattern(
        style=CTAStyle.STRATEGIC_ALIGNMENT,
        verbs=["discuss", "align", "explore", "advance"],
        focus="business_impact",
        tone="strategic, outcome-focused",
        formality="very high",
        example="Would you have 15 minutes to discuss {business_impact}?",
    ),
    RecipientArchetype.EXECUTIVE: CTAPattern(
        style=CTAStyle.COLLABORATIVE_VALUE,
        verbs=["collaborate", "discuss", "connect", "share"],
        focus="team_objectives",
        tone="succinct, high-level",
        formality="high",
        example=("Would {date_window} work for a brief discussion on {strategic_topic}?"),
    ),
    RecipientArchetype.SENIOR_TA: CTAPattern(
        style=CTAStyle.TECHNICAL_PEER,
        verbs=["build", "implement", "architect", "optimize"],
        focus="technical_challenges",
        tone="consultative, respectful",
        formality="medium-high",
        example="Would you have time to explore how {topic} could support {company}?",
    ),
    RecipientArchetype.RECRUITER: CTAPattern(
        style=CTAStyle.WARM_PROFESSIONAL,
        verbs=["match", "connect", "support", "assist"],
        focus="role_alignment",
        tone="warm, efficient",
        formality="low-medium",
        example="Would you be open to a quick chat about {topic}?",
    ),
}


@dataclass
class CTATemplate:
    """Template for CTA generation by Route."""

    template: str
    word_limit: int | None = None
    examples: list[str] = field(default_factory=list)
    variables: dict[str, str] = field(default_factory=dict)


# CTA templates by Route
CTA_TEMPLATES: dict[str, CTATemplate] = {
    "CONNECTION_REQ": CTATemplate(
        template="Would you be open to a brief chat about {topic}?",
        word_limit=5,
        examples=[
            "Open to a brief chat?",
            "Available for a quick call?",
            "Time for a conversation?",
        ],
    ),
    "INMAIL": CTATemplate(
        template="Would {date_window} work for a {duration} conversation?",
        variables={
            "date_window": "Generated by date_window_engine",
            "duration": "15-minute, 20-minute, 30-minute",
        },
    ),
    "SHORT_NEW": CTATemplate(
        template="Are you available for a quick call on {date_window}?",
    ),
    "LONG_NEW": CTATemplate(
        template="Would you have time on {date_window} to discuss {specific_topic}?",
    ),
    "FOLLOW_UP": CTATemplate(
        template="Following up on {prior_topic}--would {date_window} work?",
    ),
}


@dataclass
class DateWindowConfig:
    """configuration for date window generation."""

    window_size_days: int = 2
    avoid_weekends: bool = True
    avoid_holidays: bool = True
    date_format: str = "EEE MMM d"


@dataclass
class DayBufferConfig:
    """Buffer configuration for a specific day."""

    min_buffer_days: int
    suggested_pattern: str


# Business day buffer map
DAY_BUFFER_MAP: dict[str, DayBufferConfig] = {
    "Monday": DayBufferConfig(
        min_buffer_days=2,
        suggested_pattern="Wed-Thu same week",
    ),
    "Tuesday": DayBufferConfig(
        min_buffer_days=2,
        suggested_pattern="Thu-Fri same week",
    ),
    "Wednesday": DayBufferConfig(
        min_buffer_days=2,
        suggested_pattern="Fri-Mon (crosses weekend)",
    ),
    "Thursday": DayBufferConfig(
        min_buffer_days=3,
        suggested_pattern="Tue-Wed next week",
    ),
    "Friday": DayBufferConfig(
        min_buffer_days=3,
        suggested_pattern="Wed-Thu next week",
    ),
}

# US Federal Holidays (approximate dates for 2025)
US_HOLIDAYS_2025 = [
    datetime(2025, 1, 1),  # New Year's Day
    datetime(2025, 1, 20),  # MLK Day
    datetime(2025, 2, 17),  # Presidents Day
    datetime(2025, 5, 26),  # Memorial Day
    datetime(2025, 6, 19),  # Juneteenth
    datetime(2025, 7, 4),  # Independence Day
    datetime(2025, 9, 1),  # Labor Day
    datetime(2025, 10, 13),  # Columbus Day
    datetime(2025, 11, 11),  # Veterans Day
    datetime(2025, 11, 27),  # Thanksgiving
    datetime(2025, 12, 25),  # Christmas
]


class DateWindowEngine:
    """Engine for generating date windows for CTAs."""

    def __init__(
        self,
        config: DateWindowConfig | None = None,
    ) -> None:
        """Initialize the date window engine."""
        self.config = config or DateWindowConfig()
        self._holidays = {h.date() for h in US_HOLIDAYS_2025}

    def generate_date_window(
        self,
        from_date: datetime | None = None,
        num_dates: int = 3,
    ) -> list[datetime]:
        """
        Generate a window of available dates.

        Args:
            from_date: Starting date (defaults to today)
            num_dates: Number of dates to generate

        Returns:
            List of available dates
        """
        if from_date is None:
            from_date = datetime.now()

        # Get day of week
        day_name = from_date.strftime("%A")
        buffer_config = DAY_BUFFER_MAP.get(
            day_name,
            DayBufferConfig(min_buffer_days=2, suggested_pattern=""),
        )

        # Start from buffer days ahead
        current_date = from_date + timedelta(days=buffer_config.min_buffer_days)

        available_dates: list[datetime] = []
        max_attempts = 14  # Look up to 2 weeks ahead

        attempts = 0
        while len(available_dates) < num_dates and attempts < max_attempts:
            if self._is_available_date(current_date):
                available_dates.append(current_date)
            current_date += timedelta(days=1)
            attempts += 1

        return available_dates

    def format_date_window(
        self,
        dates: list[datetime],
        format_style: str = "natural",
    ) -> str:
        """
        Format a date window as a string.

        Args:
            dates: List of dates
            format_style: "natural" or "numeric"

        Returns:
            Formatted date window string
        """
        if not dates:
            return "next week"

        if format_style == "numeric":
            formatted = [d.strftime("%m/%d") for d in dates]
        else:
            formatted = [d.strftime("%a %b %d") for d in dates]

        if len(formatted) == 1:
            return formatted[0]
        elif len(formatted) == 2:
            return f"{formatted[0]} or {formatted[1]}"
        else:
            return f"{', '.join(formatted[:-1])}, or {formatted[-1]}"

    def _is_available_date(self, date: datetime) -> bool:
        """Check if a date is available (not weekend or holiday)."""
        # Check weekend
        if self.config.avoid_weekends and date.weekday() >= 5:
            return False

        # Check holiday
        if self.config.avoid_holidays and date.date() in self._holidays:
            return False

        return True


class CTAGenerator:
    """Generator for call-to-action text."""

    def __init__(self) -> None:
        """Initialize the CTA generator."""
        self._patterns = CTA_PATTERNS
        self._templates = CTA_TEMPLATES
        self._date_engine = DateWindowEngine()

    def get_pattern(self, Archetype: RecipientArchetype) -> CTAPattern:
        """Get CTA pattern for an Archetype."""
        return self._patterns.get(
            Archetype,
            self._patterns[RecipientArchetype.EXECUTIVE],
        )

    def get_template(self, Route: str) -> CTATemplate:
        """Get CTA template for a Route."""
        return self._templates.get(
            Route,
            self._templates["SHORT_NEW"],
        )

    def generate_date_window(
        self,
        from_date: datetime | None = None,
        num_dates: int = 3,
    ) -> str:
        """Generate a formatted date window."""
        dates = self._date_engine.generate_date_window(from_date, num_dates)
        return self._date_engine.format_date_window(dates)

    def generate_cta(
        self,
        Route: str,
        Archetype: RecipientArchetype,
        topic: str | None = None,
        include_date_window: bool = True,
    ) -> dict[str, object]:
        """
        Generate a CTA based on Route and Archetype.

        Args:
            Route: Message Route
            Archetype: Recipient Archetype
            topic: Optional topic for the CTA
            include_date_window: Whether to include date window

        Returns:
            Dictionary with CTA components
        """
        template = self.get_template(Route)
        pattern = self.get_pattern(Archetype)

        result: dict[str, object] = {
            "template": template.template,
            "pattern": pattern,
            "verbs": pattern.verbs,
            "tone": pattern.tone,
            "formality": pattern.formality,
        }

        if include_date_window:
            result["date_window"] = self.generate_date_window()

        if topic:
            result["topic"] = topic

        if template.word_limit:
            result["word_limit"] = template.word_limit

        if template.examples:
            result["examples"] = template.examples

        return result

    def validate_cta(
        self,
        cta_text: str,
        Route: str,
    ) -> dict[str, object]:
        """
        Validate a CTA against Route requirements.

        Args:
            cta_text: CTA text to validate
            Route: Message Route

        Returns:
            Validation result dictionary
        """
        template = self.get_template(Route)
        result: dict[str, object] = {
            "is_valid": True,
            "violations": [],
            "word_count": len(cta_text.split()),
        }

        # Check word limit
        if template.word_limit:
            word_count = len(cta_text.split())
            if word_count > template.word_limit:
                result["is_valid"] = False
                result["violations"].append(
                    f"Word count {word_count} exceeds limit {template.word_limit}"
                )

        # Check for question mark (CTAs should be questions)
        if "?" not in cta_text:
            result["violations"].append("CTA should end with a question mark")

        return result


def create_cta_generator() -> CTAGenerator:
    """builder function to create a CTA generator."""
    return CTAGenerator()


def create_date_window_engine(
    config: DateWindowConfig | None = None,
) -> DateWindowEngine:
    """builder function to create a date window engine."""
    return DateWindowEngine(config)


def get_cta_pattern(Archetype: RecipientArchetype) -> CTAPattern:
    """Get CTA pattern for an Archetype."""
    return CTA_PATTERNS.get(
        Archetype,
        CTA_PATTERNS[RecipientArchetype.EXECUTIVE],
    )
