#!/usr/bin/env python3
"""
Build a consolidated report from all deep_analysis_*.json reports.
Produces a human-readable markdown file with per-directory, per-subdirectory,
and per-file findings.
"""

import json
from pathlib import Path
from typing import Any

REPORTS = {
    "system_learning": "docs/reports/plans/deep_analysis_system_learning.json",
    "agentic_core/prompt_governance": "docs/reports/plans/deep_analysis_prompt_governance.json",
    "agentic_core/runtime": "docs/reports/plans/deep_analysis_runtime.json",
    "ops_scripts": "docs/reports/plans/deep_analysis_ops_scripts.json",
    "data": "docs/reports/plans/deep_analysis_data.json",
    "docs": "docs/reports/plans/deep_analysis_docs.json",
    "infrastructure": "docs/reports/plans/deep_analysis_infrastructure.json",
    "tools": "docs/reports/plans/deep_analysis_tools.json",
}

OUTPUT = "docs/reports/plans/CONSOLIDATED_REFACTORING_REPORT.md"


def load(path: str) -> dict[str, Any]:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def section(title: str, level: int = 2) -> str:
    return f"\n{'#' * level} {title}\n"


def build_report() -> str:
    lines = []
    lines.append("# Consolidated Recursive Refactoring Report\n")
    lines.append("Generated by `tools/analysis/build_consolidated_report.py`\n")
    lines.append("ADG database: `artifacts/adg/adg_indexed_04062026_0952.sqlite`\n")

    # ── Grand totals ──────────────────────────────────────────────────────
    grand_files = 0
    grand_issues = 0
    grand_root_violations = 0
    grand_dead = 0
    grand_misplaced = 0

    dir_summaries = {}
    for dir_key, report_path in REPORTS.items():
        data = load(report_path)
        s = data["summary"]
        dir_summaries[dir_key] = (s, data["files"])
        grand_files += s["total_files"]
        grand_issues += s["total_with_issues"]
        grand_root_violations += s["total_root_violations"]
        grand_dead += s["total_dead_code_files"]
        grand_misplaced += s["total_misplaced_files"]

    lines.append(section("Grand Totals"))
    lines.append("| Metric | Count |")
    lines.append("|--------|-------|")
    lines.append(f"| Total files scanned | {grand_files} |")
    lines.append(f"| Files with dead-code issues | {grand_issues} |")
    lines.append(f"| Root-level violations | {grand_root_violations} |")
    lines.append(f"| Dead code files | {grand_dead} |")
    lines.append(f"| Misplaced files | {grand_misplaced} |")

    # ── Per-directory summary table ───────────────────────────────────────
    lines.append(section("Directory Summary"))
    lines.append("| Directory | Files | Issues | Root Violations | Dead Code | Misplaced |")
    lines.append("|-----------|-------|--------|-----------------|-----------|-----------|")
    for dir_key, (s, _) in dir_summaries.items():
        lines.append(
            f"| `{dir_key}` | {s['total_files']} | {s['total_with_issues']} "
            f"| {s['total_root_violations']} | {s['total_dead_code_files']} "
            f"| {s['total_misplaced_files']} |",
        )

    # ── Per-directory deep drill-down ─────────────────────────────────────
    lines.append(section("Per-Directory Deep Analysis"))

    for dir_key, (summary, file_records) in dir_summaries.items():
        lines.append(section(f"`{dir_key}/`", level=3))

        # Per-folder table
        folder_bd = summary.get("folder_breakdown", {})
        if folder_bd:
            lines.append("**Folder breakdown:**\n")
            lines.append("| Folder | Files | Lines | Root Violations | Dead Code | Misplaced |")
            lines.append("|--------|-------|-------|-----------------|-----------|-----------|")
            for folder, fs in sorted(folder_bd.items()):
                rv = len(fs.get("root_violations", []))
                dc = len(fs.get("dead_code_files", []))
                mp = len(fs.get("misplaced_files", []))
                marker = "⚠️" if (rv + dc + mp) > 0 else "✅"
                lines.append(
                    f"| {marker} `{folder}/` | {fs['files']} | {fs['total_lines']} | {rv} | {dc} | {mp} |",
                )

        # Root violations detail
        root_files = [r for r in file_records if r.get("root_violation")]
        if root_files:
            lines.append("\n**Root-level violations (files that must be moved to a subdirectory):**\n")
            for r in root_files:
                funcs = r.get("functions", [])
                lines.append(
                    f"- `{r['path']}` — {r['code_lines']} code lines, "
                    f"{len(funcs)} functions, {r['size_bytes']} bytes",
                )
                if funcs:
                    lines.append(f"  - Functions: `{'`, `'.join(funcs[:8])}`{'…' if len(funcs) > 8 else ''}")

        # Dead code detail — only genuine issues
        dead_files = [r for r in file_records if r.get("issues") and not r.get("root_violation")]
        if dead_files:
            lines.append("\n**Files with dead-code signals:**\n")
            for r in dead_files:
                lines.append(f"- `{r['path']}` — issues: `{'`, `'.join(r['issues'])}`")
                for imp in r.get("adg_unused_imports", [])[:5]:
                    lines.append(f"  - unused import line {imp['line']}: `{imp['symbol']}`")
                for imp in r.get("adg_dead_imports", [])[:5]:
                    lines.append(f"  - dead import line {imp['line']}: `{imp['symbol']}`")
                for u in r.get("adg_unreachable", [])[:3]:
                    lines.append(f"  - unreachable code line {u['line']}: `{u['symbol']}`")
                for d in r.get("adg_duplicate_methods", [])[:3]:
                    lines.append(f"  - duplicate method line {d['line']}: `{d['symbol']}`")

        # Empty / hollow subdirs
        hollow = []
        for folder, fs in folder_bd.items():
            if fs["files"] == 0:
                hollow.append(folder)
        if hollow:
            lines.append("\n**Empty subdirectories:**\n")
            for h in hollow:
                lines.append(f"- `{h}/`")

    # ── Action plan ───────────────────────────────────────────────────────
    lines.append(section("Action Plan"))
    lines.append("Priority order based on impact:\n")

    action_items = []

    for dir_key, (summary, file_records) in dir_summaries.items():
        root_files = [r for r in file_records if r.get("root_violation")]
        for r in root_files:
            action_items.append(
                {
                    "priority": "HIGH",
                    "action": "MOVE",
                    "file": r["path"],
                    "reason": f"Root-level violation — {len(r.get('functions', []))} functions, {r['code_lines']} code lines",
                }
            )
        dead_files = [r for r in file_records if r.get("issues")]
        for r in dead_files:
            for imp in r.get("adg_unused_imports", []):
                action_items.append(
                    {
                        "priority": "MEDIUM",
                        "action": "REMOVE_IMPORT",
                        "file": r["path"],
                        "reason": f"Unused import line {imp['line']}: `{imp['symbol']}`",
                    }
                )
            for d in r.get("adg_duplicate_methods", []):
                action_items.append(
                    {
                        "priority": "HIGH",
                        "action": "REMOVE_DUPLICATE",
                        "file": r["path"],
                        "reason": f"Duplicate method line {d['line']}: `{d['symbol']}`",
                    }
                )
            for u in r.get("adg_unreachable", []):
                action_items.append(
                    {
                        "priority": "HIGH",
                        "action": "REMOVE_UNREACHABLE",
                        "file": r["path"],
                        "reason": f"Unreachable code line {u['line']}: `{u['symbol']}`",
                    }
                )

    # Group by priority
    for priority in ("HIGH", "MEDIUM", "LOW"):
        bucket = [a for a in action_items if a["priority"] == priority]
        if bucket:
            lines.append(f"\n### {priority} Priority ({len(bucket)} actions)\n")
            for a in bucket:
                lines.append(f"- **{a['action']}** `{a['file']}` — {a['reason']}")

    return "\n".join(lines)


if __name__ == "__main__":
    report = build_report()
    out = Path(OUTPUT)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")
    print(f"Consolidated report written to: {OUTPUT}")
    # Print a short executive summary
    lines = report.splitlines()
    for line in lines[:60]:
        print(line)
