from __future__ import annotations

from agentic_core.L2_execution.tools import write_gateway as _wg
from agentic_core.L_CONTRACTS.lifecycle_trace_contract import (
    _emit_agent_executes_agent,
    _emit_authorize_and_execute,
    _emit_blocks_direct_write,
    _emit_captures_evaluation_metric,
    _emit_captures_execution_output,
    _emit_checks_agent_registry,
    _emit_coordinates_agents,
    _emit_dispatches_agent,
    _emit_dispatches_execution_plan,
    _emit_dispatches_healing_run,
    # noqa: E402,
    # noqa: E402
    _emit_escalates_failure,
    _emit_escalates_to_human,
    # noqa: E402
    _emit_gated_by_confidence,
    _emit_hard_fails_untranscripted,
    _emit_invokes_evaluation,
    _emit_links_execution_to_snapshot,
    _emit_observes_runtime_state,
    _emit_orchestrates_workflow,
    _emit_reads_policy_state,
    # noqa: E402
    _emit_records_healing_outcome,
    _emit_records_telemetry_event,
    _emit_records_tool_invocation,
    _emit_records_workflow_lineage,
    _emit_routes_through,
    # noqa: E402
    _emit_routes_to_agent,
    _emit_routes_to_capability,
    _emit_signs_execution_trace,
    _emit_snapshots_state,
    # noqa: E402
    _emit_stores_embedding,
    _emit_transcripts_response,
    _emit_updates_meta_learning_state,
    _emit_validates_agent_capability,
    _emit_validates_capability,
    _emit_verifies_boundary,
    _emit_verifies_policy,
    _emit_writes_via_uwg,
    emit_determinism_digest,
    # noqa: E402
    emit_replay_key,
)

emit_replay_key("p0", "action_router")
emit_determinism_digest("p0", "action_router")

_emit_dispatches_healing_run("p1", "action_router", "L3")
_emit_routes_through("p1", "action_router", "L3")
_emit_verifies_policy("p1", "action_router", "policy_check")
_emit_observes_runtime_state("p1", "action_router", "runtime_state")
_emit_verifies_boundary("p1", "action_router", "boundary_check")
_emit_transcripts_response("p1", "action_router", "transcript")
_emit_hard_fails_untranscripted("p1", "action_router")
_emit_gated_by_confidence("p1", "action_router", "confidence_gate")
_emit_escalates_to_human("p1", "action_router", "L3")
_emit_reads_policy_state("p1", "action_router", "L3")
_emit_routes_to_agent("p1", "action_router", "L3")
_emit_orchestrates_workflow("p1", "action_router", "L3")
_emit_dispatches_execution_plan("p1", "action_router", "L3")
_emit_validates_agent_capability("p1", "action_router", "L3")
_emit_checks_agent_registry("p1", "action_router", "L3")

_emit_snapshots_state("p0", "action_router", "state_snapshot")
_emit_authorize_and_execute("p2", "action_router", "execution_auth")
_emit_validates_capability("p2", "action_router", "capability_check")
_emit_routes_to_capability("p2", "action_router", "capability_route")
_emit_writes_via_uwg("p2", "action_router", "uwg_write")
_emit_blocks_direct_write("p2", "action_router", "direct_write_block")
_emit_records_tool_invocation("p2", "action_router", "tool_invocation")
_emit_captures_execution_output("p2", "action_router", "exec_output")
_emit_dispatches_agent("p3", "action_router", "agent_dispatch")
_emit_coordinates_agents("p3", "action_router", "agent_coordination")
_emit_records_workflow_lineage("p3", "action_router", "workflow_lineage")
_emit_records_healing_outcome("p3", "action_router", "healing_outcome")
_emit_escalates_failure("p3", "action_router", "failure_escalation")
_emit_orchestrates_workflow("p3", "action_router", "workflow_orchestration")
_emit_dispatches_healing_run("p3", "action_router", "healing_dispatch")
_emit_invokes_evaluation("p3", "action_router", "evaluation_signal")
_emit_records_telemetry_event("p4", "action_router", "telemetry_event")
_emit_captures_evaluation_metric("p4", "action_router", "eval_metric")
_emit_stores_embedding("p4", "action_router", "embedding_store")
_emit_updates_meta_learning_state("p4", "action_router", "meta_learning")
_emit_links_execution_to_snapshot("p4", "action_router", "exec_snapshot_link")

"\nAction Node - L3 Orchestration router\nAuto-generated by Atomic Fission Protocol (Dec 20, 2025)\nOriginal 351-line monolith split into 2 atomic sub-modules\n\nZERO-LOSS GUARANTEE: All functionality preserved via composition\n"
import logging
import uuid
from pathlib import Path
from typing import Any

from agentic_core.action_node_modules import ActionNodeCore, SecureToolsImpl
from agentic_core.L_CONTRACTS.lifecycle_trace_contract import (
    LayerSegment,
    _emit_agent_executes_agent,
    _emit_applies_guardrail,
    _emit_captures_pattern,
    _emit_captures_runtime_anomaly,
    _emit_emits_metric_event,
    _emit_execution_terminates_at_uwg,
    _emit_feeds_meta_learning,
    _emit_gated_by_confidence,
    _emit_hard_fails_untranscripted,
    _emit_improves_agent_policy,
    _emit_invokes_eval,
    _emit_links_incident_trace,
    _emit_observes_runtime_state,
    _emit_proposal_commits_routing,
    _emit_pulls_context,
    _emit_reads_environ,
    _emit_reads_runtime_state,
    _emit_records_execution_trace,
    _emit_records_incident_event,
    _emit_records_learning_event,
    _emit_signs_execution_trace,
    _emit_stores_learning_state,
    _emit_transcripts_response,
    _emit_triggers_alert,
    _emit_updates_monitoring_state,
    _emit_updates_routing_strategy,
    _emit_validated_by_safety_plane,
    _emit_verifies_boundary,
    _emit_verifies_policy,
    _emit_writes_learning_snapshot,
    _emit_writes_observability_log,
    _emit_writes_through,
)

_emit_emits_metric_event("action_router", "p4obs", "metric_1")
_emit_emits_metric_event("action_router", "p4obs", "metric_2")
_emit_emits_metric_event("action_router", "p4obs", "metric_3")
_emit_emits_metric_event("action_router", "p4obs", "metric_4")
_emit_emits_metric_event("action_router", "p4obs", "metric_5")
_emit_emits_metric_event("action_router", "p4obs", "metric_6")
_emit_records_incident_event("action_router", "p4obs", "incident")
_emit_captures_runtime_anomaly("action_router", "p4obs", "anomaly")
_emit_writes_observability_log("action_router", "p4obs", "obs_log")
_emit_updates_monitoring_state("action_router", "p4obs", "mon_state")
_emit_triggers_alert("action_router", "p4obs", "alert")
_emit_links_incident_trace("action_router", "p4obs", "trace_link")
_emit_captures_pattern("action_router", "p3lm", "pattern")
_emit_records_learning_event("action_router", "p3lm", "learning_event")
_emit_writes_learning_snapshot("action_router", "p3lm", "snapshot")
_emit_feeds_meta_learning("action_router", "p3lm", "meta_feed")
_emit_updates_routing_strategy("action_router", "p3lm", "routing")
_emit_improves_agent_policy("action_router", "p3lm", "policy")
_emit_stores_learning_state("action_router", "p3lm", "state")
_emit_records_execution_trace("action_router", "L0_ROUTING", "p2_trace_1")
_emit_records_execution_trace("action_router", "L1_REASONING", "p2_trace_2")
_emit_records_execution_trace("action_router", "L2_EXECUTION", "p2_trace_3")
_emit_records_execution_trace("action_router", "L3_ORCHESTRATION", "p2_trace_4")
_emit_records_execution_trace("action_router", "L4_STATE", "p2_trace_5")
_emit_reads_environ("action_router", "env_read", "p2_env_1")
_emit_reads_environ("action_router", "env_read", "p2_env_2")
_emit_reads_runtime_state("action_router", "runtime_state", "p2_rt_1")
_emit_reads_runtime_state("action_router", "runtime_state", "p2_rt_2")
_emit_pulls_context("p1", "action_router", "context_pull")
_emit_pulls_context("p1", "action_router", "context_pull_2")
_emit_execution_terminates_at_uwg("p1", "action_router", "uwg_term")
_emit_execution_terminates_at_uwg("p1", "action_router", "uwg_term_2")
_emit_writes_through("p1", "action_router", "write_through")
_emit_writes_through("p1", "action_router", "write_through_2")
_emit_validated_by_safety_plane("p1", "action_router", "safety_validation")
_emit_invokes_eval("p1", "action_router", "eval_call")
_emit_proposal_commits_routing("p1", "action_router", "routing_commit")

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
Logger: Any = logging.getLogger("ActionNode")


class ActionNode:
    """
    The 'Hands' of the Agent.
    Responsibility: Execute the Cognitive Node's plan safely.
    Security: STRICT WHITELIST of allowed tools.
    """

    def __init__(self, work_dir: str = "./workspace"):
        """
        Initializes the ActionNode with a specified working directory.

        Args:
            work_dir (str): The path to the workspace directory.
        """
        import hashlib as _hashlib  # noqa: PLC0415
        import uuid as _uuid  # noqa: PLC0415

        _tid = str(_uuid.uuid4())
        _emit_signs_execution_trace(_tid, _hashlib.sha256(_tid.encode()).hexdigest()[:12], "p0_trace", 0)
        import uuid as _uuid  # noqa: PLC0415

        _emit_applies_guardrail(str(_uuid.uuid4()), "ActionNode.__init__", "p0_governance")
        import uuid as _uuid  # noqa: PLC0415

        _trace_id = str(_uuid.uuid4())
        _emit_records_execution_trace(_trace_id, LayerSegment.L3_ORCHESTRATION, "ActionNode.__init__")
        self.work_dir: Path = Path(work_dir).resolve()
        self.tools_impl = SecureToolsImpl(self.work_dir)
        self.allowed_tools: dict[str, Any] = {
            "write_file": self.tools_impl.tool_write_file,
            "read_file": self.tools_impl.tool_read_file,
            "list_files": self.tools_impl.tool_list_files,
            "run_command": self.tools_impl.tool_run_command,
        }
        self.core = ActionNodeCore(str(self.work_dir), self.allowed_tools)
        if not self.work_dir.exists():
            Logger.info(f"Creating workspace directory: {self.work_dir}")
            _wg.ensure_dir(self.work_dir)
        else:
            Logger.info(f"Using existing workspace directory: {self.work_dir}")

    def execute_plan(self, plan: dict[str, Any]) -> dict[str, Any]:
        """
        Executes a full plan sequence from the Cognitive Node.

        Args:
            plan (Dict[str, Any]): A dictionary representing the plan,
                                   expected to contain 'goal' and 'steps'.

        Returns:
            Dict[str, Any]: A dictionary containing the overall status and results
                            of each executed step.
        """
        _emit_agent_executes_agent(str(uuid.uuid4()), "ActionNode", "ActionNode.execute_plan")
        return self.core.execute_plan(plan)


__all__ = ["ActionNode"]
