from __future__ import annotations

from agentic_core.L2_execution.tools import write_gateway as _wg
from agentic_core.runtime.lifecycle_trace_contract import (
    _emit_authorize_and_execute,
    _emit_blocks_direct_write,
    _emit_captures_evaluation_metric,
    _emit_captures_execution_output,
    _emit_checks_agent_registry,
    _emit_coordinates_agents,
    _emit_dispatches_agent,
    _emit_dispatches_execution_plan,
    _emit_dispatches_healing_run,  # noqa: E402
    _emit_escalates_failure,
    _emit_escalates_to_human,  # noqa: E402
    _emit_invokes_evaluation,
    _emit_links_execution_to_snapshot,
    _emit_orchestrates_workflow,
    _emit_reads_policy_state,  # noqa: E402
    _emit_records_healing_outcome,
    _emit_records_telemetry_event,
    _emit_records_tool_invocation,
    _emit_records_workflow_lineage,
    _emit_routes_through,  # noqa: E402
    _emit_routes_to_agent,
    _emit_routes_to_capability,
    _emit_snapshots_state,  # noqa: E402
    _emit_stores_embedding,
    _emit_updates_meta_learning_state,
    _emit_validates_agent_capability,
    _emit_validates_capability,
    _emit_writes_via_uwg,
    emit_determinism_digest,  # noqa: E402
    emit_replay_key,  # noqa: E402
)

emit_replay_key("p0", "action_router")
emit_determinism_digest("p0", "action_router")

_emit_dispatches_healing_run("p1", "action_router", "L3")
_emit_routes_through("p1", "action_router", "L3")
_emit_escalates_to_human("p1", "action_router", "L3")
_emit_reads_policy_state("p1", "action_router", "L3")
_emit_routes_to_agent("p1", "action_router", "L3")
_emit_orchestrates_workflow("p1", "action_router", "L3")
_emit_dispatches_execution_plan("p1", "action_router", "L3")
_emit_validates_agent_capability("p1", "action_router", "L3")
_emit_checks_agent_registry("p1", "action_router", "L3")

_emit_snapshots_state("p0", "action_router", "state_snapshot")
_emit_authorize_and_execute("p2", "action_router", "execution_auth")
_emit_validates_capability("p2", "action_router", "capability_check")
_emit_routes_to_capability("p2", "action_router", "capability_route")
_emit_writes_via_uwg("p2", "action_router", "uwg_write")
_emit_blocks_direct_write("p2", "action_router", "direct_write_block")
_emit_records_tool_invocation("p2", "action_router", "tool_invocation")
_emit_captures_execution_output("p2", "action_router", "exec_output")
_emit_dispatches_agent("p3", "action_router", "agent_dispatch")
_emit_coordinates_agents("p3", "action_router", "agent_coordination")
_emit_records_workflow_lineage("p3", "action_router", "workflow_lineage")
_emit_records_healing_outcome("p3", "action_router", "healing_outcome")
_emit_escalates_failure("p3", "action_router", "failure_escalation")
_emit_orchestrates_workflow("p3", "action_router", "workflow_orchestration")
_emit_dispatches_healing_run("p3", "action_router", "healing_dispatch")
_emit_invokes_evaluation("p3", "action_router", "evaluation_signal")
_emit_records_telemetry_event("p4", "action_router", "telemetry_event")
_emit_captures_evaluation_metric("p4", "action_router", "eval_metric")
_emit_stores_embedding("p4", "action_router", "embedding_store")
_emit_updates_meta_learning_state("p4", "action_router", "meta_learning")
_emit_links_execution_to_snapshot("p4", "action_router", "exec_snapshot_link")

"\nAction Node - L3 Orchestration router\nAuto-generated by Atomic Fission Protocol (Dec 20, 2025)\nOriginal 351-line monolith split into 2 atomic sub-modules\n\nZERO-LOSS GUARANTEE: All functionality preserved via composition\n"
import logging
import uuid
from pathlib import Path
from typing import Any

from agentic_core.action_node_modules import ActionNodeCore, SecureToolsImpl

from agentic_core.runtime.lifecycle_trace_contract import (
    LayerSegment,
    _emit_agent_executes_agent,
    _emit_applies_guardrail,
    _emit_records_execution_trace,
    _emit_signs_execution_trace,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
Logger: Any = logging.getLogger("ActionNode")


class ActionNode:
    """
    The 'Hands' of the Agent.
    Responsibility: Execute the Cognitive Node's plan safely.
    Security: STRICT WHITELIST of allowed tools.
    """

    def __init__(self, work_dir: str = "./workspace"):
        """
        Initializes the ActionNode with a specified working directory.

        Args:
            work_dir (str): The path to the workspace directory.
        """
        import hashlib as _hashlib  # noqa: PLC0415
        import uuid as _uuid  # noqa: PLC0415

        _tid = str(_uuid.uuid4())
        _emit_signs_execution_trace(_tid, _hashlib.sha256(_tid.encode()).hexdigest()[:12], "p0_trace", 0)
        import uuid as _uuid  # noqa: PLC0415

        _emit_applies_guardrail(str(_uuid.uuid4()), "ActionNode.__init__", "p0_governance")
        import uuid as _uuid  # noqa: PLC0415

        _trace_id = str(_uuid.uuid4())
        _emit_records_execution_trace(_trace_id, LayerSegment.L3_ORCHESTRATION, "ActionNode.__init__")
        self.work_dir: Path = Path(work_dir).resolve()
        self.tools_impl = SecureToolsImpl(self.work_dir)
        self.allowed_tools: dict[str, Any] = {
            "write_file": self.tools_impl.tool_write_file,
            "read_file": self.tools_impl.tool_read_file,
            "list_files": self.tools_impl.tool_list_files,
            "run_command": self.tools_impl.tool_run_command,
        }
        self.core = ActionNodeCore(str(self.work_dir), self.allowed_tools)
        if not self.work_dir.exists():
            Logger.info(f"Creating workspace directory: {self.work_dir}")
            _wg.ensure_dir(self.work_dir)
        else:
            Logger.info(f"Using existing workspace directory: {self.work_dir}")

    def execute_plan(self, plan: dict[str, Any]) -> dict[str, Any]:
        """
        Executes a full plan sequence from the Cognitive Node.

        Args:
            plan (Dict[str, Any]): A dictionary representing the plan,
                                   expected to contain 'goal' and 'steps'.

        Returns:
            Dict[str, Any]: A dictionary containing the overall status and results
                            of each executed step.
        """
        _emit_agent_executes_agent(str(uuid.uuid4()), "ActionNode", "ActionNode.execute_plan")
        return self.core.execute_plan(plan)


__all__ = ["ActionNode"]
