#!/usr/bin/env python3
"""
Wave 2: Fix INVALID skip patterns in enhanced test files.

Targets:
1. Files generated by enhance_import_only_tests.py with broken templates
   (class_name/func_name used as bare variables instead of strings)
2. try/except ImportError → pytest.skip() for first-party modules
3. Converts to hard imports that FAIL honestly on import errors

Strategy:
- For each enhanced file, re-read MODULE_PATH, re-analyze the module,
  and regenerate with correct hard-import patterns.
"""

import importlib
import re
import sys
from pathlib import Path


def analyze_module_api(module_path: str):
    """Analyze a module's public API."""
    try:
        mod = importlib.import_module(module_path)
    except Exception:
        return [], [], []

    public = [n for n in dir(mod) if not n.startswith("_")]
    classes = []
    functions = []

    for name in public:
        obj = getattr(mod, name, None)
        if obj is None:
            continue
        if isinstance(obj, type):
            classes.append(name)
        elif callable(obj):
            functions.append(name)

    return public, classes, functions


def generate_hardened_test(module_path: str, classes: list, functions: list, public_symbols: list) -> str:
    """Generate a hardened test file with no skip-on-import patterns."""
    # Use direct import - if it fails, the test FAILS, not skips
    lines = []
    lines.append(f'"""Behavioral contract tests for {module_path}."""')
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("import importlib")
    lines.append("import pytest")
    lines.append("")
    lines.append(f'MODULE_PATH = "{module_path}"')
    lines.append("")
    lines.append("")
    lines.append("@pytest.fixture(scope=\"module\")")
    lines.append("def mod():")
    lines.append('    """Import the module under test. Fails hard if first-party import broken."""')
    lines.append("    return importlib.import_module(MODULE_PATH)")
    lines.append("")
    lines.append("")
    lines.append("def test_module_importable(mod):")
    lines.append('    """Module imports without errors."""')
    lines.append("    assert mod.__name__ == MODULE_PATH")
    lines.append("")

    # Public API test
    if public_symbols:
        lines.append("")
        lines.append("def test_module_exposes_public_api(mod):")
        lines.append('    """Module exposes expected public symbols."""')
        lines.append('    public = [n for n in dir(mod) if not n.startswith("_")]')
        lines.append("    assert len(public) >= 1, f\"{MODULE_PATH} must expose at least one public symbol\"")
        lines.append("")
    else:
        lines.append("")
        lines.append("def test_module_is_namespace_package(mod):")
        lines.append('    """Module is a valid namespace package (empty __init__)."""')
        lines.append('    public = [n for n in dir(mod) if not n.startswith("_")]')
        lines.append("    # Empty namespace packages are valid - just verify import succeeded")
        lines.append("    assert mod is not None")
        lines.append("")

    # Class instantiability tests
    for cls_name in classes[:8]:  # Cap at 8 to avoid bloat
        lines.append("")
        lines.append(f"def test_{cls_name.lower()}_is_instantiable(mod):")
        lines.append(f'    """{cls_name} is accessible and is a type."""')
        lines.append(f'    cls = getattr(mod, "{cls_name}", None)')
        lines.append(f'    assert cls is not None, "{cls_name} must be defined in {{MODULE_PATH}}"')
        lines.append(f"    assert isinstance(cls, type), \"{cls_name} must be a class\"")
        lines.append("")

    # Function callability tests
    for func_name in functions[:8]:  # Cap at 8
        safe_name = re.sub(r"[^a-zA-Z0-9_]", "_", func_name.lower())
        lines.append("")
        lines.append(f"def test_{safe_name}_is_callable(mod):")
        lines.append(f'    """{func_name} is accessible and callable."""')
        lines.append(f'    func = getattr(mod, "{func_name}", None)')
        lines.append(f'    assert func is not None, "{func_name} must be defined in {{MODULE_PATH}}"')
        lines.append(f'    assert callable(func), "{func_name} must be callable"')
        lines.append("")

    return "\n".join(lines) + "\n"


def is_enhanced_file_with_skip_pattern(filepath: Path) -> str | None:
    """Check if file is an enhanced test with skip-on-import pattern. Returns MODULE_PATH if so."""
    try:
        source = filepath.read_text("utf-8")
    except Exception:
        return None

    # Must have MODULE_PATH
    match = re.search(r'MODULE_PATH\s*=\s*["\']([^"\']+)["\']', source)
    if not match:
        return None

    module_path = match.group(1)

    # Must have the skip-on-import pattern
    if "pytest.skip(" not in source:
        return None

    # Must have try/except ImportError or try/except (ImportError, AttributeError)
    if "except ImportError" not in source and "except (ImportError" not in source:
        return None

    return module_path


def main():
    tests_dir = Path("tests")
    enhanced = 0
    skipped = 0
    failed = 0
    errors = []

    # Find all enhanced files with skip patterns
    candidates = []
    for p in sorted(tests_dir.rglob("test_*.py")):
        module_path = is_enhanced_file_with_skip_pattern(p)
        if module_path:
            candidates.append((p, module_path))

    print(f"Found {len(candidates)} enhanced files with skip-on-import patterns")

    for filepath, module_path in candidates:
        try:
            # Analyze the module
            public_symbols, classes, functions = analyze_module_api(module_path)

            # Generate hardened test
            content = generate_hardened_test(module_path, classes, functions, public_symbols)

            # Write
            filepath.write_text(content, encoding="utf-8")
            enhanced += 1

        except Exception as e:
            errors.append(f"{filepath}: {e}")
            failed += 1

    print(f"Enhanced: {enhanced}")
    print(f"Failed: {failed}")

    if errors:
        print("\nErrors:")
        for e in errors[:20]:
            print(f"  {e}")

    return enhanced, failed


if __name__ == "__main__":
    enhanced, failed = main()
    sys.exit(1 if failed > 0 and enhanced == 0 else 0)
