#!/usr/bin/env python3
"""
Audit Dashboard SSOT (Single Source of Truth) Flow
===================================================

This script audits the entire dashboard data flow to ensure strict SSOT compliance.

Dashboard Data Flow:
1. SOURCE: agent_discovery_full.json (generated by full_agent_discovery.py)
2. SSOT DEFINITIONS: scripts/dashboard_ssot_definitions.py
3. DATA GENERATION: scripts/regenerate_dashboard_data.py
4. OUTPUT: agentic_core/L6_observability/dashboards/data/dashboard_data.js
5. VALIDATION: scripts/test_dashboard_data_integrity.py

This audit verifies:
- All data sources are consistent
- No duplicate or conflicting definitions
- All calculations use SSOT functions
- Territory names are canonical
- Sort order is enforced
"""

import json
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent.parent.parent

print("\n" + "=" * 70)
print("DASHBOARD SSOT AUDIT")
print("=" * 70)

# ============================================================================
# AUDIT 1: Data Source Verification
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 1: Data Source Verification")
print("=" * 70)

discovery_file = project_root / "agent_discovery_full.json"
dashboard_data_file = (
    project_root / "agentic_core" / "L6_observability" / "dashboards" / "data" / "dashboard_data.js"
)
ssot_file = project_root / "agentic_core" / "L0_maintenance" / "scripts" / "dashboard_ssot_definitions.py"

files_exist = {
    "agent_discovery_full.json": discovery_file.exists(),
    "dashboard_data.js": dashboard_data_file.exists(),
    "dashboard_ssot_definitions.py": ssot_file.exists(),
}

for file, exists in files_exist.items():
    status = "✅" if exists else "❌"
    print(f"{status} {file}: {'EXISTS' if exists else 'MISSING'}")

if not all(files_exist.values()):
    print("\n❌ CRITICAL: Missing required files for SSOT flow")
    sys.exit(1)

# ============================================================================
# AUDIT 2: SSOT Definitions Consistency
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 2: SSOT Definitions Consistency")
print("=" * 70)

# Import SSOT definitions
# guardian: allow-global-mutation
sys.path.insert(0, str(project_root / "agentic_core" / "L0_maintenance" / "scripts"))
from dashboard_ssot_definitions import (
    COL_CANONICAL_INHERITANCE,
    COL_CODE_QUALITY,
    COL_COMPLEXITY_HEALTH,
    COL_DOCUMENTED,
    COL_HARDENED,
    COL_HEAL_CAP,
    COL_HEALTH,
    COL_INVOCATION,
    COL_SCHEMA_STRICTNESS,
    COL_TEST,
    COL_TYPED,
    FIELD_DOCUMENTED_PCT,
    FIELD_HAS_HEALING,
    FIELD_HAS_TESTS,
    FIELD_INVOCATION,
    FIELD_MCP_HARDENED,
    FIELD_PROPER_BASE_CLASS,
    FIELD_SCHEMA_STRICTNESS,
    FIELD_TYPED_PCT,
    calc_heal_cap_pct,
)

# Verify all column names are defined
required_columns = [
    COL_HEAL_CAP,
    COL_INVOCATION,
    COL_TEST,
    COL_HARDENED,
    COL_COMPLEXITY_HEALTH,
    COL_TYPED,
    COL_DOCUMENTED,
    COL_SCHEMA_STRICTNESS,
    COL_CANONICAL_INHERITANCE,
    COL_CODE_QUALITY,
    COL_HEALTH,
]

print("\n✅ SSOT Column Definitions:")
for col in required_columns:
    print(f"  - {col}")

# Verify all field names are defined
required_fields = [
    FIELD_HAS_HEALING,
    FIELD_INVOCATION,
    FIELD_HAS_TESTS,
    FIELD_MCP_HARDENED,
    FIELD_TYPED_PCT,
    FIELD_DOCUMENTED_PCT,
    FIELD_SCHEMA_STRICTNESS,
    FIELD_PROPER_BASE_CLASS,
]

print("\n✅ SSOT Field Definitions:")
for field in required_fields:
    print(f"  - {field}")

# Verify all calculation functions are defined
calculation_functions = [
    "calc_heal_cap",
    "calc_invocation_pct",
    "calc_test_pct",
    "calc_avg_cc",
    "calc_complexity_health",
    "calc_code_quality_score",
    "calc_health_score",
]

print("\n✅ SSOT Calculation Functions:")
for func_name in calculation_functions:
    print(f"  - {func_name}()")

# ============================================================================
# AUDIT 3: Territory Name Consistency
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 3: Territory Name Consistency")
print("=" * 70)

# Load discovery data
with open(discovery_file, encoding="utf-8") as f:
    discovery_data = json.load(f)

# Load dashboard data
content = dashboard_data_file.read_text(encoding="utf-8")
lines = [l for l in content.split("\n") if not l.strip().startswith("//")]
content = "\n".join(lines).replace("window.dashboardData = ", "").strip().rstrip(";")
dashboard_data = json.loads(content)

# Check for "Base Class" in discovery data (should be "Base Agent")
base_class_count = sum(1 for a in discovery_data if "Base Class" in a.get("territory", ""))
if base_class_count > 0:
    print(
        f"❌ SSOT VIOLATION: {base_class_count} agents with 'Base Class' in territory (should be 'Base Agent')",
    )
else:
    print("✅ No 'Base Class' territories in discovery data")

# Check for "Base Class" in dashboard data
dashboard_base_class = [r for r in dashboard_data if "Base Class" in r.get("Territory", "")]
if dashboard_base_class:
    print(f"❌ SSOT VIOLATION: {len(dashboard_base_class)} rows with 'Base Class' in dashboard data")
    for row in dashboard_base_class[:5]:
        print(f"  - {row['Territory']}")
else:
    print("✅ No 'Base Class' territories in dashboard data")

# Verify canonical territory names
canonical_territories = [
    "Sovereign Base Agent",
    "L6_Observability/Base Agent",
    "L5 Safety/Base Agent",
    "L4 State/Base Agent",
    "L3 Orchestration/Base Agent",
    "L2 Execution/Base Agent",
    "L1 Cognition/Base Agent",
    "L0 Maintenance/Base Agent",
]

dashboard_territories = [r["Territory"] for r in dashboard_data if r["Territory"] != "TOTAL"]
missing_canonical = [t for t in canonical_territories if t not in dashboard_territories]

if missing_canonical:
    print("\n❌ SSOT VIOLATION: Missing canonical territories:")
    for t in missing_canonical:
        print(f"  - {t}")
else:
    print("\n✅ All canonical Base Agent territories present")

# ============================================================================
# AUDIT 4: Calculation Consistency
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 4: Calculation Consistency")
print("=" * 70)

# Verify dashboard data uses SSOT calculations
# Sample a few rows and recalculate to verify
sample_rows = [r for r in dashboard_data if r["Territory"] != "TOTAL"][:3]

calculation_mismatches = []
for row in sample_rows:
    territory = row["Territory"]

    # Find agents for this territory
    territory_agents = [a for a in discovery_data if a.get("territory") == territory]

    if not territory_agents:
        continue

    # Recalculate using SSOT functions
    heal_cap_expected = calc_heal_cap_pct(territory_agents)
    heal_cap_actual = row.get("Heal Cap %", 0)

    if abs(heal_cap_expected - heal_cap_actual) > 0.1:
        calculation_mismatches.append(
            f"{territory}: Heal Cap % mismatch (expected {heal_cap_expected:.1f}, got {heal_cap_actual:.1f})",
        )

if calculation_mismatches:
    print("❌ SSOT VIOLATION: Calculation mismatches:")
    for mismatch in calculation_mismatches:
        print(f"  - {mismatch}")
else:
    print("✅ Sample calculations match SSOT functions")

# ============================================================================
# AUDIT 5: Sort Order Consistency
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 5: Sort Order Consistency")
print("=" * 70)

# Verify TOTAL is first
if dashboard_data[0]["Territory"] != "TOTAL":
    print(f"❌ SSOT VIOLATION: TOTAL row not first (found: {dashboard_data[0]['Territory']})")
else:
    print("✅ TOTAL row is first")

# Verify Base Agents come first for each layer
layer_prefixes = [
    "L6_Observability",
    "L5 Safety",
    "L4 State",
    "L3 Orchestration",
    "L2 Execution",
    "L1 Cognition",
    "L0 Maintenance",
]

sort_violations = []
for prefix in layer_prefixes:
    layer_rows = [
        (i, r["Territory"]) for i, r in enumerate(dashboard_data) if r["Territory"].startswith(prefix)
    ]

    if layer_rows:
        base_agent_name = f"{prefix}/Base Agent"
        base_agent_positions = [i for i, t in layer_rows if t == base_agent_name]

        if not base_agent_positions:
            sort_violations.append(f"{prefix}: No Base Agent found")
        elif base_agent_positions[0] != layer_rows[0][0]:
            sort_violations.append(
                f"{prefix}: Base Agent not first (position {base_agent_positions[0]}, should be {layer_rows[0][0]})",
            )

if sort_violations:
    print("❌ SSOT VIOLATION: Sort order violations:")
    for violation in sort_violations:
        print(f"  - {violation}")
else:
    print("✅ Base Agents are first for each layer")

# ============================================================================
# AUDIT 6: Data Flow Integrity
# ============================================================================
print("\n" + "=" * 70)
print("AUDIT 6: Data Flow Integrity")
print("=" * 70)

# Verify data flow: discovery → dashboard
discovery_agent_count = len(discovery_data)
dashboard_total_row = next((r for r in dashboard_data if r["Territory"] == "TOTAL"), None)

if dashboard_total_row:
    dashboard_agent_count = dashboard_total_row.get("Total", 0)

    if discovery_agent_count == dashboard_agent_count:
        print(f"✅ Agent count matches: {discovery_agent_count} agents")
    else:
        print("❌ SSOT VIOLATION: Agent count mismatch")
        print(f"  Discovery: {discovery_agent_count} agents")
        print(f"  Dashboard: {dashboard_agent_count} agents")
else:
    print("❌ SSOT VIOLATION: TOTAL row not found in dashboard data")

# ============================================================================
# FINAL RESULT
# ============================================================================
print("\n" + "=" * 70)
print("SSOT AUDIT SUMMARY")
print("=" * 70)

all_checks_passed = (
    all(files_exist.values())
    and base_class_count == 0
    and len(dashboard_base_class) == 0
    and len(missing_canonical) == 0
    and len(calculation_mismatches) == 0
    and len(sort_violations) == 0
    and dashboard_data[0]["Territory"] == "TOTAL"
)

if all_checks_passed:
    print("\n✅ ALL SSOT AUDITS PASSED")
    print("\nDashboard data flow maintains strict SSOT:")
    print("  1. ✅ All required files exist")
    print("  2. ✅ SSOT definitions are consistent")
    print("  3. ✅ Territory names are canonical")
    print("  4. ✅ Calculations use SSOT functions")
    print("  5. ✅ Sort order is enforced")
    print("  6. ✅ Data flow integrity maintained")
    print("\n✅ SSOT COMPLIANCE VERIFIED")
    sys.exit(0)
else:
    print("\n❌ SSOT VIOLATIONS DETECTED")
    print("\nFix the violations above to ensure strict SSOT compliance.")
    print("\n❌ SSOT COMPLIANCE FAILED")
    sys.exit(1)
