"""W3 of plan apps-fort-knox-parity-c5d9a3 \u2014 Apps_e2e Fort Knox Sign-off Compiler.

HOSTILE VERIFIER. Distrusts:
  * the W2 emitter's summary line
  * cached reports
  * previous statuses
  * its own prior output
  * any assertion not produced by an allowlisted command

The ONLY authoritative inputs are:
  data/certification/apps_e2e_requirements_source.json    (what must be proven)
  data/certification/apps_evidence_assertions.jsonl       (atomic proof assertions)
  referenced on-disk artifacts                       (re-opened, re-hashed every run)

A requirement is SIGNED_OFF only when every required control has at least
one valid PASS assertion that:
  - is schema-valid
  - is deterministically identified
  - carries exact req_id, exact control, row_specific=true
  - references an artifact that exists on disk with matching sha256
  - references a pointer that resolves inside the artifact
  - proves row-specificity per apps_e2e's app-keyed semantics (see below)
  - was generated by a command on the row's allowed_verifier_commands list
  - uses an artifact_class on the row's allowed_artifact_classes list
  - was generated within the row's freshness_hours window

Row-specificity for apps_e2e (diverges from agentic_core):
  The authoritative verifier artifact (verifier_report.json) is keyed by
  app_name, not by req_id. Claiming "the artifact contains the req_id"
  would be a lie. Instead:
    - canary (APPS-REQ-001, compiler-self-emitted): req_id literal in the
      catalog artifact is the proof;
    - matrix-governance (APPS-REQ-033): the matrix IS the authoritative
      artifact for matrix_integrity; pointer resolution on the matrix
      is the proof;
    - per-app rows (owner_app set): assertion.app_name == row.owner_app
      AND the pointer-resolved payload contains the app_name is the proof;
    - cross-cutting rows iterating over certified apps: assertion.app_name
      is set and the pointer-resolved payload contains that app_name.

Positive-control canary (APPS-REQ-001):
  The compiler SELF-EMITS a PASS assertion for (APPS-REQ-001,
  catalog_self_consistency) iff every catalog invariant holds
  (schema-valid, no duplicate req_ids, every depends_on resolves, exactly
  one is_positive_control=true). Any catalog-invariant failure prevents
  emission, which flips the canary to BLOCKED, which fails the run.

Trust levels (in ascending order):
  FAILED                       \u2014 compiler crashed or report schema-invalid
  DEVELOPMENT_PROOF            \u2014 one or more non-waiver rows still open
  INTEGRITY_PROOF              \u2014 every non-waiver row SIGNED_OFF, Merkle verified, no signature yet
  SIGNED_OFF_WITH_WAIVERS      \u2014 same as INTEGRITY_PROOF plus at least one active waiver row (expected steady state while apps_qna + apps_underwriting_ai remain waivers)
  SIGNED_PROOF                 \u2014 signature verified (W5 will upgrade this)
  FINAL_SIGNED_CERTIFICATION   \u2014 external trust authority (out of repo scope)

Outputs (all under artifacts/certification/apps_e2e/):
  apps_e2e_signoff_report.json
  apps_e2e_signoff_report.sha256
  apps_e2e_signoff_report.merkle.json
"""
from __future__ import annotations

import argparse
import collections
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from jsonschema import Draft202012Validator
except ImportError:  # pragma: no cover
    print("FATAL: jsonschema is required (pip install jsonschema)", file=sys.stderr)
    sys.exit(2)

try:
    from .cert_paths import (
        APPS_ASSERTION_SCHEMA,
        APPS_ASSERTIONS_PATH,
        APPS_REPORT_SCHEMA,
        APPS_REQS_PATH,
        APPS_REQS_SCHEMA,
        CERT_ARTIFACTS_DIR,
        REPO_ROOT,
    )
except ImportError:  # pragma: no cover - direct script execution
    from cert_paths import (
        APPS_ASSERTION_SCHEMA,
        APPS_ASSERTIONS_PATH,
        APPS_REPORT_SCHEMA,
        APPS_REQS_PATH,
        APPS_REQS_SCHEMA,
        CERT_ARTIFACTS_DIR,
        REPO_ROOT,
    )

COMPILER_VERSION = "apps_e2e_fortknox-v1.0"
SCHEMA_VERSION = "apps_e2e_fortknox-v1"
COMPILER_PATH_REL = "tools/cert/compile_apps_e2e_signoff.py"

REQS_PATH = APPS_REQS_PATH
ASSERTIONS_PATH = APPS_ASSERTIONS_PATH
REQS_SCHEMA = APPS_REQS_SCHEMA
ASSERTION_SCHEMA = APPS_ASSERTION_SCHEMA
REPORT_SCHEMA = APPS_REPORT_SCHEMA

OUTPUT_DIR = CERT_ARTIFACTS_DIR / "apps_e2e"
REPORT_PATH = OUTPUT_DIR / "apps_e2e_signoff_report.json"
SHA256_PATH = OUTPUT_DIR / "apps_e2e_signoff_report.sha256"
MERKLE_PATH = OUTPUT_DIR / "apps_e2e_signoff_report.merkle.json"

# Claim types that are always SIGNED_OFF_WITH_WAIVER (never plain SIGNED_OFF).
WAIVER_CLAIM_TYPES = {"APPS_WAIVER"}


# =============================================================================
# Hash + pointer utilities
# =============================================================================

def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_json_canonical(obj: Any) -> str:
    return sha256_bytes(
        json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")
    )


class _MissingSentinel:
    def __repr__(self) -> str:
        return "<_MISSING>"


_MISSING = _MissingSentinel()


def resolve_json_pointer(doc: Any, pointer: str) -> Any:
    """RFC 6901 pointer. Returns _MISSING on miss."""
    if pointer in ("", "/"):
        return doc
    if not pointer.startswith("/"):
        pointer = "/" + pointer
    parts = pointer.split("/")[1:]
    cur = doc
    for p in parts:
        p = p.replace("~1", "/").replace("~0", "~")
        if isinstance(cur, list):
            try:
                cur = cur[int(p)]
            except (ValueError, IndexError):
                return _MISSING
        elif isinstance(cur, dict):
            if p not in cur:
                return _MISSING
            cur = cur[p]
        else:
            return _MISSING
    return cur


# =============================================================================
# Schema + time helpers
# =============================================================================

def _load_schema(p: Path) -> Draft202012Validator:
    return Draft202012Validator(json.loads(p.read_text(encoding="utf-8")))


def _iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def _git_state() -> tuple[str, bool]:
    try:
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
                              capture_output=True, text=True, timeout=15)
        status = subprocess.run(["git", "status", "--porcelain"], cwd=REPO_ROOT,
                                capture_output=True, text=True, timeout=15)
        commit = (head.stdout or "").strip() or "unknown"
        dirty = bool((status.stdout or "").strip())
        return (commit, dirty)
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return ("unknown", False)


def _freshness_ok(generated_at_utc: str, freshness_hours: int) -> bool:
    try:
        gen = datetime.fromisoformat(generated_at_utc.replace("Z", "+00:00"))
    except ValueError:
        return False
    now = datetime.now(timezone.utc)
    return (now - gen).total_seconds() <= freshness_hours * 3600


# =============================================================================
# Catalog self-consistency \u2014 the canary's truth condition
# =============================================================================

class CompileError(Exception):
    pass


def check_catalog_self_consistency(catalog: dict[str, Any]) -> list[str]:
    """Return a list of catalog-invariant violations. Empty list == canary PASS.

    The compiler will emit a PASS assertion for APPS-REQ-001 iff this returns [].
    """
    violations: list[str] = []
    reqs = catalog.get("requirements", [])
    # 1. No duplicate req_ids.
    ids = [r["req_id"] for r in reqs]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        violations.append(f"duplicate req_ids: {sorted(dupes)}")
    # 2. Every depends_on resolves.
    known = set(ids)
    for r in reqs:
        for dep in r.get("depends_on_req_ids", []):
            if dep not in known:
                violations.append(f"{r['req_id']} depends on unknown {dep}")
    # 3. No self-dependency.
    for r in reqs:
        if r["req_id"] in r.get("depends_on_req_ids", []):
            violations.append(f"{r['req_id']} depends on itself")
    # 4. Exactly one is_positive_control=true row.
    canaries = [r for r in reqs if r.get("is_positive_control")]
    if len(canaries) != 1:
        violations.append(
            f"expected exactly 1 positive_control row; got {len(canaries)}"
        )
    elif canaries[0]["req_id"] != catalog.get("positive_control_req_id"):
        violations.append(
            f"positive_control_req_id header mismatch: "
            f"header={catalog.get('positive_control_req_id')!r}, "
            f"row={canaries[0]['req_id']!r}"
        )
    # 5. requirement_count lockstep check (W1.P1 of apps-fortknox-evidence-repackage)
    declared_count = catalog.get("requirement_count")
    actual_count = len(reqs)
    if declared_count != actual_count:
        violations.append(
            f"requirement_count mismatch: declared={declared_count}, "
            f"actual={actual_count} (len(requirements))"
        )
    return violations


# =============================================================================
# Row-specificity guard (app-keyed semantics)
# =============================================================================

def _row_specificity_ok(
    assertion: dict[str, Any],
    req: dict[str, Any],
    parsed_artifact: Any,
) -> tuple[bool, str]:
    """Enforce apps_e2e's app-keyed row-specificity guard.

    Returns (ok, reason). See module docstring for the four rules.
    """
    req_id = req["req_id"]
    claim_type = req["claim_type"]
    owner_app = req.get("owner_app")
    pointer = assertion["artifact_payload_pointer"]
    app_name = assertion.get("app_name")

    # Canary: req_id literal in the catalog artifact.
    if claim_type == "APPS_POSITIVE_CONTROL":
        # Compiler-self-emitted; accept unconditionally if we got this far.
        # Row_specificity is proven by the catalog-self-consistency check.
        return (True, "")

    # Matrix governance: pointer resolved is the matrix root.
    if claim_type == "APPS_MATRIX_GOVERNANCE":
        if parsed_artifact is None:
            return (False, "matrix artifact not JSON-parseable")
        val = resolve_json_pointer(parsed_artifact, pointer)
        if isinstance(val, _MissingSentinel):
            return (False, f"pointer {pointer!r} did not resolve in matrix")
        return (True, "")

    # Per-app rows (owner_app set).
    if owner_app is not None:
        if app_name != owner_app:
            return (False, f"assertion.app_name={app_name!r} does not match row.owner_app={owner_app!r}")
        if parsed_artifact is not None:
            val = resolve_json_pointer(parsed_artifact, pointer)
            if isinstance(val, _MissingSentinel):
                return (False, f"pointer {pointer!r} did not resolve")
            snippet = json.dumps(val, sort_keys=True) if not isinstance(val, str) else val
            if owner_app not in snippet:
                return (False, f"app_name {owner_app!r} not in payload at {pointer!r}")
        return (True, "")

    # Cross-cutting over certified apps.
    if app_name is None:
        return (False, f"cross-cutting row {req_id} requires assertion.app_name to be set")
    if parsed_artifact is not None:
        val = resolve_json_pointer(parsed_artifact, pointer)
        if isinstance(val, _MissingSentinel):
            return (False, f"pointer {pointer!r} did not resolve")
        snippet = json.dumps(val, sort_keys=True) if not isinstance(val, str) else val
        if app_name not in snippet:
            return (False, f"app_name {app_name!r} not in payload at {pointer!r}")
    return (True, "")


# =============================================================================
# Assertion validator
# =============================================================================

def validate_assertion(
    assertion: dict[str, Any],
    req: dict[str, Any],
    artifact_cache: dict[str, tuple[str, Any]],
) -> tuple[bool, str]:
    """Hostile per-assertion validator. Returns (is_valid_PASS, reason)."""
    if assertion["assertion_result"] != "PASS":
        return (False, f"assertion_result={assertion['assertion_result']}")
    allowed_ctrls = set(req.get("required_controls", [])) | set(
        req.get("supplemental_controls", [])
    )
    if assertion["control"] not in allowed_ctrls:
        return (False, f"control {assertion['control']!r} not in required/supplemental")
    if assertion["generated_by_command"] not in req.get("allowed_verifier_commands", []):
        return (
            False,
            f"generated_by_command {assertion['generated_by_command']!r} "
            f"not in allowed_verifier_commands",
        )
    if assertion["artifact_class"] not in req.get("allowed_artifact_classes", []):
        return (
            False,
            f"artifact_class {assertion['artifact_class']!r} "
            f"not in allowed_artifact_classes",
        )
    if not assertion.get("row_specific"):
        return (False, "row_specific=false")
    if not assertion.get("artifact_contains_control"):
        return (False, "artifact_contains_control=false")
    if not _freshness_ok(
        assertion["generated_at_utc"], int(assertion.get("freshness_hours", 168))
    ):
        return (
            False,
            f"assertion stale (generated {assertion['generated_at_utc']}, "
            f"window {assertion['freshness_hours']}h)",
        )
    # Artifact exists + re-hash
    art_rel = assertion["artifact_path"]
    art_abs = REPO_ROOT / art_rel
    if not art_abs.exists():
        return (False, f"artifact missing on disk: {art_rel}")
    cached = artifact_cache.get(art_rel)
    if cached is None:
        actual_sha = sha256_file(art_abs)
        parsed: Any = None
        try:
            parsed = json.loads(art_abs.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            parsed = None
        artifact_cache[art_rel] = (actual_sha, parsed)
    actual_sha, parsed = artifact_cache[art_rel]
    if actual_sha != assertion["artifact_sha256"]:
        return (
            False,
            f"artifact sha256 mismatch: expected {assertion['artifact_sha256'][:12]}, "
            f"got {actual_sha[:12]}",
        )
    # Row-specificity (app-keyed for apps_e2e)
    ok, reason = _row_specificity_ok(assertion, req, parsed)
    if not ok:
        return (False, reason)
    return (True, "")


# =============================================================================
# Canary self-assertion
# =============================================================================

def _make_canary_assertion(
    catalog_sha: str, now_iso: str, reqs_path: Path
) -> dict[str, Any]:
    """Compiler-self-emitted PASS assertion for APPS-REQ-001.

    Shape mirrors the emitter's output so the standard validator can chew it.
    artifact_path is derived from reqs_path relative to REPO_ROOT so tests
    with tmp-path workspaces work correctly.
    """
    req_id = "APPS-REQ-001"
    control = "catalog_self_consistency"
    pointer = "/positive_control_req_id"
    try:
        artifact_rel = reqs_path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        artifact_rel = reqs_path.name
    h = hashlib.sha256(
        f"{req_id}|{control}|{catalog_sha}|{pointer}".encode("utf-8")
    ).hexdigest()
    return {
        "assertion_id": f"ASRT-{h[:40]}",
        "req_id": req_id,
        "control": control,
        "assertion_result": "PASS",
        "assertion_class": "APPS_POSITIVE_CONTROL_ASSERTION",
        "generated_by_command": COMPILER_PATH_REL,
        "verifier_exit_code": 0,
        "verifier_version": COMPILER_VERSION,
        "generated_at_utc": now_iso,
        "artifact_path": artifact_rel,
        "artifact_sha256": catalog_sha,
        "artifact_class": "APPS_CATALOG_SELF_REPORT",
        "artifact_payload_pointer": pointer,
        "artifact_contains_req_id": True,
        "artifact_contains_control": True,
        "row_specific": True,
        "freshness_hours": 168,
        "proof_payload": {
            "extracted_value": "PASS",
            "expected_value": "PASS",
            "match": True,
            "notes": "Compiler self-emitted canary. Catalog invariants passed.",
        },
        "app_name": None,
    }


# =============================================================================
# Main compile
# =============================================================================

def compile_report(
    reqs_path: Path = REQS_PATH,
    assertions_path: Path = ASSERTIONS_PATH,
) -> dict[str, Any]:
    if not reqs_path.exists():
        raise CompileError(f"catalog missing at {reqs_path}")
    if not assertions_path.exists():
        raise CompileError(f"assertions jsonl missing at {assertions_path}")

    # Load + schema-validate catalog.
    catalog = json.loads(reqs_path.read_text(encoding="utf-8"))
    reqs_schema = _load_schema(REQS_SCHEMA)
    errors = sorted(reqs_schema.iter_errors(catalog), key=lambda e: list(e.path))
    if errors:
        msgs = "; ".join(e.message for e in errors[:5])
        raise CompileError(f"catalog fails schema: {msgs}")
    reqs = catalog["requirements"]

    # Canary invariant check \u2014 compiler health proof.
    canary_violations = check_catalog_self_consistency(catalog)

    # Load + schema-validate every assertion.
    assertion_schema = _load_schema(ASSERTION_SCHEMA)
    assertions: list[dict[str, Any]] = []
    seen_aids: set[str] = set()
    schema_violations: list[tuple[int, str]] = []
    req_ids = {r["req_id"] for r in reqs}

    with assertions_path.open("r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                schema_violations.append((lineno, f"unparseable JSON: {e}"))
                continue
            vs = list(assertion_schema.iter_errors(obj))
            if vs:
                schema_violations.append((lineno, f"schema: {vs[0].message}"))
                continue
            if obj["assertion_id"] in seen_aids:
                raise CompileError(f"duplicate assertion_id: {obj['assertion_id']}")
            seen_aids.add(obj["assertion_id"])
            if obj["req_id"] not in req_ids:
                schema_violations.append(
                    (lineno, f"assertion for unknown req_id {obj['req_id']}")
                )
                continue
            assertions.append(obj)

    # Inject compiler-self-emitted canary assertion iff invariants hold.
    now_iso = _iso_now()
    catalog_sha = sha256_file(reqs_path)
    if not canary_violations:
        canary_assertion = _make_canary_assertion(catalog_sha, now_iso, reqs_path)
        if canary_assertion["assertion_id"] not in seen_aids:
            assertions.append(canary_assertion)
            seen_aids.add(canary_assertion["assertion_id"])

    # Index.
    by_req_ctrl: dict[tuple[str, str], list[dict[str, Any]]] = {}
    for a in assertions:
        by_req_ctrl.setdefault((a["req_id"], a["control"]), []).append(a)

    # Evaluate each requirement.
    artifact_cache: dict[str, tuple[str, Any]] = {}
    rows: list[dict[str, Any]] = []

    for req in reqs:
        rid = req["req_id"]
        required = req.get("required_controls", [])
        is_waiver = req["claim_type"] in WAIVER_CLAIM_TYPES
        control_evals: list[dict[str, Any]] = []
        missing_any = False
        had_any_evidence = False

        for ctrl in required:
            candidates = by_req_ctrl.get((rid, ctrl), [])
            had_any_evidence = had_any_evidence or bool(candidates)

            if not candidates:
                missing_any = True
                control_evals.append(
                    {
                        "name": ctrl,
                        "passed": False,
                        "reason": "no assertion for this control",
                        "assertion_id": None,
                        "artifact_path": None,
                        "artifact_sha256": None,
                    }
                )
                continue

            chosen = None
            last_reason = ""
            for a in candidates:
                ok, reason = validate_assertion(a, req, artifact_cache)
                if ok:
                    chosen = a
                    break
                last_reason = reason

            if chosen is not None:
                control_evals.append(
                    {
                        "name": ctrl,
                        "passed": True,
                        "reason": None,
                        "assertion_id": chosen["assertion_id"],
                        "artifact_path": chosen["artifact_path"],
                        "artifact_sha256": chosen["artifact_sha256"],
                    }
                )
            else:
                missing_any = True
                control_evals.append(
                    {
                        "name": ctrl,
                        "passed": False,
                        "reason": last_reason or "no valid PASS assertion",
                        "assertion_id": candidates[0]["assertion_id"],
                        "artifact_path": candidates[0]["artifact_path"],
                        "artifact_sha256": candidates[0]["artifact_sha256"],
                    }
                )

        # Row status.
        if not missing_any and control_evals:
            status = "SIGNED_OFF_WITH_WAIVER" if is_waiver else "SIGNED_OFF"
            blocking_gap = None
        elif had_any_evidence:
            status = "BLOCKED"
            first_failing = next((c for c in control_evals if not c["passed"]), None)
            blocking_gap = (
                f"{first_failing['name']}: {first_failing['reason']}"
                if first_failing else "unknown"
            )
        else:
            status = "NOT_VERIFIED"
            blocking_gap = "no atomic assertion provided for required controls"

        assertion_ids = sorted({c["assertion_id"] for c in control_evals if c["assertion_id"]})
        row = {
            "req_id": rid,
            "title": req.get("title", ""),
            "claim_type": req.get("claim_type", ""),
            "priority": req.get("priority", ""),
            "requirement_group": req.get("requirement_group", ""),
            "is_final_hundred_percent_row": bool(req.get("is_final_hundred_percent_row", False)),
            "is_positive_control": bool(req.get("is_positive_control", False)),
            "owner_app": req.get("owner_app"),
            "depends_on_req_ids": list(req.get("depends_on_req_ids", [])),
            "required_controls": list(required),
            "computed_status": status,
            "blocking_gap": blocking_gap,
            "controls": control_evals,
            "assertion_ids": assertion_ids,
            "row_evidence_sha256": "",
            "row_digest": "",
            "evaluated_at_utc": now_iso,
        }
        rows.append(row)

    # depends_on_req_ids gate \u2014 block any row whose dep is not SIGNED_OFF(_WITH_WAIVER).
    def _is_ok(status: str) -> bool:
        return status in ("SIGNED_OFF", "SIGNED_OFF_WITH_WAIVER")

    status_by_id = {r["req_id"]: r["computed_status"] for r in rows}
    for row in rows:
        if not _is_ok(row["computed_status"]):
            continue
        for dep in row["depends_on_req_ids"]:
            if not _is_ok(status_by_id.get(dep, "MISSING")):
                row["computed_status"] = "BLOCKED"
                row["blocking_gap"] = (
                    f"depends_on {dep} (status={status_by_id.get(dep, 'MISSING')})"
                )
                break
    # Refresh status_by_id after deps pass.
    status_by_id = {r["req_id"]: r["computed_status"] for r in rows}

    # Per-row digests (run-independent).
    EXCLUDE = {"evaluated_at_utc", "row_digest", "row_evidence_sha256"}
    for row in rows:
        evidence_input = {
            "req_id": row["req_id"],
            "status": row["computed_status"],
            "blocking_gap": row["blocking_gap"],
            "controls": row["controls"],
            "required_controls": row["required_controls"],
            "depends_on_req_ids": row["depends_on_req_ids"],
        }
        row["row_evidence_sha256"] = sha256_json_canonical(evidence_input)
        digest_input = {k: v for k, v in row.items() if k not in EXCLUDE}
        row["row_digest"] = sha256_json_canonical(digest_input)

    # Summary.
    total = len(rows)
    signed_off = sum(1 for r in rows if r["computed_status"] == "SIGNED_OFF")
    signed_off_waiver = sum(1 for r in rows if r["computed_status"] == "SIGNED_OFF_WITH_WAIVER")
    blocked = sum(1 for r in rows if r["computed_status"] == "BLOCKED")
    not_verified = sum(1 for r in rows if r["computed_status"] == "NOT_VERIFIED")

    by_claim_type: dict[str, dict[str, int]] = collections.defaultdict(
        lambda: {"total": 0, "signed_off": 0, "signed_off_with_waiver": 0, "blocked": 0, "not_verified": 0}
    )
    for row in rows:
        ct = row["claim_type"] or "UNKNOWN"
        by_claim_type[ct]["total"] += 1
        status = row["computed_status"]
        if status == "SIGNED_OFF":
            by_claim_type[ct]["signed_off"] += 1
        elif status == "SIGNED_OFF_WITH_WAIVER":
            by_claim_type[ct]["signed_off_with_waiver"] += 1
        elif status == "BLOCKED":
            by_claim_type[ct]["blocked"] += 1
        else:
            by_claim_type[ct]["not_verified"] += 1

    canary_row = next((r for r in rows if r["is_positive_control"]), None)
    canary_status = (canary_row or {}).get("computed_status", "MISSING")

    assertions_sha = sha256_file(assertions_path)
    row_digest_all = sha256_json_canonical(
        [r["row_digest"] for r in sorted(rows, key=lambda x: x["req_id"])]
    )
    evidence_digest_all = sha256_json_canonical(
        [r["row_evidence_sha256"] for r in sorted(rows, key=lambda x: x["req_id"])]
    )
    git_commit, git_dirty = _git_state()

    percent = round(
        100.0 * (signed_off + signed_off_waiver) / max(1, total), 1
    )

    report: dict[str, Any] = {
        "schema_version": SCHEMA_VERSION,
        "compiler_version": COMPILER_VERSION,
        "compiler_path": COMPILER_PATH_REL,
        "compiler_sha256": sha256_file(Path(__file__)),
        "run_timestamp_utc": now_iso,
        "source_repo_root": str(REPO_ROOT).replace("\\", "/"),
        "git_commit": git_commit,
        "git_dirty": git_dirty,
        "requirements_source_sha256": catalog_sha,
        "evidence_assertions_sha256": assertions_sha,
        "row_digest": row_digest_all,
        "evidence_digest": evidence_digest_all,
        "rows": sorted(rows, key=lambda r: r["req_id"]),
        "summary": {
            "total": total,
            "signed_off": signed_off,
            "signed_off_with_waiver": signed_off_waiver,
            "blocked": blocked,
            "not_verified": not_verified,
            "percent_signed_off": percent,
            "by_claim_type": dict(by_claim_type),
            "canary_status": canary_status,
        },
        "positive_control_status": "PASS" if canary_status in ("SIGNED_OFF", "SIGNED_OFF_WITH_WAIVER") else "FAIL",
        "trust_level": "DEVELOPMENT_PROOF",
    }

    # Schema validation.
    report_schema = _load_schema(REPORT_SCHEMA)
    report_errs = list(report_schema.iter_errors(report))
    if report_errs:
        report["trust_level"] = "FAILED"
        report["schema_errors"] = [str(e.message) for e in report_errs[:10]]
        return report

    # Trust level (pre-signature).
    all_ok_or_waiver = (blocked + not_verified) == 0 and total > 0
    if not all_ok_or_waiver:
        report["trust_level"] = "DEVELOPMENT_PROOF"
    elif signed_off_waiver > 0:
        report["trust_level"] = "SIGNED_OFF_WITH_WAIVERS"
    else:
        report["trust_level"] = "INTEGRITY_PROOF"
    # W5 will upgrade to SIGNED_PROOF after signature verification.

    return report


# =============================================================================
# Merkle
# =============================================================================

def build_merkle(rows: list[dict[str, Any]]) -> dict[str, Any]:
    sorted_rows = sorted(rows, key=lambda r: r["req_id"])
    leaves = [{"req_id": r["req_id"], "leaf_hash": r["row_digest"]} for r in sorted_rows]

    def _pair(a: str, b: str) -> str:
        return sha256_bytes(bytes.fromhex(a) + bytes.fromhex(b))

    level = [L["leaf_hash"] for L in leaves]
    if not level:
        root = ""
    else:
        while len(level) > 1:
            if len(level) % 2 == 1:
                level.append(level[-1])
            level = [_pair(level[i], level[i + 1]) for i in range(0, len(level), 2)]
        root = level[0]

    return {
        "root": root,
        "leaf_count": len(leaves),
        "leaves": leaves,
        "computed_at_utc": _iso_now(),
        "algorithm": "sha256 pairwise, odd-node duplication",
        "schema_version": SCHEMA_VERSION,
    }


# =============================================================================
# Main
# =============================================================================

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out-dir", type=Path, default=OUTPUT_DIR)
    parser.add_argument("--reqs", type=Path, default=REQS_PATH)
    parser.add_argument("--assertions", type=Path, default=ASSERTIONS_PATH)
    parser.add_argument("--quiet", action="store_true")
    args = parser.parse_args(argv)

    try:
        report = compile_report(args.reqs, args.assertions)
    except CompileError as e:
        print(f"FATAL: {e}", file=sys.stderr)
        return 2

    args.out_dir.mkdir(parents=True, exist_ok=True)
    report_path = args.out_dir / REPORT_PATH.name
    sha_path = args.out_dir / SHA256_PATH.name
    merkle_path = args.out_dir / MERKLE_PATH.name

    report_path.write_text(
        json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    report_sha = sha256_file(report_path)
    sha_path.write_text(f"{report_sha}  {report_path.name}\n", encoding="utf-8")

    merkle = build_merkle(report["rows"])
    merkle_path.write_text(
        json.dumps(merkle, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    s = report["summary"]
    if not args.quiet:
        print(
            f"[compile_apps_e2e_signoff] {s['total']} reqs; "
            f"signed_off={s['signed_off']} with_waiver={s['signed_off_with_waiver']} "
            f"blocked={s['blocked']} not_verified={s['not_verified']}"
        )
        print(f"  trust_level:        {report['trust_level']}")
        print(f"  positive_control:   {report['positive_control_status']}")
        print(f"  merkle root:        {merkle['root']}")
        print(f"  report sha256:      {report_sha}")

    return 0 if report["trust_level"] != "FAILED" else 1


if __name__ == "__main__":
    sys.exit(main())
