"""Fort Knox v2 — Runtime Certification Requirement Sign-off Compiler.

HOSTILE VERIFIER. This script distrusts:
  - spreadsheets
  - cached reports
  - previous statuses
  - summary counts
  - manifests
  - verifier output that was not explicitly asserted as row-specific
  - manually-written assertions
  - its own prior output

The ONLY authoritative inputs are:
  data/certification/requirements_source.json       (what must be proven)
  data/certification/evidence_assertions.jsonl      (atomic proof assertions)
  referenced on-disk artifacts                 (re-opened, re-hashed every run)

A requirement is SIGNED_OFF only when every required control has at least
one valid PASS assertion that:
  * is schema-valid;
  * is deterministically identified;
  * carries exact req_id, exact control, row_specific=true;
  * references an artifact that exists on disk with matching sha256;
  * references an artifact_payload_pointer that resolves inside the
    artifact and contains the req_id literally;
  * was generated by a command on the req's allowed_verifier_commands list;
  * uses an artifact_class on the req's allowed_artifact_classes list;
  * was produced by a verifier whose exit_code matches the control's
    expected-exit contract;
  * was generated within the req's freshness_hours window.

A final-100% row is downgraded to BLOCKED while any non-final row is not
SIGNED_OFF.

Trust levels:
  DEVELOPMENT_PROOF    — some rows still open, or signature absent
  INTEGRITY_PROOF      — all rows SIGNED_OFF, Merkle verified, signature absent
  SIGNED_PROOF         — all rows SIGNED_OFF, signature verified, bundle not verified
  FINAL_SIGNED_CERTIFICATION — all four gates pass

Outputs (all under artifacts/certification/):
  final_requirement_signoff_report.json
  final_requirement_signoff_report.sha256
  final_requirement_signoff_report.merkle.json
  final_requirement_signoff_report.signature.json
"""
from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

try:
    from jsonschema import Draft202012Validator
except ImportError:  # pragma: no cover
    print("FATAL: jsonschema is required (pip install jsonschema)", file=sys.stderr)
    sys.exit(2)

from cert_paths import (
    ASSERTION_SCHEMA,
    ASSERTIONS_PATH,
    CERT_ARTIFACTS_DIR,
    REPORT_SCHEMA,
    REQS_PATH,
    REQS_SCHEMA,
    REPO_ROOT,
)

COMPILER_VERSION = "fortknox-v2.0"
SCHEMA_VERSION = "fortknox-v2"

OUTPUT_DIR = CERT_ARTIFACTS_DIR
REPORT_PATH = OUTPUT_DIR / "final_requirement_signoff_report.json"
SHA256_PATH = OUTPUT_DIR / "final_requirement_signoff_report.sha256"
MERKLE_PATH = OUTPUT_DIR / "final_requirement_signoff_report.merkle.json"
SIGNATURE_PATH = OUTPUT_DIR / "final_requirement_signoff_report.signature.json"


# ===========================================================================
# Hash helpers
# ===========================================================================

def sha256_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def sha256_file(p: Path) -> str:
    h = hashlib.sha256()
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def sha256_json_canonical(obj: Any) -> str:
    """Deterministic canonical JSON hash."""
    return sha256_bytes(json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8"))


# ===========================================================================
# JSON Pointer (RFC 6901) resolver
# ===========================================================================

def resolve_json_pointer(doc: Any, pointer: str) -> Any:
    """Resolve an RFC 6901 JSON pointer. Returns sentinel _MISSING on miss."""
    if pointer in ("", "/"):
        return doc
    if not pointer.startswith("/"):
        pointer = "/" + pointer
    parts = pointer.split("/")[1:]
    cur = doc
    for p in parts:
        p = p.replace("~1", "/").replace("~0", "~")
        if isinstance(cur, list):
            try:
                cur = cur[int(p)]
            except (ValueError, IndexError):
                return _MISSING
        elif isinstance(cur, dict):
            if p not in cur:
                return _MISSING
            cur = cur[p]
        else:
            return _MISSING
    return cur


class _MissingSentinel:
    def __repr__(self):
        return "<_MISSING>"


_MISSING = _MissingSentinel()


# ===========================================================================
# Schema validation
# ===========================================================================

def _load_schema(p: Path) -> Draft202012Validator:
    return Draft202012Validator(json.loads(p.read_text(encoding="utf-8")))


def _iso_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")


def _git_state() -> tuple[str, bool]:
    try:
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
                              capture_output=True, text=True, timeout=15)
        status = subprocess.run(["git", "status", "--porcelain"], cwd=REPO_ROOT,
                                capture_output=True, text=True, timeout=15)
        commit = head.stdout.strip() or "unknown"
        dirty = bool(status.stdout.strip())
        return (commit, dirty)
    except (subprocess.TimeoutExpired, FileNotFoundError, OSError):
        return ("unknown", False)


# ===========================================================================
# Control exit-code expectations
# ===========================================================================

# Controls where the verifier MUST have exited 0 for the assertion to be
# considered a PASS. Other controls may legitimately come from verifiers
# with non-zero exits (e.g., negative_controls where a failing subsystem
# IS the proof).
EXIT_ZERO_REQUIRED_CONTROLS = {
    "verifier_exit_zero",
    "ci_gate",
    "verifier_pass",
}


# ===========================================================================
# Compiler
# ===========================================================================

class CompileError(Exception):
    pass


def _freshness_ok(generated_at_utc: str, freshness_hours: int) -> bool:
    try:
        gen = datetime.fromisoformat(generated_at_utc.replace("Z", "+00:00"))
    except ValueError:
        return False
    now = datetime.now(timezone.utc)
    delta = now - gen
    return delta.total_seconds() <= freshness_hours * 3600


def validate_assertion_against_requirement(
    assertion: dict, req: dict, artifact_cache: dict[str, tuple[str, Any]]
) -> tuple[bool, str]:
    """Hostile validator. Returns (is_valid_PASS, reason_if_not).

    `artifact_cache` caches (sha256, parsed_json) per artifact_path to avoid
    repeated disk reads.
    """
    # 0. assertion_result must be PASS to even consider
    if assertion["assertion_result"] != "PASS":
        return (False, f"assertion_result={assertion['assertion_result']} (not PASS)")
    # 1. control must be in required OR supplemental
    allowed_ctrls = set(req.get("required_controls", [])) | set(req.get("supplemental_controls", []))
    if assertion["control"] not in allowed_ctrls:
        return (False, f"control '{assertion['control']}' not in required/supplemental for {req['req_id']}")
    # 2. generated_by_command must be allowed
    if assertion["generated_by_command"] not in req.get("allowed_verifier_commands", []):
        return (False,
                f"generated_by_command '{assertion['generated_by_command']}' not in allowed_verifier_commands")
    # 3. artifact_class must be allowed
    if assertion["artifact_class"] not in req.get("allowed_artifact_classes", []):
        return (False,
                f"artifact_class '{assertion['artifact_class']}' not in allowed_artifact_classes")
    # 4. row_specific must be true
    if not assertion.get("row_specific"):
        return (False, "row_specific=false")
    # 5. artifact_contains_req_id & artifact_contains_control
    if not assertion.get("artifact_contains_req_id"):
        return (False, "artifact_contains_req_id=false")
    if not assertion.get("artifact_contains_control"):
        return (False, "artifact_contains_control=false")
    # 6. freshness
    if not _freshness_ok(assertion["generated_at_utc"], int(assertion.get("freshness_hours", 168))):
        return (False, f"assertion stale (generated {assertion['generated_at_utc']}, "
                       f"window {assertion['freshness_hours']}h)")
    # 7. verifier_exit_code contract
    if assertion["control"] in EXIT_ZERO_REQUIRED_CONTROLS:
        if assertion.get("verifier_exit_code") != 0:
            return (False, f"verifier_exit_code={assertion.get('verifier_exit_code')} "
                           f"but control '{assertion['control']}' requires exit==0")
    # 8. Artifact must exist on disk
    art_rel = assertion["artifact_path"]
    art_abs = REPO_ROOT / art_rel
    if not art_abs.exists():
        return (False, f"artifact missing on disk: {art_rel}")
    # Artifact freshness: check mtime
    mtime = datetime.fromtimestamp(art_abs.stat().st_mtime, tz=timezone.utc)
    age_hours = (datetime.now(timezone.utc) - mtime).total_seconds() / 3600.0
    if age_hours > int(assertion.get("freshness_hours", 168)):
        return (False, f"artifact stale: mtime {age_hours:.1f}h > freshness_hours {assertion['freshness_hours']}h")
    # 9. Re-hash artifact and compare
    cached = artifact_cache.get(art_rel)
    if cached is None:
        actual_sha = sha256_file(art_abs)
        parsed = None
        try:
            parsed = json.loads(art_abs.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, UnicodeDecodeError):
            parsed = None
        artifact_cache[art_rel] = (actual_sha, parsed)
    actual_sha, parsed = artifact_cache[art_rel]
    if actual_sha != assertion["artifact_sha256"]:
        return (False, f"artifact sha256 mismatch: expected {assertion['artifact_sha256'][:12]}, "
                       f"got {actual_sha[:12]}")
    # 10. For JSON artifacts: pointer must resolve AND the resolved value
    # OR its pointer path must carry the req_id. Walking up to the root to
    # search for the req_id is FORBIDDEN — that's the "broad artifact with
    # linked_req_ids list at root" loophole Fort Knox explicitly guards.
    if parsed is not None:
        pointer = assertion["artifact_payload_pointer"]
        val = resolve_json_pointer(parsed, pointer)
        if val is _MISSING or isinstance(val, _MissingSentinel):
            return (False, f"artifact_payload_pointer '{pointer}' "
                           f"does not resolve in artifact")
        rid = req["req_id"]
        # A) req_id literally appears in the resolved payload (JSON-encoded)
        snippet = json.dumps(val, sort_keys=True) if not isinstance(val, str) else val
        if rid in snippet:
            return (True, "")
        # B) OR the pointer path itself contains the req_id as a segment
        # (e.g., /per_req/RTC-REQ-010 — the path is the row-specificity proof)
        segments = pointer.split("/")
        if rid in segments:
            return (True, "")
        return (False, f"req_id '{rid}' not present at pointer '{pointer}' "
                       f"nor in its path segments (broad-artifact guard)")
    # All checks passed
    return (True, "")


def compile_report() -> dict:
    if not REQS_PATH.exists():
        raise CompileError(f"requirements_source.json missing at {REQS_PATH}")
    if not ASSERTIONS_PATH.exists():
        raise CompileError(f"evidence_assertions.jsonl missing at {ASSERTIONS_PATH}")

    reqs_doc = json.loads(REQS_PATH.read_text(encoding="utf-8"))
    # Validate requirements source against schema
    reqs_schema = _load_schema(REQS_SCHEMA)
    errors = sorted(reqs_schema.iter_errors(reqs_doc), key=lambda e: e.path)
    if errors:
        msgs = "; ".join(e.message for e in errors[:5])
        raise CompileError(f"requirements_source.json fails schema: {msgs}")
    reqs = reqs_doc["requirements"]
    # Reject duplicate req_id
    seen_req_ids: set[str] = set()
    for r in reqs:
        if r["req_id"] in seen_req_ids:
            raise CompileError(f"duplicate req_id in requirements_source: {r['req_id']}")
        seen_req_ids.add(r["req_id"])

    # Load + validate assertions
    assertion_schema = _load_schema(ASSERTION_SCHEMA)
    assertions: list[dict] = []
    seen_aids: set[str] = set()
    schema_violations: list[tuple[int, str]] = []
    with ASSERTIONS_PATH.open("r", encoding="utf-8") as f:
        for lineno, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
            except json.JSONDecodeError as e:
                schema_violations.append((lineno, f"unparseable JSON: {e}"))
                continue
            vs = list(assertion_schema.iter_errors(obj))
            if vs:
                schema_violations.append((lineno, f"schema: {vs[0].message}"))
                continue
            if obj["assertion_id"] in seen_aids:
                raise CompileError(f"duplicate assertion_id: {obj['assertion_id']}")
            seen_aids.add(obj["assertion_id"])
            # Reject assertion for unknown req_id
            if obj["req_id"] not in seen_req_ids:
                schema_violations.append((lineno, f"assertion for unknown req_id {obj['req_id']}"))
                continue
            assertions.append(obj)

    # Index assertions by (req_id, control)
    by_req_ctrl: dict[tuple[str, str], list[dict]] = {}
    for a in assertions:
        by_req_ctrl.setdefault((a["req_id"], a["control"]), []).append(a)

    # Evaluate each requirement
    artifact_cache: dict[str, tuple[str, Any]] = {}
    rows: list[dict] = []
    req_by_id = {r["req_id"]: r for r in reqs}

    for req in reqs:
        rid = req["req_id"]
        required = req.get("required_controls", [])
        artifactless = set(req.get("artifactless_controls", []))
        control_evals: list[dict] = []
        missing_any = False
        had_any_evidence = False

        for ctrl in required:
            candidates = by_req_ctrl.get((rid, ctrl), [])
            had_any_evidence = had_any_evidence or bool(candidates)

            if not candidates:
                # Artifactless allowance: the requirements_source.json must
                # EXPLICITLY mark this control as artifactless OR it fails closed.
                if ctrl in artifactless:
                    control_evals.append({
                        "name": ctrl, "passed": True,
                        "reason": "explicitly declared artifactless",
                        "assertion_id": None, "artifact_path": None, "artifact_sha256": None,
                    })
                    continue
                missing_any = True
                control_evals.append({
                    "name": ctrl, "passed": False,
                    "reason": "no assertion for this control",
                    "assertion_id": None, "artifact_path": None, "artifact_sha256": None,
                })
                continue

            # Find first PASS candidate
            chosen_pass = None
            last_reason = ""
            for a in candidates:
                ok, reason = validate_assertion_against_requirement(a, req, artifact_cache)
                if ok:
                    chosen_pass = a
                    break
                last_reason = reason

            if chosen_pass is not None:
                control_evals.append({
                    "name": ctrl, "passed": True, "reason": None,
                    "assertion_id": chosen_pass["assertion_id"],
                    "artifact_path": chosen_pass["artifact_path"],
                    "artifact_sha256": chosen_pass["artifact_sha256"],
                })
            else:
                missing_any = True
                control_evals.append({
                    "name": ctrl, "passed": False,
                    "reason": last_reason or "no valid PASS assertion",
                    "assertion_id": candidates[0]["assertion_id"] if candidates else None,
                    "artifact_path": candidates[0]["artifact_path"] if candidates else None,
                    "artifact_sha256": candidates[0]["artifact_sha256"] if candidates else None,
                })

        # Compute row status
        if not missing_any and control_evals:
            status = "SIGNED_OFF"
            blocking_gap = None
        elif had_any_evidence:
            status = "BLOCKED"
            first_failing = next((c for c in control_evals if not c["passed"]), None)
            blocking_gap = f"{first_failing['name']}: {first_failing['reason']}" if first_failing else "unknown"
        else:
            status = "NOT_VERIFIED"
            blocking_gap = "no atomic assertion provided for required controls"

        # Assemble row
        assertion_ids = sorted({c["assertion_id"] for c in control_evals if c["assertion_id"]})
        row = {
            "req_id": rid,
            "title": req.get("title", ""),
            "claim_type": req.get("claim_type", ""),
            "priority": req.get("priority", ""),
            "requirement_group": req.get("requirement_group", ""),
            "is_final_hundred_percent_row": bool(req.get("is_final_hundred_percent_row", False)),
            "depends_on_req_ids": list(req.get("depends_on_req_ids", [])),
            "required_controls": list(required),
            "computed_status": status,
            "blocking_gap": blocking_gap,
            "controls": control_evals,
            "assertion_ids": assertion_ids,
            "row_evidence_sha256": "",  # placeholder, filled below
            "row_digest": "",           # placeholder, filled below
            "evaluated_at_utc": _iso_now(),
        }
        rows.append(row)

    # First pass done. Now apply dependency gate for final 100% rows.
    non_final_pending = [r["req_id"] for r in rows
                        if not r["is_final_hundred_percent_row"]
                        and r["computed_status"] != "SIGNED_OFF"]
    if non_final_pending:
        for row in rows:
            if row["is_final_hundred_percent_row"] and row["computed_status"] == "SIGNED_OFF":
                row["computed_status"] = "BLOCKED"
                row["blocking_gap"] = (
                    f"final-100% dependency gate: "
                    f"{len(non_final_pending)} non-final rows still open"
                )

    # Apply explicit depends_on_req_ids per row
    status_by_id = {r["req_id"]: r["computed_status"] for r in rows}
    for row in rows:
        if row["computed_status"] != "SIGNED_OFF":
            continue
        for dep in row["depends_on_req_ids"]:
            if status_by_id.get(dep) != "SIGNED_OFF":
                row["computed_status"] = "BLOCKED"
                row["blocking_gap"] = f"depends_on {dep} (status={status_by_id.get(dep)})"
                break

    # Compute per-row digests over the verdict payload (controls + status + gap).
    # Explicitly exclude `evaluated_at_utc` and `row_digest`/`row_evidence_sha256`
    # themselves — the digest must be run-independent and reproducible. A
    # second compile over the same inputs MUST produce the same digest.
    EXCLUDE_FROM_DIGEST = {"evaluated_at_utc", "row_digest", "row_evidence_sha256"}
    for row in rows:
        evidence_sha_input = {
            "req_id": row["req_id"],
            "status": row["computed_status"],
            "blocking_gap": row["blocking_gap"],
            "controls": row["controls"],
            "required_controls": row["required_controls"],
            "depends_on_req_ids": row["depends_on_req_ids"],
        }
        row["row_evidence_sha256"] = sha256_json_canonical(evidence_sha_input)
        digest_input = {k: v for k, v in row.items() if k not in EXCLUDE_FROM_DIGEST}
        row["row_digest"] = sha256_json_canonical(digest_input)

    # Summary
    total = len(rows)
    signed_off = sum(1 for r in rows if r["computed_status"] == "SIGNED_OFF")
    blocked = sum(1 for r in rows if r["computed_status"] == "BLOCKED")
    not_verified = sum(1 for r in rows if r["computed_status"] == "NOT_VERIFIED")

    # Per-claim-type breakdown
    import collections
    by_claim_type: dict[str, dict[str, int]] = collections.defaultdict(lambda: {
        "total": 0, "signed_off": 0, "blocked": 0, "not_verified": 0})
    for row in rows:
        ct = row["claim_type"] or "UNKNOWN"
        by_claim_type[ct]["total"] += 1
        if row["computed_status"] == "SIGNED_OFF":
            by_claim_type[ct]["signed_off"] += 1
        elif row["computed_status"] == "BLOCKED":
            by_claim_type[ct]["blocked"] += 1
        else:
            by_claim_type[ct]["not_verified"] += 1

    # Provenance hashes
    reqs_sha = sha256_file(REQS_PATH)
    assertions_sha = sha256_file(ASSERTIONS_PATH)
    row_digest_all = sha256_json_canonical([r["row_digest"] for r in sorted(rows, key=lambda x: x["req_id"])])
    evidence_digest_all = sha256_json_canonical([r["row_evidence_sha256"] for r in sorted(rows, key=lambda x: x["req_id"])])

    git_commit, git_dirty = _git_state()

    report = {
        "schema_version": SCHEMA_VERSION,
        "compiler_version": COMPILER_VERSION,
        "compiler_path": "tools/cert/compile_requirement_signoff.py",
        "compiler_sha256": sha256_file(Path(__file__)),
        "run_timestamp_utc": _iso_now(),
        "source_repo_root": str(REPO_ROOT).replace("\\", "/"),
        "git_commit": git_commit,
        "git_dirty": git_dirty,
        "requirements_source_sha256": reqs_sha,
        "evidence_assertions_sha256": assertions_sha,
        "row_digest": row_digest_all,
        "evidence_digest": evidence_digest_all,
        "rows": sorted(rows, key=lambda r: r["req_id"]),
        "summary": {
            "total": total,
            "signed_off": signed_off,
            "blocked": blocked,
            "not_verified": not_verified,
            "percent_signed_off": round(100.0 * signed_off / max(1, total), 1),
            "by_claim_type": dict(by_claim_type),
        },
        "trust_level": "DEVELOPMENT_PROOF",  # will be upgraded after all gates
    }

    # Validate report against schema BEFORE gating trust_level
    report_schema = _load_schema(REPORT_SCHEMA)
    report_errs = list(report_schema.iter_errors(report))
    if report_errs:
        # Report schema violations but don't fail — we want the report written
        # so operators can inspect. Instead downgrade trust_level.
        report["trust_level"] = "FAILED"
        report["schema_errors"] = [str(e.message) for e in report_errs[:10]]

    # Compute trust level
    all_signed = (signed_off == total and total > 0)
    report["trust_level"] = "INTEGRITY_PROOF" if all_signed else "DEVELOPMENT_PROOF"
    # Signature + bundle verifier can upgrade further; done by downstream tools.

    return report


# ===========================================================================
# Merkle tree
# ===========================================================================

def build_merkle(rows: list[dict]) -> dict:
    """Build a Merkle tree where each leaf = row_digest (covers verdict payload,
    controls, evidence hashes, and blocking_gap — per Fort Knox spec)."""
    sorted_rows = sorted(rows, key=lambda r: r["req_id"])
    leaves = [{"req_id": r["req_id"], "leaf_hash": r["row_digest"]} for r in sorted_rows]

    def _pair_hash(a: str, b: str) -> str:
        return sha256_bytes(bytes.fromhex(a) + bytes.fromhex(b))

    level = [L["leaf_hash"] for L in leaves]
    if not level:
        root = ""
    else:
        while len(level) > 1:
            if len(level) % 2 == 1:
                level.append(level[-1])  # duplicate last to pad
            level = [_pair_hash(level[i], level[i + 1]) for i in range(0, len(level), 2)]
        root = level[0]

    return {
        "root": root,
        "leaf_count": len(leaves),
        "leaves": leaves,
        "computed_at_utc": _iso_now(),
        "algorithm": "sha256 pairwise, odd-node duplication",
    }


# ===========================================================================
# Signature envelope
# ===========================================================================

def build_signature_envelope(report_sha256: str, report: dict) -> dict:
    """Current build: UNSIGNED. Future: HMAC or GPG. Required fields present."""
    all_signed = (report["summary"]["signed_off"] == report["summary"]["total"]
                  and report["summary"]["total"] > 0)
    status = "UNSIGNED_BLOCKED"
    if all_signed and report.get("trust_level") == "INTEGRITY_PROOF":
        status = "UNSIGNED_PENDING_SIGNATURE"  # ready to sign
    return {
        "schema_version": SCHEMA_VERSION,
        "report_sha256": report_sha256,
        "signed_bytes_sha256": None,
        "signer_identity": None,
        "signing_timestamp_utc": None,
        "signature_algorithm": None,
        "signature_verification_status": status,
        "notes": ("Signing is out-of-band. UNSIGNED_BLOCKED is fail-closed for "
                  "FINAL_SIGNED_CERTIFICATION."),
    }


# ===========================================================================
# Main
# ===========================================================================

def main() -> int:
    try:
        report = compile_report()
    except CompileError as e:
        print(f"FATAL: {e}", file=sys.stderr)
        return 2

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Write JSON report first (without merkle - merkle goes in sidecar)
    REPORT_PATH.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    report_sha = sha256_file(REPORT_PATH)
    SHA256_PATH.write_text(f"{report_sha}  {REPORT_PATH.name}\n", encoding="utf-8")

    # Merkle sidecar
    merkle = build_merkle(report["rows"])
    MERKLE_PATH.write_text(json.dumps(merkle, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    # Signature envelope
    sig = build_signature_envelope(report_sha, report)
    SIGNATURE_PATH.write_text(json.dumps(sig, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    s = report["summary"]
    print(f"[compile_requirement_signoff] {s['total']} reqs; "
          f"signed_off={s['signed_off']} blocked={s['blocked']} not_verified={s['not_verified']}")
    print(f"  trust_level:   {report['trust_level']}")
    print(f"  merkle root:   {merkle['root']}")
    print(f"  report sha256: {report_sha}")
    print(f"  signature:     {sig['signature_verification_status']}")
    return 0 if report["trust_level"] != "FAILED" else 1


if __name__ == "__main__":
    sys.exit(main())
