#!/usr/bin/env python3
"""Fort Knox release signer — graduates INTEGRITY_PROOF to SIGNED_PROOF.

Reads `artifacts/certification/final_requirement_signoff_report.json`,
produces a real ed25519 signature over its bytes, and rewrites
`final_requirement_signoff_report.signature.json` with all signature
fields populated.

Trust-level graduation ladder
-----------------------------
- ``UNSIGNED_PENDING_SIGNATURE``  — no signature present (initial state from
  ``sign_requirement_signoff_envelope.py`` scaffold).
- ``VERIFIED`` (this script)       — real ed25519 signature present and
  re-verified on emit. Trust level reaches ``SIGNED_PROOF``.
- ``FINAL_SIGNED_CERTIFICATION``  — signed by a third-party-bound identity
  (cosign keyless via GitHub OIDC, ADR-091 §Deferred). NOT this script.

Key material
------------
- **Public key**:  ``config/release_signer/release_signer.pub.pem``
  (PEM, committed — anyone can verify).
- **Private key**: ``artifacts/keys/release_signer/release_signer.key.pem``
  (PEM, gitignored — held only by the signer host).

On first run, both are generated by ed25519. On subsequent runs, the
existing key is loaded. The signer is identified as
``DEVELOPMENT_SIGNER:<sha256-prefix-of-public-key-bytes>`` — verifiable
but not bound to any external identity authority.

Usage
-----
::

    python tools/cert/sign_release_bundle.py
    python tools/cert/sign_release_bundle.py --rotate-keys     # generate new keypair
    python tools/cert/sign_release_bundle.py --signer-identity 'release@example.com'

Exit codes
----------
- ``0`` — signature emitted, status=VERIFIED.
- ``1`` — report missing or invalid; refused to sign.
- ``2`` — signature emitted but post-emit re-verification FAILED.
"""
from __future__ import annotations

import argparse
import base64
import datetime as _dt
import hashlib
import json
import os
import sys
from pathlib import Path

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)


_REPORT_NAME = "final_requirement_signoff_report.json"
_ENVELOPE_NAME = "final_requirement_signoff_report.signature.json"
_SHA_NAME = "final_requirement_signoff_report.sha256"

_PUBKEY_REL = Path("config/release_signer/release_signer.pub.pem")
_PRIVKEY_REL = Path("artifacts/keys/release_signer/release_signer.key.pem")


def _repo_root() -> Path:
    here = Path(__file__).resolve()
    for p in [here, *here.parents]:
        if (p / ".git").exists():
            return p
    return Path.cwd()


def _utc_now() -> str:
    return _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _sha256_hex(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _ensure_keypair(repo: Path, rotate: bool) -> tuple[Ed25519PrivateKey, Ed25519PublicKey, Path, Path]:
    """Generate keypair if missing (or rotate). Return (priv, pub, priv_path, pub_path)."""
    pub_path = repo / _PUBKEY_REL
    priv_path = repo / _PRIVKEY_REL

    if rotate or not (pub_path.exists() and priv_path.exists()):
        priv = Ed25519PrivateKey.generate()
        pub = priv.public_key()

        priv_pem = priv.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
        pub_pem = pub.public_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PublicFormat.SubjectPublicKeyInfo,
        )
        priv_path.parent.mkdir(parents=True, exist_ok=True)
        pub_path.parent.mkdir(parents=True, exist_ok=True)
        priv_path.write_bytes(priv_pem)
        pub_path.write_bytes(pub_pem)
        action = "rotated" if rotate else "generated"
        print(f"[sign_release_bundle] keypair {action} at "
              f"priv={_PRIVKEY_REL} pub={_PUBKEY_REL}")
    else:
        priv = serialization.load_pem_private_key(priv_path.read_bytes(), password=None)
        pub = serialization.load_pem_public_key(pub_path.read_bytes())
        if not isinstance(priv, Ed25519PrivateKey) or not isinstance(pub, Ed25519PublicKey):
            print(f"[sign_release_bundle] FAIL: keypair is not ed25519", file=sys.stderr)
            sys.exit(1)

    return priv, pub, priv_path, pub_path


def _signer_identity(pub: Ed25519PublicKey, override: str | None) -> str:
    if override:
        return override
    pub_raw = pub.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )
    pub_fp = _sha256_hex(pub_raw)[:16]
    return f"DEVELOPMENT_SIGNER:ed25519:{pub_fp}"


def _read_sidecar_sha(sidecar_path: Path) -> str | None:
    if not sidecar_path.exists():
        return None
    parts = sidecar_path.read_text(encoding="utf-8").strip().split()
    if not parts:
        return None
    candidate = parts[0]
    if len(candidate) == 64 and all(c in "0123456789abcdef" for c in candidate.lower()):
        return candidate.lower()
    return None


def _build_signed_envelope(
    report_bytes: bytes,
    report: dict,
    sidecar_sha: str | None,
    signature_b64: str,
    pub_pem: bytes,
    signer_id: str,
) -> dict:
    report_sha = _sha256_hex(report_bytes)
    sha_status = "MATCHES_SIDECAR" if (sidecar_sha and sidecar_sha == report_sha) else (
        "DRIFT" if sidecar_sha else "SIDECAR_MISSING")

    return {
        "schema_version": "fortknox-signature-envelope-v1",
        "envelope_generated_at_utc": _utc_now(),
        "report_filename": _REPORT_NAME,
        "report_sha256": report_sha,
        "sidecar_sha256": sidecar_sha,
        "report_sha_vs_sidecar": sha_status,
        "report_trust_level": report.get("trust_level"),
        "report_row_count": len(report.get("rows") or []),
        "merkle_root": (report.get("merkle") or {}).get("root") or report.get("merkle_root"),
        "signed_bytes_sha256": report_sha,
        "signer_identity": signer_id,
        "signing_timestamp_utc": _utc_now(),
        "signature_algorithm": "ed25519",
        "signature_value": signature_b64,
        "signature_value_encoding": "base64",
        "signer_public_key_pem": pub_pem.decode("ascii"),
        "signer_public_key_path": str(_PUBKEY_REL).replace("\\", "/"),
        "signature_verification_status": "VERIFIED",
        "transparency_log_entry_id": None,
        "notes": (
            "ed25519 signature over the canonical bytes of "
            f"{_REPORT_NAME}. Verify with "
            "`python tools/cert/verify_release_signature.py`. "
            "Trust level: SIGNED_PROOF (verifiable cryptographic signature, "
            "not yet bound to a third-party identity authority — "
            "FINAL_SIGNED_CERTIFICATION requires cosign keyless via GitHub "
            "OIDC per ADR-091 §Deferred decisions)."
        ),
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rotate-keys", action="store_true",
                        help="Generate a fresh keypair (overwrites existing).")
    parser.add_argument("--signer-identity", default=None,
                        help="Override signer identity string (default: DEVELOPMENT_SIGNER:<fp>).")
    parser.add_argument("--report", default=None,
                        help="Override path to the final report JSON.")
    args = parser.parse_args()

    if os.environ.get("FORTKNOX_DISCIPLINE_BYPASS") == "1":
        print("[sign_release_bundle] BYPASS (FORTKNOX_DISCIPLINE_BYPASS=1)")
        return 0

    repo = _repo_root()
    cert_dir = repo / "artifacts" / "certification"
    report_path = Path(args.report) if args.report else cert_dir / _REPORT_NAME
    envelope_path = cert_dir / _ENVELOPE_NAME
    sidecar_path = cert_dir / _SHA_NAME

    if not report_path.exists():
        print(f"[sign_release_bundle] FAIL: report missing at {report_path}",
              file=sys.stderr)
        return 1

    try:
        report_bytes = report_path.read_bytes()
        report = json.loads(report_bytes.decode("utf-8"))
    except (OSError, ValueError) as exc:
        print(f"[sign_release_bundle] FAIL: report unreadable: {exc}", file=sys.stderr)
        return 1

    # Sanity: report must already be at INTEGRITY_PROOF level (compiler emitted it).
    trust = report.get("trust_level", "")
    if trust not in ("INTEGRITY_PROOF", "SIGNED_PROOF"):
        print(f"[sign_release_bundle] FAIL: report.trust_level={trust!r} "
              f"— signer expects INTEGRITY_PROOF or SIGNED_PROOF",
              file=sys.stderr)
        return 1

    priv, pub, priv_path, pub_path = _ensure_keypair(repo, rotate=args.rotate_keys)
    signer_id = _signer_identity(pub, args.signer_identity)

    # Sign the canonical bytes
    sig_raw = priv.sign(report_bytes)
    sig_b64 = base64.b64encode(sig_raw).decode("ascii")

    # Re-verify our own signature before emitting the envelope (fail-closed)
    try:
        pub.verify(sig_raw, report_bytes)
    except InvalidSignature:
        print("[sign_release_bundle] FAIL: post-sign self-verification failed",
              file=sys.stderr)
        return 2

    pub_pem = pub_path.read_bytes()
    sidecar_sha = _read_sidecar_sha(sidecar_path)
    envelope = _build_signed_envelope(
        report_bytes, report, sidecar_sha, sig_b64, pub_pem, signer_id
    )
    envelope_path.write_text(
        json.dumps(envelope, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(
        f"[sign_release_bundle] VERIFIED — "
        f"signer={signer_id} "
        f"report_sha256={envelope['report_sha256'][:12]}... "
        f"signature_b64={sig_b64[:24]}..."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
