"""JSONL-backed telemetry bus for apps_lic outreach validators.

Final follow-up — provides the durable consumer surface for telemetry
events emitted by W1-W4 validators / engines:

    - ``message_length_cap_violation``      (W1-P2 archetype length validator)
    - ``mutual_connection_rendered``        (W2-P5 mutual-connection resolver)
    - ``mutual_connection_no_candidates``   (W2-P5)
    - ``question_ending_violation``         (W2-P6 question-ending validator)
    - ``spam_trigger_hits``                 (W3-P8 spam-trigger validator)

Every validator class accepts an optional ``telemetry_bus`` argument and
calls ``bus.record(event_name, payload)``. Until this module shipped
that contract had no concrete implementation — events were emitted but
not durably captured. The bus closes that loop.

Design choices:
    1. **JSONL on disk** — append-only, crash-safe, trivially replayable.
       One event per line. No external service dependency.
    2. **Best-effort writes** — bus errors NEVER propagate up to the
       validator. The bus catches OSError and logs a soft warning.
    3. **Schema-thin** — events are arbitrary JSON-serialisable dicts.
       Schema validation lives in the consumer (``OutreachLearningSubscriber``).
    4. **Fingerprinting** — every emitted line carries a UTC ISO
       timestamp and a session_id (caller-supplied or autogenerated)
       so replay can scope to a single run.
"""

from __future__ import annotations

import json
import os
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Optional


class JsonlEventBus:
    """File-backed event bus with the ``record(name, payload)`` contract.

    Thread-safe within a single process via an internal lock. Cross-
    process safety is provided by ``open(..., "a")`` semantics on POSIX
    and Windows — append writes are atomic up to PIPE_BUF / 4096 bytes
    on Linux and serialised by NTFS on Windows. For events larger than
    that, callers should serialise externally.
    """

    def __init__(
        self,
        log_path: str | Path,
        *,
        session_id: Optional[str] = None,
    ) -> None:
        self._log_path = Path(log_path)
        self._log_path.parent.mkdir(parents=True, exist_ok=True)
        self._session_id = session_id or uuid.uuid4().hex
        self._lock = threading.Lock()

    @property
    def log_path(self) -> Path:
        return self._log_path

    @property
    def session_id(self) -> str:
        return self._session_id

    def record(self, event_name: str, payload: Mapping[str, Any]) -> None:
        """Append one event to the JSONL log.

        Never raises — IO errors are swallowed (the bus is best-effort
        observability, not a system-of-record). Validators MUST be able
        to call this without try/except.
        """
        try:
            row = {
                "ts_utc": datetime.now(timezone.utc).isoformat(),
                "session_id": self._session_id,
                "event": event_name,
                "payload": dict(payload),
            }
            line = json.dumps(row, ensure_ascii=False, default=str)
            with self._lock:
                with self._log_path.open("a", encoding="utf-8") as fh:
                    fh.write(line + "\n")
        except (OSError, TypeError, ValueError):  # guardian: allow-log-and-swallow -- bus must never break callers
            return

    def close(self) -> None:
        """No-op — kept for symmetry with stateful bus implementations."""
        return


class InMemoryEventBus:
    """In-memory bus for tests — captures every record() to a list."""

    def __init__(self) -> None:
        self.events: list[tuple[str, dict]] = []
        self._lock = threading.Lock()

    def record(self, event_name: str, payload: Mapping[str, Any]) -> None:
        with self._lock:
            self.events.append((event_name, dict(payload)))

    def clear(self) -> None:
        with self._lock:
            self.events.clear()


__all__ = [
    "InMemoryEventBus",
    "JsonlEventBus",
]
