"""Classify skip audit entries by legitimacy category."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


CATEGORIES = {
    "LEGITIMATE: external service": [],
    "LEGITIMATE: opt-in env flag": [],
    "LEGITIMATE: platform-specific": [],
    "LEGITIMATE: conditional (faiss-gpu)": [],
    "ILLEGITIMATE: importorskip": [],
    "ILLEGITIMATE: module/symbol not importable": [],
    "ILLEGITIMATE: file/dir not found": [],
    "ILLEGITIMATE: not yet implemented": [],
    "ILLEGITIMATE: generated artifact missing": [],
    "ILLEGITIMATE: other": [],
}


def classify_reason(kind: str, reason: str) -> str:
    r = reason.lower()

    if kind == "importorskip":
        return "ILLEGITIMATE: importorskip"

    if any(
        token in r
        for token in (
            "redis not running",
            "playwright not installed",
            "playwright visual tests should be run separately",
        )
    ):
        return "LEGITIMATE: external service"

    if "ssot_orch_negctrl_tamper" in r or "activate tamper" in r:
        return "LEGITIMATE: opt-in env flag"

    if "read-only directory" in r or "platform" in r:
        return "LEGITIMATE: platform-specific"

    if "faiss-gpu" in r:
        return "LEGITIMATE: conditional (faiss-gpu)"

    if any(
        token in r
        for token in (
            "cannot import",
            "not importable",
            "not found in module",
            "not available (import commented out)",
            "not available",
            "module not available",
            "scanner not available",
        )
    ):
        return "ILLEGITIMATE: module/symbol not importable"

    if any(
        token in r
        for token in (
            "not found",
            "not present",
            "does not exist",
            "directory not found",
            "not found at",
        )
    ):
        return "ILLEGITIMATE: file/dir not found"

    if any(
        token in r
        for token in (
            "not yet implemented",
            "using mock for tests",
            "method not implemented yet",
            "should be run separately",
        )
    ):
        return "ILLEGITIMATE: not yet implemented"

    if any(
        token in r
        for token in (
            "dashboard html not found",
            "discovery artifact not found",
            "discovery output not found",
            "no snapshot yet",
        )
    ):
        return "ILLEGITIMATE: generated artifact missing"

    return "ILLEGITIMATE: other"


def parse_line(line: str) -> tuple[str, str, str, str] | None:
    parts = line.split("|", 3)
    if len(parts) < 3:
        return None
    kind = parts[0]
    file_path = parts[1]
    lineno = parts[2]
    reason = parts[3] if len(parts) > 3 else ""
    return kind, file_path, lineno, reason


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input",
        type=Path,
        default=Path.cwd() / "skip_audit.txt",
        help="Path to the skip audit file generated by audit_skips.py.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = args.input.resolve()

    if not input_path.exists():
        print(f"CRITICAL: skip audit file not found: {input_path}", file=sys.stderr)
        return 1

    try:
        lines = input_path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        print(f"CRITICAL: could not read skip audit file: {exc}", file=sys.stderr)
        return 1

    categories = {key: [] for key in CATEGORIES}
    malformed = 0

    for line in lines:
        parsed = parse_line(line)
        if parsed is None:
            malformed += 1
            continue

        kind, file_path, lineno, reason = parsed
        entry = (file_path, lineno, reason)
        categories[classify_reason(kind, reason)].append(entry)

    total_legit = sum(
        len(categories[name])
        for name in (
            "LEGITIMATE: external service",
            "LEGITIMATE: opt-in env flag",
            "LEGITIMATE: platform-specific",
            "LEGITIMATE: conditional (faiss-gpu)",
        )
    )
    total_illegit = sum(len(categories[name]) for name in categories if name.startswith("ILLEGITIMATE:"))

    print(f"TOTAL: {len(lines)}  |  LEGITIMATE: {total_legit}  |  ILLEGITIMATE: {total_illegit}")
    if malformed:
        print(f"MALFORMED LINES: {malformed}")
    print()

    for label, items in categories.items():
        print(f"=== {label} ({len(items)}) ===")
        for file_path, lineno, reason in items:
            print(f"  tests/{file_path}:{lineno}  {reason[:120]}")
        print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
