"""Generated registry of every L5 doctrine output contract.

``CONTRACT_REGISTRY`` maps the canonical output name (as written in the
doctrine docs, snake_case or PascalCase exactly) to its dataclass type.

Re-run ``python tools/l5_contracts/generate_contracts.py`` to regenerate.
"""

from __future__ import annotations

from typing import Final

from ._base import L5OutputBase

from .parent import (
    AuthorityContextEvidenceRef,
    CertificationGapEvidenceRef,
    EgressCertificationEvidenceRef,
    HumanReclearanceEvidenceRef,
    OriginTrustEvidenceRef,
    ReplayAuditEvidenceRef,
    StaticGovernanceEvidenceRef,
)
from .enforcement import (
    AgentProfileReceipt,
    AgentRegistryValidationReport,
    AgentRegistryViolationReport,
    AllowedConnectorReceipt,
    AllowedModelReceipt,
    AllowedToolReceipt,
    AuditChainIntegrityReport,
    BootL5EnforcementReport,
    CapabilityScopeReceipt,
    ClassificationCacheReport,
    ClassificationReport,
    ClassificationStatus,
    ClassifierErrorReport,
    CompileTimeL5EnforcementReport,
    ComponentStaticRegressionReport,
    ConfigWithLogicReport,
    ConnectorScopeViolationReport,
    CriticalRegistryGapReport,
    DelegationDepthViolationReport,
    DelegationScopeReceipt,
    DirectBypassAbsenceReceipt,
    DirectSdkBypassReport,
    DirectWritePathReport,
    DualTagConflictReport,
    EgressEvidenceStatus,
    EnforcementReceiptStatus,
    ExecutionModeReceipt,
    ExecutionModeViolationReport,
    GatewayAuditLog,
    GatewayInitReceipt,
    GatewayStatus,
    HiddenEgressPathReport,
    HybridAuthoritySmellReport,
    ImportBoundaryReport,
    InjectionScanReport,
    L5EnforcementViolationReport,
    LlmGatewayValidationReceipt,
    ModelEgressReceipt,
    ModelResolutionReceipt,
    ModelScopeReceipt,
    ModelScopeViolationReport,
    ModelSubstitutionReport,
    PathValidationReport,
    PromptHashReceipt,
    PromptRef,
    ProviderBypassScanReport,
    ProviderHealthReport,
    ProviderLaneReceipt,
    ProviderResolutionMapReceipt,
    RegistryDigestReceipt,
    RegistryFreezeReceipt,
    RegistryIntegrityViolationReport,
    RegistryStatus,
    RegistrySubstitutionReport,
    RegistryValidationReport,
    ReplayBindingReceipt,
    ReplayGatewayViolationReport,
    ReplayModeReceipt,
    RootProtectionReport,
    RuntimeL5EnforcementReceipt,
    SafeExtractionReceipt,
    SandboxEnvelope,
    SandboxScopeReceipt,
    SanitizedPromptRef,
    SovereignKernelIntegrityReport,
    StructureStatus,
    StructureValidationReport,
    TestPlacementReport,
    ToolScopeViolationReport,
    TypeSsotReport,
    UnknownClassificationReport,
    WaiverRequiredReport,
)
from .authority import (
    AffectedConsumersReport,
    AgentDigestReceipt,
    AgentRegistryGapReport,
    AgentRegistryReceipt,
    AgentScopeReceipt,
    AgentSubstitutionReport,
    AuthorityContextReceipt,
    AuthorityContextStatus,
    AuthorityFieldIntegrityReport,
    AuthorityGapReport,
    AuthorityIssuerReceipt,
    AuthoritySourceMap,
    BlueprintBindingStatus,
    BlueprintHashReceipt,
    BlueprintLoadReceipt,
    BlueprintMismatchReport,
    BlueprintRegistryCompatibilityReport,
    BootL5AuthorityReport,
    BroadScopeReport,
    CapabilityExpirationReceipt,
    CapabilityGapReport,
    CapabilityScopeStatus,
    CapabilityTokenRef,
    CapabilityWideningReport,
    ChangedAuthorityFieldReport,
    ClockPolicyReceipt,
    CompileTimeL5AuthorityReport,
    ConnectorAllowlistReceipt,
    ConnectorCredentialPolicyReceipt,
    ConnectorDomainReceipt,
    ConnectorGrantReceipt,
    ConnectorRegistryGapReport,
    ConnectorRegistryReceipt,
    ConnectorScopeReceipt,
    ConnectorSubstitutionReport,
    CriticalAuthorityGapReport,
    CrossPrincipalBleedReport,
    CrossTenantBleedReport,
    DanglingRegistryReferenceReport,
    DelegatedActorReceipt,
    DelegationDepthReceipt,
    DownstreamAuthorityConsumerMap,
    DownstreamAuthorityOverwriteReport,
    EnvironmentDigestReceipt,
    EscalationThresholdRef,
    ExternalCommitScopeReport,
    FilesystemScopeReceipt,
    GovernedValidationContext,
    HITLReentryPacket,
    HardConstraintMapRef,
    HashBindingReport,
    HitlAuthorityBindingReceipt,
    HumanActorReceipt,
    HumanAuthorityGapReport,
    HumanDiffBindingReceipt,
    HumanReentryReplayReceipt,
    HumanReviewScopeReceipt,
    HumanReviewThresholdRef,
    HumanReviewerScopeReceipt,
    HumanScopeWideningReport,
    IncidentReviewPacket,
    InvariantMapReceipt,
    LayerAuthorityGapReport,
    LayerAuthorityMatrixReceipt,
    MemoryScopeReceipt,
    NetworkAllowlistReceipt,
    NetworkScopeReceipt,
    NoImpliedAuthorityReceipt,
    NonReplayableGapReport,
    OldNewAuthorityBindingDiff,
    OriginTrustManifest,
    OriginTrustManifestRef,
    OriginalPrincipalReceipt,
    PacketAuthorityContextReceipt,
    PacketAuthorityGapReport,
    PolicyBindingGapReport,
    PolicyBindingStatus,
    PolicyBundleReceipt,
    PolicyEffectiveTimeReceipt,
    PolicyHashReceipt,
    PolicyLoadReceipt,
    PolicyMismatchReport,
    PolicyRegistryCompatibilityReport,
    PolicyStalenessReport,
    PrincipalChainGapReport,
    PrincipalChainReceipt,
    PrincipalChainStatus,
    PrincipalScopeWideningReport,
    PromptPolicyCompatibilityReceipt,
    PromptRegistryGapReport,
    PromptRegistryReceipt,
    PromptSlotMapReceipt,
    PromptSubstitutionReport,
    PromptVersionReceipt,
    ProviderAllowlistReceipt,
    ReCertificationRequiredReceipt,
    ReCertificationRequiredReport,
    ReadScopeReceipt,
    RecertificationStatus,
    RecertificationTriggerReport,
    RegistryBindingStatus,
    RegistryCompatibilityReport,
    RegistryCompatibilityStatus,
    RegistryDigestSetReceipt,
    RegistryFreshnessReport,
    RegistryGapReport,
    RegistryIntegrityReport,
    ReplayAuthorityMismatchReport,
    ReplayBindingStatus,
    ReplayEnvelope,
    ReplayKeyReceipt,
    RequestEnvelope,
    RequiredFieldGapReport,
    RouteTopologyMismatchReport,
    RouteTopologyReceipt,
    RuntimeL5AuthorityReceipt,
    SandboxBindingStatus,
    SandboxGapReport,
    SandboxWideningReport,
    ScopeCeilingReceipt,
    SecretsScopeReceipt,
    SectorOverlayReceipt,
    SideEffectBoundaryReceipt,
    SideEffectClassReceipt,
    SideEffectMismatchReport,
    SnapshotManifest,
    SnapshotManifestReceipt,
    StandardsFingerprintReceipt,
    StructureBlueprintReceipt,
    TargetSubstitutionReport,
    ToolRegistryGapReport,
    ToolRegistryReceipt,
    ToolSchemaReceipt,
    ToolScopeReceipt,
    ToolSideEffectReceipt,
    ToolSubstitutionReport,
    TranscriptBindingReceipt,
    TranscriptRef,
    UnderstatedAuthorityReport,
    UntrustedAuthorityAttemptReport,
    WriteIntentSmugglingReport,
    WriteScopeReceipt,
)
from .origin import (
    AuthorityAttemptStatus,
    AuthorityLabelMap,
    AuthorityOverrideAttemptReport,
    AuthoritySmugglingReport,
    BootOriginTrustReport,
    BoundaryRuleReceipt,
    BoundaryTransitionReport,
    CitationOrSpanRef,
    ConnectorOriginPolicyReport,
    ContentAuthorityHierarchyReceipt,
    ContentAuthorityIntegrityReport,
    ContentBoundaryStatus,
    CredentialLikePayloadReport,
    CriticalOriginTrustGapReport,
    CrossPrincipalContentBoundaryReport,
    CrossTenantContentBoundaryReport,
    DataClassBoundaryReport,
    EvidenceBundleRef,
    ExemplarAuthorityReport,
    ExtractedPayloadRef,
    ExtractionTransformLog,
    FencedDataReceipt,
    FreshnessStatus,
    GatewayReceiptRef,
    HallucinatedAuthorityReport,
    HumanInstructionAttemptReport,
    HumanReclearanceRequiredReceipt,
    HumanReviewBoundaryReceipt,
    HumanReviewOriginGapReport,
    HumanReviewRef,
    InstructionBoundaryStatus,
    InstructionDataBoundaryReceipt,
    LowerAuthorityOverwriteReport,
    ModelAuthorityAttemptReport,
    ModelOutputBoundaryReceipt,
    ModelOutputRef,
    ModelToolProposalBoundaryReport,
    ModelWriteProposalBoundaryReport,
    NoUntrustedAuthorityReceipt,
    OmittedSpanReport,
    OriginLabelCatalogReceipt,
    OriginLabelConflictReport,
    OriginLabelMap,
    OriginLabelStatus,
    OriginManifestGapReport,
    OriginManifestHashReceipt,
    OriginManifestReceipt,
    OriginManifestStatus,
    OriginTrustStaticReadinessReport,
    OutputSchemaRef,
    ParentArtifactRef,
    PolicyCompatibilityStatus,
    PrincipalChainRef,
    PriorArtifactBoundaryReceipt,
    PriorArtifactFreshnessReport,
    PriorArtifactLineageGapReport,
    PriorArtifactPolicyCompatibilityReport,
    PriorPacketRef,
    PromptLikeContentReport,
    PromptTemplateBoundaryReport,
    ProposedDiffRef,
    ProposedStateDiff,
    QuarantineFailureReport,
    QuarantineMap,
    QuarantinePolicyReceipt,
    QuarantineReasonMap,
    QuarantineReceipt,
    QuarantineReport,
    QuarantineStatus,
    QuotedContentOriginReport,
    RedactionPolicyReceipt,
    RedactionReceipt,
    RegionScopeBoundaryReport,
    ResidualRiskReport,
    RetrievedContentBoundaryReceipt,
    RetrievedContentFencingReport,
    RetrievedInstructionAttemptReport,
    RetrievedLineageGapReport,
    RetrievedStalenessBoundaryReport,
    RuntimeOriginTrustReceipt,
    RuntimeQuarantineReport,
    RuntimeSafeExtractionReport,
    SafeExtractionFailureReport,
    SafeExtractionMap,
    SafeExtractionPolicyReceipt,
    SafeExtractionReceiptRef,
    SafeExtractionStatus,
    SandboxEnvelopeRef,
    SanitizedPayloadGapReport,
    SanitizedPayloadMap,
    SecretDetectionReport,
    SecretQuarantineReceipt,
    SensitiveDataBoundaryReport,
    SessionScopeBoundaryReport,
    SourceRef,
    SpanRef,
    StaleArtifactAuthorityAttemptReport,
    StaleAuthoritySourceReport,
    StaticHiddenInstructionReport,
    StaticOriginTrustEvidenceIntakeReceipt,
    StaticOriginTrustGapRefMap,
    StaticOriginTrustReport,
    SupportTargetRef,
    ToolInvocationRef,
    ToolOutputBoundaryReceipt,
    ToolOutputInstructionAttemptReport,
    ToolOutputQuarantineReport,
    ToolOutputSchemaBoundaryReport,
    ToolOutputSecretReport,
    TransformationHashReceipt,
    TransformationReceipt,
    TrustBoundaryMap,
    TrustClassMappingReceipt,
    TrustClassMismatchReport,
    TrustClassReceipt,
    TrustClassificationReport,
    UnknownOriginLabelReport,
    UnknownTrustClassReport,
    UnsupportedOriginLabelReport,
    UntrustedInstructionAttemptReport,
    UserAuthorityAttemptReport,
    UserIntentExtractionRef,
    UserTurnBoundaryReceipt,
)
from .hitl import (
    AllowedResponseTypeReceipt,
    AuthorityFreezeReceipt,
    AuthorityImpactingHumanDiffReport,
    BootHitlGovernanceReport,
    CertificationScopeRef,
    CriticalHitlGapReport,
    DirectHumanWritePathReport,
    FreezeReplayBindingReceipt,
    FrozenEvidenceBundleReceipt,
    FrozenPacketHashReceipt,
    FrozenPacketRef,
    HITLAuditReceipt,
    HITLFreezePacket,
    HardConstraintHumanOverrideReport,
    HitlAuditGapReport,
    HitlAuditStatus,
    HitlFreezeGapReport,
    HitlFreezeReceipt,
    HitlPacketStatus,
    HitlStaticGapRefMap,
    HitlStaticGapReport,
    HitlTemplateGovernanceReadinessReport,
    HumanAddedEvidenceClaimReport,
    HumanAuthorityAttemptReport,
    HumanAuthorityWideningAttemptReport,
    HumanDiffReceipt,
    HumanDiffRef,
    HumanDiffReplayReceipt,
    HumanInputOriginReceipt,
    HumanInputStatus,
    HumanModificationDiff,
    HumanModificationDiffReceipt,
    HumanOriginGapReport,
    HumanOriginStatus,
    HumanOverrideAttemptReport,
    HumanOverrideLimitReceipt,
    HumanPolicyExceptionRequestReport,
    HumanPromptLikeContentReport,
    HumanProvidedFactReport,
    HumanProvidedSourceReport,
    HumanReclearanceReceipt,
    HumanReclearanceTriggerReport,
    HumanResponseReceipt,
    HumanReviewContextBoundaryReport,
    HumanReviewEvidencePacket,
    HumanReviewHashChainReceipt,
    HumanReviewOriginLabelReport,
    HumanReviewPacketGapReport,
    HumanReviewPacketReceipt,
    HumanReviewPolicyReceipt,
    HumanReviewReconstructionReport,
    HumanReviewReplayReceipt,
    HumanReviewTemplateBoundaryReport,
    HumanScopeGapReport,
    HumanScopeStatus,
    HumanSourceOriginGapReport,
    HumanSourceValidationNeededReceipt,
    L5ReclearanceReceipt,
    L5ReclearanceRequiredReceipt,
    ModifiedPacketRef,
    OldNewScopeDiff,
    OperatorOverridePolicyReport,
    ProhibitedResponseTypeReceipt,
    ProposedActionRef,
    ProposedStateDiffRef,
    ReClearanceRequiredReceipt,
    ReClearanceStatus,
    ReclearanceGapReport,
    ReclearanceReceiptRef,
    ReclearanceRequiredReceipt,
    ReclearanceRuleReceipt,
    ReclearanceStatus,
    ReclearanceStatusReport,
    ResumeAuthorityReceipt,
    ResumeAuthorityStatus,
    ResumeGapReport,
    ResumeReplayReceipt,
    ResumeScopeReceipt,
    ResumedPacketRef,
    ReviewerRoleMapReceipt,
    ReviewerRoleRef,
    ReviewerVisibleScopeReceipt,
    RuntimeHitlGapReport,
    RuntimeHitlGovernanceReceipt,
    ScopeImpactingHumanDiffReport,
    StaticHitlEvidenceIntakeReceipt,
    StaticHitlGovernanceReport,
    UpdatedPacketRef,
)
from .egress import (
    ArgumentSchemaRef,
    BootEgressGovernanceReport,
    BroadNetworkScopeReport,
    CertificationStatus,
    ConnectorAuditReceipt,
    ConnectorEgressReceipt,
    ConnectorEgressReceiptRef,
    ConnectorEgressStatus,
    ConnectorGrantGapReport,
    ConnectorGrantRef,
    ConnectorReplayReceipt,
    ConnectorRetentionReceipt,
    ConnectorScopeStaticReport,
    CredentialAuditReceipt,
    CredentialExpirationReceipt,
    CredentialExposureRiskReport,
    CredentialIssuerReceipt,
    CredentialMinimizationReceipt,
    CredentialPolicyReceipt,
    CredentialRedactionReceipt,
    CredentialScopeReceipt,
    CredentialScopeReceiptRef,
    CredentialScopeRef,
    CredentialScopeStatus,
    CredentialSubstitutionReport,
    CriticalEgressGapReport,
    DataMinimizationReceipt,
    DirectApiKeyUsageReport,
    DirectSDKBypassReport,
    DirectSdkBypassEvidenceRef,
    EgressAuditGapReport,
    EgressAuditPolicyReceipt,
    EgressAuditReceipt,
    EgressCertificationGapReport,
    EgressCertificationHashReceipt,
    EgressCertificationReceipt,
    EgressCertificationScopeReceipt,
    EgressCertificationStatus,
    EgressClassReceipt,
    EgressHashChainReceipt,
    EgressPayloadBoundaryReceipt,
    EgressReconstructionReport,
    EgressReplayGapReport,
    EgressReplayReceipt,
    EgressRequestGapReport,
    EgressRequestReceipt,
    EgressTargetIdentityReceipt,
    EgressWrapperBypassEvidenceRef,
    EgressWrapperBypassReport,
    ExternalCommitAuditReceipt,
    ExternalCommitDownstreamReviewReceipt,
    ExternalCommitEgressReceipt,
    ExternalCommitHumanReviewRequirementReceipt,
    ExternalCommitReplayReceipt,
    ExternalCommitScopeReceipt,
    FallbackCandidateReceipt,
    FallbackPolicyReceipt,
    FallbackReceiptRef,
    FallbackRecertificationRequiredReport,
    FallbackStatus,
    HardcodedModelLiteralReport,
    HiddenEgressCertificationImpactReport,
    IrreversibleActionEvidenceReport,
    ModelAllowlistReceipt,
    ModelAuditReceipt,
    ModelCredentialExposureReport,
    ModelDirectBypassReport,
    ModelEgressReceiptRef,
    ModelEgressStatus,
    ModelReplayReceipt,
    ModelResolutionMapReceipt,
    NetworkAuditReceipt,
    NetworkBroadScopeReport,
    NetworkDestinationReceipt,
    NetworkDestinationRef,
    NetworkEgressReceipt,
    NetworkEgressReceiptRef,
    NetworkEgressStatus,
    NetworkMethodReceipt,
    NetworkRegionReceipt,
    NetworkReplayReceipt,
    NetworkSubstitutionReport,
    NoSilentFallbackReceipt,
    OldNewEgressTargetDiff,
    PayloadCrossPrincipalReport,
    PayloadCrossTenantReport,
    PayloadHashReceipt,
    PayloadScopeReceipt,
    PayloadSecretExposureReport,
    PreviousCertificationRef,
    PromptArtifactRef,
    ProviderLaneReceiptRef,
    ProviderLaneStatus,
    ProviderRegistryReceipt,
    ProviderSdkBypassStaticReport,
    ProviderSubstitutionReport,
    RegionSubstitutionReport,
    RuntimeConnectorEgressReceipt,
    RuntimeCredentialScopeReceipt,
    RuntimeEgressGapReport,
    RuntimeEgressGovernanceReceipt,
    RuntimeFallbackReceipt,
    RuntimeModelEgressReceipt,
    RuntimeNetworkEgressReceipt,
    RuntimeToolEgressReceipt,
    SilentFallbackStaticReport,
    SsrfRiskEvidenceReport,
    StaticEgressCertificationReadinessReport,
    StaticEgressEvidenceIntakeReceipt,
    StaticEgressEvidenceRefMap,
    StaticEgressGapReport,
    StaticEgressGovernanceReport,
    ToolAuditReceipt,
    ToolBroadScopeReport,
    ToolEgressReceipt,
    ToolEgressReceiptRef,
    ToolEgressStatus,
    ToolReplayReceipt,
    ToolSchemaBindingReceipt,
    UnauthorizedNetworkClientEvidenceRef,
    UnauthorizedNetworkClientReport,
    UnauthorizedNetworkClientStaticReport,
    UnauthorizedSecretAccessEvidenceRef,
    UnauthorizedSecretAccessReport,
)
from .replay import (
    AffectedConsumerReport,
    AuditBindingStatus,
    AuditGapReport,
    AuditHashChainReceipt,
    AuditLogEventRef,
    AuditManifest,
    AuditManifestHashReceipt,
    AuditManifestReceipt,
    AuditManifestRef,
    AuditRedactionReceipt,
    AuditSchemaReceipt,
    AuditSecretExposureStaticReport,
    AuditSinkReceipt,
    AuthorityContextRef,
    AuthorityReconstructionPacket,
    BootReplayAuditGovernanceReport,
    CanonicalSerializationReceipt,
    CertificationEvidenceStatus,
    CertificationGapReport,
    CertificationPacketGapReport,
    CertificationPacketHashReceipt,
    CertificationPacketReceipt,
    CertificationResult,
    CertificationResultHashReceipt,
    CertificationResultReceipt,
    CertificationReuseViolationReport,
    CertificationSchemaAuditReadinessReport,
    CertificationSchemaIntegrityReport,
    CertificationSchemaReceipt,
    CertificationSchemaReplayReadinessReport,
    CertificationScopeGapReport,
    CertificationScopeHashReceipt,
    CertificationScopeReceipt,
    CertificationScopeStatus,
    CertificationScopeWideningReport,
    ComplianceHashGapReport,
    ComplianceHashReceipt,
    ContextHashReceipt,
    CriticalReplayAuditGapReport,
    DownstreamReviewEvidenceRef,
    EvidenceContractHashReceipt,
    EvidenceContractRef,
    ExpectedRef,
    ForbiddenDispositionAbsenceReceipt,
    ForbiddenDispositionFieldReport,
    HardConstraintMap,
    HashAlgorithmReceipt,
    HashBindingReportRef,
    HashBindingStatus,
    HashMismatchReport,
    HmacConfigReceipt,
    HmacSignatureReceipt,
    L5CertificationPacket,
    L5CertificationResult,
    MissingAuditRefStaticReport,
    MissingReceiptReport,
    MissingReplayRefStaticReport,
    ObservedRef,
    OriginTrustManifestReceipt,
    OrphanArtifactReport,
    OrphanReceiptReport,
    OrphanSpanReport,
    ProposedStateDiffHashReceipt,
    ReceiptChainCompletenessReceipt,
    ReceiptChainReport,
    ReceiptChainReportRef,
    ReceiptCrossPrincipalReport,
    ReclearanceReceipt,
    ReconstructionGapReport,
    ReconstructionPacketHashReceipt,
    ReconstructionPacketReceipt,
    ReconstructionStatus,
    RedactionPolicyRef,
    ReplayEnvelopeReceipt,
    ReplayEnvelopeRef,
    ReplayGapReport,
    ReplayHashBindingReport,
    ReplaySchemaReceipt,
    ReplayStorageReceipt,
    RequiredHashGapReport,
    RouteContractRef,
    RuntimeAuditManifestReceipt,
    RuntimeCertificationPacketReceipt,
    RuntimeHashBindingReport,
    RuntimeReconstructionReadinessReport,
    RuntimeReplayAuditCertificationReceipt,
    RuntimeReplayBindingReceipt,
    RuntimeTraceCompletenessReport,
    SpanBindingReceipt,
    StaleReceiptReport,
    StandardsFingerprintGapReport,
    StaticReplayAuditEvidenceIntakeReceipt,
    StaticReplayAuditGapReport,
    StaticReplayAuditGovernanceReport,
    TamperEvidenceReport,
    TraceAuditBindingReceipt,
    TraceBindingStatus,
    TraceCompletenessReport,
    TraceCompletenessReportRef,
    TraceCorrelationReceipt,
    TraceGapReport,
    TraceReplayBindingReceipt,
    WallClockDecisionFieldReport,
)
from .static import (
    ADRRequiredReport,
    AdgSnapshotRef,
    AdrRequiredReport,
    AdrStatus,
    AffectedAuthoritySurfaceMap,
    AgentRegistryDriftReport,
    ArchitectureDriftGapReport,
    ArchitectureDriftReport,
    BranchOrCommitRef,
    BypassEvidenceStatus,
    BypassWrapperWaiverReport,
    ConfigWithLogicStaticReport,
    ConnectorAuditRequirementDriftReport,
    ConnectorConfigDriftReport,
    ConnectorCredentialPolicyDriftReport,
    ConnectorDomainDriftReport,
    ConnectorGrantDriftReport,
    ConnectorRegistryDriftReport,
    ConnectorRetentionDriftReport,
    ConnectorScopeWideningReport,
    CurrentAdgSnapshotRef,
    DeletedGateStaticReport,
    DependencyDirectionDriftReport,
    DirectExternalWriteStaticReport,
    DirectSdkBypassStaticReport,
    DirectWritePathStaticReport,
    DirectWriteWaiverReport,
    DownstreamConsumerStaticReadinessMap,
    DownstreamStaticImpactReport,
    DownstreamStaticRegressionImpactReport,
    DriftCategoryMap,
    EgressWrapperStaticReport,
    ExceptionTaxonomyDriftReport,
    FallbackChainDriftReport,
    GoldenArchitectureSnapshotRef,
    GoldenAuditReplaySnapshotRef,
    GoldenConnectorSnapshotRef,
    GoldenPolicySnapshotRef,
    GoldenPromptSnapshotRef,
    GoldenRegistrySnapshotRef,
    GoldenRouteSnapshotRef,
    GoldenSnapshotComparisonReport,
    GoldenSnapshotGapReport,
    GoldenSnapshotRef,
    HardConstraintChangeReport,
    HardcodedModelLiteralStaticReport,
    HiddenEgressStaticReport,
    HiddenEgressWaiverReport,
    HitlDirectWriteStaticReport,
    HitlThresholdDriftReport,
    L4DirectWriteReport,
    L6CurrentRunMutationStaticReport,
    LayerBoundaryDriftReport,
    LearningBoundaryDriftReport,
    ManagedWorkflowAutonomyDriftReport,
    MissingAuditMetadataReport,
    MissingReplayMetadataReport,
    NewlyIntroducedBypassReport,
    OrphanRegistryRef,
    OrphanRegistryReferenceReport,
    PolicyDriftStatus,
    PolicyWeakeningReport,
    PolicyWeakeningWaiverReport,
    PromptAssemblyBoundaryDriftReport,
    PromptAuthorityBoundaryDriftReport,
    PromptDriftReport,
    PromptRegistryCompatibilityDriftReport,
    PromptRegistryDriftReport,
    PromptSchemaBindingDriftReport,
    PromptShadowArtifactReport,
    PromptSlotMapDriftReport,
    PromptStablePrefixDriftReport,
    ProposedDiffBoundaryReport,
    RefusalTaxonomyDriftReport,
    RegistryDigestDriftReport,
    RegistryDriftReport,
    RegistryDriftStatus,
    RegistryScopeWideningReport,
    RegistrySubstitutionStaticReport,
    RelaxedScopeReport,
    RetrievalBoundaryDriftReport,
    RiskTierMappingDriftReport,
    RollbackPlanReceipt,
    RouteBudgetDriftReport,
    RouteContractIntegrityReport,
    RouteTopologyDriftReport,
    RouteTopologyStaticReport,
    RouteWorkflowDriftReport,
    SectorOverlayDriftReport,
    StaleRegistryRef,
    StaleWaiverReport,
    StandardsFingerprintDriftReport,
    StaticAuditGapReport,
    StaticBypassWrapperReport,
    StaticCertificationReadinessReport,
    StaticDriftEvidencePacket,
    StaticDriftHashReceipt,
    StaticDriftReport,
    StaticGovernanceAuditReceipt,
    StaticGovernanceReplayReceipt,
    StaticGovernanceReviewPacket,
    StaticGovernanceStatus,
    StaticReadinessStatusReceipt,
    StaticReconstructionPacket,
    StaticRegressionEvidenceReport,
    StaticRegressionGapReport,
    StaticRegressionHashReceipt,
    StaticRegressionStatus,
    StaticReplayGapReport,
    StaticReportHashChainReceipt,
    StaticReviewGapReport,
    StaticReviewPacketHashReceipt,
    StaticReviewPacketReceipt,
    StructureDriftStatus,
    ToolRegistryDriftReport,
    UnauthorizedConnectorClientReport,
    UnauthorizedHttpClientReport,
    UnresolvedStaticGapReport,
    UwgBypassStaticReport,
    WaiverCompatibilityReport,
    WaiverPresenceReport,
    WaiverScopeMismatchReport,
    WaiverStatus,
    WeakenedDefaultReport,
    WorkflowBoundaryDriftReport,
    WrapperAuthorityExpansionReport,
    WrapperTargetResolutionReport,
    WritePathDriftReport,
)
from .runtime_binding import (
    BlueprintEvidenceRef,
    CapabilityScopeRef,
    EgressCertRef,
    HitlReclearanceRef,
    L5SnapshotVerificationReceipt,
    LiveSnapshotRef,
    MatchStatus,
    OriginTrustRef,
    PacketRef,
    PolicyEvidenceRef,
    PrincipalRef,
    PromptEnvelope,
    RegistryEvidenceRef,
    ReplayAuditRef,
    ReplaySnapshotRef,
    SandboxScopeRef,
    StaticGovernanceRef,
    TestExitRequiresL5ReclearanceForHumanModifiedPacket,
    TestL2E2RejectsMissingL5BindingForGovernedPacket,
)

CONTRACT_REGISTRY: Final[dict[str, type[L5OutputBase]]] = {
    "authority_context_evidence_ref": AuthorityContextEvidenceRef,
    "certification_gap_evidence_ref": CertificationGapEvidenceRef,
    "egress_certification_evidence_ref": EgressCertificationEvidenceRef,
    "human_reclearance_evidence_ref": HumanReclearanceEvidenceRef,
    "origin_trust_evidence_ref": OriginTrustEvidenceRef,
    "replay_audit_evidence_ref": ReplayAuditEvidenceRef,
    "static_governance_evidence_ref": StaticGovernanceEvidenceRef,
    "agent_profile_receipt": AgentProfileReceipt,
    "agent_registry_validation_report": AgentRegistryValidationReport,
    "agent_registry_violation_report": AgentRegistryViolationReport,
    "allowed_connector_receipt": AllowedConnectorReceipt,
    "allowed_model_receipt": AllowedModelReceipt,
    "allowed_tool_receipt": AllowedToolReceipt,
    "audit_chain_integrity_report": AuditChainIntegrityReport,
    "boot_l5_enforcement_report": BootL5EnforcementReport,
    "capability_scope_receipt": CapabilityScopeReceipt,
    "classification_cache_report": ClassificationCacheReport,
    "classification_report": ClassificationReport,
    "classification_status": ClassificationStatus,
    "classifier_error_report": ClassifierErrorReport,
    "compile_time_l5_enforcement_report": CompileTimeL5EnforcementReport,
    "component_static_regression_report": ComponentStaticRegressionReport,
    "config_with_logic_report": ConfigWithLogicReport,
    "connector_scope_violation_report": ConnectorScopeViolationReport,
    "critical_registry_gap_report": CriticalRegistryGapReport,
    "delegation_depth_violation_report": DelegationDepthViolationReport,
    "delegation_scope_receipt": DelegationScopeReceipt,
    "direct_bypass_absence_receipt": DirectBypassAbsenceReceipt,
    "direct_sdk_bypass_report": DirectSdkBypassReport,
    "direct_write_path_report": DirectWritePathReport,
    "dual_tag_conflict_report": DualTagConflictReport,
    "egress_evidence_status": EgressEvidenceStatus,
    "enforcement_receipt_status": EnforcementReceiptStatus,
    "execution_mode_receipt": ExecutionModeReceipt,
    "execution_mode_violation_report": ExecutionModeViolationReport,
    "gateway_audit_log": GatewayAuditLog,
    "gateway_init_receipt": GatewayInitReceipt,
    "gateway_status": GatewayStatus,
    "HiddenEgressPathReport": HiddenEgressPathReport,
    "hidden_egress_path_report": HiddenEgressPathReport,
    "hybrid_authority_smell_report": HybridAuthoritySmellReport,
    "import_boundary_report": ImportBoundaryReport,
    "injection_scan_report": InjectionScanReport,
    "l5_enforcement_violation_report": L5EnforcementViolationReport,
    "llm_gateway_validation_receipt": LlmGatewayValidationReceipt,
    "ModelEgressReceipt": ModelEgressReceipt,
    "model_egress_receipt": ModelEgressReceipt,
    "model_resolution_receipt": ModelResolutionReceipt,
    "model_scope_receipt": ModelScopeReceipt,
    "model_scope_violation_report": ModelScopeViolationReport,
    "ModelSubstitutionReport": ModelSubstitutionReport,
    "model_substitution_report": ModelSubstitutionReport,
    "path_validation_report": PathValidationReport,
    "prompt_hash_receipt": PromptHashReceipt,
    "prompt_ref": PromptRef,
    "provider_bypass_scan_report": ProviderBypassScanReport,
    "provider_health_report": ProviderHealthReport,
    "ProviderLaneReceipt": ProviderLaneReceipt,
    "provider_lane_receipt": ProviderLaneReceipt,
    "provider_resolution_map_receipt": ProviderResolutionMapReceipt,
    "registry_digest_receipt": RegistryDigestReceipt,
    "registry_freeze_receipt": RegistryFreezeReceipt,
    "registry_integrity_violation_report": RegistryIntegrityViolationReport,
    "registry_status": RegistryStatus,
    "registry_substitution_report": RegistrySubstitutionReport,
    "registry_validation_report": RegistryValidationReport,
    "replay_binding_receipt": ReplayBindingReceipt,
    "replay_gateway_violation_report": ReplayGatewayViolationReport,
    "replay_mode_receipt": ReplayModeReceipt,
    "root_protection_report": RootProtectionReport,
    "runtime_l5_enforcement_receipt": RuntimeL5EnforcementReceipt,
    "safe_extraction_receipt": SafeExtractionReceipt,
    "sandbox_envelope": SandboxEnvelope,
    "sandbox_scope_receipt": SandboxScopeReceipt,
    "sanitized_prompt_ref": SanitizedPromptRef,
    "sovereign_kernel_integrity_report": SovereignKernelIntegrityReport,
    "structure_status": StructureStatus,
    "structure_validation_report": StructureValidationReport,
    "test_placement_report": TestPlacementReport,
    "tool_scope_violation_report": ToolScopeViolationReport,
    "type_ssot_report": TypeSsotReport,
    "unknown_classification_report": UnknownClassificationReport,
    "WaiverRequiredReport": WaiverRequiredReport,
    "waiver_required_report": WaiverRequiredReport,
    "affected_consumers_report": AffectedConsumersReport,
    "agent_digest_receipt": AgentDigestReceipt,
    "agent_registry_gap_report": AgentRegistryGapReport,
    "agent_registry_receipt": AgentRegistryReceipt,
    "agent_scope_receipt": AgentScopeReceipt,
    "agent_substitution_report": AgentSubstitutionReport,
    "authority_context_receipt": AuthorityContextReceipt,
    "authority_context_status": AuthorityContextStatus,
    "authority_field_integrity_report": AuthorityFieldIntegrityReport,
    "authority_gap_report": AuthorityGapReport,
    "authority_issuer_receipt": AuthorityIssuerReceipt,
    "authority_source_map": AuthoritySourceMap,
    "blueprint_binding_status": BlueprintBindingStatus,
    "blueprint_hash_receipt": BlueprintHashReceipt,
    "blueprint_load_receipt": BlueprintLoadReceipt,
    "blueprint_mismatch_report": BlueprintMismatchReport,
    "blueprint_registry_compatibility_report": BlueprintRegistryCompatibilityReport,
    "boot_l5_authority_report": BootL5AuthorityReport,
    "broad_scope_report": BroadScopeReport,
    "capability_expiration_receipt": CapabilityExpirationReceipt,
    "capability_gap_report": CapabilityGapReport,
    "capability_scope_status": CapabilityScopeStatus,
    "capability_token_ref": CapabilityTokenRef,
    "capability_widening_report": CapabilityWideningReport,
    "changed_authority_field_report": ChangedAuthorityFieldReport,
    "clock_policy_receipt": ClockPolicyReceipt,
    "compile_time_l5_authority_report": CompileTimeL5AuthorityReport,
    "connector_allowlist_receipt": ConnectorAllowlistReceipt,
    "connector_credential_policy_receipt": ConnectorCredentialPolicyReceipt,
    "connector_domain_receipt": ConnectorDomainReceipt,
    "connector_grant_receipt": ConnectorGrantReceipt,
    "connector_registry_gap_report": ConnectorRegistryGapReport,
    "connector_registry_receipt": ConnectorRegistryReceipt,
    "connector_scope_receipt": ConnectorScopeReceipt,
    "ConnectorSubstitutionReport": ConnectorSubstitutionReport,
    "connector_substitution_report": ConnectorSubstitutionReport,
    "critical_authority_gap_report": CriticalAuthorityGapReport,
    "cross_principal_bleed_report": CrossPrincipalBleedReport,
    "cross_tenant_bleed_report": CrossTenantBleedReport,
    "dangling_registry_reference_report": DanglingRegistryReferenceReport,
    "delegated_actor_receipt": DelegatedActorReceipt,
    "delegation_depth_receipt": DelegationDepthReceipt,
    "downstream_authority_consumer_map": DownstreamAuthorityConsumerMap,
    "downstream_authority_overwrite_report": DownstreamAuthorityOverwriteReport,
    "environment_digest_receipt": EnvironmentDigestReceipt,
    "escalation_threshold_ref": EscalationThresholdRef,
    "external_commit_scope_report": ExternalCommitScopeReport,
    "filesystem_scope_receipt": FilesystemScopeReceipt,
    "GovernedValidationContext": GovernedValidationContext,
    "HITLReentryPacket": HITLReentryPacket,
    "hard_constraint_map_ref": HardConstraintMapRef,
    "hash_binding_report": HashBindingReport,
    "hitl_authority_binding_receipt": HitlAuthorityBindingReceipt,
    "human_actor_receipt": HumanActorReceipt,
    "human_authority_gap_report": HumanAuthorityGapReport,
    "human_diff_binding_receipt": HumanDiffBindingReceipt,
    "human_reentry_replay_receipt": HumanReentryReplayReceipt,
    "HumanReviewScopeReceipt": HumanReviewScopeReceipt,
    "human_review_scope_receipt": HumanReviewScopeReceipt,
    "human_review_threshold_ref": HumanReviewThresholdRef,
    "human_reviewer_scope_receipt": HumanReviewerScopeReceipt,
    "human_scope_widening_report": HumanScopeWideningReport,
    "IncidentReviewPacket": IncidentReviewPacket,
    "invariant_map_receipt": InvariantMapReceipt,
    "layer_authority_gap_report": LayerAuthorityGapReport,
    "layer_authority_matrix_receipt": LayerAuthorityMatrixReceipt,
    "memory_scope_receipt": MemoryScopeReceipt,
    "network_allowlist_receipt": NetworkAllowlistReceipt,
    "network_scope_receipt": NetworkScopeReceipt,
    "no_implied_authority_receipt": NoImpliedAuthorityReceipt,
    "non_replayable_gap_report": NonReplayableGapReport,
    "old_new_authority_binding_diff": OldNewAuthorityBindingDiff,
    "OriginTrustManifest": OriginTrustManifest,
    "origin_trust_manifest": OriginTrustManifest,
    "origin_trust_manifest_ref": OriginTrustManifestRef,
    "original_principal_receipt": OriginalPrincipalReceipt,
    "packet_authority_context_receipt": PacketAuthorityContextReceipt,
    "packet_authority_gap_report": PacketAuthorityGapReport,
    "policy_binding_gap_report": PolicyBindingGapReport,
    "policy_binding_status": PolicyBindingStatus,
    "policy_bundle_receipt": PolicyBundleReceipt,
    "policy_effective_time_receipt": PolicyEffectiveTimeReceipt,
    "policy_hash_receipt": PolicyHashReceipt,
    "policy_load_receipt": PolicyLoadReceipt,
    "policy_mismatch_report": PolicyMismatchReport,
    "policy_registry_compatibility_report": PolicyRegistryCompatibilityReport,
    "policy_staleness_report": PolicyStalenessReport,
    "principal_chain_gap_report": PrincipalChainGapReport,
    "principal_chain_receipt": PrincipalChainReceipt,
    "principal_chain_status": PrincipalChainStatus,
    "principal_scope_widening_report": PrincipalScopeWideningReport,
    "prompt_policy_compatibility_receipt": PromptPolicyCompatibilityReceipt,
    "prompt_registry_gap_report": PromptRegistryGapReport,
    "prompt_registry_receipt": PromptRegistryReceipt,
    "prompt_slot_map_receipt": PromptSlotMapReceipt,
    "prompt_substitution_report": PromptSubstitutionReport,
    "prompt_version_receipt": PromptVersionReceipt,
    "provider_allowlist_receipt": ProviderAllowlistReceipt,
    "re_certification_required_receipt": ReCertificationRequiredReceipt,
    "re_certification_required_report": ReCertificationRequiredReport,
    "read_scope_receipt": ReadScopeReceipt,
    "recertification_status": RecertificationStatus,
    "recertification_trigger_report": RecertificationTriggerReport,
    "registry_binding_status": RegistryBindingStatus,
    "registry_compatibility_report": RegistryCompatibilityReport,
    "registry_compatibility_status": RegistryCompatibilityStatus,
    "registry_digest_set_receipt": RegistryDigestSetReceipt,
    "registry_freshness_report": RegistryFreshnessReport,
    "registry_gap_report": RegistryGapReport,
    "registry_integrity_report": RegistryIntegrityReport,
    "replay_authority_mismatch_report": ReplayAuthorityMismatchReport,
    "replay_binding_status": ReplayBindingStatus,
    "replay_envelope": ReplayEnvelope,
    "replay_key_receipt": ReplayKeyReceipt,
    "RequestEnvelope": RequestEnvelope,
    "required_field_gap_report": RequiredFieldGapReport,
    "route_topology_mismatch_report": RouteTopologyMismatchReport,
    "route_topology_receipt": RouteTopologyReceipt,
    "runtime_l5_authority_receipt": RuntimeL5AuthorityReceipt,
    "sandbox_binding_status": SandboxBindingStatus,
    "sandbox_gap_report": SandboxGapReport,
    "sandbox_widening_report": SandboxWideningReport,
    "scope_ceiling_receipt": ScopeCeilingReceipt,
    "secrets_scope_receipt": SecretsScopeReceipt,
    "sector_overlay_receipt": SectorOverlayReceipt,
    "side_effect_boundary_receipt": SideEffectBoundaryReceipt,
    "side_effect_class_receipt": SideEffectClassReceipt,
    "side_effect_mismatch_report": SideEffectMismatchReport,
    "snapshot_manifest": SnapshotManifest,
    "snapshot_manifest_receipt": SnapshotManifestReceipt,
    "standards_fingerprint_receipt": StandardsFingerprintReceipt,
    "structure_blueprint_receipt": StructureBlueprintReceipt,
    "target_substitution_report": TargetSubstitutionReport,
    "tool_registry_gap_report": ToolRegistryGapReport,
    "tool_registry_receipt": ToolRegistryReceipt,
    "tool_schema_receipt": ToolSchemaReceipt,
    "tool_scope_receipt": ToolScopeReceipt,
    "tool_side_effect_receipt": ToolSideEffectReceipt,
    "ToolSubstitutionReport": ToolSubstitutionReport,
    "tool_substitution_report": ToolSubstitutionReport,
    "transcript_binding_receipt": TranscriptBindingReceipt,
    "transcript_ref": TranscriptRef,
    "understated_authority_report": UnderstatedAuthorityReport,
    "untrusted_authority_attempt_report": UntrustedAuthorityAttemptReport,
    "write_intent_smuggling_report": WriteIntentSmugglingReport,
    "write_scope_receipt": WriteScopeReceipt,
    "authority_attempt_status": AuthorityAttemptStatus,
    "authority_label_map": AuthorityLabelMap,
    "authority_override_attempt_report": AuthorityOverrideAttemptReport,
    "authority_smuggling_report": AuthoritySmugglingReport,
    "boot_origin_trust_report": BootOriginTrustReport,
    "boundary_rule_receipt": BoundaryRuleReceipt,
    "boundary_transition_report": BoundaryTransitionReport,
    "citation_or_span_ref": CitationOrSpanRef,
    "connector_origin_policy_report": ConnectorOriginPolicyReport,
    "content_authority_hierarchy_receipt": ContentAuthorityHierarchyReceipt,
    "content_authority_integrity_report": ContentAuthorityIntegrityReport,
    "content_boundary_status": ContentBoundaryStatus,
    "credential_like_payload_report": CredentialLikePayloadReport,
    "critical_origin_trust_gap_report": CriticalOriginTrustGapReport,
    "cross_principal_content_boundary_report": CrossPrincipalContentBoundaryReport,
    "cross_tenant_content_boundary_report": CrossTenantContentBoundaryReport,
    "data_class_boundary_report": DataClassBoundaryReport,
    "evidence_bundle_ref": EvidenceBundleRef,
    "exemplar_authority_report": ExemplarAuthorityReport,
    "extracted_payload_ref": ExtractedPayloadRef,
    "extraction_transform_log": ExtractionTransformLog,
    "fenced_data_receipt": FencedDataReceipt,
    "freshness_status": FreshnessStatus,
    "gateway_receipt_ref": GatewayReceiptRef,
    "hallucinated_authority_report": HallucinatedAuthorityReport,
    "human_instruction_attempt_report": HumanInstructionAttemptReport,
    "human_reclearance_required_receipt": HumanReclearanceRequiredReceipt,
    "human_review_boundary_receipt": HumanReviewBoundaryReceipt,
    "human_review_origin_gap_report": HumanReviewOriginGapReport,
    "human_review_ref": HumanReviewRef,
    "instruction_boundary_status": InstructionBoundaryStatus,
    "instruction_data_boundary_receipt": InstructionDataBoundaryReceipt,
    "lower_authority_overwrite_report": LowerAuthorityOverwriteReport,
    "model_authority_attempt_report": ModelAuthorityAttemptReport,
    "model_output_boundary_receipt": ModelOutputBoundaryReceipt,
    "model_output_ref": ModelOutputRef,
    "model_tool_proposal_boundary_report": ModelToolProposalBoundaryReport,
    "model_write_proposal_boundary_report": ModelWriteProposalBoundaryReport,
    "no_untrusted_authority_receipt": NoUntrustedAuthorityReceipt,
    "omitted_span_report": OmittedSpanReport,
    "origin_label_catalog_receipt": OriginLabelCatalogReceipt,
    "origin_label_conflict_report": OriginLabelConflictReport,
    "origin_label_map": OriginLabelMap,
    "origin_label_status": OriginLabelStatus,
    "origin_manifest_gap_report": OriginManifestGapReport,
    "origin_manifest_hash_receipt": OriginManifestHashReceipt,
    "origin_manifest_receipt": OriginManifestReceipt,
    "origin_manifest_status": OriginManifestStatus,
    "origin_trust_static_readiness_report": OriginTrustStaticReadinessReport,
    "output_schema_ref": OutputSchemaRef,
    "parent_artifact_ref": ParentArtifactRef,
    "policy_compatibility_status": PolicyCompatibilityStatus,
    "principal_chain_ref": PrincipalChainRef,
    "prior_artifact_boundary_receipt": PriorArtifactBoundaryReceipt,
    "prior_artifact_freshness_report": PriorArtifactFreshnessReport,
    "prior_artifact_lineage_gap_report": PriorArtifactLineageGapReport,
    "prior_artifact_policy_compatibility_report": PriorArtifactPolicyCompatibilityReport,
    "prior_packet_ref": PriorPacketRef,
    "prompt_like_content_report": PromptLikeContentReport,
    "prompt_template_boundary_report": PromptTemplateBoundaryReport,
    "proposed_diff_ref": ProposedDiffRef,
    "proposed_state_diff": ProposedStateDiff,
    "quarantine_failure_report": QuarantineFailureReport,
    "quarantine_map": QuarantineMap,
    "quarantine_policy_receipt": QuarantinePolicyReceipt,
    "quarantine_reason_map": QuarantineReasonMap,
    "quarantine_receipt": QuarantineReceipt,
    "quarantine_report": QuarantineReport,
    "quarantine_status": QuarantineStatus,
    "quoted_content_origin_report": QuotedContentOriginReport,
    "redaction_policy_receipt": RedactionPolicyReceipt,
    "redaction_receipt": RedactionReceipt,
    "region_scope_boundary_report": RegionScopeBoundaryReport,
    "residual_risk_report": ResidualRiskReport,
    "retrieved_content_boundary_receipt": RetrievedContentBoundaryReceipt,
    "retrieved_content_fencing_report": RetrievedContentFencingReport,
    "retrieved_instruction_attempt_report": RetrievedInstructionAttemptReport,
    "retrieved_lineage_gap_report": RetrievedLineageGapReport,
    "retrieved_staleness_boundary_report": RetrievedStalenessBoundaryReport,
    "runtime_origin_trust_receipt": RuntimeOriginTrustReceipt,
    "runtime_quarantine_report": RuntimeQuarantineReport,
    "runtime_safe_extraction_report": RuntimeSafeExtractionReport,
    "safe_extraction_failure_report": SafeExtractionFailureReport,
    "safe_extraction_map": SafeExtractionMap,
    "safe_extraction_policy_receipt": SafeExtractionPolicyReceipt,
    "safe_extraction_receipt_ref": SafeExtractionReceiptRef,
    "safe_extraction_status": SafeExtractionStatus,
    "sandbox_envelope_ref": SandboxEnvelopeRef,
    "sanitized_payload_gap_report": SanitizedPayloadGapReport,
    "sanitized_payload_map": SanitizedPayloadMap,
    "secret_detection_report": SecretDetectionReport,
    "secret_quarantine_receipt": SecretQuarantineReceipt,
    "sensitive_data_boundary_report": SensitiveDataBoundaryReport,
    "session_scope_boundary_report": SessionScopeBoundaryReport,
    "source_ref": SourceRef,
    "span_ref": SpanRef,
    "stale_artifact_authority_attempt_report": StaleArtifactAuthorityAttemptReport,
    "stale_authority_source_report": StaleAuthoritySourceReport,
    "static_hidden_instruction_report": StaticHiddenInstructionReport,
    "static_origin_trust_evidence_intake_receipt": StaticOriginTrustEvidenceIntakeReceipt,
    "static_origin_trust_gap_ref_map": StaticOriginTrustGapRefMap,
    "static_origin_trust_report": StaticOriginTrustReport,
    "support_target_ref": SupportTargetRef,
    "tool_invocation_ref": ToolInvocationRef,
    "tool_output_boundary_receipt": ToolOutputBoundaryReceipt,
    "tool_output_instruction_attempt_report": ToolOutputInstructionAttemptReport,
    "tool_output_quarantine_report": ToolOutputQuarantineReport,
    "tool_output_schema_boundary_report": ToolOutputSchemaBoundaryReport,
    "tool_output_secret_report": ToolOutputSecretReport,
    "transformation_hash_receipt": TransformationHashReceipt,
    "transformation_receipt": TransformationReceipt,
    "trust_boundary_map": TrustBoundaryMap,
    "trust_class_mapping_receipt": TrustClassMappingReceipt,
    "trust_class_mismatch_report": TrustClassMismatchReport,
    "trust_class_receipt": TrustClassReceipt,
    "trust_classification_report": TrustClassificationReport,
    "unknown_origin_label_report": UnknownOriginLabelReport,
    "unknown_trust_class_report": UnknownTrustClassReport,
    "unsupported_origin_label_report": UnsupportedOriginLabelReport,
    "untrusted_instruction_attempt_report": UntrustedInstructionAttemptReport,
    "user_authority_attempt_report": UserAuthorityAttemptReport,
    "user_intent_extraction_ref": UserIntentExtractionRef,
    "user_turn_boundary_receipt": UserTurnBoundaryReceipt,
    "allowed_response_type_receipt": AllowedResponseTypeReceipt,
    "authority_freeze_receipt": AuthorityFreezeReceipt,
    "authority_impacting_human_diff_report": AuthorityImpactingHumanDiffReport,
    "boot_hitl_governance_report": BootHitlGovernanceReport,
    "certification_scope_ref": CertificationScopeRef,
    "critical_hitl_gap_report": CriticalHitlGapReport,
    "direct_human_write_path_report": DirectHumanWritePathReport,
    "freeze_replay_binding_receipt": FreezeReplayBindingReceipt,
    "frozen_evidence_bundle_receipt": FrozenEvidenceBundleReceipt,
    "frozen_packet_hash_receipt": FrozenPacketHashReceipt,
    "frozen_packet_ref": FrozenPacketRef,
    "HITLAuditReceipt": HITLAuditReceipt,
    "HITLFreezePacket": HITLFreezePacket,
    "hard_constraint_human_override_report": HardConstraintHumanOverrideReport,
    "hitl_audit_gap_report": HitlAuditGapReport,
    "hitl_audit_status": HitlAuditStatus,
    "hitl_freeze_gap_report": HitlFreezeGapReport,
    "hitl_freeze_receipt": HitlFreezeReceipt,
    "hitl_packet_status": HitlPacketStatus,
    "hitl_static_gap_ref_map": HitlStaticGapRefMap,
    "hitl_static_gap_report": HitlStaticGapReport,
    "hitl_template_governance_readiness_report": HitlTemplateGovernanceReadinessReport,
    "human_added_evidence_claim_report": HumanAddedEvidenceClaimReport,
    "human_authority_attempt_report": HumanAuthorityAttemptReport,
    "human_authority_widening_attempt_report": HumanAuthorityWideningAttemptReport,
    "human_diff_receipt": HumanDiffReceipt,
    "human_diff_ref": HumanDiffRef,
    "human_diff_replay_receipt": HumanDiffReplayReceipt,
    "HumanInputOriginReceipt": HumanInputOriginReceipt,
    "human_input_origin_receipt": HumanInputOriginReceipt,
    "human_input_status": HumanInputStatus,
    "HumanModificationDiff": HumanModificationDiff,
    "human_modification_diff_receipt": HumanModificationDiffReceipt,
    "human_origin_gap_report": HumanOriginGapReport,
    "human_origin_status": HumanOriginStatus,
    "human_override_attempt_report": HumanOverrideAttemptReport,
    "human_override_limit_receipt": HumanOverrideLimitReceipt,
    "human_policy_exception_request_report": HumanPolicyExceptionRequestReport,
    "human_prompt_like_content_report": HumanPromptLikeContentReport,
    "human_provided_fact_report": HumanProvidedFactReport,
    "human_provided_source_report": HumanProvidedSourceReport,
    "HumanReclearanceReceipt": HumanReclearanceReceipt,
    "human_reclearance_trigger_report": HumanReclearanceTriggerReport,
    "human_response_receipt": HumanResponseReceipt,
    "human_review_context_boundary_report": HumanReviewContextBoundaryReport,
    "HumanReviewEvidencePacket": HumanReviewEvidencePacket,
    "human_review_hash_chain_receipt": HumanReviewHashChainReceipt,
    "human_review_origin_label_report": HumanReviewOriginLabelReport,
    "human_review_packet_gap_report": HumanReviewPacketGapReport,
    "human_review_packet_receipt": HumanReviewPacketReceipt,
    "human_review_policy_receipt": HumanReviewPolicyReceipt,
    "human_review_reconstruction_report": HumanReviewReconstructionReport,
    "human_review_replay_receipt": HumanReviewReplayReceipt,
    "human_review_template_boundary_report": HumanReviewTemplateBoundaryReport,
    "human_scope_gap_report": HumanScopeGapReport,
    "human_scope_status": HumanScopeStatus,
    "human_source_origin_gap_report": HumanSourceOriginGapReport,
    "human_source_validation_needed_receipt": HumanSourceValidationNeededReceipt,
    "L5ReclearanceReceipt": L5ReclearanceReceipt,
    "L5ReclearanceRequiredReceipt": L5ReclearanceRequiredReceipt,
    "modified_packet_ref": ModifiedPacketRef,
    "old_new_scope_diff": OldNewScopeDiff,
    "operator_override_policy_report": OperatorOverridePolicyReport,
    "prohibited_response_type_receipt": ProhibitedResponseTypeReceipt,
    "proposed_action_ref": ProposedActionRef,
    "proposed_state_diff_ref": ProposedStateDiffRef,
    "re_clearance_required_receipt": ReClearanceRequiredReceipt,
    "re_clearance_status": ReClearanceStatus,
    "reclearance_gap_report": ReclearanceGapReport,
    "reclearance_receipt_ref": ReclearanceReceiptRef,
    "reclearance_required_receipt": ReclearanceRequiredReceipt,
    "reclearance_rule_receipt": ReclearanceRuleReceipt,
    "reclearance_status": ReclearanceStatus,
    "reclearance_status_report": ReclearanceStatusReport,
    "ResumeAuthorityReceipt": ResumeAuthorityReceipt,
    "resume_authority_receipt": ResumeAuthorityReceipt,
    "resume_authority_status": ResumeAuthorityStatus,
    "resume_gap_report": ResumeGapReport,
    "resume_replay_receipt": ResumeReplayReceipt,
    "resume_scope_receipt": ResumeScopeReceipt,
    "resumed_packet_ref": ResumedPacketRef,
    "reviewer_role_map_receipt": ReviewerRoleMapReceipt,
    "reviewer_role_ref": ReviewerRoleRef,
    "reviewer_visible_scope_receipt": ReviewerVisibleScopeReceipt,
    "runtime_hitl_gap_report": RuntimeHitlGapReport,
    "runtime_hitl_governance_receipt": RuntimeHitlGovernanceReceipt,
    "scope_impacting_human_diff_report": ScopeImpactingHumanDiffReport,
    "static_hitl_evidence_intake_receipt": StaticHitlEvidenceIntakeReceipt,
    "static_hitl_governance_report": StaticHitlGovernanceReport,
    "updated_packet_ref": UpdatedPacketRef,
    "argument_schema_ref": ArgumentSchemaRef,
    "boot_egress_governance_report": BootEgressGovernanceReport,
    "broad_network_scope_report": BroadNetworkScopeReport,
    "certification_status": CertificationStatus,
    "connector_audit_receipt": ConnectorAuditReceipt,
    "ConnectorEgressReceipt": ConnectorEgressReceipt,
    "connector_egress_receipt": ConnectorEgressReceipt,
    "connector_egress_receipt_ref": ConnectorEgressReceiptRef,
    "connector_egress_status": ConnectorEgressStatus,
    "connector_grant_gap_report": ConnectorGrantGapReport,
    "connector_grant_ref": ConnectorGrantRef,
    "connector_replay_receipt": ConnectorReplayReceipt,
    "connector_retention_receipt": ConnectorRetentionReceipt,
    "connector_scope_static_report": ConnectorScopeStaticReport,
    "credential_audit_receipt": CredentialAuditReceipt,
    "credential_expiration_receipt": CredentialExpirationReceipt,
    "credential_exposure_risk_report": CredentialExposureRiskReport,
    "credential_issuer_receipt": CredentialIssuerReceipt,
    "credential_minimization_receipt": CredentialMinimizationReceipt,
    "credential_policy_receipt": CredentialPolicyReceipt,
    "credential_redaction_receipt": CredentialRedactionReceipt,
    "CredentialScopeReceipt": CredentialScopeReceipt,
    "credential_scope_receipt": CredentialScopeReceipt,
    "credential_scope_receipt_ref": CredentialScopeReceiptRef,
    "credential_scope_ref": CredentialScopeRef,
    "credential_scope_status": CredentialScopeStatus,
    "credential_substitution_report": CredentialSubstitutionReport,
    "critical_egress_gap_report": CriticalEgressGapReport,
    "data_minimization_receipt": DataMinimizationReceipt,
    "direct_api_key_usage_report": DirectApiKeyUsageReport,
    "DirectSDKBypassReport": DirectSDKBypassReport,
    "direct_sdk_bypass_evidence_ref": DirectSdkBypassEvidenceRef,
    "egress_audit_gap_report": EgressAuditGapReport,
    "egress_audit_policy_receipt": EgressAuditPolicyReceipt,
    "EgressAuditReceipt": EgressAuditReceipt,
    "egress_audit_receipt": EgressAuditReceipt,
    "egress_certification_gap_report": EgressCertificationGapReport,
    "egress_certification_hash_receipt": EgressCertificationHashReceipt,
    "EgressCertificationReceipt": EgressCertificationReceipt,
    "egress_certification_receipt": EgressCertificationReceipt,
    "egress_certification_scope_receipt": EgressCertificationScopeReceipt,
    "egress_certification_status": EgressCertificationStatus,
    "egress_class_receipt": EgressClassReceipt,
    "egress_hash_chain_receipt": EgressHashChainReceipt,
    "egress_payload_boundary_receipt": EgressPayloadBoundaryReceipt,
    "egress_reconstruction_report": EgressReconstructionReport,
    "egress_replay_gap_report": EgressReplayGapReport,
    "EgressReplayReceipt": EgressReplayReceipt,
    "egress_replay_receipt": EgressReplayReceipt,
    "egress_request_gap_report": EgressRequestGapReport,
    "egress_request_receipt": EgressRequestReceipt,
    "egress_target_identity_receipt": EgressTargetIdentityReceipt,
    "egress_wrapper_bypass_evidence_ref": EgressWrapperBypassEvidenceRef,
    "egress_wrapper_bypass_report": EgressWrapperBypassReport,
    "external_commit_audit_receipt": ExternalCommitAuditReceipt,
    "external_commit_downstream_review_receipt": ExternalCommitDownstreamReviewReceipt,
    "external_commit_egress_receipt": ExternalCommitEgressReceipt,
    "external_commit_human_review_requirement_receipt": ExternalCommitHumanReviewRequirementReceipt,
    "external_commit_replay_receipt": ExternalCommitReplayReceipt,
    "external_commit_scope_receipt": ExternalCommitScopeReceipt,
    "fallback_candidate_receipt": FallbackCandidateReceipt,
    "fallback_policy_receipt": FallbackPolicyReceipt,
    "fallback_receipt_ref": FallbackReceiptRef,
    "fallback_recertification_required_report": FallbackRecertificationRequiredReport,
    "fallback_status": FallbackStatus,
    "hardcoded_model_literal_report": HardcodedModelLiteralReport,
    "hidden_egress_certification_impact_report": HiddenEgressCertificationImpactReport,
    "irreversible_action_evidence_report": IrreversibleActionEvidenceReport,
    "model_allowlist_receipt": ModelAllowlistReceipt,
    "model_audit_receipt": ModelAuditReceipt,
    "model_credential_exposure_report": ModelCredentialExposureReport,
    "model_direct_bypass_report": ModelDirectBypassReport,
    "model_egress_receipt_ref": ModelEgressReceiptRef,
    "model_egress_status": ModelEgressStatus,
    "model_replay_receipt": ModelReplayReceipt,
    "model_resolution_map_receipt": ModelResolutionMapReceipt,
    "network_audit_receipt": NetworkAuditReceipt,
    "network_broad_scope_report": NetworkBroadScopeReport,
    "network_destination_receipt": NetworkDestinationReceipt,
    "network_destination_ref": NetworkDestinationRef,
    "NetworkEgressReceipt": NetworkEgressReceipt,
    "network_egress_receipt": NetworkEgressReceipt,
    "network_egress_receipt_ref": NetworkEgressReceiptRef,
    "network_egress_status": NetworkEgressStatus,
    "network_method_receipt": NetworkMethodReceipt,
    "network_region_receipt": NetworkRegionReceipt,
    "network_replay_receipt": NetworkReplayReceipt,
    "network_substitution_report": NetworkSubstitutionReport,
    "NoSilentFallbackReceipt": NoSilentFallbackReceipt,
    "no_silent_fallback_receipt": NoSilentFallbackReceipt,
    "old_new_egress_target_diff": OldNewEgressTargetDiff,
    "payload_cross_principal_report": PayloadCrossPrincipalReport,
    "payload_cross_tenant_report": PayloadCrossTenantReport,
    "payload_hash_receipt": PayloadHashReceipt,
    "payload_scope_receipt": PayloadScopeReceipt,
    "payload_secret_exposure_report": PayloadSecretExposureReport,
    "previous_certification_ref": PreviousCertificationRef,
    "prompt_artifact_ref": PromptArtifactRef,
    "provider_lane_receipt_ref": ProviderLaneReceiptRef,
    "provider_lane_status": ProviderLaneStatus,
    "provider_registry_receipt": ProviderRegistryReceipt,
    "provider_sdk_bypass_static_report": ProviderSdkBypassStaticReport,
    "ProviderSubstitutionReport": ProviderSubstitutionReport,
    "provider_substitution_report": ProviderSubstitutionReport,
    "region_substitution_report": RegionSubstitutionReport,
    "runtime_connector_egress_receipt": RuntimeConnectorEgressReceipt,
    "runtime_credential_scope_receipt": RuntimeCredentialScopeReceipt,
    "runtime_egress_gap_report": RuntimeEgressGapReport,
    "runtime_egress_governance_receipt": RuntimeEgressGovernanceReceipt,
    "runtime_fallback_receipt": RuntimeFallbackReceipt,
    "runtime_model_egress_receipt": RuntimeModelEgressReceipt,
    "runtime_network_egress_receipt": RuntimeNetworkEgressReceipt,
    "runtime_tool_egress_receipt": RuntimeToolEgressReceipt,
    "silent_fallback_static_report": SilentFallbackStaticReport,
    "ssrf_risk_evidence_report": SsrfRiskEvidenceReport,
    "static_egress_certification_readiness_report": StaticEgressCertificationReadinessReport,
    "static_egress_evidence_intake_receipt": StaticEgressEvidenceIntakeReceipt,
    "static_egress_evidence_ref_map": StaticEgressEvidenceRefMap,
    "static_egress_gap_report": StaticEgressGapReport,
    "static_egress_governance_report": StaticEgressGovernanceReport,
    "tool_audit_receipt": ToolAuditReceipt,
    "tool_broad_scope_report": ToolBroadScopeReport,
    "ToolEgressReceipt": ToolEgressReceipt,
    "tool_egress_receipt": ToolEgressReceipt,
    "tool_egress_receipt_ref": ToolEgressReceiptRef,
    "tool_egress_status": ToolEgressStatus,
    "tool_replay_receipt": ToolReplayReceipt,
    "tool_schema_binding_receipt": ToolSchemaBindingReceipt,
    "unauthorized_network_client_evidence_ref": UnauthorizedNetworkClientEvidenceRef,
    "unauthorized_network_client_report": UnauthorizedNetworkClientReport,
    "unauthorized_network_client_static_report": UnauthorizedNetworkClientStaticReport,
    "unauthorized_secret_access_evidence_ref": UnauthorizedSecretAccessEvidenceRef,
    "unauthorized_secret_access_report": UnauthorizedSecretAccessReport,
    "affected_consumer_report": AffectedConsumerReport,
    "audit_binding_status": AuditBindingStatus,
    "audit_gap_report": AuditGapReport,
    "audit_hash_chain_receipt": AuditHashChainReceipt,
    "audit_log_event_ref": AuditLogEventRef,
    "audit_manifest": AuditManifest,
    "audit_manifest_hash_receipt": AuditManifestHashReceipt,
    "audit_manifest_receipt": AuditManifestReceipt,
    "audit_manifest_ref": AuditManifestRef,
    "audit_redaction_receipt": AuditRedactionReceipt,
    "audit_schema_receipt": AuditSchemaReceipt,
    "audit_secret_exposure_static_report": AuditSecretExposureStaticReport,
    "audit_sink_receipt": AuditSinkReceipt,
    "authority_context_ref": AuthorityContextRef,
    "authority_reconstruction_packet": AuthorityReconstructionPacket,
    "boot_replay_audit_governance_report": BootReplayAuditGovernanceReport,
    "canonical_serialization_receipt": CanonicalSerializationReceipt,
    "certification_evidence_status": CertificationEvidenceStatus,
    "certification_gap_report": CertificationGapReport,
    "certification_packet_gap_report": CertificationPacketGapReport,
    "certification_packet_hash_receipt": CertificationPacketHashReceipt,
    "certification_packet_receipt": CertificationPacketReceipt,
    "certification_result": CertificationResult,
    "certification_result_hash_receipt": CertificationResultHashReceipt,
    "certification_result_receipt": CertificationResultReceipt,
    "certification_reuse_violation_report": CertificationReuseViolationReport,
    "certification_schema_audit_readiness_report": CertificationSchemaAuditReadinessReport,
    "certification_schema_integrity_report": CertificationSchemaIntegrityReport,
    "certification_schema_receipt": CertificationSchemaReceipt,
    "certification_schema_replay_readiness_report": CertificationSchemaReplayReadinessReport,
    "certification_scope_gap_report": CertificationScopeGapReport,
    "certification_scope_hash_receipt": CertificationScopeHashReceipt,
    "certification_scope_receipt": CertificationScopeReceipt,
    "certification_scope_status": CertificationScopeStatus,
    "certification_scope_widening_report": CertificationScopeWideningReport,
    "compliance_hash_gap_report": ComplianceHashGapReport,
    "compliance_hash_receipt": ComplianceHashReceipt,
    "context_hash_receipt": ContextHashReceipt,
    "critical_replay_audit_gap_report": CriticalReplayAuditGapReport,
    "downstream_review_evidence_ref": DownstreamReviewEvidenceRef,
    "evidence_contract_hash_receipt": EvidenceContractHashReceipt,
    "evidence_contract_ref": EvidenceContractRef,
    "expected_ref": ExpectedRef,
    "forbidden_disposition_absence_receipt": ForbiddenDispositionAbsenceReceipt,
    "forbidden_disposition_field_report": ForbiddenDispositionFieldReport,
    "hard_constraint_map": HardConstraintMap,
    "hash_algorithm_receipt": HashAlgorithmReceipt,
    "hash_binding_report_ref": HashBindingReportRef,
    "hash_binding_status": HashBindingStatus,
    "hash_mismatch_report": HashMismatchReport,
    "hmac_config_receipt": HmacConfigReceipt,
    "hmac_signature_receipt": HmacSignatureReceipt,
    "L5CertificationPacket": L5CertificationPacket,
    "L5CertificationResult": L5CertificationResult,
    "missing_audit_ref_static_report": MissingAuditRefStaticReport,
    "missing_receipt_report": MissingReceiptReport,
    "missing_replay_ref_static_report": MissingReplayRefStaticReport,
    "observed_ref": ObservedRef,
    "origin_trust_manifest_receipt": OriginTrustManifestReceipt,
    "orphan_artifact_report": OrphanArtifactReport,
    "orphan_receipt_report": OrphanReceiptReport,
    "orphan_span_report": OrphanSpanReport,
    "proposed_state_diff_hash_receipt": ProposedStateDiffHashReceipt,
    "receipt_chain_completeness_receipt": ReceiptChainCompletenessReceipt,
    "receipt_chain_report": ReceiptChainReport,
    "receipt_chain_report_ref": ReceiptChainReportRef,
    "receipt_cross_principal_report": ReceiptCrossPrincipalReport,
    "reclearance_receipt": ReclearanceReceipt,
    "reconstruction_gap_report": ReconstructionGapReport,
    "reconstruction_packet_hash_receipt": ReconstructionPacketHashReceipt,
    "reconstruction_packet_receipt": ReconstructionPacketReceipt,
    "reconstruction_status": ReconstructionStatus,
    "redaction_policy_ref": RedactionPolicyRef,
    "replay_envelope_receipt": ReplayEnvelopeReceipt,
    "replay_envelope_ref": ReplayEnvelopeRef,
    "replay_gap_report": ReplayGapReport,
    "replay_hash_binding_report": ReplayHashBindingReport,
    "replay_schema_receipt": ReplaySchemaReceipt,
    "replay_storage_receipt": ReplayStorageReceipt,
    "required_hash_gap_report": RequiredHashGapReport,
    "route_contract_ref": RouteContractRef,
    "runtime_audit_manifest_receipt": RuntimeAuditManifestReceipt,
    "runtime_certification_packet_receipt": RuntimeCertificationPacketReceipt,
    "runtime_hash_binding_report": RuntimeHashBindingReport,
    "runtime_reconstruction_readiness_report": RuntimeReconstructionReadinessReport,
    "runtime_replay_audit_certification_receipt": RuntimeReplayAuditCertificationReceipt,
    "runtime_replay_binding_receipt": RuntimeReplayBindingReceipt,
    "runtime_trace_completeness_report": RuntimeTraceCompletenessReport,
    "span_binding_receipt": SpanBindingReceipt,
    "stale_receipt_report": StaleReceiptReport,
    "standards_fingerprint_gap_report": StandardsFingerprintGapReport,
    "static_replay_audit_evidence_intake_receipt": StaticReplayAuditEvidenceIntakeReceipt,
    "static_replay_audit_gap_report": StaticReplayAuditGapReport,
    "static_replay_audit_governance_report": StaticReplayAuditGovernanceReport,
    "tamper_evidence_report": TamperEvidenceReport,
    "trace_audit_binding_receipt": TraceAuditBindingReceipt,
    "trace_binding_status": TraceBindingStatus,
    "trace_completeness_report": TraceCompletenessReport,
    "trace_completeness_report_ref": TraceCompletenessReportRef,
    "trace_correlation_receipt": TraceCorrelationReceipt,
    "trace_gap_report": TraceGapReport,
    "trace_replay_binding_receipt": TraceReplayBindingReceipt,
    "wall_clock_decision_field_report": WallClockDecisionFieldReport,
    "ADRRequiredReport": ADRRequiredReport,
    "adg_snapshot_ref": AdgSnapshotRef,
    "adr_required_report": AdrRequiredReport,
    "adr_status": AdrStatus,
    "affected_authority_surface_map": AffectedAuthoritySurfaceMap,
    "agent_registry_drift_report": AgentRegistryDriftReport,
    "architecture_drift_gap_report": ArchitectureDriftGapReport,
    "ArchitectureDriftReport": ArchitectureDriftReport,
    "architecture_drift_report": ArchitectureDriftReport,
    "branch_or_commit_ref": BranchOrCommitRef,
    "bypass_evidence_status": BypassEvidenceStatus,
    "bypass_wrapper_waiver_report": BypassWrapperWaiverReport,
    "config_with_logic_static_report": ConfigWithLogicStaticReport,
    "connector_audit_requirement_drift_report": ConnectorAuditRequirementDriftReport,
    "ConnectorConfigDriftReport": ConnectorConfigDriftReport,
    "connector_config_drift_report": ConnectorConfigDriftReport,
    "connector_credential_policy_drift_report": ConnectorCredentialPolicyDriftReport,
    "connector_domain_drift_report": ConnectorDomainDriftReport,
    "connector_grant_drift_report": ConnectorGrantDriftReport,
    "connector_registry_drift_report": ConnectorRegistryDriftReport,
    "connector_retention_drift_report": ConnectorRetentionDriftReport,
    "connector_scope_widening_report": ConnectorScopeWideningReport,
    "current_adg_snapshot_ref": CurrentAdgSnapshotRef,
    "deleted_gate_static_report": DeletedGateStaticReport,
    "dependency_direction_drift_report": DependencyDirectionDriftReport,
    "direct_external_write_static_report": DirectExternalWriteStaticReport,
    "direct_sdk_bypass_static_report": DirectSdkBypassStaticReport,
    "DirectWritePathStaticReport": DirectWritePathStaticReport,
    "direct_write_path_static_report": DirectWritePathStaticReport,
    "direct_write_waiver_report": DirectWriteWaiverReport,
    "downstream_consumer_static_readiness_map": DownstreamConsumerStaticReadinessMap,
    "downstream_static_impact_report": DownstreamStaticImpactReport,
    "downstream_static_regression_impact_report": DownstreamStaticRegressionImpactReport,
    "drift_category_map": DriftCategoryMap,
    "egress_wrapper_static_report": EgressWrapperStaticReport,
    "exception_taxonomy_drift_report": ExceptionTaxonomyDriftReport,
    "fallback_chain_drift_report": FallbackChainDriftReport,
    "golden_architecture_snapshot_ref": GoldenArchitectureSnapshotRef,
    "golden_audit_replay_snapshot_ref": GoldenAuditReplaySnapshotRef,
    "golden_connector_snapshot_ref": GoldenConnectorSnapshotRef,
    "golden_policy_snapshot_ref": GoldenPolicySnapshotRef,
    "golden_prompt_snapshot_ref": GoldenPromptSnapshotRef,
    "golden_registry_snapshot_ref": GoldenRegistrySnapshotRef,
    "golden_route_snapshot_ref": GoldenRouteSnapshotRef,
    "GoldenSnapshotComparisonReport": GoldenSnapshotComparisonReport,
    "golden_snapshot_comparison_report": GoldenSnapshotComparisonReport,
    "golden_snapshot_gap_report": GoldenSnapshotGapReport,
    "golden_snapshot_ref": GoldenSnapshotRef,
    "hard_constraint_change_report": HardConstraintChangeReport,
    "hardcoded_model_literal_static_report": HardcodedModelLiteralStaticReport,
    "HiddenEgressStaticReport": HiddenEgressStaticReport,
    "hidden_egress_static_report": HiddenEgressStaticReport,
    "hidden_egress_waiver_report": HiddenEgressWaiverReport,
    "hitl_direct_write_static_report": HitlDirectWriteStaticReport,
    "hitl_threshold_drift_report": HitlThresholdDriftReport,
    "l4_direct_write_report": L4DirectWriteReport,
    "l6_current_run_mutation_static_report": L6CurrentRunMutationStaticReport,
    "layer_boundary_drift_report": LayerBoundaryDriftReport,
    "learning_boundary_drift_report": LearningBoundaryDriftReport,
    "managed_workflow_autonomy_drift_report": ManagedWorkflowAutonomyDriftReport,
    "missing_audit_metadata_report": MissingAuditMetadataReport,
    "missing_replay_metadata_report": MissingReplayMetadataReport,
    "newly_introduced_bypass_report": NewlyIntroducedBypassReport,
    "orphan_registry_ref": OrphanRegistryRef,
    "orphan_registry_reference_report": OrphanRegistryReferenceReport,
    "policy_drift_status": PolicyDriftStatus,
    "PolicyWeakeningReport": PolicyWeakeningReport,
    "policy_weakening_report": PolicyWeakeningReport,
    "policy_weakening_waiver_report": PolicyWeakeningWaiverReport,
    "prompt_assembly_boundary_drift_report": PromptAssemblyBoundaryDriftReport,
    "prompt_authority_boundary_drift_report": PromptAuthorityBoundaryDriftReport,
    "PromptDriftReport": PromptDriftReport,
    "prompt_drift_report": PromptDriftReport,
    "prompt_registry_compatibility_drift_report": PromptRegistryCompatibilityDriftReport,
    "prompt_registry_drift_report": PromptRegistryDriftReport,
    "prompt_schema_binding_drift_report": PromptSchemaBindingDriftReport,
    "prompt_shadow_artifact_report": PromptShadowArtifactReport,
    "prompt_slot_map_drift_report": PromptSlotMapDriftReport,
    "prompt_stable_prefix_drift_report": PromptStablePrefixDriftReport,
    "proposed_diff_boundary_report": ProposedDiffBoundaryReport,
    "refusal_taxonomy_drift_report": RefusalTaxonomyDriftReport,
    "registry_digest_drift_report": RegistryDigestDriftReport,
    "RegistryDriftReport": RegistryDriftReport,
    "registry_drift_report": RegistryDriftReport,
    "registry_drift_status": RegistryDriftStatus,
    "registry_scope_widening_report": RegistryScopeWideningReport,
    "registry_substitution_static_report": RegistrySubstitutionStaticReport,
    "relaxed_scope_report": RelaxedScopeReport,
    "retrieval_boundary_drift_report": RetrievalBoundaryDriftReport,
    "risk_tier_mapping_drift_report": RiskTierMappingDriftReport,
    "rollback_plan_receipt": RollbackPlanReceipt,
    "route_budget_drift_report": RouteBudgetDriftReport,
    "route_contract_integrity_report": RouteContractIntegrityReport,
    "route_topology_drift_report": RouteTopologyDriftReport,
    "route_topology_static_report": RouteTopologyStaticReport,
    "RouteWorkflowDriftReport": RouteWorkflowDriftReport,
    "route_workflow_drift_report": RouteWorkflowDriftReport,
    "sector_overlay_drift_report": SectorOverlayDriftReport,
    "stale_registry_ref": StaleRegistryRef,
    "stale_waiver_report": StaleWaiverReport,
    "standards_fingerprint_drift_report": StandardsFingerprintDriftReport,
    "static_audit_gap_report": StaticAuditGapReport,
    "StaticBypassWrapperReport": StaticBypassWrapperReport,
    "static_bypass_wrapper_report": StaticBypassWrapperReport,
    "StaticCertificationReadinessReport": StaticCertificationReadinessReport,
    "static_certification_readiness_report": StaticCertificationReadinessReport,
    "StaticDriftEvidencePacket": StaticDriftEvidencePacket,
    "static_drift_hash_receipt": StaticDriftHashReceipt,
    "static_drift_report": StaticDriftReport,
    "static_governance_audit_receipt": StaticGovernanceAuditReceipt,
    "static_governance_replay_receipt": StaticGovernanceReplayReceipt,
    "StaticGovernanceReviewPacket": StaticGovernanceReviewPacket,
    "static_governance_status": StaticGovernanceStatus,
    "static_readiness_status_receipt": StaticReadinessStatusReceipt,
    "static_reconstruction_packet": StaticReconstructionPacket,
    "StaticRegressionEvidenceReport": StaticRegressionEvidenceReport,
    "static_regression_evidence_report": StaticRegressionEvidenceReport,
    "static_regression_gap_report": StaticRegressionGapReport,
    "static_regression_hash_receipt": StaticRegressionHashReceipt,
    "static_regression_status": StaticRegressionStatus,
    "static_replay_gap_report": StaticReplayGapReport,
    "static_report_hash_chain_receipt": StaticReportHashChainReceipt,
    "static_review_gap_report": StaticReviewGapReport,
    "static_review_packet_hash_receipt": StaticReviewPacketHashReceipt,
    "static_review_packet_receipt": StaticReviewPacketReceipt,
    "structure_drift_status": StructureDriftStatus,
    "tool_registry_drift_report": ToolRegistryDriftReport,
    "unauthorized_connector_client_report": UnauthorizedConnectorClientReport,
    "unauthorized_http_client_report": UnauthorizedHttpClientReport,
    "unresolved_static_gap_report": UnresolvedStaticGapReport,
    "uwg_bypass_static_report": UwgBypassStaticReport,
    "waiver_compatibility_report": WaiverCompatibilityReport,
    "waiver_presence_report": WaiverPresenceReport,
    "waiver_scope_mismatch_report": WaiverScopeMismatchReport,
    "waiver_status": WaiverStatus,
    "weakened_default_report": WeakenedDefaultReport,
    "workflow_boundary_drift_report": WorkflowBoundaryDriftReport,
    "wrapper_authority_expansion_report": WrapperAuthorityExpansionReport,
    "wrapper_target_resolution_report": WrapperTargetResolutionReport,
    "write_path_drift_report": WritePathDriftReport,
    "blueprint_evidence_ref": BlueprintEvidenceRef,
    "capability_scope_ref": CapabilityScopeRef,
    "egress_cert_ref": EgressCertRef,
    "hitl_reclearance_ref": HitlReclearanceRef,
    "L5SnapshotVerificationReceipt": L5SnapshotVerificationReceipt,
    "live_snapshot_ref": LiveSnapshotRef,
    "match_status": MatchStatus,
    "origin_trust_ref": OriginTrustRef,
    "packet_ref": PacketRef,
    "policy_evidence_ref": PolicyEvidenceRef,
    "principal_ref": PrincipalRef,
    "PromptEnvelope": PromptEnvelope,
    "registry_evidence_ref": RegistryEvidenceRef,
    "replay_audit_ref": ReplayAuditRef,
    "replay_snapshot_ref": ReplaySnapshotRef,
    "sandbox_scope_ref": SandboxScopeRef,
    "static_governance_ref": StaticGovernanceRef,
    "test_exit_requires_l5_reclearance_for_human_modified_packet": TestExitRequiresL5ReclearanceForHumanModifiedPacket,
    "test_l2_e2_rejects_missing_l5_binding_for_governed_packet": TestL2E2RejectsMissingL5BindingForGovernedPacket,
}

ALL_OUTPUT_NAMES: Final[frozenset[str]] = frozenset(CONTRACT_REGISTRY.keys())


def get_contract(name: str) -> type[L5OutputBase]:
    """Lookup contract class by canonical doctrine name. Raises KeyError."""
    return CONTRACT_REGISTRY[name]


__all__ = ["CONTRACT_REGISTRY", "ALL_OUTPUT_NAMES", "get_contract"]
