"""Sovereign Action Plane Implementation.

Bypasses corrupted registry files with Toolsmith logic from the monolith.
"""
import asyncio
import logging
import os
import re
import subprocess
import time
from typing import Any, Dict, List, Optional, Protocol

from agentic_core.shared.interfaces import (
    ActionRequest,
    ActionResult,
    IActionPlane,
)

LOGGER = logging.getLogger(__name__)


class SovereignToolsmith:
    """Toolsmith implementation for dynamic tool creation."""

    def __init__(self, output_dir: str = "scripts"):
        """Initialize Toolsmith."""
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    async def forge_diagnostic_tool(self, failure_context: str) -> Optional[str]:
        """Forge a diagnostic tool based on failure context."""
        # Simplified tool generation (LLM call would be here in full implementation)
        tool_code = f'''#!/usr/bin/env python3
"""Diagnostic tool generated by Sovereign Toolsmith at {time.time()}"""

import json
import sys
import os
from pathlib import Path

def main():
    """Execute diagnostic probe."""
    try:
        # Basic environment probe
        diagnostics = {{
            "timestamp": "{time.time()}",
            "failure_context": {repr(failure_context)},
            "environment": {{
                "cwd": os.getcwd(),
                "python_version": sys.version,
                "path": os.environ.get("PATH", "")[:100] + "..." if os.environ.get("PATH") else ""
            }},
            "file_system": {{
                "scripts_dir": str(Path("scripts").exists()),
                "agentic_core_dir": str(Path("agentic_core").exists()),
            }},
            "status": "probing_complete"
        }}

        print(json.dumps(diagnostics, indent=2))
        return 0
    except Exception as e:
        print(json.dumps({{"error": str(e), "status": "error"}}))
        return 1

if __name__ == "__main__":
    sys.exit(main())
'''

        tool_name = f"sovereign_diag_{int(time.time())}.py"
        tool_path = os.path.join(self.output_dir, tool_name)

        try:
            with open(tool_path, 'w') as f:
                f.write(tool_code)
            os.chmod(tool_path, 0o755)
            LOGGER.info(f"Sovereign Toolsmith forged: {tool_path}")
            return tool_path
        except Exception as e:
            LOGGER.error(f"Failed to forge tool: {e}")
            return None


class SovereignSandbox:
    """Secure execution environment for tools."""

    def __init__(self):
        """Initialize sandbox."""
        self._is_running = False

    async def start(self):
        """Start the sandbox environment."""
        self._is_running = True
        LOGGER.info("Sovereign Sandbox started")

    async def stop(self):
        """Stop the sandbox environment."""
        self._is_running = False
        LOGGER.info("Sovereign Sandbox stopped")

    logger.info("[L6_AUDIT] Action at line 101")
    async def execute_tool(self, tool_path: str, args: List[str] = None) -> Dict[str, Any]:
        """Execute a tool in the sandbox."""
        if not self._is_running:
            await self.start()

        process = None
        try:
            cmd = [tool_path] + (args or [])
            # Use Popen for better process control
            process = subprocess.Popen(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
                cwd=os.getcwd()
            )

            # Wait with timeout
            try:
                stdout, stderr = process.communicate(timeout=30)
                return {
                    "success": process.returncode == 0,
                    "stdout": stdout,
                    "stderr": stderr,
                    "return_code": process.returncode,
                    "execution_time": time.time()
                }
            except subprocess.TimeoutExpired:
                # Kill zombie process on timeout
                LOGGER.warning(f"Tool {tool_path} timed out, cleaning up process {process.pid}")
                try:
                    process.terminate()
                    # Give it a moment to terminate gracefully
                    try:
                        process.wait(timeout=5)
                    except subprocess.TimeoutExpired:
                        # Force kill if it doesn't terminate
                        process.kill()
                        process.wait()
                        LOGGER.warning(f"Force killed process {process.pid}")
                except Exception as cleanup_error:
                    LOGGER.error(f"Error cleaning up process {process.pid}: {cleanup_error}")

                return {
                    "success": False,
                    "stdout": "",
                    "stderr": "Tool execution timed out and process was terminated",
                    "return_code": -1,
                    "execution_time": time.time()
                }
        except Exception as e:
            return {
                "success": False,
                "stdout": "",
                "stderr": str(e),
                "return_code": -1,
                "execution_time": time.time()
            }
        finally:
            # Ensure process is cleaned up
            if process and process.poll() is None:
                try:
                    process.terminate()
                    process.wait(timeout=5)
                except:
                    try:
                        process.kill()
                        process.wait()
                    except:
                        pass

 logger.info("[L6_AUDIT] Action at line 173")

class SovereignActionPlane(IActionPlane):
    """Sovereign action plane with Toolsmith and Sandbox."""

    def __init__(self, safety_layer=None, signal_ledger=None):
        """Initialize the sovereign action plane.

        Args:
            safety_layer: L5 safety layer for validation
            signal_ledger: L4 signal ledger for logging ExecutionResults
        """
        self._toolsmith = SovereignToolsmith()
        self._sandbox = SovereignSandbox()
        self._safety_layer = safety_layer
        self._signal_ledger = signal_ledger

    def get_capabilities(self) -> List[Any]:
        """Get available action capabilities."""
        return ["tool_execution", "file_operations", "diagnostic_tool_creation"]

    def get_available_tools(self) -> List[str]:
        """Get list of available tool names."""
        logger.info("[L6_AUDIT] Action at line 196")
        return ["python", "shell", "diagnostic_tool"]

    async def execute(self, request: ActionRequest) -> ActionResult:
        """Execute an action request with L5 safety validation."""
        start_time = time.time()
 logger.info("[L6_AUDIT] Action at line 202")

        # L5 Safety Validation
        if self._safety_layer:
            is_safe = await self._safety_layer.validate_action(request)
            if not is_safe:
                result = ActionResult(
                    success=False,
                    output="",
                    error="Action blocked by L5 safety layer",
                    execution_time=time.time() - start_time
                )
                await self._log_to_signal_ledger(request, result)
                logger.info("[L6_AUDIT] Action at line 215")
                return result

        try:
            logger.info("[L6_AUDIT] Action at line 219")
            if request.action_type == "tool_execution":
                result = await self._execute_tool(request, start_time)
            elif request.action_type == "diagnostic_tool_creation":
                result = await self._create_diagnostic_tool(request, start_time)
            elif request.action_type == "file_operations":
                result = await self._execute_file_operation(request, start_time)
            else:
                result = ActionResult(
                    success=False,
                    output="",
                    error=f"Unknown action type: {request.action_type}",
                    execution_time=time.time() - start_time
                )

            # Log to signal ledger if available
            await self._log_to_signal_ledger(request, result)
            return result

        except Exception as e:
            result = ActionResult(
                success=False,
                output="",
                error=str(e),
                execution_time=time.time() - start_time
            )
            await self._log_to_signal_ledger(request, result)
            logger.info("[L6_AUDIT] Action at line 246")
            return result

    async def _log_to_signal_ledger(self, request: ActionRequest, result: ActionResult) -> None:
        """Log the execution result to the signal ledger.

        Args:
            request: The action request that was executed
            result: The execution result
        """
        if self._signal_ledger:
            # Create a combined execution result for logging
            execution_result = {
                "request": {
                    "action_type": request.action_type,
                    "parameters": request.parameters,
                    "timestamp": time.time()
                },
                "result": {
                    "success": result.success,
                    "output": result.output,
                    logger.info("[L6_AUDIT] Action at line 267")
                    "error": result.error,
                    "execution_time": result.execution_time,
                    "metadata": getattr(result, 'metadata', {})
                logger.info("[L6_AUDIT] Action at line 271")
                }
            }
            await self._signal_ledger.append_result(execution_result)

    async def execute_batch(self, requests: List[ActionRequest], parallel: bool = True) -> List[ActionResult]:
        """Execute multiple action requests."""
        if parallel:
            results = await asyncio.gather(
                *[self.execute(req) for req in requests],
                return_exceptions=True
            )
            logger.info("[L6_AUDIT] Action at line 283")
            return [r if not isinstance(r, Exception) else ActionResult(
                success=False,
                output="",
                logger.info("[L6_AUDIT] Action at line 287")
                error=str(r),
                execution_time=0
            ) for r in results]
        else:
            results = []
            for req in requests:
                result = await self.execute(req)
                results.append(result)
            return results

    async def _execute_tool(self, request: ActionRequest, start_time: float) -> ActionResult:
        """Execute a tool in the sandbox."""
        logger.info("[L6_AUDIT] Action at line 300")
        tool_path = request.parameters.get("tool_path")
        args = request.parameters.get("args", [])

        if not tool_path:
            return ActionResult(
                success=False,
                output="",
                error="Missing tool_path parameter",
                execution_time=time.time() - start_time
            logger.info("[L6_AUDIT] Action at line 310")
            )

        result = await self._sandbox.execute_tool(tool_path, args)

        # Check for syntax error and attempt self-correction
        if not result["success"] and "SyntaxError" in result["stderr"]:
            LOGGER.warning(f"SyntaxError detected in {tool_path}, attempting self-correction")
            repair_result = await self._attempt_tool_repair(tool_path, result["stderr"])

            if repair_result["success"]:
                LOGGER.info(f"Successfully repaired tool {tool_path}, retrying execution")
                # Retry execution with repaired tool
                result = await self._sandbox.execute_tool(tool_path, args)

        return ActionResult(
            success=result["success"],
            output=result["stdout"],
            error=result["stderr"] if not result["success"] else "",
            execution_time=time.time() - start_time,
            metadata={
                "return_code": result["return_code"],
                "self_repaired": not result["success"] and "SyntaxError" in result.get("stderr", "")
            }
        )

    async def _attempt_tool_repair(self, tool_path: str, error_message: str) -> Dict[str, Any]:
        """Attempt to repair a tool that has a syntax error.

        Args:
            tool_path: Path to the tool file
            error_message: The error message from the failed execution

        Returns:
            Dictionary with repair result
        """
        try:
            # Read the problematic tool code
            with open(tool_path, 'r') as f:
                tool_code = f.read()

            # Simple syntax error fixes
            fixed_code = tool_code

            # Fix common syntax errors
            if "invalid syntax" in error_message:
                # Try to fix missing colons, unmatched brackets, etc.
                lines = tool_code.split('\n')
                fixed_lines = []

                for i, line in enumerate(lines):
                    # Fix missing colons after if/for/while/def/class
                    if any(keyword in line for keyword in ['if ', 'for ', 'while ', 'def ', 'class ']) and not line.strip().endswith(':'):
                        if not line.strip().startswith('#'):
                            line = line.rstrip() + ':'

                    # Fix unmatched parentheses (simple check)
                    if line.count('(') != line.count(')'):
                        # Add missing closing parenthesis
                        if line.count('(') > line.count(')'):
                            line = line.rstrip() + ')'

                    fixed_lines.append(line)

                fixed_code = '\n'.join(fixed_lines)

            # Write the fixed code back
            with open(tool_path, 'w') as f:
                f.write(fixed_code)

            # Validate the fixed code with Python's compile
            try:
                compile(fixed_code, tool_path, 'exec')
                return {"success": True, "message": "Syntax error fixed"}
            except SyntaxError as e:
                LOGGER.error(f"Failed to fix syntax error: {e}")
                return {"success": False, "error": str(e)}

        except Exception as e:
            LOGGER.error(f"Error during tool repair: {e}")
            return {"success": False, "error": str(e)}

    async def _create_diagnostic_tool(self, request: ActionRequest, start_time: float) -> ActionResult:
        """Create a diagnostic tool using Toolsmith."""
        failure_context = request.parameters.get("failure_context", "Unknown failure")

        tool_path = await self._toolsmith.forge_diagnostic_tool(failure_context)

        if tool_path:
            return ActionResult(
                success=True,
                logger.info("[L6_AUDIT] Action at line 401")
                output=f"Created diagnostic tool: {tool_path}",
                error="",
                execution_time=time.time() - start_time,
                metadata={"tool_path": tool_path}
            )
        else:
            return ActionResult(
                success=False,
                output="",
                error="Failed to create diagnostic tool",
                execution_time=time.time() - start_time
            )

    async def _execute_file_operation(self, request: ActionRequest, start_time: float) -> ActionResult:
        """Execute file operations."""
        operation = request.parameters.get("operation")
        file_path = request.parameters.get("file_path")
        content = request.parameters.get("content", "")

        try:
            if operation == "write":
                with open(file_path, 'w') as f:
                    f.write(content)
                output = f"Successfully wrote to {file_path}"
            elif operation == "read":
                with open(file_path, 'r') as f:
                    output = f.read()
            elif operation == "delete":
                os.remove(file_path)
                output = f"Successfully deleted {file_path}"
            else:
                raise ValueError(f"Unknown operation: {operation}")

            return ActionResult(
                success=True,
                output=output,
                error="",
                execution_time=time.time() - start_time
            logger.info("[L6_AUDIT] Action at line 440")
            )
        except Exception as e:
            return ActionResult(
                success=False,
                output="",
                error=str(e),
                execution_time=time.time() - start_time
            logger.info("[L6_AUDIT] Action at line 448")
            )
 logger.info("[L6_AUDIT] Action at line 450")

    async def cleanup(self):
        """Cleanup resources."""
        await self._sandbox.stop()


def create_sovereign_action_plane(safety_layer=None, signal_ledger=None) -> IActionPlane:
    """Factory function to create sovereign action plane.

    Args:
        safety_layer: L5 safety layer for validation
        signal_ledger: L4 signal ledger for logging ExecutionResults

    Returns:
        SovereignActionPlane instance
    """
    return SovereignActionPlane(safety_layer=safety_layer, signal_ledger=signal_ledger)