# This file was regenerated by Phase 3 using the semantic cache.
# Do not edit this file directly; edits may be overwritten.

"""Stack-specific agent implementations for v10.7."""

# from archives.legacy_resume_gen.Agentic-Workflow-10_7_main.prompting import PromptEngineerAgent...

# from archives.legacy_resume_gen.Agentic-Workflow-10_7_main.rag import RAG_SearchAgent  # INVALI...

__all__ = [
    # Models
    "SpecialistDraftPacket",
    "EvidenceClarificationRecord",
    "EvidenceBriefRecord",
    "EvidenceLiaisonPacket",
    "CritiqueFindingRecord",
    "CritiquePanelPacket",
    # Safety
    "PIISanitizerAgent",
    "BiasDetectorAgent",
    "PromptInjectionDetectorAgent",
    "ConstitutionalReviewerAgent",
    # Strategy
    "QueryComplexityClassifier",
    "ToTStrategistAgent",
    # Prompting
    "PromptEngineerAgent",
    # RAG
    "RAG_SearchAgent",
    # Drafting
    "StructureLeadAgent",
    "NarrativeStylistAgent",
    "ComplianceEditorAgent",
    "EvidenceLiaisonAgent",
    "CritiqueRoutingPanel",
    "DraftingGuildCoordinator",
    # Bullet
    "BulletEntityExtractionAgent",
    "BulletMetricsEnrichmentAgent",
    "BulletNarrativeSynthesisAgent",
    "BulletEvidenceLinkerAgent",
    "BulletConfidenceScoringAgent",
    "BulletCoordinatorAgent",
    "BulletProvenanceAuditorAgent",
    "AsyncBulletGeneratorAgent",
    "AsyncBulletCritiqueAgent",
    # HIL
    "VirtualReviewerPersonaAgent",
    "VirtualReviewerCouncilAgent",
    "HILFeedbackSummarizerAgent",
    "HILReconciliationAgent",
    "HILAmbiguityDetectorAgent",
    "HILFeedbackRouterAgent",
]
