"""Auto-generated flattened view for meta/test_advanced_meta.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "meta/test_advanced_meta.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import pytest
from types import MethodType

from core_v10_7 import (
    AdvancedMetaLearner,
    ConfigV10_7,
    GeneratedPrompts,
    MetricsCollector,
    StrategyPlan,
)
from agent_stacks_v10_8.components.prompting import PromptEngineerAgent


@pytest.mark.asyncio
async def test_advanced_meta_learner_reports_when_enabled():
    config = ConfigV10_7("master_config_v10_7.json")
    metrics = MetricsCollector()
    learner = AdvancedMetaLearner(config=config, metrics=metrics)

    assert learner.enabled() is False

    config.meta_learning_advanced_config.enabled = True
    assert learner.enabled() is True
    assert learner.analyze("wf-meta") == {"prune_boost": True}


@pytest.mark.asyncio
async def test_prompt_stack_receives_meta_hints(workflow_context):
    workflow_context.config.meta_learning_advanced_config.enabled = True
    workflow_context.advanced_meta_learner.config.meta_learning_advanced_config.enabled = True

    agent = PromptEngineerAgent(workflow_context)

    strategy = StrategyPlan(
        strategy_name="Expansion",
        focus_areas=["impact"],
        key_achievements_to_highlight=["led growth"],
        tone="confident",
    )
    prompts = GeneratedPrompts(
        bullet_generation_prompt="Use quantified achievements.",
        critique_prompt="Surface issues",
        qa_prompts={"qa": "check"},
    )

    async def fake_execute(self, *_args, **_kwargs):
        return {"prompts": prompts}, prompts

    async def fake_self_correct(self, _strategy, _complexity, _workflow_id, base_result, _validated_output):
        return base_result

    agent._execute_prompt_engineer = MethodType(fake_execute, agent)
    agent._maybe_self_correct = MethodType(fake_self_correct, agent)

    state: dict = {}
    result = await agent.run_async(strategy, "simple", "wf-meta", state=state)

    assert state["meta_hints"]["prune_boost"] is True
    assert result["prompts"] == prompts
"""
}

ORIGINAL_MODULE_NAME = "tests.meta.test_advanced_meta"
FLAT_MODULE_NAME = "tests_flat.meta__test_advanced_meta"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
