"""Auto-generated flattened view for auto_tuning/test_auto_tuning_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "auto_tuning/test_auto_tuning_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import copy

import pytest

from core_v10_7 import ConfigV10_7, MetricsCollector, PolicyAutoTuner, TuningProfile


CONFIG_PATH = "master_config_v10_7.json"


def _enabled_config() -> ConfigV10_7:
    cfg = ConfigV10_7(CONFIG_PATH)
    cfg.auto_tuning_config.enabled = True
    return cfg


def _make_metrics(*entries):
    metrics = MetricsCollector()
    for entry in entries:
        metrics.metrics.append(entry)
    return metrics


def _drafting_metric(duration_ms: float, workflow_id: str = "wf-1"):
    return {
        "agent_name": "DraftingStrategistTool",
        "task_name": "tool_drafting_llm",
        "duration_ms": duration_ms,
        "success": True,
        "metadata": {"workflow_id": workflow_id},
    }


def _rag_metric(duration_ms: float, workflow_id: str = "wf-1"):
    return {
        "agent_name": "RAG_SearchAgent",
        "task_name": "run_agentic_rag",
        "duration_ms": duration_ms,
        "success": True,
        "metadata": {"workflow_id": workflow_id},
    }


def _drafting_signal_metric(stage: str):
    return {
        "agent_name": "ArbitrationEngine",
        "task_name": "run_check",
        "duration_ms": 5,
        "success": True,
        "metadata": {"stage": stage, "workflow_id": "wf-2"},
    }


def test_auto_tuning_disabled_no_change():
    cfg = ConfigV10_7(CONFIG_PATH)
    metrics = _make_metrics(_drafting_metric(2500))
    tuner = PolicyAutoTuner(cfg, metrics)
    profile = TuningProfile()
    before = copy.deepcopy(profile.model_dump())

    updated = tuner.tune_profile(profile)

    assert updated.temperature == before["temperature"]
    assert updated.history == []
    assert updated.drafting_expand_summary == before["drafting_expand_summary"]


def test_temperature_adjusts_with_latency():
    cfg = _enabled_config()
    metrics = _make_metrics(_drafting_metric(4000))
    tuner = PolicyAutoTuner(cfg, metrics)
    profile = TuningProfile(temperature=0.5)
    original_prune = profile.prune_factor

    updated = tuner.tune_profile(profile)

    assert pytest.approx(updated.temperature) == 0.45
    assert updated.prune_factor == original_prune


def test_rag_force_multi_tool_engages():
    cfg = _enabled_config()
    metrics = _make_metrics(
        _drafting_metric(2000),
        _rag_metric(cfg.auto_tuning_config.latency_target_ms * 1.2),
    )
    tuner = PolicyAutoTuner(cfg, metrics)
    profile = TuningProfile()

    updated = tuner.tune_profile(profile)

    assert updated.rag_force_multi_tool is True


def test_drafting_overrides_trigger():
    cfg = _enabled_config()
    metrics = _make_metrics(
        _drafting_metric(2000),
        _drafting_signal_metric("draft_post_assembly"),
    )
    tuner = PolicyAutoTuner(cfg, metrics)
    profile = TuningProfile()

    updated = tuner.tune_profile(profile)

    assert updated.drafting_expand_summary is True
    assert updated.drafting_boost_metrics is True


def test_profile_history_populates():
    cfg = _enabled_config()
    metrics = _make_metrics(_drafting_metric(2000))
    tuner = PolicyAutoTuner(cfg, metrics)
    profile = TuningProfile()

    updated = tuner.tune_profile(profile)

    assert len(updated.history) == 1
    record = updated.history[0]
    assert "timestamp" in record
    assert record["temperature"] == updated.temperature
    assert updated.last_update >= record["timestamp"]
"""
}

ORIGINAL_MODULE_NAME = "tests.auto_tuning.test_auto_tuning_v10_7"
FLAT_MODULE_NAME = "tests_flat.auto_tuning__test_auto_tuning_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
