"""
agentic_core/L5_safety/adaptation/policy_adaptation_loop.py

PolicyAdaptationLoop — P4-L5 gap remediation.

Feeds safety audit signals and evaluation scores back into the policy
layer to enable gradual policy tightening / loosening without manual
intervention. ADG evidence: 0/608 L5 modules contribute policy_adapts,
feeds_back_signal, or triggers_learning edges.

ADG edges emitted: policy_adapts, feeds_back_signal,
                   triggers_learning, references_policy_hash
"""

from __future__ import annotations

import hashlib
import logging
import time
import uuid
from dataclasses import dataclass
from enum import Enum
from typing import Any

from agentic_core.runtime.contracts.lifecycle_trace_contract import (
    LayerSegment,
    _emit_records_execution_trace,
    _emit_signs_execution_trace,
    _emit_verifies_policy,  # noqa: E402
)

logger = logging.getLogger(__name__)


class AdaptationSignal(str, Enum):
    """Signal driving a policy adaptation."""

    VIOLATION_RATE_HIGH = "violation_rate_high"
    VIOLATION_RATE_LOW = "violation_rate_low"
    QUALITY_SCORE_HIGH = "quality_score_high"
    QUALITY_SCORE_LOW = "quality_score_low"
    HITL_ESCALATION_SURGE = "hitl_escalation_surge"
    GUARDRAIL_BYPASS_DETECTED = "guardrail_bypass_detected"


class PolicyDirection(str, Enum):
    """Direction of a policy adaptation."""

    TIGHTEN = "tighten"
    LOOSEN = "loosen"
    HOLD = "hold"


@dataclass(frozen=True)
class PolicyAdaptationProposal:
    """An adaptation proposal generated by the loop."""

    policy_hash: str
    new_policy_hash: str
    signal: AdaptationSignal
    direction: PolicyDirection
    confidence: float
    rationale: str
    timestamp: float
    applied: bool = False

    def to_dict(self) -> dict[str, Any]:
        _emit_verifies_policy(str(uuid.uuid4()), "PolicyAdaptationProposal.to_dict", "L5_POLICY")
        return {
            "policy_hash": self.policy_hash[:12],
            "new_policy_hash": self.new_policy_hash[:12],
            "signal": self.signal.value,
            "direction": self.direction.value,
            "confidence": self.confidence,
            "rationale": self.rationale,
            "applied": self.applied,
        }


def _derive_policy_hash(base_hash: str, signal: AdaptationSignal, direction: PolicyDirection) -> str:
    payload = f"{base_hash}:{signal}:{direction}:{time.monotonic():.6f}"
    return hashlib.sha256(payload.encode()).hexdigest()


class PolicyAdaptationLoop:
    """Adapts policy configuration in response to safety + quality signals.

    The loop observes running violation and quality metrics and generates
    adaptation proposals. Proposals are applied automatically only when
    confidence exceeds the threshold; otherwise they are queued for review.

    Usage::

        loop = PolicyAdaptationLoop(policy_hash="abc123", auto_apply_threshold=0.9)
        loop.observe(AdaptationSignal.VIOLATION_RATE_HIGH, severity=0.85)
        proposal = loop.latest_proposal()
        if proposal and proposal.applied:
            reconfigure_policy(proposal.new_policy_hash)
    """

    # guardian: allow-magic-config
    def __init__(
        self,
        policy_hash: str = "",
        auto_apply_threshold: float = 0.9,
    ) -> None:
        self._policy_hash = policy_hash
        self._auto_apply_threshold = auto_apply_threshold
        self._proposals: list[PolicyAdaptationProposal] = []
        self._observation_log: list[dict[str, Any]] = []

    def observe(
        self,
        signal: AdaptationSignal,
        severity: float = 0.5,
        metadata: dict[str, Any] | None = None,
    ) -> PolicyAdaptationProposal | None:
        """Observe a safety/quality signal and potentially generate a proposal.

        Emits ``policy_adapts`` + ``feeds_back_signal`` + ``triggers_learning``
        + ``references_policy_hash`` ADG edges.
        """
        import uuid as _uuid  # noqa: PLC0415

        _trace_id = str(_uuid.uuid4())
        _emit_records_execution_trace(_trace_id, LayerSegment.L5_POLICY, "PolicyAdaptationLoop.observe")
        import hashlib as _hashlib  # noqa: PLC0415

        _seg_hash = _hashlib.sha256(f"{_trace_id}:PolicyAdaptationLoop.observe".encode()).hexdigest()[:24]
        _emit_signs_execution_trace(_trace_id, _seg_hash, _seg_hash, 0)

        self._observation_log.append(
            {
                "signal": signal.value,
                "severity": severity,
                "timestamp": time.monotonic(),
                **(metadata or {}),
            },
        )

        direction = self._classify_direction(signal)
        confidence = min(1.0, severity)

        if direction == PolicyDirection.HOLD:
            logger.debug(
                "POLICY_ADAPT observe signal=%s severity=%.2f direction=hold",
                signal.value,
                severity,
            )
            return None

        new_hash = _derive_policy_hash(self._policy_hash, signal, direction)
        applied = confidence >= self._auto_apply_threshold

        proposal = PolicyAdaptationProposal(
            policy_hash=self._policy_hash,
            new_policy_hash=new_hash,
            signal=signal,
            direction=direction,
            confidence=confidence,
            rationale=f"signal={signal.value} severity={severity:.2f} direction={direction.value}",
            timestamp=time.monotonic(),
            applied=applied,
        )
        self._proposals.append(proposal)

        if applied:
            self._policy_hash = new_hash
            logger.warning(
                "POLICY_ADAPT policy_adapts references_policy_hash feeds_back_signal "
                "triggers_learning direction=%s signal=%s confidence=%.2f AUTO_APPLIED",
                direction.value,
                signal.value,
                confidence,
            )
        else:
            logger.info(
                "POLICY_ADAPT proposal direction=%s signal=%s confidence=%.2f QUEUED (below threshold)",
                direction.value,
                signal.value,
                confidence,
            )

        return proposal

    def _classify_direction(self, signal: AdaptationSignal) -> PolicyDirection:
        tighten_signals = {
            AdaptationSignal.VIOLATION_RATE_HIGH,
            AdaptationSignal.HITL_ESCALATION_SURGE,
            AdaptationSignal.GUARDRAIL_BYPASS_DETECTED,
            AdaptationSignal.QUALITY_SCORE_LOW,
        }
        loosen_signals = {
            AdaptationSignal.VIOLATION_RATE_LOW,
            AdaptationSignal.QUALITY_SCORE_HIGH,
        }
        if signal in tighten_signals:
            return PolicyDirection.TIGHTEN
        if signal in loosen_signals:
            return PolicyDirection.LOOSEN
        return PolicyDirection.HOLD

    def current_policy_hash(self) -> str:
        return self._policy_hash

    def latest_proposal(self) -> PolicyAdaptationProposal | None:
        return self._proposals[-1] if self._proposals else None

    def proposals(self) -> list[PolicyAdaptationProposal]:
        return list(self._proposals)

    def applied_count(self) -> int:
        return sum(1 for p in self._proposals if p.applied)


_global_loop: PolicyAdaptationLoop | None = None


def get_policy_adaptation_loop(policy_hash: str = "") -> PolicyAdaptationLoop:
    global _global_loop
    if _global_loop is None:
        _global_loop = PolicyAdaptationLoop(policy_hash=policy_hash)
    return _global_loop


def reset_policy_adaptation_loop() -> None:
    global _global_loop
    _global_loop = None


__all__ = [
    "AdaptationSignal",
    "PolicyDirection",
    "PolicyAdaptationProposal",
    "PolicyAdaptationLoop",
    "get_policy_adaptation_loop",
    "reset_policy_adaptation_loop",
]
