"""
Plan Contracts — v10_9 (L1 Cognition Layer)

Defines the PlanObject schema used by all L1 reasoners.
This file contains *structure only* — no logic, no cross-layer imports.

L1 MUST:
  • emit PlanObject instances
  • never mutate state
  • never depend on L2/L3/L4/L5
  • remain fully deterministic and side-effect-free

PlanObject is intentionally flexible and forward-compatible.
"""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class PlanObject(BaseModel):
    """
    Canonical output of L1 planners.

    Required fields:
        • plan_id: unique identifier for this planning instance
        • description: human-readable summary of the plan
        • steps: ordered list of planning steps (dicts)

    Optional metadata:
        • rationale: why this plan was generated
        • layer / mode: identification for orchestration
        • objective, constraints, dependencies
        • retrieval metadata (if generated by RAGReasoner)
        • injection_framing / injection_reasoning
        • safety_metadata
        • handoff: instructions to L2 executor

    Notes:
        • All fields are forward-compatible (extra = allow)
        • No validation beyond structural Pydantic rules
    """

    plan_id: str
    description: str
    steps: List[Dict[str, Any]] = Field(default_factory=list)

    rationale: Optional[str] = None

    # L1 identity metadata
    layer: Optional[str] = None
    mode: Optional[str] = None

    # Planning inputs / outputs
    objective: Optional[str] = None
    constraints: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)
    deliverables: List[str] = Field(default_factory=list)
    sections: List[str] = Field(default_factory=list)

    # Drafting metadata (if relevant)
    tone: Optional[str] = None
    audience: Optional[str] = None

    # Retrieval metadata (for RAGReasoner)
    retrieval: Dict[str, Any] = Field(default_factory=dict)
    ranking: Dict[str, Any] = Field(default_factory=dict)
    retrieval_metadata: Dict[str, Any] = Field(default_factory=dict)

    # Injection metadata added by L1 Reasoners
    injection_framing: Dict[str, Any] = Field(default_factory=dict)
    injection_reasoning: Dict[str, Any] = Field(default_factory=dict)

    # Safety metadata passed to L5 (high-level only)
    safety_metadata: Dict[str, Any] = Field(default_factory=dict)

    # Defines how L2 should execute the plan
    handoff: Dict[str, Any] = Field(default_factory=dict)

    class Config:
        extra = "allow"
        validate_assignment = True
        allow_mutation = True
