"""Auto-generated flattened view for core/test_prompt_templates_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "core/test_prompt_templates_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import asyncio
from types import SimpleNamespace

import pytest

from core_v10_7 import PromptTemplateManager
from core_v10_7.services import _format_prompt_with_defaults


class NoopBudgetManager:
    async def prune(self, document: str, max_tokens: int | None = None) -> str:  # pragma: no cover - trivial helper
        return document or ""


class StubLLMClient:
    def __init__(self, content: str):
        self._content = content

    async def chat_completion_async(self, *_, **__):
        return {"content": self._content}


class PruningBudgetManager:
    def __init__(self, marker: str = "AGENTIC"):
        self.marker = marker

    async def prune(self, document: str, max_tokens: int | None = None) -> str:
        text = document or ""
        if len(text) > 50:
            return f"compressed\n\n[... DOCUMENT PRUNED ({self.marker}) ...]"
        return text


@pytest.mark.asyncio
async def test_prompt_injects_goal_and_failures_header():
    manager = PromptTemplateManager(feedback_reader=SimpleNamespace(get_failures=lambda max_entries=100: []))
    manager.top_failures = ["PromptAgent::alignment"]
    template = manager.get_template("review_draft_strategy")

    formatted = await _format_prompt_with_defaults(
        template,
        {
            "master_resume": "resume text",
            "draft_text": "draft",
            "job_description": "job",
            "strategy": {"tone": "executive"},
        },
        NoopBudgetManager(),
        manager.goal_state,
        manager.top_failures,
    )

    assert "GLOBAL_GOAL:" in formatted
    assert "BEWARE:" in formatted
    assert "executive" in formatted


@pytest.mark.asyncio
async def test_prompt_prunes_long_inputs(monkeypatch):
    template_manager = PromptTemplateManager(feedback_reader=SimpleNamespace(get_failures=lambda max_entries=100: []))
    template_manager.top_failures = ["Stack::failure"]
    template = template_manager.get_template("validate_claims")

    huge_text = "Long " * 1000
    formatted = await _format_prompt_with_defaults(
        template,
        {
            "master_resume": huge_text,
            "draft_text": huge_text,
            "job_description": huge_text,
            "strategy": {"tone": "analytical"},
        },
        PruningBudgetManager(),
        template_manager.goal_state,
        template_manager.top_failures,
    )

    assert "DOCUMENT PRUNED" in formatted
    assert len(formatted) < len(huge_text)


def test_template_fallback_error_message():
    manager = PromptTemplateManager(feedback_reader=SimpleNamespace(get_failures=lambda max_entries=100: []))
    missing_prompt = manager.get_template("nonexistent_tool_name")
    assert "ERROR: PROMPT NOT FOUND" in missing_prompt


@pytest.mark.asyncio
async def test_prompt_handles_missing_optional_fields():
    manager = PromptTemplateManager(feedback_reader=SimpleNamespace(get_failures=lambda max_entries=100: []))
    template = manager.get_template("prompt_engineer")
    formatted = await _format_prompt_with_defaults(
        template,
        {"strategy": {}},
        NoopBudgetManager(),
        manager.goal_state,
        manager.top_failures,
    )

    assert "unknown" in formatted
    assert "Default style" in formatted
"""
}

ORIGINAL_MODULE_NAME = "tests.core.test_prompt_templates_v10_7"
FLAT_MODULE_NAME = "tests_flat.core__test_prompt_templates_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
