"""Code Validator Utility - Deterministic code validation.

This module provides deterministic code validation functionality previously
implemented in CodeValidatorAgent. Converted from agent to utility script
as part of SCRIPT agent conversion (Micro-wave 8).

Usage:
    from agentic_core.L5_safety.utils.code_validator_util import (
        CodeValidator, Violation, ViolationType, RuleSet, validate_file
    )

    # Validate a file
    violations = validate_file("path/to/file.py")
"""

from __future__ import annotations

import ast
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum, auto
from pathlib import Path
from typing import Any
from tqdm import tqdm

Logger = logging.getLogger(__name__)


class ViolationType(Enum):
    """Types of code violations."""

    SYNTAX = auto()
    CANON = auto()
    ASYNC = auto()
    PRINT = auto()


@dataclass
class Violation:
    """Represents a code violation."""

    violation_type: ViolationType
    file_path: str
    line_number: int
    issue: str
    severity: str = "MEDIUM"
    suggested_fix: str | None = None
    auto_fixable: bool = False

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "type": self.violation_type.name,
            "file_path": self.file_path,
            "line_number": self.line_number,
            "issue": self.issue,
            "severity": self.severity,
            "suggested_fix": self.suggested_fix,
            "auto_fixable": self.auto_fixable,
        }


@dataclass
class RuleSet:
    """Configuration for validation rules."""

    check_syntax: bool = True
    check_canon: bool = True
    check_async: bool = True
    check_prints: bool = True
    canon_patterns: dict[str, str] = field(default_factory=dict)
    async_patterns: dict[str, str] = field(default_factory=dict)
    print_policy: str = "warn"  # warn, error, ignore


@dataclass
class ValidationReport:
    """Report generated by code validation."""

    violations: list[Violation] = field(default_factory=list)
    total_violations: int = 0
    auto_fixable_count: int = 0
    high_severity_count: int = 0
    validation_timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "violations": [v.to_dict() for v in self.violations],
            "total_violations": self.total_violations,
            "auto_fixable_count": self.auto_fixable_count,
            "high_severity_count": self.high_severity_count,
            "validation_timestamp": self.validation_timestamp,
        }


class CodeValidator:
    """Deterministic code validator."""

    def __init__(self, ruleset: RuleSet | None = None) -> None:
        """Initialize validator.

        Args:
            ruleset: Validation rules configuration
        """
        self.ruleset = ruleset or RuleSet()
        self._violations: list[Violation] = []

    def validate_syntax(self, file_path: Path) -> list[Violation]:
        """Validate Python syntax for a file."""
        violations: list[Violation] = []

        if not self.ruleset.check_syntax:
            return violations

        try:
            with open(file_path, encoding="utf-8") as f:
                content = f.read()

            try:
                ast.parse(content)
            except SyntaxError as e:
                violations.append(
                    Violation(
                        violation_type=ViolationType.SYNTAX,
                        file_path=str(file_path),
                        line_number=e.lineno or 0,
                        issue=f"Syntax error: {e.msg}",
                        severity="HIGH",
                        suggested_fix="Fix syntax error",
                        auto_fixable=False,
                    ),
                )
        except (RuntimeError, OSError) as e:
            Logger.warning(f"Could not read {file_path}: {e}")

        return violations

    def validate_canon(self, file_path: Path) -> list[Violation]:
        """Validate canonical patterns for a file."""
        violations: list[Violation] = []

        if not self.ruleset.check_canon:
            return violations

        try:
            with open(file_path, encoding="utf-8") as f:
                content = f.read()

            lines = content.split("\n")

            for i, line in tqdm(enumerate(lines, 1), desc="Processing", unit="item"):
                # Check for proper class naming
                class_match = re.search(r"class\s+(\w+)", line)
                if class_match:
                    class_name = class_match.group(1)
                    if not class_name.endswith("Agent") and "Agent" in line:
                        violations.append(
                            Violation(
                                violation_type=ViolationType.CANON,
                                file_path=str(file_path),
                                line_number=i,
                                issue=f"Class '{class_name}' should end with 'Agent' if it's an agent",
                                severity="MEDIUM",
                                suggested_fix=f"Rename class to {class_name}Agent",
                                auto_fixable=True,
                            ),
                        )

                # Check for wildcard imports
                if "import *" in line:
                    violations.append(
                        Violation(
                            violation_type=ViolationType.CANON,
                            file_path=str(file_path),
                            line_number=i,
                            issue="Wildcard import detected",
                            severity="MEDIUM",
                            suggested_fix="Import specific modules instead of using *",
                            auto_fixable=False,
                        ),
                    )
        except (RuntimeError, OSError) as e:
            Logger.warning(f"Could not read {file_path}: {e}")

        return violations

    def validate_async(self, file_path: Path) -> list[Violation]:
        """Validate async/await usage for a file."""
        violations: list[Violation] = []

        if not self.ruleset.check_async:
            return violations

        try:
            with open(file_path, encoding="utf-8") as f:
                content = f.read()

            lines = content.split("\n")

            for i, line in tqdm(enumerate(lines, 1), desc="Processing", unit="item"):
                if "async def" in line:
                    # Look for the function body to check for await
                    func_lines = []
                    indent_level = len(line) - len(line.lstrip())

                    # Start from current line index (i-1 due to enumerate starting at 1)
                    for j in range(i, len(lines)):
                        current_line = lines[j]
                        if current_line.strip() == "":
                            continue
                        current_indent = len(current_line) - len(current_line.lstrip())
                        if current_indent <= indent_level and current_line.strip():
                            break
                        func_lines.append((j + 1, current_line))

                    has_await = any("await" in fl[1] for fl in func_lines)
                    if not has_await and len(func_lines) > 2:
                        violations.append(
                            Violation(
                                violation_type=ViolationType.ASYNC,
                                file_path=str(file_path),
                                line_number=i,
                                issue="Async function does not use await",
                                severity="LOW",
                                suggested_fix="Consider making function synchronous or add await",
                                auto_fixable=False,
                            ),
                        )
        except (RuntimeError, OSError) as e:
            Logger.warning(f"Could not read {file_path}: {e}")

        return violations

    def validate_prints(self, file_path: Path) -> list[Violation]:
        """Validate print statement usage for a file."""
        violations: list[Violation] = []

        if not self.ruleset.check_prints or self.ruleset.print_policy == "ignore":
            return violations

        try:
            with open(file_path, encoding="utf-8") as f:
                content = f.read()

            lines = content.split("\n")

            for i, line in tqdm(enumerate(lines, 1), desc="Processing", unit="item"):
                if "print(" in line and not line.strip().startswith("#"):
                    severity = "HIGH" if self.ruleset.print_policy == "error" else "MEDIUM"
                    violations.append(
                        Violation(
                            violation_type=ViolationType.PRINT,
                            file_path=str(file_path),
                            line_number=i,
                            issue="Print statement detected",
                            severity=severity,
                            suggested_fix="Use logging instead of print",
                            auto_fixable=False,
                        ),
                    )
        except (RuntimeError, OSError) as e:
            Logger.warning(f"Could not read {file_path}: {e}")

        return violations

    def validate_file(self, file_path: Path) -> list[Violation]:
        """Validate a single file for all code rules."""
        violations: list[Violation] = []

        violations.extend(self.validate_syntax(file_path))
        violations.extend(self.validate_canon(file_path))
        violations.extend(self.validate_async(file_path))
        violations.extend(self.validate_prints(file_path))

        return violations

    def validate_directory(self, directory: Path) -> ValidationReport:
        """Validate all Python files in a directory."""
        report = ValidationReport()

        if not directory.exists():
            Logger.warning(f"Directory does not exist: {directory}")
            return report

        for py_file in directory.rglob("*.py"):
            violations = self.validate_file(py_file)
            report.violations.extend(violations)

        report.total_violations = len(report.violations)
        report.auto_fixable_count = sum(1 for v in report.violations if v.auto_fixable)
        report.high_severity_count = sum(1 for v in report.violations if v.severity == "HIGH")

        return report


def validate_file(file_path: str | Path, ruleset: RuleSet | None = None) -> list[Violation]:
    """Convenience function to validate a single file.

    Args:
        file_path: Path to the file to validate
        ruleset: Optional ruleset configuration

    Returns:
        List of violations found
    """
    validator = CodeValidator(ruleset)
    return validator.validate_file(Path(file_path))


def validate_directory(directory: str | Path, ruleset: RuleSet | None = None) -> ValidationReport:
    """Convenience function to validate a directory.

    Args:
        directory: Path to the directory to validate
        ruleset: Optional ruleset configuration

    Returns:
        ValidationReport with all violations
    """
    validator = CodeValidator(ruleset)
    return validator.validate_directory(Path(directory))
