"""Complexity Analyzer Utility - Deterministic code complexity analysis.

This module provides deterministic complexity analysis functionality previously
implemented in ComplexityAnalyzerAgent. Converted from agent to utility script
as part of SCRIPT agent conversion (Micro-wave 8).

Usage:
    from agentic_core.L5_safety.utils.complexity_analyzer_util import (
        ComplexityAnalyzer, ComplexityViolation, ComplexityConfig, analyze_repository
    )

    # Analyze complexity
    result = analyze_repository(Path("."))
"""

from __future__ import annotations

import ast
import logging
import threading
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

Logger = logging.getLogger(__name__)


@dataclass
class ComplexityViolation:
    """Represents a complexity violation."""

    file_path: Path
    function_name: str
    line_number: int
    complexity: int
    max_allowed: int
    type: str  # 'CYCLOMATIC', 'LENGTH', 'ARGUMENTS'
    severity: str

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "file_path": str(self.file_path),
            "function_name": self.function_name,
            "line_number": self.line_number,
            "complexity": self.complexity,
            "max_allowed": self.max_allowed,
            "type": self.type,
            "severity": self.severity,
        }


@dataclass
class ComplexityConfig:
    """Configuration for complexity analysis."""

    max_cyclomatic_complexity: int = 10  # Standard strict limit
    max_function_length: int = 50  # Lines of code
    max_arguments: int = 6  # Function arguments
    ignore_tests: bool = True
    project_root: Path | None = None


@dataclass
class ComplexityReport:
    """Report generated by complexity analysis."""

    total_files: int = 0
    violations: list[ComplexityViolation] = field(default_factory=list)
    status: str = "PASS"  # "PASS" or "FAIL"

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "total_files": self.total_files,
            "violations": [v.to_dict() for v in self.violations],
            "status": self.status,
            "violation_count": len(self.violations),
        }


def calculate_cyclomatic_complexity(node: ast.AST) -> int:
    """Compute McCabe Cyclomatic Complexity for a node.

    Args:
        node: AST node to analyze

    Returns:
        Cyclomatic complexity score
    """
    complexity = 1
    for child in ast.walk(node):
        # Branching nodes
        if isinstance(
            child,
            ast.If
            | ast.While
            | ast.For
            | ast.AsyncFor
            | ast.ExceptHandler
            | ast.With
            | ast.AsyncWith
            | ast.Assert,
        ):
            complexity += 1
        # Boolean operators (and/or counts as branches)
        elif isinstance(child, ast.BoolOp):
            complexity += len(child.values) - 1
    return complexity


class ComplexityAnalyzer:
    """Deterministic code complexity analyzer."""

    def __init__(self, config: ComplexityConfig | None = None) -> None:
        """Initialize analyzer.

        Args:
            config: Complexity analysis configuration
        """
        self.config = config or ComplexityConfig()
        self.project_root = self.config.project_root or Path.cwd()
        self._lock = threading.RLock()
        self._violations: list[ComplexityViolation] = []

    def analyze_file(self, file_path: Path) -> list[ComplexityViolation]:
        """Analyze a single file for complexity metrics.

        Args:
            file_path: Path to the file to analyze

        Returns:
            List of complexity violations found
        """
        if not file_path.exists():
            return []

        try:
            content = file_path.read_text(encoding="utf-8")
            tree = ast.parse(content)
        except (ValueError, TypeError, SyntaxError) as e:
            Logger.error(f"Failed to parse {file_path}: {e}")
            return []

        violations: list[ComplexityViolation] = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                # 1. Cyclomatic Complexity
                complexity = calculate_cyclomatic_complexity(node)
                if complexity > self.config.max_cyclomatic_complexity:
                    violations.append(
                        ComplexityViolation(
                            file_path=file_path,
                            function_name=node.name,
                            line_number=node.lineno or 0,
                            complexity=complexity,
                            max_allowed=self.config.max_cyclomatic_complexity,
                            type="CYCLOMATIC",
                            severity="CRITICAL" if complexity > 20 else "WARNING",
                        ),
                    )

                # 2. Function Length
                if node.end_lineno and node.lineno:
                    length = node.end_lineno - node.lineno
                    if length > self.config.max_function_length:
                        violations.append(
                            ComplexityViolation(
                                file_path=file_path,
                                function_name=node.name,
                                line_number=node.lineno,
                                complexity=length,
                                max_allowed=self.config.max_function_length,
                                type="LENGTH",
                                severity="WARNING",
                            ),
                        )

                # 3. Argument Count
                arg_count = len(node.args.args)
                if arg_count > self.config.max_arguments:
                    violations.append(
                        ComplexityViolation(
                            file_path=file_path,
                            function_name=node.name,
                            line_number=node.lineno or 0,
                            complexity=arg_count,
                            max_allowed=self.config.max_arguments,
                            type="ARGUMENTS",
                            severity="INFO",
                        ),
                    )

        with self._lock:
            self._violations.extend(violations)

        return violations

    def analyze_repository(self, target_path: Path | None = None) -> ComplexityReport:
        """Analyze entire repository for complexity metrics.

        Args:
            target_path: Optional path to analyze (defaults to project_root)

        Returns:
            ComplexityReport with all violations
        """
        target = target_path or self.project_root
        self._violations = []

        files = list(target.rglob("*.py"))

        for file_path in files:
            if self.config.ignore_tests and (
                "test" in file_path.name or "tests" in file_path.parts
            ):
                continue
            self.analyze_file(file_path)

        return ComplexityReport(
            total_files=len(files),
            violations=self._violations.copy(),
            status="FAIL" if self._violations else "PASS",
        )

    def heal_repository(
        self,
        dry_run: bool = True,
        execute: bool = False,
        **kwargs: Any,
    ) -> dict[str, Any]:
        """Sovereign Interface - report complexity issues (cannot auto-fix).

        Args:
            dry_run: If True, only report without changes
            execute: If True, execute fixes (not applicable for complexity)

        Returns:
            Healing result dictionary
        """
        report = self.analyze_repository(self.project_root)
        Logger.info(f"[Complexity] Found {len(report.violations)} violations.")
        return {
            "violations_found": len(report.violations),
            "violations_fixed": 0,  # Cannot auto-fix complexity
            "report": report.to_dict(),
        }

    def heal(self, violation: dict[str, Any]) -> dict[str, Any]:
        """Heal complexity violations (requires manual refactoring).

        Args:
            violation: Dictionary with violation details

        Returns:
            Healing result dictionary
        """
        Logger.info("[COMPLEXITY_ANALYZER] Complexity violations require manual refactoring")
        return {
            "violations_fixed": 0,
            "violations_found": 1,
            "errors": 0,
            "skipped": 1,
            "reason": "Complexity violations require manual refactoring",
        }


def analyze_repository(
    target_path: str | Path | None = None,
    config: ComplexityConfig | None = None,
) -> ComplexityReport:
    """Convenience function to analyze repository complexity.

    Args:
        target_path: Path to analyze (defaults to current directory)
        config: Optional complexity configuration

    Returns:
        ComplexityReport with analysis results
    """
    analyzer = ComplexityAnalyzer(config)
    return analyzer.analyze_repository(Path(target_path) if target_path else None)


def analyze_file(
    file_path: str | Path,
    config: ComplexityConfig | None = None,
) -> list[ComplexityViolation]:
    """Convenience function to analyze a single file.

    Args:
        file_path: Path to the file to analyze
        config: Optional complexity configuration

    Returns:
        List of complexity violations
    """
    analyzer = ComplexityAnalyzer(config)
    return analyzer.analyze_file(Path(file_path))
