from __future__ import annotations
"""
Autonomous Resume Engine - Phase 1 & 2: Foundation + Self-Healing

This module provides the autonomous agent architecture for resume generation,
bringing it to Level 4+ autonomy with multi-agent coordination, self-diagnosis,
and self-healing capabilities.
"""

from .agents import (
    ATSCompatibilityAgent,
    BrandComplianceAgent,
    ContentQualityAgent,
    FactCheckAgent,
    ReflectionAgent,
    SectionBalanceAgent,
    StrategicPlannerAgent,
    TemplateOptimizerAgent,
    TestPilot,
)
from .gitops import (
    ConversationalRepair,
    FileBackup,
    GitOpsManager,
    ImportPatcher,
    MutationMode,
    MutationResult,
    Phase4OrchestratorAgent,
    RepairProposal,
    ResilientMutator,
    DashboardGenerator,
    DependencyArbiter,
    DependencyIssue,
    DependencyStatus,
    DocComplianceLevel,
    DocViolation,
    Phase7OrchestratorAgent,
    PredictiveBudgetManager,
    PromptGovernor,
    PromptIssue,
    PromptRisk,
    StrictDocEnforcerAgent,
)
from .healing import (
    AgentFactory,
    AutomaticRollback,
    CycleResult,
    HealingCycle,
    HealingResult,
    HealingStrategy,
    SignalRouterAgent,
    run_self_healing_mission,
)
from .RgHealingOrchestratorAgent import LicHealingOrchestratorAgent

from .learning import (
    ConfidenceLevel,
    ConfidenceResult,
    ConfidenceScorer,
    Instruction,
    InstructionInjector,
    LearningExample,
    LearningLoop,
    MemoryPersistence,
    MemoryState,
    ResumeLearningAgent,
    AuditReporter,
    ExecutionTrace,
    ExecutionTracer,
    Metric,
    MetricsCollector,
    MetricType,
    Phase5Orchestrator,
    TelemetryExporter,
    TraceLevel,
    TraceStep,
    ValidationAgent,
    ValidationIssue,
    ValidationSeverity,
)
from .orchestrator import quick_validate, run_resume_mission
from .proactive import (
    CapabilityMonitorAgent,
    CapabilityProfile,
    HandoffReason,
    HandoffRequest,
    PredictiveHandoff,
    ProactiveAgent,
    ProactiveScheduler,
    ProactiveTask,
    TaskPriority,
)

__all__ = [
    # Context
    "ResumeEngineContext",
    "BudgetManager",
    "SectionDependencyGraph",
    # Base
    "ResumeAgent",
    # Agents
    "ContentQualityAgent",
    "FactCheckAgent",
    "BrandComplianceAgent",
    "TemplateOptimizerAgent",
    "SectionBalanceAgent",
    "ATSCompatibilityAgent",
    "TestPilot",
    "StrategicPlannerAgent",
    "ReflectionAgent",
    # Orchestration (Phase 1)
    "run_resume_mission",
    "quick_validate",
    # Self-Healing (Phase 2)
    "HealingStrategy",
    "CycleResult",
    "HealingResult",
    "SignalRouterAgent",
    "AgentFactory",
    "HealingCycle",
    "HealingOrchestratorAgent",
    "run_self_healing_mission",
    "ConvergenceDetectorAgent",
    "AutomaticRollback",
    # Learning & Intelligence (Phase 3)
    "ConfidenceLevel",
    "LearningExample",
    "ConfidenceResult",
    "Instruction",
    "MemoryState",
    "LearningLoop",
    "ConfidenceScorer",
    "InstructionInjector",
    "MemoryPersistence",
    "ResumeLearningAgent",
    # GitOps & Advanced Mutation (Phase 4)
    "MutationMode",
    "FileBackup",
    "MutationResult",
    "RepairProposal",
    "GitOpsManager",
    "ResilientMutator",
    "ImportPatcher",
    "ConversationalRepair",
    "Phase4OrchestratorAgent",
    # Observability & Telemetry (Phase 5)
    "TraceLevel",
    "MetricType",
    "ValidationSeverity",
    "TraceStep",
    "ExecutionTrace",
    "Metric",
    "ValidationIssue",
    "AuditReport",
    "ExecutionTracer",
    "MetricsCollector",
    "ValidationAgent",
    "AuditReporter",
    "TelemetryExporter",
    "Phase5Orchestrator",
    # Intelligence & Strategic Analysis (Phase 6)
    "SecurityLevel",
    "AnalysisType",
    "RefactorType",
    "PhaseType",
    "SecurityIssue",
    "SemanticMatch",
    "RefactorProposal",
    "PhaseResult",
    "SecurityHardener",
    "SemanticAnalyzer",
    "StrategicAdvisor",
    "OmniContext",
    "UnifiedOrchestratorAgent",
    "Phase6OrchestratorAgent",
    # Governance & Meta-Optimization (Phase 7)
    "DependencyStatus",
    "DocComplianceLevel",
    "PromptRisk",
    "DependencyIssue",
    "DocViolation",
    "PromptIssue",
    "CostPrediction",
    "DependencyArbiter",
    "StrictDocEnforcerAgent",
    "DashboardGenerator",
    "PromptGovernor",
    "PredictiveBudgetManager",
    "Phase7OrchestratorAgent",
    # Proactive & Predictive (L4.5 Enhancements)
    "TaskPriority",
    "HandoffReason",
    "ProactiveTask",
    "HandoffRequest",
    "CapabilityProfile",
    "ProactiveScheduler",
    "PredictiveHandoff",
    "CapabilityMonitorAgent",
    "ProactiveAgent",
]
