"""Proof-evidence test for 10C-REQ-145 (03A_C0_Context_Engine).

Severity      : CRITICAL
Surface       : 03A_C0_Context_Engine
Layer owner   : C0 retrieval
Artifact      : FinalEvidenceContract
OTEL span     : c0.evidence.contract_emitted
Source        : C5_Retrieval_Prompt_Assembly.md :: C0.4 EVIDENCE CONTRACT C5

Canonical requirement (paraphrased): C5 C0.4 MUST: Validate verified_chunks cited_spans source_ids identify coverage gaps recommend next steps

Negative control text (from ledger row, paraphrased): Row-specific [10C-REQ-145]: FinalEvidenceContract emitted without satisfying 'C5 C0.4 MUST: Validate verified_chunks cited_spans source_ids ...

Generated by tools/requirements/generate_wave1_tests.py from
artifacts/requirements/wave1_critical_specs.json. Re-run the generator to
regenerate; do NOT hand-edit the rows that match the ledger spec.
"""

from __future__ import annotations

import pytest

from tests.fixtures.proof_evidence.otel_span_receipt import (
    BASE_REQUIRED_ATTRS,
    SpanAssertionError,
    assert_owner_surface_matches,
    assert_span_shape,
    make_receipt,
)
from tests.fixtures.proof_evidence.replay_digest import (
    assert_replay_drift_detected,
    assert_replay_stable,
)
from tests.fixtures.proof_evidence.runtime_artifact_validators import (
    ArtifactShapeError,
    assert_final_evidence_contract_anchored,
    validate_artifact_shape,
)

REQ_ID = "10C-REQ-145"
OWNER_SURFACE = "03A_C0_Context_Engine"
EXPECTED_SPAN = "c0.evidence.contract_emitted"
ARTIFACT_TYPE = "FinalEvidenceContract"

# OTEL required attributes from the ledger row's otel_required_attributes
# column (pipe-delimited). BASE_REQUIRED_ATTRS already covers req_id, run_id,
# trace_id, request_id, owner_surface, policy_hash, blueprint_hash, replay_key.
EXTRA_SPAN_ATTRS = tuple(
    a for a in 'req_id|run_id|trace_id|request_id|owner_surface|policy_hash|blueprint_hash|replay_key|artifact_id'.split("|")
    if a and a not in BASE_REQUIRED_ATTRS
)
REQUIRED_ATTRS = BASE_REQUIRED_ATTRS + EXTRA_SPAN_ATTRS

def _valid_artifact() -> dict:
    return {
        "contract_id": "fec-145-001",
        "evidence_chain": [
            {"ref": "evidence-145-1", "doc_id": "doc-A", "span": "p1"},
            {"ref": "evidence-145-2", "doc_id": "doc-B", "span": "p2"},
        ],
        "citation_anchors": [
            {"claim_id": "claim-145-1", "evidence_ref": "evidence-145-1"},
        ],
        "support_targets": ["PA", "L2"],
        "owner_surface": OWNER_SURFACE,
        "assembly_hash": "asm-145-h",
        "evidence_chain_complete": True,
        "citation_anchors_resolved": True,
        "no_unanchored_claims_assertion": True,
    }

def _valid_span_attrs() -> dict:
    attrs = {
        "req_id": REQ_ID,
        "run_id": "run-145-001",
        "trace_id": "trace-145-001",
        "request_id": "req-145-001",
        "owner_surface": OWNER_SURFACE,
        "policy_hash": "policy-145-h",
        "blueprint_hash": "blueprint-145-h",
        "replay_key": "replay-145-k",
    }
    # Add any extra row-required span attrs with deterministic placeholders.
    for a in EXTRA_SPAN_ATTRS:
        attrs.setdefault(a, f"{a}-145-v")
    return attrs


# ---------------------------------------------------------------------------
# Positive controls
# ---------------------------------------------------------------------------

def test_artifact_shape_positive() -> None:
    """A well-formed FinalEvidenceContract must validate cleanly + satisfy boundary invariant."""
    record = _valid_artifact()
    validate_artifact_shape(ARTIFACT_TYPE, record)
    assert_final_evidence_contract_anchored(record)


def test_span_shape_positive() -> None:
    """The c0.evidence.contract_emitted span must carry all required attrs."""
    receipt = make_receipt(EXPECTED_SPAN, _valid_span_attrs())
    assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)
    assert_owner_surface_matches(receipt, OWNER_SURFACE)


def test_replay_digest_stability_positive() -> None:
    """Same artifact yields the same digest across runs."""
    digest = assert_replay_stable(_valid_artifact())
    assert len(digest) == 64  # sha256 hex


# ---------------------------------------------------------------------------
# Negative controls (matches negative_control_specific from the ledger row)
# ---------------------------------------------------------------------------

def test_negative_control_specific_violation() -> None:
    """10C-REQ-145: per ledger row, a FinalEvidenceContract that violates the canonical
    requirement MUST raise. Drift inducer: no_unanchored_claims_assertion.
    """
    record = _valid_artifact()
    record["no_unanchored_claims_assertion"] = False
    with pytest.raises(ArtifactShapeError):
        assert_final_evidence_contract_anchored(record)


def test_negative_control_missing_required_field() -> None:
    """A FinalEvidenceContract missing the required field 'contract_id' MUST fail shape validation."""
    record = _valid_artifact()
    del record['contract_id']
    with pytest.raises(ArtifactShapeError) as excinfo:
        validate_artifact_shape(ARTIFACT_TYPE, record)
    assert 'contract_id' in str(excinfo.value)


def test_negative_control_span_missing_owner_surface() -> None:
    """Span without owner_surface MUST fail shape assertion."""
    attrs = _valid_span_attrs()
    del attrs["owner_surface"]
    receipt = make_receipt(EXPECTED_SPAN, attrs)
    with pytest.raises(SpanAssertionError):
        assert_span_shape(receipt, EXPECTED_SPAN, REQUIRED_ATTRS)


def test_negative_control_replay_drift() -> None:
    """Two semantically different artifacts MUST produce different digests."""
    a = _valid_artifact()
    b = _valid_artifact()
    # Mutate a deterministic field that participates in the digest.
    if "owner_surface" in b:
        b["owner_surface"] = OWNER_SURFACE + "-DRIFTED"
    assert_replay_drift_detected(a, b)
