"""L0 Routing Config Package."""

from agentic_core.L0_routing.config.path_constants import (
    AGENT_DISCOVERY_JSON,
    AGENT_DISCOVERY_MANIFEST_JSON,
    AGENTIC_CORE_DIR,
    APPS_EVAL_DIR,
    APPS_EXEC_DIR,
    APPS_LIC_DIR,
    APPS_RESEARCH_DIR,
    APPS_RFP_DIR,
    APPS_RG_DIR,
    APPS_SHARED_DIR,
    ARCHIVES_DIR,
    DASHBOARD_DIR,
    DISCOVERY_EXCLUDED_TERRITORIES,
    GLOBAL_EXCLUDED_DIRS,
    INFRASTRUCTURE_DIR,
    L0_MAINTENANCE_DIR,
    L0_ROUTING_DIR,
    L1_COGNITION_DIR,
    L2_EXECUTION_DIR,
    L3_ORCHESTRATION_DIR,
    L4_APPROVED_FOLDERS,
    L4_STATE_DIR,
    L5_SAFETY_DIR,
    L6_OBSERVABILITY_DIR,
    LAYER_ROOTS,
    OPS_SCRIPTS_DIR,
    PROJECT_ROOT_MARKERS,
    REPORTS_DIR,
    ROOT_ALLOWED_PATTERNS,
    ROOT_PROTECTED_FILES,
    ROOT_WHITELIST,
    RUNTIME_STATE_JSON,
    SCRIPTS_DIR,
    SOVEREIGN_EXCLUDED_FOLDERS,
    SYSTEM_LEARNING_DIR,
    TESTS_DIR,
    TOOLS_DIR,
    VARIABLE_DEPTH_SUBFOLDERS,
    get_all_apps_paths,
    get_apps_directories,
    get_validated_project_root,
)
from agentic_core.L0_routing.config.structure_blueprint_data import (
    APP_DOMAIN_PREFIXES,
    AST_PLACEMENT_SIGNALS,
    CANONICAL_LOCATION_PRIORITY,
    COMPOUND_SUFFIX_CONFLICTS,
    DUPLICATE_DETECTION_EXEMPT,
    EPHEMERAL_PATTERN_EXEMPTIONS,
    FILETYPE_TO_FOLDER,
    FOLDER_PURITY_RULES,
    FORBIDDEN_EPHEMERAL_PATTERNS,
    FORENSIC_DISCOVERY_INTEGRITY_HASH,
    FORENSIC_DISCOVERY_SCRIPT,
    GLOBAL_INTERFACES_FOLDER,
    INTERFACE_FILENAME_PATTERN,
    L5_SUBPROCESS_ALLOWLIST,
    L6_HYBRID_ALLOWLIST,
    LAYER_KEYWORD_AFFINITY,
    LAYER_PREFIX_PATTERN,
    SCRIPTS_FORBIDDEN_PATTERNS,
    SUFFIX_TO_FOLDER,
)
from agentic_core.runtime.contracts.lifecycle_trace_contract import (
    _emit_agent_executes_agent,
    _emit_applies_guardrail,  # noqa: E402
    _emit_authorize_and_execute,
    _emit_blocks_direct_write,
    _emit_captures_evaluation_metric,
    _emit_captures_execution_output,
    _emit_captures_pattern,
    _emit_captures_runtime_anomaly,
    _emit_checks_agent_registry,
    _emit_coordinates_agents,
    _emit_dispatches_agent,
    _emit_dispatches_execution_plan,
    _emit_dispatches_healing_run,  # noqa: E402
    _emit_emits_metric_event,
    _emit_escalates_failure,
    _emit_escalates_to_human,  # noqa: E402
    _emit_execution_terminates_at_uwg,
    _emit_feeds_meta_learning,
    _emit_gated_by_confidence,
    _emit_hard_fails_untranscripted,
    _emit_improves_agent_policy,
    _emit_invokes_eval,
    _emit_invokes_evaluation,
    _emit_links_execution_to_snapshot,
    _emit_links_incident_trace,
    _emit_observes_runtime_state,
    _emit_orchestrates_workflow,
    _emit_proposal_commits_routing,
    _emit_pulls_context,
    _emit_reads_environ,
    _emit_reads_policy_state,  # noqa: E402
    _emit_reads_runtime_state,
    _emit_records_execution_trace,  # noqa: E402
    _emit_records_healing_outcome,
    _emit_records_incident_event,
    _emit_records_learning_event,
    _emit_records_telemetry_event,
    _emit_records_tool_invocation,
    _emit_records_workflow_lineage,
    _emit_routes_through,  # noqa: E402
    _emit_routes_to_agent,
    _emit_routes_to_capability,
    _emit_signs_execution_trace,  # noqa: E402
    _emit_snapshots_state,  # noqa: E402
    _emit_stores_embedding,
    _emit_stores_learning_state,
    _emit_transcripts_response,
    _emit_triggers_alert,
    _emit_updates_meta_learning_state,
    _emit_updates_monitoring_state,
    _emit_updates_routing_strategy,
    _emit_validated_by_safety_plane,
    _emit_validates_agent_capability,
    _emit_validates_capability,
    _emit_verifies_boundary,
    _emit_verifies_policy,
    _emit_writes_learning_snapshot,
    _emit_writes_observability_log,
    _emit_writes_through,
    _emit_writes_via_uwg,
    emit_determinism_digest,  # noqa: E402
    emit_replay_key,  # noqa: E402
)

_emit_records_execution_trace("p0", "evidence", "__init__")
__all__ = [
    "AGENT_DISCOVERY_JSON",
    "AGENT_DISCOVERY_MANIFEST_JSON",
    "AGENTIC_CORE_DIR",
    "APP_DOMAIN_PREFIXES",
    "APPS_LIC_DIR",
    "APPS_RG_DIR",
    "APPS_SHARED_DIR",
    "ARCHIVES_DIR",
    "AST_PLACEMENT_SIGNALS",
    "CANONICAL_LOCATION_PRIORITY",
    "COMPOUND_SUFFIX_CONFLICTS",
    "DASHBOARD_DIR",
    "DISCOVERY_EXCLUDED_TERRITORIES",
    "DUPLICATE_DETECTION_EXEMPT",
    "EPHEMERAL_PATTERN_EXEMPTIONS",
    "FILETYPE_TO_FOLDER",
    "FOLDER_PURITY_RULES",
    "FORBIDDEN_EPHEMERAL_PATTERNS",
    "FORENSIC_DISCOVERY_INTEGRITY_HASH",
    "FORENSIC_DISCOVERY_SCRIPT",
    "GLOBAL_EXCLUDED_DIRS",
    "GLOBAL_INTERFACES_FOLDER",
    "INTERFACE_FILENAME_PATTERN",
    "L0_MAINTENANCE_DIR",
    "L0_ROUTING_DIR",
    "L1_COGNITION_DIR",
    "L2_EXECUTION_DIR",
    "L3_ORCHESTRATION_DIR",
    "L4_APPROVED_FOLDERS",
    "L4_STATE_DIR",
    "L5_SAFETY_DIR",
    "L5_SUBPROCESS_ALLOWLIST",
    "L6_HYBRID_ALLOWLIST",
    "L6_OBSERVABILITY_DIR",
    "LAYER_KEYWORD_AFFINITY",
    "LAYER_PREFIX_PATTERN",
    "LAYER_ROOTS",
    "OPS_SCRIPTS_DIR",
    "PROJECT_ROOT_MARKERS",
    "ROOT_ALLOWED_PATTERNS",
    "ROOT_PROTECTED_FILES",
    "ROOT_WHITELIST",
    "RUNTIME_STATE_JSON",
    "SCRIPTS_DIR",
    "SCRIPTS_FORBIDDEN_PATTERNS",
    "SOVEREIGN_EXCLUDED_FOLDERS",
    "SOVEREIGN_TERRITORIES",
    "SUFFIX_TO_FOLDER",
    "TESTS_DIR",
    "VARIABLE_DEPTH_SUBFOLDERS",
    "get_all_apps_paths",
    "get_apps_directories",
    "get_validated_project_root",
]
