"""Harness identity + signing utilities.

Plan: .windsurf/plans/apps-dom-real-evidence-enhancement-c7f4d8.md W1+W2.

Closes two residual synthetics in the runtime harness:

* **W1**: `request_id` / `run_id` / `session_id` / `replay_key` — previously
  synthesized as `f"req-{app}-harness"`-style strings. Now generated as real
  random identifiers (`uuid4://<32hex>`). A deterministic mode (seeded by
  `(app, harness_variant)`) is supported so fixture digests can be reproduced
  bit-for-bit across runs when `deterministic=True`.

* **W2**: `hmac_sig` — previously synthetic `f"sig-{app}-1"`. Now a real
  `hmac-sha256://<64hex>` over a canonical-JSON form of the receipt content.
  The canonical form:
    - Excludes the `hmac_sig` field itself (would be circular)
    - Excludes the identity fields generated by this module when
      `include_identity=False` (so the sig is content-bound, not run-bound)
    - Sorts all keys recursively so reordering doesn't change the sig

Harness HMAC key is a documented dev-tier constant. Prod signing requires an
ADR-bound KMS path (deferred to a separate plan). Fixture-level
`hmac_sig_class: "dev_harness"` surfaces the trust tier for auditors.

Authority: READ-ONLY on inputs. Returns fresh strings; never mutates args.
"""
from __future__ import annotations

import hashlib
import hmac
import json
import secrets
import uuid
from typing import Any, Mapping

# W2 — dev-tier harness HMAC key. ANY change to this key invalidates all
# prior fixtures' signatures (intentional: the fixture is content-bound, and
# replacing the key is a trust-boundary event that must be observable).
# Production signing uses a KMS-sourced key per ADR-xxx (deferred plan).
_HARNESS_HMAC_KEY: bytes = (
    b"apps-dom-harness:dev:v1:apps-runtime-domain-enforcement-a7e9d4"
)

HARNESS_HMAC_KEY_FINGERPRINT: str = hashlib.sha256(_HARNESS_HMAC_KEY).hexdigest()[:16]


def generate_id(*, app: str = "", purpose: str = "run", deterministic: bool = False) -> str:
    """Generate a `uuid4://<32hex>` identifier.

    Args:
        app: App name (used only when ``deterministic=True`` to derive a stable id).
        purpose: One of ``request | run | session | replay`` (also only used
            when ``deterministic=True``).
        deterministic: If True, returns a content-bound id derived from
            ``(app, purpose)`` via SHA256. Used for reproducible fixture digests.
            If False (default), returns a fresh random uuid4.
    """
    if deterministic:
        digest = hashlib.sha256(f"{app}|{purpose}".encode("utf-8")).hexdigest()
        return f"uuid4://{digest[:32]}"
    return f"uuid4://{uuid.uuid4().hex}"


def build_identity_block(
    app: str, *, deterministic: bool = True,
) -> dict[str, str]:
    """Return dict with the 4 identity fields.

    Default is ``deterministic=True`` so re-running the harness produces
    identical fixtures (the evidence shape is stable across sessions). Set
    ``deterministic=False`` for non-reproducible stress runs.
    """
    return {
        "request_id": generate_id(app=app, purpose="request", deterministic=deterministic),
        "run_id": generate_id(app=app, purpose="run", deterministic=deterministic),
        "session_id": generate_id(app=app, purpose="session", deterministic=deterministic),
        "replay_key": generate_id(app=app, purpose="replay", deterministic=deterministic),
    }


def _canonicalize(obj: Any, *, exclude_keys: frozenset[str]) -> Any:
    """Recursively sort dict keys and drop excluded keys at any nesting level.

    Returns a JSON-serializable shape with deterministic key ordering so
    `json.dumps(..., sort_keys=True, separators=(",", ":"))` yields a stable
    canonical bytestring for HMAC.
    """
    if isinstance(obj, dict):
        return {
            k: _canonicalize(v, exclude_keys=exclude_keys)
            for k, v in sorted(obj.items())
            if k not in exclude_keys
        }
    if isinstance(obj, list):
        return [_canonicalize(x, exclude_keys=exclude_keys) for x in obj]
    if isinstance(obj, tuple):
        return [_canonicalize(x, exclude_keys=exclude_keys) for x in obj]
    return obj


_DEFAULT_EXCLUDE = frozenset({
    # Self-reference — sig can never hash itself
    "hmac_sig",
    # Generated identities are content-independent; excluding them makes the
    # sig content-bound, not run-bound. Harness publishes identity fields
    # separately in the fixture so verifiers can bind both.
    "request_id",
    "run_id",
    "session_id",
    "replay_key",
    "trace_root",
    # Timestamps/latencies are non-deterministic run metadata; exclude
    "generated_at_utc",
    "elapsed_ms",
    "timing_offsets",
})


def canonical_receipt_form(
    receipts: Mapping[str, Any], *, extra_exclude: frozenset[str] = frozenset(),
) -> str:
    """Return the canonical JSON string used as HMAC input."""
    excluded = _DEFAULT_EXCLUDE | extra_exclude
    canonical = _canonicalize(dict(receipts), exclude_keys=excluded)
    return json.dumps(canonical, sort_keys=True, separators=(",", ":"), ensure_ascii=False)


def compute_hmac_sig(receipts: Mapping[str, Any]) -> str:
    """Return `hmac-sha256://<64hex>` over the canonical receipt form."""
    msg = canonical_receipt_form(receipts).encode("utf-8")
    mac = hmac.new(_HARNESS_HMAC_KEY, msg, hashlib.sha256).hexdigest()
    return f"hmac-sha256://{mac}"


def verify_hmac_sig(receipts: Mapping[str, Any], sig: str) -> bool:
    """Verify a previously emitted sig. Returns True iff bytes match.

    Used by tests + the freshness gate to cheap-check that fixtures haven't
    been tampered since emission.
    """
    if not sig.startswith("hmac-sha256://"):
        return False
    expected = sig[len("hmac-sha256://"):]
    actual = compute_hmac_sig(receipts)[len("hmac-sha256://"):]
    # Use compare_digest to guard against timing attacks (harness runs in CI;
    # defensive by habit).
    return hmac.compare_digest(expected, actual)


__all__ = [
    "HARNESS_HMAC_KEY_FINGERPRINT",
    "build_identity_block",
    "canonical_receipt_form",
    "compute_hmac_sig",
    "generate_id",
    "verify_hmac_sig",
]
