"""
03_runtime/compat/config_RES_v2.py
Compatibility shim for legacy config_RES_v2 imports.

This module provides backward-compatible imports for code that references
the legacy config_RES_v2 module. All types are re-exported from the canonical
location in 03_runtime/shared/config.py.

Usage:
    # Legacy import (still works):
    from config_RES_v2 import CONFIG, DEFAULT_MAX_RETRIES
    
    # Preferred import:
    from agentic_workflow.runtime.shared import CONFIG, DEFAULT_MAX_RETRIES

Auto-generated by WINDSURF v7 — Production-hardened, type-safe, zero-loss.
"""

from __future__ import annotations

import warnings

# Emit deprecation warning on import
warnings.warn(
    "config_RES_v2 is deprecated. Use 'from agentic_workflow.runtime.shared import ...' instead.",
    DeprecationWarning,
    stacklevel=2,
)

# Re-export all config from the canonical location
from ..shared.config import (
    # Paths
    PROJECT_ROOT,
    DATA_DIR,
    OUTPUT_DIR,
    BACKUP_DIR,
    LOGS_DIR,
    CACHE_DIR,
    # Constants
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_DELAY,
    DEFAULT_API_TIMEOUT,
    DEFAULT_RATE_LIMIT_DELAY,
    DEFAULT_GENERATION_TEMPERATURE,
    DEFAULT_SYNTHESIS_TEMPERATURE,
    DEFAULT_MAX_OUTPUT_TOKENS,
    DEFAULT_MIN_OUTPUT_TOKENS,
    SAFETY_THRESHOLD,
    DEFAULT_MODEL,
    FALLBACK_MODEL,
    MAX_RETRIES_PER_NODE,
    MIN_WORD_COUNT_THRESHOLD,
    MAX_WORD_COUNT_BUFFER,
    MIN_BULLET_COUNT,
    MAX_BULLET_COUNT,
    MIN_CONFIDENCE_SCORE,
    MIN_RELEVANCE_SCORE,
    ACCEPTABLE_MIN_WC,
    ACCEPTABLE_MAX_WC,
    DEFAULT_SELF_CONSISTENCY_RUNS,
    MAX_SELF_CONSISTENCY_RUNS,
    MIN_SELF_CONSISTENCY_AGREEMENT,
    MAX_WORKFLOW_HOPS,
    DEFAULT_HOP_TIMEOUT,
    MAX_CONCURRENT_TASKS,
    CHECKPOINT_SAVE_INTERVAL,
    MIN_QUALITY_SCORE,
    MIN_COHERENCE_SCORE,
    MIN_FACTUAL_ACCURACY_SCORE,
    MAX_HALLUCINATION_SCORE,
    MAX_JOB_DESCRIPTION_LENGTH,
    MAX_RESUME_FILE_SIZE,
    MAX_LOG_FILE_SIZE,
    CACHE_TTL_SECONDS,
    MAX_CACHE_ENTRIES,
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_TIMEOUT,
    CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS,
    # Enums
    ModelProvider,
    # Config classes
    ModelConfig,
    RAGConfig,
    PromptAddendumConfig,
    PROMPT_ADDENDUM_CONFIG,
    GovernorConfig,
    WorkflowConfig,
    ContentConstraintsConfig,
    SignalConstraintsConfig,
    Config,
    CONFIG,
    # Availability flags
    GEMINI_AVAILABLE,
    SKLEARN_AVAILABLE,
    CHROMADB_AVAILABLE,
    REDIS_AVAILABLE,
)

# Re-export ReasoningConfig from models (historically in config)
from ..shared.models import ReasoningConfig

__all__ = [
    # Paths
    "PROJECT_ROOT",
    "DATA_DIR",
    "OUTPUT_DIR",
    "BACKUP_DIR",
    "LOGS_DIR",
    "CACHE_DIR",
    # Constants
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_API_TIMEOUT",
    "DEFAULT_RATE_LIMIT_DELAY",
    "DEFAULT_GENERATION_TEMPERATURE",
    "DEFAULT_SYNTHESIS_TEMPERATURE",
    "DEFAULT_MAX_OUTPUT_TOKENS",
    "DEFAULT_MIN_OUTPUT_TOKENS",
    "SAFETY_THRESHOLD",
    "DEFAULT_MODEL",
    "FALLBACK_MODEL",
    "MAX_RETRIES_PER_NODE",
    "MIN_WORD_COUNT_THRESHOLD",
    "MAX_WORD_COUNT_BUFFER",
    "MIN_BULLET_COUNT",
    "MAX_BULLET_COUNT",
    "MIN_CONFIDENCE_SCORE",
    "MIN_RELEVANCE_SCORE",
    "ACCEPTABLE_MIN_WC",
    "ACCEPTABLE_MAX_WC",
    "DEFAULT_SELF_CONSISTENCY_RUNS",
    "MAX_SELF_CONSISTENCY_RUNS",
    "MIN_SELF_CONSISTENCY_AGREEMENT",
    "MAX_WORKFLOW_HOPS",
    "DEFAULT_HOP_TIMEOUT",
    "MAX_CONCURRENT_TASKS",
    "CHECKPOINT_SAVE_INTERVAL",
    "MIN_QUALITY_SCORE",
    "MIN_COHERENCE_SCORE",
    "MIN_FACTUAL_ACCURACY_SCORE",
    "MAX_HALLUCINATION_SCORE",
    "MAX_JOB_DESCRIPTION_LENGTH",
    "MAX_RESUME_FILE_SIZE",
    "MAX_LOG_FILE_SIZE",
    "CACHE_TTL_SECONDS",
    "MAX_CACHE_ENTRIES",
    "CIRCUIT_BREAKER_FAILURE_THRESHOLD",
    "CIRCUIT_BREAKER_TIMEOUT",
    "CIRCUIT_BREAKER_HALF_OPEN_MAX_CALLS",
    # Enums
    "ModelProvider",
    # Config classes
    "ModelConfig",
    "RAGConfig",
    "PromptAddendumConfig",
    "PROMPT_ADDENDUM_CONFIG",
    "GovernorConfig",
    "WorkflowConfig",
    "ContentConstraintsConfig",
    "SignalConstraintsConfig",
    "Config",
    "CONFIG",
    "ReasoningConfig",
    # Availability flags
    "GEMINI_AVAILABLE",
    "SKLEARN_AVAILABLE",
    "CHROMADB_AVAILABLE",
    "REDIS_AVAILABLE",
]
