#!/usr/bin/env python3
"""Generate threshold ADR (PROPOSED_NOT_APPLIED).

W1.2j — Generates ADR-xxx documenting threshold calibration findings.
Per plan: ADR is PROPOSED_NOT_APPLIED. No CI magic auto-applies.

Exit codes:
  0 — ADR generated successfully (even if PROPOSED_NOT_APPLIED)
  2 — Sweep status insufficient to generate ADR
  3 — Evidence file missing or malformed

W1 implementation per runtime-cert-hardened-w0-7e3c9a.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

# Evidence artifact paths
SWEEP_EVIDENCE_PATH = Path("artifacts/certification/evidence/threshold_sweep_results.json")
ADR_OUTPUT_PATH = Path("docs/architecture/adr/ADR-threshold-calibration-proposed.md")


def load_sweep_evidence() -> dict[str, Any] | None:
    """Load threshold sweep evidence if available."""
    if not SWEEP_EVIDENCE_PATH.exists():
        return None
    try:
        with open(SWEEP_EVIDENCE_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return None


def check_sweep_status(sweep_data: dict[str, Any] | None) -> tuple[bool, str]:
    """Check if sweep status is sufficient for ADR generation.
    
    Returns: (sufficient, reason)
    """
    if sweep_data is None:
        return False, "SWEEP_EVIDENCE_MISSING"
    
    status = sweep_data.get("status", "UNKNOWN")
    
    # Sufficient statuses: OPERATIONAL, CALIBRATED, PROPOSED
    sufficient_statuses = {"OPERATIONAL", "CALIBRATED", "PROPOSED", "COMPLETE"}
    
    if status in sufficient_statuses:
        return True, status
    
    # Insufficient: DEPS_MISSING, CACHE_MISSING, INFRASTRUCTURE_GAP, BLOCKED
    return False, status


def generate_adr(sweep_data: dict[str, Any]) -> str:
    """Generate ADR markdown content."""
    threshold = sweep_data.get("proposed_threshold", 0.75)
    calibration_date = sweep_data.get("calibration_date", "TBD")
    model_name = sweep_data.get("model", "BAAI/bge-m3")
    
    adr_content = f"""# ADR-XXX: Threshold Calibration (PROPOSED_NOT_APPLIED)

## Status

**PROPOSED_NOT_APPLIED**

This ADR documents proposed threshold changes based on calibration evidence.
No automatic application — explicit engineering review required.

## Context

- Model: `{model_name}`
- Calibration Date: {calibration_date}
- Evidence Source: threshold_sweep_results.json

## Proposed Threshold

```yaml
semantic_cache:
  similarity_threshold: {threshold}
```

## Calibration Results

| Metric | Value |
|--------|-------|
| Precision @ Threshold | {sweep_data.get('precision', 'N/A')} |
| Recall @ Threshold | {sweep_data.get('recall', 'N/A')} |
| F1 @ Threshold | {sweep_data.get('f1', 'N/A')} |
| True Positives | {sweep_data.get('true_positives', 'N/A')} |
| False Positives | {sweep_data.get('false_positives', 'N/A')} |
| True Negatives | {sweep_data.get('true_negatives', 'N/A')} |
| False Negatives | {sweep_data.get('false_negatives', 'N/A')} |

## Decision

Pending engineering review. Apply via explicit ADR approval process.

## References

- Plan: runtime-cert-hardened-w0-7e3c9a.md W1.2j
- RTC-REQ-055: Semantic Cache Binding

---
*Generated by generate_threshold_adr.py*
"""
    return adr_content


def main() -> int:
    """Main entry point."""
    sweep_data = load_sweep_evidence()
    sufficient, status = check_sweep_status(sweep_data)
    
    if not sufficient:
        print(f"ADR generation blocked: sweep_status={status}")
        print(f"Expected: OPERATIONAL/CALIBRATED/PROPOSED, Got: {status}")
        return 2
    
    if sweep_data is None:
        print("ADR generation blocked: no sweep evidence available")
        return 3
    
    # Generate ADR
    adr_content = generate_adr(sweep_data)
    
    # Ensure output directory exists
    ADR_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Write ADR
    with open(ADR_OUTPUT_PATH, "w", encoding="utf-8") as f:
        f.write(adr_content)
    
    print(f"ADR generated: {ADR_OUTPUT_PATH}")
    print(f"Status: PROPOSED_NOT_APPLIED")
    print(f"Proposed threshold: {sweep_data.get('proposed_threshold', 'N/A')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
