from __future__ import annotations
"""
Action Registry - L3 Orchestration Router
Auto-generated by Atomic Fission Protocol (Dec 20, 2025)
Original 692-line monolith split into 6 atomic sub-modules (<120 LOC each)

ZERO-LOSS GUARANTEE: All functionality preserved via re-exports
"""

# Import all tool classes from atomic modules
from typing import Any, Dict, List, Optional, Protocol

# [SSOT IMPORT] Structure blueprint is the single source of truth
from agentic_core.config.blueprint_sovereign.structure_blueprint_1 import (
    SOVEREIGN_REGISTRY,
    CORE_SUBFOLDER_MAP,
)

from agentic_core.L1_cognition.thought_engine.action_registry_modules import (
    FigmaTools,
    FileIO,
    GitTools,
    MemoryTools,
    PineconeTools,
    RedisCache,
    TimeTools,
    WebSearchTools,
)

# Re-export for backward compatibility
__all__ = [
    'WebSearchTools',
    'FileIO',
    'RedisCache',
    'TimeTools',
    'GitTools',
    'FigmaTools',
    'PineconeTools',
    'MemoryTools',
]