#!/usr/bin/env python3
"""
L3 Orchestration: Fission Executor
Physical file splitting logic for atomic fission protocol.
"""
import logging
import os
import shutil
import time
from datetime import datetime
from typing import TYPE_CHECKING, Any, Dict, List, Optional, Protocol

if TYPE_CHECKING:
    from agentic_core.fission_manager import FissionManager

logger = logging.getLogger(__name__)


async def apply_fission_blueprint(
    file_path: str, 
    blueprint: dict, 
    fission_mgr: "FissionManager"
) -> bool:
    """
    Apply a fission blueprint to split a monolithic file into sub-modules.
    
    Args:
        file_path: Path to the monolithic file
        blueprint: Fission blueprint with module definitions
        fission_mgr: FissionManager instance
        
    Returns:
        bool: True if fission was successful, False otherwise
    """
    try:
        file_dir = os.path.dirname(file_path)
        file_name = os.path.basename(file_path)
        base_name = file_name.replace('.py', '')
        
        # Create sub-module directory
        submodule_dir = os.path.join(file_dir, f"{base_name}_modules")
        os.makedirs(submodule_dir, exist_ok=True)
        
        # Write sub-modules
        created_modules = []
        for module_name, module_data in blueprint.items():
            if not isinstance(module_data, dict):
                logger.warning(f"   [!] Skipping invalid module entry: {module_name}")
                continue
                
            module_content = module_data.get('content', '').strip()
            if not module_content:
                logger.warning(f"   [!] Empty content for module {module_name}")
                continue
            
            # Create sub-module file
            module_file = os.path.join(submodule_dir, f"{module_name}.py")
            with open(module_file, 'w', encoding='utf-8', errors='ignore') as f:
                f.write(module_content)
            
            created_modules.append((module_name, module_data.get('exports', [])))
            logger.info(f"   [+] Created sub-module: {module_name}.py")
        
        if not created_modules:
            logger.warning(f"   [!] No sub-modules created from blueprint")
            return False
        
        # Create router file (original filename becomes orchestrator)
        router_content = f'''"""
{base_name} - L3 Orchestration Router
Auto-generated by Atomic Fission Protocol
Original file split into sub-modules for atomicity compliance
"""

# Import all sub-modules
'''
        
        for module_name, exports in created_modules:
            if exports:
                exports_str = ', '.join(exports)
                router_content += f"from agentic_core.{base_name}_modules.{module_name} import {exports_str}\n"
            else:
                router_content += f"from agentic_core.{base_name}_modules import {module_name}\n"
        
        # Safe __all__ generation
        all_exports = [e for _, exports in created_modules for e in exports]
        if all_exports:
            router_content += f"\n__all__ = [" + ", ".join(f'"{e}"' for e in all_exports) + "]\n"
        else:
            router_content += "\n# No public exports defined\n__all__ = []\n"
        
        # Backup & Write
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        backup_path = f"{file_path}.fission_backup_{timestamp}"
        
        # Atomic backup: copy to temp then move
        shutil.copy2(file_path, f"{backup_path}.tmp")
        os.replace(f"{backup_path}.tmp", backup_path)
        
        with open(file_path, 'w', encoding='utf-8', errors='ignore') as f:
            f.write(router_content)
        
        logger.info(f"   [✓] Fission complete: {len(created_modules)} sub-modules created")
        return True
        
    except Exception as e:
        logger.error(f"   [X] Fission blueprint application failed: {e}")
        return False
