"""Canonical apps_rg full-run output filenames."""

from __future__ import annotations

APPS_RG_MANDATORY_RUN_OUTPUT_JSON = "APPS_RG_MANDATORY_RUN_OUTPUT.json"
APPS_RG_MANDATORY_RUN_OUTPUT_MD = "APPS_RG_MANDATORY_RUN_OUTPUT.md"
BCG_EXECUTIVE_OUTPUT_MD = "BCG_EXECUTIVE_OUTPUT.md"
FULL_RUN_SECTION_STATUS_MD = "FULL_RUN_SECTION_STATUS.md"
FULL_RUN_SECTION_STATUS_JSON = "full_run_section_status.json"
APPS_RG_SECTION_LOCKDOWN_MD = "APPS_RG_SECTION_LOCKDOWN.md"
APPS_RG_SECTION_LOCKDOWN_JSON = "APPS_RG_SECTION_LOCKDOWN.json"
REVIEW_BUNDLE_FILENAME = "review_bundle.zip"
REVIEW_INDEX_FILENAME = "REVIEW_INDEX.md"

MANDATORY_OUTPUT_FILENAMES: tuple[str, ...] = (
    BCG_EXECUTIVE_OUTPUT_MD,
    APPS_RG_MANDATORY_RUN_OUTPUT_MD,
    APPS_RG_MANDATORY_RUN_OUTPUT_JSON,
    APPS_RG_SECTION_LOCKDOWN_MD,
    APPS_RG_SECTION_LOCKDOWN_JSON,
    FULL_RUN_SECTION_STATUS_MD,
    FULL_RUN_SECTION_STATUS_JSON,
    REVIEW_INDEX_FILENAME,
    REVIEW_BUNDLE_FILENAME,
)

__all__ = [
    "APPS_RG_MANDATORY_RUN_OUTPUT_JSON",
    "APPS_RG_MANDATORY_RUN_OUTPUT_MD",
    "APPS_RG_SECTION_LOCKDOWN_JSON",
    "APPS_RG_SECTION_LOCKDOWN_MD",
    "BCG_EXECUTIVE_OUTPUT_MD",
    "FULL_RUN_SECTION_STATUS_JSON",
    "FULL_RUN_SECTION_STATUS_MD",
    "MANDATORY_OUTPUT_FILENAMES",
    "REVIEW_BUNDLE_FILENAME",
    "REVIEW_INDEX_FILENAME",
]
