#!/usr/bin/env python3
"""
Phase 5: Remediation Strategy - Deterministic Extraction

This module provides deterministic extraction strategies for AI-checking logic,
generating proposed remediations that replace heuristic validation with
subprocess calls to Guardian tests.

Remediation Strategy:
1. Extract AI-checking logic from agent
2. Replace with subprocess/pytest call to Guardian layer
3. Generate new deterministic test script template for tests/guardian/
4. Provide aggressive test cases for the new Guardian script

The Law: AI Agents are prohibited from performing structural validation.
These checks must be deterministic Python scripts in tests/guardian/.
"""

import ast
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

PROJECT_ROOT = Path(__file__).resolve().parents[2]


@dataclass
class RemediationProposal:
    """A proposed remediation for an AI-checking violation."""

    agent_name: str
    file_path: Path
    violation_type: str
    original_code: str
    proposed_removal: str
    proposed_replacement: str
    guardian_test_template: str
    test_cases: list[str]
    severity: str = "HIGH"
    auto_remediable: bool = False


@dataclass
class Phase5AuditResult:
    """Result of Phase 5 Remediation Strategy audit."""

    total_violations_analyzed: int = 0
    remediations_proposed: int = 0
    auto_remediable_count: int = 0
    manual_review_count: int = 0
    proposals: list[RemediationProposal] = field(default_factory=list)
    health_score: float = 0.0


# Remediation templates
GUARDIAN_TEST_TEMPLATE = '''#!/usr/bin/env python3
"""
Guardian Test: {test_name}

Deterministic validation extracted from {agent_name}.
This test replaces AI-checking logic with deterministic assertions.

Generated by Phase 5 Remediation Strategy.
"""

import pytest
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]


class Test{test_class_name}:
    """Deterministic tests for {validation_description}."""

    def test_positive_case(self):
        """Test that valid input passes validation."""
        # TODO: Implement positive test case
        {positive_test_body}

    def test_negative_case(self):
        """Test that invalid input fails validation."""
        # TODO: Implement negative test case
        {negative_test_body}

    def test_edge_case(self):
        """Test edge cases and boundary conditions."""
        # TODO: Implement edge case test
        {edge_test_body}

    def test_regression_case(self):
        """Test known regression scenarios."""
        # TODO: Implement regression test
        {regression_test_body}


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
'''

SUBPROCESS_REPLACEMENT_TEMPLATE = '''
    def {method_name}(self, *args, **kwargs):
        """
        Deterministic validation via Guardian Layer.
        
        Replaces AI-checking logic with subprocess call to Guardian tests.
        """
        import subprocess
        import sys
        
        result = subprocess.run(
            [sys.executable, "-m", "pytest", 
             "tests/guardian/{guardian_test_file}", "-v", "--tb=short"],
            capture_output=True,
            text=True,
            cwd=str(Path(__file__).resolve().parents[2])
        )
        
        if result.returncode != 0:
            self.log_error(f"Guardian validation failed: {{result.stderr}}")
            return {{"violations_found": 1, "violations_fixed": 0, "errors": 1}}
        
        return {{"violations_found": 0, "violations_fixed": 0, "errors": 0}}
'''


def extract_validation_logic(file_path: Path) -> list[dict[str, Any]]:
    """Extract validation logic from an agent file."""
    validation_blocks = []

    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")
        tree = ast.parse(content)

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
                # Check if method contains validation logic
                validation_keywords = ["validate", "check", "verify", "audit"]
                if any(kw in node.name.lower() for kw in validation_keywords):
                    # Extract the source code for this method
                    start_line = node.lineno
                    end_line = node.end_lineno or start_line + 10

                    lines = content.splitlines()
                    method_code = "\n".join(lines[start_line - 1 : end_line])

                    validation_blocks.append(
                        {
                            "method_name": node.name,
                            "start_line": start_line,
                            "end_line": end_line,
                            "code": method_code,
                            "is_async": isinstance(node, ast.AsyncFunctionDef),
                        }
                    )

    except Exception:
        pass

    return validation_blocks


def generate_guardian_test_template(agent_name: str, method_name: str, validation_type: str) -> str:
    """Generate a Guardian test template for extracted validation logic."""
    test_name = f"test_{agent_name.lower()}_{method_name}"
    test_class_name = f"{agent_name}{method_name.title().replace('_', '')}Validation"

    template = GUARDIAN_TEST_TEMPLATE.format(
        test_name=test_name,
        agent_name=agent_name,
        test_class_name=test_class_name,
        validation_description=f"{validation_type} validation from {agent_name}",
        positive_test_body="assert True  # Replace with actual validation",
        negative_test_body="assert True  # Replace with actual validation",
        edge_test_body="assert True  # Replace with actual validation",
        regression_test_body="assert True  # Replace with actual validation",
    )

    return template


def generate_replacement_code(method_name: str, guardian_test_file: str) -> str:
    """Generate replacement code that calls Guardian tests."""
    return SUBPROCESS_REPLACEMENT_TEMPLATE.format(
        method_name=method_name, guardian_test_file=guardian_test_file
    )


def generate_test_cases(agent_name: str, validation_type: str) -> list[str]:
    """Generate aggressive test cases for a validation type."""
    test_cases = [
        f"test_{validation_type}_with_valid_input_{agent_name.lower()}",
        f"test_{validation_type}_with_invalid_input_{agent_name.lower()}",
        f"test_{validation_type}_with_empty_input_{agent_name.lower()}",
        f"test_{validation_type}_with_malformed_input_{agent_name.lower()}",
    ]
    return test_cases


def analyze_agent_for_remediation(file_path: Path) -> list[RemediationProposal]:
    """Analyze an agent and generate remediation proposals."""
    proposals = []

    try:
        content = file_path.read_text(encoding="utf-8", errors="ignore")

        # Extract agent class name
        agent_name = "Unknown"
        try:
            tree = ast.parse(content)
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef) and node.name.endswith("Agent"):
                    agent_name = node.name
                    break
        except Exception:
            pass

        # Extract validation logic
        validation_blocks = extract_validation_logic(file_path)

        for block in validation_blocks:
            method_name = block["method_name"]
            original_code = block["code"]

            # Determine violation type
            violation_type = "structural_validation"
            if "llm" in original_code.lower():
                violation_type = "llm_validation"
            elif "layer" in original_code.lower() or "gravity" in original_code.lower():
                violation_type = "layer_validation"

            # Generate Guardian test template
            guardian_test = generate_guardian_test_template(agent_name, method_name, violation_type)

            # Generate replacement code
            guardian_test_file = f"test_{agent_name.lower()}_{method_name}.py"
            replacement = generate_replacement_code(method_name, guardian_test_file)

            # Generate test cases
            test_cases = generate_test_cases(agent_name, violation_type)

            # Determine if auto-remediable
            auto_remediable = "llm" not in original_code.lower()

            proposals.append(
                RemediationProposal(
                    agent_name=agent_name,
                    file_path=file_path,
                    violation_type=violation_type,
                    original_code=original_code[:500],  # Truncate for readability
                    proposed_removal=f"Remove {method_name} validation logic",
                    proposed_replacement=replacement[:500],  # Truncate
                    guardian_test_template=guardian_test[:1000],  # Truncate
                    test_cases=test_cases,
                    auto_remediable=auto_remediable,
                )
            )

    except Exception:
        pass

    return proposals


def calculate_health_score(result: "Phase5AuditResult") -> float:
    """Calculate Subatomic Health Score based on violations."""
    if result.total_violations_analyzed == 0:
        return 100.0

    # Score based on auto-remediable vs manual review
    auto_ratio = result.auto_remediable_count / result.total_violations_analyzed
    manual_penalty = result.manual_review_count * 5  # 5 points per manual review item

    score = (auto_ratio * 50) + 50 - manual_penalty
    return max(0.0, min(100.0, score))


def run_phase5_audit(project_root: Path | None = None) -> Phase5AuditResult:
    """Run the Phase 5 Remediation Strategy audit."""
    if project_root is None:
        project_root = PROJECT_ROOT

    result = Phase5AuditResult()

    territories = [
        project_root / "agentic_core",
        project_root / "apps_lic",
        project_root / "apps_rg",
        project_root / "apps_shared",
    ]

    for territory in territories:
        if not territory.exists():
            continue

        for file_path in territory.rglob("*Agent.py"):
            if "__pycache__" in str(file_path):
                continue
            if "tests/" in str(file_path).replace("\\", "/"):
                continue

            proposals = analyze_agent_for_remediation(file_path)

            for proposal in proposals:
                result.total_violations_analyzed += 1
                result.remediations_proposed += 1

                if proposal.auto_remediable:
                    result.auto_remediable_count += 1
                else:
                    result.manual_review_count += 1

                result.proposals.append(proposal)

    result.health_score = calculate_health_score(result)
    return result


def generate_phase5_report(result: Phase5AuditResult) -> str:
    """Generate a formatted Phase 5 audit report."""
    report = []
    report.append("=" * 70)
    report.append("PHASE 5: REMEDIATION STRATEGY - DETERMINISTIC EXTRACTION REPORT")
    report.append("=" * 70)
    report.append("")
    report.append(f"Total Violations Analyzed: {result.total_violations_analyzed}")
    report.append(f"Remediations Proposed: {result.remediations_proposed}")
    report.append(f"Auto-Remediable: {result.auto_remediable_count}")
    report.append(f"Manual Review Required: {result.manual_review_count}")
    report.append("")
    report.append(f"SUBATOMIC HEALTH SCORE: {result.health_score:.1f}/100")
    report.append("")

    if result.proposals:
        report.append("REMEDIATION PROPOSALS (First 10):")
        report.append("-" * 50)

        for proposal in result.proposals[:10]:
            auto_icon = "🤖" if proposal.auto_remediable else "👤"
            report.append(f"\n{auto_icon} {proposal.agent_name}")
            report.append(f"   Violation: {proposal.violation_type}")
            report.append(f"   File: {proposal.file_path.name}")
            report.append(f"   Proposed: {proposal.proposed_removal}")
            report.append(f"   Test Cases: {len(proposal.test_cases)}")

        if len(result.proposals) > 10:
            report.append(f"\n   ... and {len(result.proposals) - 10} more proposals")

        report.append("")

    # Health Score Interpretation
    report.append("HEALTH SCORE INTERPRETATION:")
    report.append("-" * 50)
    if result.health_score >= 80:
        report.append("   ✅ HEALTHY: Repository is well-maintained")
    elif result.health_score >= 60:
        report.append("   ⚠️  MODERATE: Some remediation needed")
    elif result.health_score >= 40:
        report.append("   🟡 CONCERNING: Significant remediation required")
    else:
        report.append("   🔴 CRITICAL: Major architectural debt detected")

    report.append("")
    report.append("=" * 70)

    return "\n".join(report)


# ============================================================================
# PYTEST TEST CASES
# ============================================================================


class TestForensicAuditPhase5:
    """Test suite for Phase 5 Remediation Strategy."""

    def test_scan_runs_without_error(self):
        """Test that the scanner runs without errors."""
        result = run_phase5_audit(PROJECT_ROOT)
        assert result is not None

    def test_health_score_calculated(self):
        """Test that health score is calculated."""
        result = run_phase5_audit(PROJECT_ROOT)
        assert 0 <= result.health_score <= 100

    def test_remediation_proposals_generated(self):
        """Test that remediation proposals are generated."""
        result = run_phase5_audit(PROJECT_ROOT)
        # May or may not have proposals depending on codebase state
        assert isinstance(result.proposals, list)

    def test_guardian_test_template(self):
        """Test Guardian test template generation."""
        template = generate_guardian_test_template("TestAgent", "validate_structure", "structural")
        assert "def test_positive_case" in template
        assert "def test_negative_case" in template
        assert "TestAgent" in template

    def test_replacement_code_generation(self):
        """Test replacement code generation."""
        replacement = generate_replacement_code("validate", "test_validate.py")
        assert "subprocess.run" in replacement
        assert "tests/guardian" in replacement

    def test_test_cases_generation(self):
        """Test test case generation."""
        test_cases = generate_test_cases("TestAgent", "structural")
        assert len(test_cases) == 4
        assert all("testagent" in tc.lower() for tc in test_cases)

    def test_remediation_dataclass(self):
        """Test RemediationProposal dataclass."""
        proposal = RemediationProposal(
            agent_name="TestAgent",
            file_path=Path("test.py"),
            violation_type="structural",
            original_code="def validate(): pass",
            proposed_removal="Remove validate",
            proposed_replacement="subprocess call",
            guardian_test_template="test template",
            test_cases=["test1", "test2"],
        )
        assert proposal.agent_name == "TestAgent"
        assert proposal.severity == "HIGH"

    def test_report_generation(self):
        """Test that report is properly generated."""
        result = run_phase5_audit(PROJECT_ROOT)
        report = generate_phase5_report(result)

        assert "PHASE 5" in report
        assert "REMEDIATION STRATEGY" in report
        assert "HEALTH SCORE" in report

    def test_health_score_calculation(self):
        """Test health score calculation logic."""
        # Test with no violations
        result = Phase5AuditResult()
        assert calculate_health_score(result) == 100.0

        # Test with all auto-remediable
        result.total_violations_analyzed = 10
        result.auto_remediable_count = 10
        result.manual_review_count = 0
        assert calculate_health_score(result) == 100.0

        # Test with all manual review
        result.auto_remediable_count = 0
        result.manual_review_count = 10
        score = calculate_health_score(result)
        assert score < 50  # Should be penalized

    def test_auto_vs_manual_classification(self):
        """Test that violations are classified as auto vs manual."""
        result = run_phase5_audit(PROJECT_ROOT)
        total = result.auto_remediable_count + result.manual_review_count
        assert total == result.total_violations_analyzed

    def test_validation_extraction(self):
        """Test validation logic extraction."""
        # Test with a non-existent file (should not crash)
        blocks = extract_validation_logic(Path("nonexistent.py"))
        assert blocks == []


def test_forensic_audit_phase5():
    """Main test entry point for Phase 5 Remediation Strategy."""
    print("\n" + "=" * 70)
    print("PHASE 5: REMEDIATION STRATEGY - RUNNING TESTS")
    print("=" * 70 + "\n")

    result = run_phase5_audit(PROJECT_ROOT)
    report = generate_phase5_report(result)
    print(report)

    # Assertions
    assert result.health_score >= 0, "Health score should be non-negative"

    print("\n✅ Phase 5 Remediation Strategy: PASSED")
    print(f"   Analyzed {result.total_violations_analyzed} violations")
    print(f"   Proposed {result.remediations_proposed} remediations")
    print(f"   Health Score: {result.health_score:.1f}/100")


if __name__ == "__main__":
    test_forensic_audit_phase5()
