"""
Structure Blueprint Package - Modular SSOT (2026-02-08).

This package is the Single Source of Truth for all structural configuration.
The monolithic structure_blueprint_config.py is a backward-compatible shim
that re-exports everything from this package.

Modules:
  ssot.py           - Core constants, path utilities, whitelists, flat enforcement
  territories.py    - SOVEREIGN_TERRITORIES definition
  classification.py - Suffix patterns, folder purity, naming rules
  semantics.py      - AST signals, keyword affinity, agent/placement registries
  artifacts.py      - File patterns, artifact routing, subfolder metadata
  derived.py        - Derived registries (computed from territories)
  governance.py     - Healing, mission, gravity, MCP operational config
"""

from __future__ import annotations

MAX_RETRIES = 3
DEFAULT_SLEEP = 1.0
THRESHOLD = 0.95
BUFFER_SIZE = 8192
BATCH_SIZE = 32
MAX_DEPTH = 6
MAX_FILES = 1000
DEFAULT_TIMEOUT = 300  # 5 minutes
# Configuration constants

# Territories - loaded eagerly from leaf node directly (no shim hop)
# Governance constants - merged into _constants (2026-03-08)
from agentic_core.L5_safety.config.structure_blueprint._constants import (
    AGENT_RESILIENCE_CONFIG,
    DOWNSTREAM_ROOTS,
    GRAVITY_CONFIG,
    GRAVITY_SURGERY_ENABLED,
    HEALING_CONFIG,
    LAYER_OVERRIDES,
    MCP_CAPABILITIES,
    MISSION_CONFIG,
    # SOVEREIGN_TERRITORIES removed from public API - use get_all_territories() instead
    # Still available via _constants for internal testing only
    UPSTREAM_SOVEREIGN_ROOTS,
    SubfolderDefinition,
    TerritoryDefinition,
    # build_sovereign_territories removed from public API - internal only
)

# HOT imports - always loaded (ssot.py is minimal-cost)
from agentic_core.L5_safety.config.structure_blueprint.ssot import (
    AGENT_DISCOVERY_JSON,
    AGENT_DISCOVERY_MANIFEST_JSON,
    AGENTIC_CORE_DIR,
    ALLOW_ROOT_PY_TERRITORIES,
    ALLOWED_DUPLICATE_FILENAMES,
    APPS_LIC_DIR,
    APPS_RG_DIR,
    APPS_SHARED_DIR,
    ARCHIVES_DIR,
    AUTONOMOUS_AGENT_WHITELIST,
    BLUEPRINT_SOVEREIGN_DIR,
    CODE_TERRITORIES,
    COVERAGE_HTML_DIR,
    DASHBOARD_DIR,
    DISCOVERY_EXCLUDED_TERRITORIES,
    DOCS_REPORTS_PLANS,
    ENFORCED_TERRITORIES,
    FLAT_DIRECTORIES,
    FORBIDDEN_FOLDER_PATTERN,
    FORBIDDEN_PATTERNS,
    FORBIDDEN_ROOT_FOLDERS,
    FORENSIC_DISCOVERY_INTEGRITY_HASH,
    FORENSIC_DISCOVERY_SCRIPT,
    GLOBAL_EXCLUDED_DIRS,
    L0_MAINTENANCE_DIR,
    L1_COGNITION_DIR,
    L2_EXECUTION_DIR,
    L3_ORCHESTRATION_DIR,
    L4_STATE_DIR,
    L5_SAFETY_DIR,
    L5_SUBPROCESS_ALLOWLIST,
    L6_HYBRID_ALLOWLIST,
    L6_OBSERVABILITY_DIR,
    LAYER_PREFIX_EXEMPT_TERRITORIES,
    LAYER_ROOTS,
    LEAF_DOMAINS_NO_LCD,
    NAMING_EXEMPT_DIRS,
    NAMING_EXEMPT_FILES,
    OPS_SCRIPTS_DIR,
    PROJECT_ROOT_MARKERS,
    PROJECT_ROOT_WHITELIST,
    PROMPT_GOVERNANCE_DIR,
    PYTHON_STDLIB_MODULES,
    REPORTS_DIR,
    REQUIRED_LCD_SUBFOLDERS,
    ROOT_ALLOWED_PATTERNS,
    ROOT_PROTECTED_FILES,
    ROOT_WHITELIST,
    RUNTIME_DIR,
    RUNTIME_STATE_JSON,
    SCHEMAS_DIR,
    SCOPE_SUMMARY_EXCLUSIONS,
    SCRIPTS_FORBIDDEN_PATTERNS,
    SOVEREIGN_EXCLUDED_FOLDERS,
    STANDARD_LAYER_STRUCTURE,
    TEST_CANONICAL_LOCATION_MAP,
    TEST_MIRROR_BASE,
    TEST_MIRROR_ROOTS,
    TESTS_AUTOGEN_DIR,
    TESTS_DIR,
    TESTS_E2E_DIR,
    TESTS_INTEGRATION_DIR,
    TESTS_ROOT_FILE_WHITELIST,
    TESTS_UNIT_DIR,
    UTILS_DIR,
    VALIDATED_FILE_EXTENSIONS,
    VARIABLE_DEPTH_SUBFOLDERS,
    VOLATILE_TERRITORIES,
    get_apps_lic_subfolder_map,
    get_apps_rg_subfolder_map,
    get_apps_shared_subfolder_map,
    get_canonical_test_path,
    get_core_subfolder_map,
    get_sovereign_territories,
    get_subfolder_metadata,
    get_validated_project_root,
    ignore_dirs,
    is_allowed_subfolder,
    is_l4_approved,
    is_layer_root,
    is_path_allowed,
    protected_folders,
    safe_path_join,
    safe_prefixed_filename,
    sovereign_ignored_folders,
    validate_flat_directory,
    validate_no_duplicate_prefix,
    validate_no_nested_lcd,
    validate_path_within_project,
)
from agentic_core.L5_safety.config.structure_blueprint.territories import (
    get_all_territories,
    get_territory_metadata,
    is_valid_root_folder,
)


# COLD imports - lazy loaded via __getattr__
def __getattr__(name: str):
    """Lazy load cold module exports on first access."""
    if name in {
        "CANONICAL_LOCATION_PRIORITY",
        "CLASSIFICATION_SUFFIX_PATTERNS",
        "COMPOUND_SUFFIX_CONFLICTS",
        "DOMAIN_CONTENT_SIGNALS",
        "DUPLICATE_DETECTION_EXEMPT",
        "FILETYPE_TO_FOLDER",
        "FOLDER_PURITY_DISALLOWED",
        "FOLDER_PURITY_RULES",
        "INFRASTRUCTURE_PROFILES",
        "FOLDER_ALIASES",
        "NO_ROOT_FILES_FOLDERS",
        "APPROVED_SUBFOLDERS",
        "FORBIDDEN_COMPOUND_PATTERNS",
        "GLOBAL_INTERFACES_FOLDER",
        "INTERFACE_FILENAME_PATTERN",
        "KNOWN_ARCHITECTURAL_SUFFIXES",
        "L5_ENFORCEMENT_ALLOWED_SUFFIXES",
        "LAYER_PREFIX_PATTERN",
        "NON_PYTHON_FOLDER_ROUTES",
        "SERVICE_CLASS_INDICATORS",
        "SUFFIX_TO_FOLDER",
        "get_classification_suffix_patterns_compiled",
        "get_compound_suffix_patterns_compiled",
        "get_folder_purity_disallowed_compiled",
        "get_folder_purity_patterns_compiled",
        "get_forbidden_compound_patterns_compiled",
    }:
        from agentic_core.L5_safety.config.structure_blueprint import classification

        return getattr(classification, name)

    if name in {
        "AGENT_REGISTRY",
        "APP_DOMAIN_PREFIXES",
        "APP_LIC_AST_TERMS",
        "APP_LIC_STRING_TERMS",
        "APP_LIC_VARIABLE_TERMS",
        "APP_RG_AST_TERMS",
        "APP_RG_STRING_TERMS",
        "APP_RG_VARIABLE_TERMS",
        "AST_DOMAIN_HIT_THRESHOLD",
        "AST_PLACEMENT_SIGNALS",
        "CORE_TERRITORY_KEYWORDS",
        "DEFAULT_APP_HEALING_TARGET",
        "DEFAULT_CORE_HEALING_TERRITORY",
        "EXERCISER_REGISTRY",
        "FORBIDDEN_APP_MODULES",
        "L2_TO_L1_MAP",
        "LAYER_FORBIDDEN_IMPORTS",
        "LAYER_KEYWORD_AFFINITY",
        "LEGACY_AST_SIGNALS",
        "MIN_ALIGNMENT_SCORE",
        "NAMING_CONVENTIONS",
        "PLACEMENT_CONFIDENCE",
        "POLYGLOT_DOMAIN_SIGNALS",
        "SEMANTIC_L2_REGISTRY",
        "STRING_HIT_WEIGHT",
        "TERRITORY_MISMATCH_THRESHOLD",
        "TEST_TYPE_SIGNALS",
        "VARIABLE_HIT_WEIGHT",
        "VIOLATION_SEVERITY",
        "semantic_l2_registry",
    }:
        from agentic_core.L5_safety.config.structure_blueprint import semantics

        return getattr(semantics, name)

    if name in {
        "APP_SPECIFIC_PATTERNS",
        "APP_SPECIFIC_PATTERN_STRINGS",
        "APP_SPECIFIC_PREFIXES",
        "APP_SPECIFIC_TARGET_SUBFOLDER",
        "ARTIFACT_ROUTING_MAP",
        "DATA_SUBFOLDER_METADATA",
        "DOCS_SUBFOLDER_METADATA",
        "EPHEMERAL_PATTERN_EXEMPTIONS",
        "FORBIDDEN_BACKUP_PATTERNS",
        "FORBIDDEN_BACKUP_PATTERN_STRINGS",
        "FORBIDDEN_EPHEMERAL_PATTERNS",
        "FORBIDDEN_FILENAME_PATTERNS",
        "FORBIDDEN_LAYER_PREFIXES",
        "PROJECT_ROOT_METADATA",
        "PROJECT_ROOT_SUBFOLDERS",
        "STUTTERING_PREFIX_MAP",
        "check_forbidden_signals",
        "get_app_specific_patterns_compiled",
        "get_correct_app_folder",
        "get_correct_app_path",
        "get_ephemeral_exemption_patterns_compiled",
        "get_forbidden_backup_patterns_compiled",
        "get_forbidden_ephemeral_patterns_compiled",
        "has_forbidden_layer_prefix",
        "is_app_specific_file",
        "is_broken_backup_file",
        "validate_artifact_routing",
    }:
        from agentic_core.L5_safety.config.structure_blueprint import artifacts

        return getattr(artifacts, name)

    if name in {
        "APPS_LIC_SUBFOLDER_MAP",
        "APPS_RG_SUBFOLDER_MAP",
        "APPS_SHARED_SUBFOLDER_MAP",
        "CORE_SUBFOLDER_MAP",
        "DEPTH_RULES",
        "L4_APPROVED_FOLDERS",
        "L4_SUBFOLDER_MAP",
        "SCRIPTS_PLACEMENT_RULES",
        "SUBFOLDER_METADATA",
        "TESTS_L2_SUBFOLDER_MAP",
        "TESTS_SUBFOLDER_MAP",
        "agentic_core_registry",
        "verify_derived_registries",
    }:
        from agentic_core.L5_safety.config.structure_blueprint import derived

        return getattr(derived, name)

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


# ---------------------------------------------------------------------------
# PUBLIC API — exactly 163 names.
#
# Internal helpers, sub-module scaffolding, lazy loaders, and TypedDicts used
# only by the build machinery are intentionally excluded.  They remain
# importable via explicit ``from … import …`` but are NOT part of the
# stable public surface exposed by ``from … import *``.
#
# Excluded (18 internal names):
#   SubfolderDefinition, TerritoryDefinition, build_sovereign_territories,
#   LAYER_OVERRIDES, get_sovereign_territories, get_core_subfolder_map,
#   get_subfolder_metadata, get_apps_lic_subfolder_map,
#   get_apps_rg_subfolder_map, get_apps_shared_subfolder_map,
#   agentic_core_registry, verify_derived_registries, L4_SUBFOLDER_MAP,
#   L4_APPROVED_FOLDERS, SCRIPTS_PLACEMENT_RULES,
#   get_app_specific_patterns_compiled,
#   get_classification_suffix_patterns_compiled,
#   get_compound_suffix_patterns_compiled
# ---------------------------------------------------------------------------
__all__ = [
    "AGENTIC_CORE_DIR",
    "AGENT_DISCOVERY_JSON",
    "AGENT_DISCOVERY_MANIFEST_JSON",
    "FORENSIC_DISCOVERY_INTEGRITY_HASH",
    "FORENSIC_DISCOVERY_SCRIPT",
    "AGENT_REGISTRY",
    "AGENT_RESILIENCE_CONFIG",
    "ALLOW_ROOT_PY_TERRITORIES",
    "ALLOWED_DUPLICATE_FILENAMES",
    "APPS_LIC_DIR",
    "APPS_LIC_SUBFOLDER_MAP",
    "APPS_RG_DIR",
    "APPS_RG_SUBFOLDER_MAP",
    "APPS_SHARED_DIR",
    "APPS_SHARED_SUBFOLDER_MAP",
    "APP_DOMAIN_PREFIXES",
    "APP_LIC_AST_TERMS",
    "APP_LIC_STRING_TERMS",
    "APP_LIC_VARIABLE_TERMS",
    "APP_RG_AST_TERMS",
    "APP_RG_STRING_TERMS",
    "APP_RG_VARIABLE_TERMS",
    "APP_SPECIFIC_PATTERNS",
    "APP_SPECIFIC_PATTERN_STRINGS",
    "APP_SPECIFIC_PREFIXES",
    "APP_SPECIFIC_TARGET_SUBFOLDER",
    "ARCHIVES_DIR",
    "ARTIFACT_ROUTING_MAP",
    "AST_DOMAIN_HIT_THRESHOLD",
    "AST_PLACEMENT_SIGNALS",
    "AUTONOMOUS_AGENT_WHITELIST",
    "BLUEPRINT_SOVEREIGN_DIR",
    "CANONICAL_LOCATION_PRIORITY",
    "CLASSIFICATION_SUFFIX_PATTERNS",
    "COMPOUND_SUFFIX_CONFLICTS",
    "CORE_SUBFOLDER_MAP",
    "CORE_TERRITORY_KEYWORDS",
    "COVERAGE_HTML_DIR",
    "DASHBOARD_DIR",
    "DATA_SUBFOLDER_METADATA",
    "DEFAULT_APP_HEALING_TARGET",
    "DEFAULT_CORE_HEALING_TERRITORY",
    "DEPTH_RULES",
    "DISCOVERY_EXCLUDED_TERRITORIES",
    "DOCS_REPORTS_PLANS",
    "DOCS_SUBFOLDER_METADATA",
    "DOMAIN_CONTENT_SIGNALS",
    "DOWNSTREAM_ROOTS",
    "DUPLICATE_DETECTION_EXEMPT",
    "EPHEMERAL_PATTERN_EXEMPTIONS",
    "EXERCISER_REGISTRY",
    "FILETYPE_TO_FOLDER",
    "FLAT_DIRECTORIES",
    "FOLDER_PURITY_DISALLOWED",
    "FOLDER_PURITY_RULES",
    "INFRASTRUCTURE_PROFILES",
    "FOLDER_ALIASES",
    "NO_ROOT_FILES_FOLDERS",
    "APPROVED_SUBFOLDERS",
    "FORBIDDEN_APP_MODULES",
    "FORBIDDEN_BACKUP_PATTERNS",
    "FORBIDDEN_BACKUP_PATTERN_STRINGS",
    "FORBIDDEN_COMPOUND_PATTERNS",
    "FORBIDDEN_EPHEMERAL_PATTERNS",
    "FORBIDDEN_FILENAME_PATTERNS",
    "FORBIDDEN_FOLDER_PATTERN",
    "FORBIDDEN_LAYER_PREFIXES",
    "FORBIDDEN_PATTERNS",
    "FORBIDDEN_ROOT_FOLDERS",
    "GLOBAL_EXCLUDED_DIRS",
    "GLOBAL_INTERFACES_FOLDER",
    "GRAVITY_CONFIG",
    "get_all_territories",
    "get_territory_metadata",
    "GRAVITY_SURGERY_ENABLED",
    "HEALING_CONFIG",
    "INTERFACE_FILENAME_PATTERN",
    "KNOWN_ARCHITECTURAL_SUFFIXES",
    "L0_MAINTENANCE_DIR",
    "L1_COGNITION_DIR",
    "L2_EXECUTION_DIR",
    "L2_TO_L1_MAP",
    "L3_ORCHESTRATION_DIR",
    "L4_STATE_DIR",
    "L5_ENFORCEMENT_ALLOWED_SUFFIXES",
    "L5_SAFETY_DIR",
    "L5_SUBPROCESS_ALLOWLIST",
    "L6_HYBRID_ALLOWLIST",
    "L6_OBSERVABILITY_DIR",
    "LAYER_FORBIDDEN_IMPORTS",
    "LAYER_KEYWORD_AFFINITY",
    "LAYER_PREFIX_PATTERN",
    "LAYER_ROOTS",
    "LEAF_DOMAINS_NO_LCD",
    "LEGACY_AST_SIGNALS",
    "CODE_TERRITORIES",
    "ENFORCED_TERRITORIES",
    "VOLATILE_TERRITORIES",
    "MCP_CAPABILITIES",
    "MIN_ALIGNMENT_SCORE",
    "MISSION_CONFIG",
    "NAMING_CONVENTIONS",
    "NAMING_EXEMPT_DIRS",
    "NAMING_EXEMPT_FILES",
    "NON_PYTHON_FOLDER_ROUTES",
    "OPS_SCRIPTS_DIR",
    "PLACEMENT_CONFIDENCE",
    "POLYGLOT_DOMAIN_SIGNALS",
    "PROJECT_ROOT_MARKERS",
    "PROJECT_ROOT_METADATA",
    "PROJECT_ROOT_SUBFOLDERS",
    "PROJECT_ROOT_WHITELIST",
    "PROMPT_GOVERNANCE_DIR",
    "PYTHON_STDLIB_MODULES",
    "REPORTS_DIR",
    "REQUIRED_LCD_SUBFOLDERS",
    "ROOT_ALLOWED_PATTERNS",
    "ROOT_PROTECTED_FILES",
    "ROOT_WHITELIST",
    "RUNTIME_DIR",
    "RUNTIME_STATE_JSON",
    "SCHEMAS_DIR",
    "SCOPE_SUMMARY_EXCLUSIONS",
    "SCRIPTS_FORBIDDEN_PATTERNS",
    "SEMANTIC_L2_REGISTRY",
    "SERVICE_CLASS_INDICATORS",
    "SOVEREIGN_EXCLUDED_FOLDERS",
    "SOVEREIGN_TERRITORIES",
    "STANDARD_LAYER_STRUCTURE",
    "STRING_HIT_WEIGHT",
    "STUTTERING_PREFIX_MAP",
    "SUBFOLDER_METADATA",
    "SUFFIX_TO_FOLDER",
    "TERRITORY_MISMATCH_THRESHOLD",
    "TEST_CANONICAL_LOCATION_MAP",
    "TEST_MIRROR_BASE",
    "TEST_MIRROR_ROOTS",
    "TESTS_AUTOGEN_DIR",
    "get_canonical_test_path",
    "TESTS_DIR",
    "TESTS_E2E_DIR",
    "TESTS_INTEGRATION_DIR",
    "TESTS_L2_SUBFOLDER_MAP",
    "TESTS_ROOT_FILE_WHITELIST",
    "TESTS_SUBFOLDER_MAP",
    "TESTS_UNIT_DIR",
    "TEST_TYPE_SIGNALS",
    "UPSTREAM_SOVEREIGN_ROOTS",
    "UTILS_DIR",
    "VALIDATED_FILE_EXTENSIONS",
    "VARIABLE_DEPTH_SUBFOLDERS",
    "VARIABLE_HIT_WEIGHT",
    "VIOLATION_SEVERITY",
    "check_forbidden_signals",
    "get_correct_app_folder",
    "get_correct_app_path",
    "get_ephemeral_exemption_patterns_compiled",
    "get_folder_purity_patterns_compiled",
    "get_forbidden_backup_patterns_compiled",
    "get_forbidden_compound_patterns_compiled",
    "get_forbidden_ephemeral_patterns_compiled",
    "get_validated_project_root",
    "has_forbidden_layer_prefix",
    "ignore_dirs",
    "is_allowed_subfolder",
    "is_app_specific_file",
    "is_broken_backup_file",
    "is_l4_approved",
    "is_layer_root",
    "is_path_allowed",
    "protected_folders",
    "safe_path_join",
    "safe_prefixed_filename",
    "semantic_l2_registry",
    "sovereign_ignored_folders",
    "validate_artifact_routing",
    "validate_flat_directory",
    "validate_no_duplicate_prefix",
    "validate_no_nested_lcd",
    "validate_path_within_project",
]
