"""
Semantics Module - COLD PATH (Semantic Analysis Registries)

This module contains semantic analysis data: naming conventions, keyword
affinities, AST domain terms, and territory keywords.

Loaded lazily on first access.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any, Final

from agentic_core.runtime.contracts import lifecycle_trace_contract as trace_contract

trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_1")
trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_2")
trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_3")
trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_4")
trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_5")
trace_contract._emit_emits_metric_event("semantics", "p4obs", "metric_6")
trace_contract._emit_records_incident_event("semantics", "p4obs", "incident")
trace_contract._emit_captures_runtime_anomaly("semantics", "p4obs", "anomaly")
trace_contract._emit_writes_observability_log("semantics", "p4obs", "obs_log")
trace_contract._emit_updates_monitoring_state("semantics", "p4obs", "mon_state")
trace_contract._emit_triggers_alert("semantics", "p4obs", "alert")
trace_contract._emit_links_incident_trace("semantics", "p4obs", "trace_link")
trace_contract._emit_captures_pattern("semantics", "p3lm", "pattern")
trace_contract._emit_records_learning_event("semantics", "p3lm", "learning_event")
trace_contract._emit_writes_learning_snapshot("semantics", "p3lm", "snapshot")
trace_contract._emit_feeds_meta_learning("semantics", "p3lm", "meta_feed")
trace_contract._emit_updates_routing_strategy("semantics", "p3lm", "routing")
trace_contract._emit_improves_agent_policy("semantics", "p3lm", "policy")
trace_contract._emit_stores_learning_state("semantics", "p3lm", "state")
trace_contract._emit_records_execution_trace("semantics", "L0_ROUTING", "p2_trace_1")
trace_contract._emit_records_execution_trace("semantics", "L1_REASONING", "p2_trace_2")
trace_contract._emit_records_execution_trace("semantics", "L2_EXECUTION", "p2_trace_3")
trace_contract._emit_records_execution_trace("semantics", "L3_ORCHESTRATION", "p2_trace_4")
trace_contract._emit_records_execution_trace("semantics", "L4_STATE", "p2_trace_5")
trace_contract._emit_reads_environ("semantics", "env_read", "p2_env_1")
trace_contract._emit_reads_environ("semantics", "env_read", "p2_env_2")
trace_contract._emit_reads_runtime_state("semantics", "runtime_state", "p2_rt_1")
trace_contract._emit_reads_runtime_state("semantics", "runtime_state", "p2_rt_2")

trace_contract.emit_replay_key("p0", "semantics")
trace_contract.emit_determinism_digest("p0", "semantics")

trace_contract._emit_dispatches_healing_run("p1", "semantics", "L5")
trace_contract._emit_routes_through("p1", "semantics", "L5")
trace_contract._emit_checks_agent_registry("p1", "semantics", "agent_registry")
trace_contract._emit_validates_agent_capability("p1", "semantics", "capability")
trace_contract._emit_dispatches_execution_plan("p1", "semantics", "exec_plan")
trace_contract._emit_agent_executes_agent("p1", "semantics", "sub_agent")
trace_contract._emit_routes_to_agent("p1", "semantics", "target_agent")
trace_contract._emit_verifies_policy("p1", "semantics", "policy_check")
trace_contract._emit_observes_runtime_state("p1", "semantics", "runtime_state")
trace_contract._emit_verifies_boundary("p1", "semantics", "boundary_check")
trace_contract._emit_transcripts_response("p1", "semantics", "transcript")
trace_contract._emit_hard_fails_untranscripted("p1", "semantics")
trace_contract._emit_gated_by_confidence("p1", "semantics", "confidence_gate")
trace_contract._emit_escalates_to_human("p1", "semantics", "L5")
trace_contract._emit_reads_policy_state("p1", "semantics", "L5")
trace_contract._emit_pulls_context("p1", "semantics", "context_pull")
trace_contract._emit_pulls_context("p1", "semantics", "context_pull_secondary")
trace_contract._emit_execution_terminates_at_uwg("p1", "semantics", "uwg_term")
trace_contract._emit_execution_terminates_at_uwg("p1", "semantics", "uwg_term_secondary")
trace_contract._emit_writes_through("p1", "semantics", "write_through")
trace_contract._emit_writes_through("p1", "semantics", "write_through_secondary")
trace_contract._emit_validated_by_safety_plane("p1", "semantics", "safety_validation")
trace_contract._emit_invokes_eval("p1", "semantics", "eval_call")
trace_contract._emit_proposal_commits_routing("p1", "semantics", "routing_commit")

trace_contract._emit_signs_execution_trace("p0", "p0hash", "p0_trace", 0)
trace_contract._emit_records_execution_trace("p0", "evidence", "semantics")
trace_contract._emit_applies_guardrail("p0", "semantics", "p0_governance")
trace_contract._emit_snapshots_state("p0", "semantics", "state_snapshot")
trace_contract._emit_authorize_and_execute("p2", "semantics", "execution_auth")
trace_contract._emit_validates_capability("p2", "semantics", "capability_check")
trace_contract._emit_routes_to_capability("p2", "semantics", "capability_route")
trace_contract._emit_writes_via_uwg("p2", "semantics", "uwg_write")
trace_contract._emit_blocks_direct_write("p2", "semantics", "direct_write_block")
trace_contract._emit_records_tool_invocation("p2", "semantics", "tool_invocation")
trace_contract._emit_captures_execution_output("p2", "semantics", "exec_output")
trace_contract._emit_dispatches_agent("p3", "semantics", "agent_dispatch")
trace_contract._emit_coordinates_agents("p3", "semantics", "agent_coordination")
trace_contract._emit_records_workflow_lineage("p3", "semantics", "workflow_lineage")
trace_contract._emit_records_healing_outcome("p3", "semantics", "healing_outcome")
trace_contract._emit_escalates_failure("p3", "semantics", "failure_escalation")
trace_contract._emit_orchestrates_workflow("p3", "semantics", "workflow_orchestration")
trace_contract._emit_dispatches_healing_run("p3", "semantics", "healing_dispatch")
trace_contract._emit_invokes_evaluation("p3", "semantics", "evaluation_signal")
trace_contract._emit_records_telemetry_event("p4", "semantics", "telemetry_event")
trace_contract._emit_captures_evaluation_metric("p4", "semantics", "eval_metric")
trace_contract._emit_stores_embedding("p4", "semantics", "embedding_store")
trace_contract._emit_updates_meta_learning_state("p4", "semantics", "meta_learning")
trace_contract._emit_links_execution_to_snapshot("p4", "semantics", "exec_snapshot_link")

NAMING_CONVENTIONS: Final[Mapping[str, Mapping[str, Any]]] = {
    "agent": {
        "pattern": "^[A-Z][a-zA-Z0-9]*Agent\\.py$",
        "description": "PascalCase ending with 'Agent'",
        "examples": ["HealerAgent.py", "NamingAgent.py", "CodeDeduplicationAgent.py"],
        "anti_examples": ["HealerAgent.py", "NamingAgent.py", "Healer.py"],
        "extensions": [".py"],
        "min_words": 2,
        "max_words": 4,
    },
    "script": {
        "pattern": "^[a-z][a-z0-9_]*_script\\.py$",
        "description": "snake_case ending with '_script.py'",
        "examples": ["db_migration_script.py", "daily_cleanup_script.py", "audit_status_script.py"],
        "anti_examples": ["main.py", "utils.py", "script.py", "run.py"],
        "extensions": [".py"],
    },
    "utility": {
        "pattern": "^[a-z][a-z0-9_]*_util\\.py$",
        "description": "snake_case ending with '_util.py'",
        "examples": ["file_util.py", "string_util.py", "path_util.py"],
        "anti_examples": ["utils.py", "helpers.py", "common.py"],
        "extensions": [".py"],
    },
    "config": {
        "pattern": "^[a-z][a-z0-9_]*_config\\.py$",
        "description": "snake_case ending with '_config.py'",
        "examples": ["app_config.py", "db_config.py", "logging_config.py"],
        "anti_examples": ["config.py", "settings.py", "constants.py"],
        "extensions": [".py"],
    },
    "types": {
        "pattern": "^[a-z][a-z0-9_]*_types\\.py$",
        "description": "snake_case ending with '_types.py'",
        "examples": ["agent_types.py", "message_types.py", "state_types.py"],
        "anti_examples": ["types.py", "models.py", "schemas.py"],
        "extensions": [".py"],
    },
    "validator": {
        "pattern": "^[a-z][a-z0-9_]*_validator\\.py$",
        "description": "snake_case ending with '_validator.py'",
        "examples": ["input_validator.py", "schema_validator.py", "path_validator.py"],
        "anti_examples": ["validator.py", "validate.py", "check.py"],
        "extensions": [".py"],
    },
    "mixin": {
        "pattern": "^[a-z][a-z0-9_]*_mixin\\.py$",
        "description": "snake_case ending with '_mixin.py'",
        "examples": ["logging_mixin.py", "caching_mixin.py", "retry_mixin.py"],
        "anti_examples": ["mixin.py", "mixins.py", "base.py"],
        "extensions": [".py"],
    },
}
LAYER_KEYWORD_AFFINITY: Final[Mapping[str, Sequence[str]]] = {
    "L0_routing": [
        "cleanup",
        "maintenance",
        "bootstrap",
        "heal",
        "repair",
        "reconcile",
        "ssot",
        "folder cleanup",
        "hygiene",
        "migration",
        "discovery",
        "manifest",
        "sync",
        "gospel",
    ],
    "L1_cognition": [
        "thought",
        "intent",
        "planning",
        "cognition",
        "reasoning",
        "decision",
        "analysis",
        "understanding",
    ],
    "L2_execution": ["tool", "mcp", "action", "execute", "invoke", "run", "embed", "search", "index"],
    "L3_orchestration": [
        "workflow",
        "orchestrat",
        "meta-learn",
        "pipeline",
        "coordinate",
        "schedule",
        "batch",
        "tier",
    ],
    "L4_state": ["state", "memory", "ledger", "cache", "redis", "pinecone", "persist", "store", "context"],
    "L5_safety": [
        "safety",
        "guard",
        "valid",
        "enforce",
        "protect",
        "sentinel",
        "threat",
        "adversarial",
        "compliance",
        "audit",
        "inspect",
    ],
    "L6_observability": [
        "observ",
        "telemetry",
        "monitor",
        "metric",
        "dashboard",
        "report",
        "log",
        "trace",
        "health",
    ],
}
APP_RG_AST_TERMS: Final[frozenset[str]] = frozenset(
    {
        "resume",
        "cv",
        "skill",
        "experience",
        "education",
        "section",
        "job",
        "outreach",
        "dispatch",
        "generation",
        "formatter",
        "parser",
        "header",
        "summary",
        "achievement",
        "certification",
    },
)
APP_LIC_AST_TERMS: Final[frozenset[str]] = frozenset(
    {
        "linkedin",
        "lic",
        "profile",
        "connection",
        "invite",
        "message",
        "connect",
        "campaign",
        "cadence",
        "note",
        "scrap",
        "navigate",
        "browser",
    },
)
APP_RG_VARIABLE_TERMS: Final[frozenset[str]] = frozenset(
    {
        "resume",
        "cv",
        "skill",
        "experience",
        "education",
        "section",
        "job",
        "header",
        "summary",
        "achievement",
        "certification",
        "applicant",
        "candidate",
        "position",
        "role",
    },
)
APP_LIC_VARIABLE_TERMS: Final[frozenset[str]] = frozenset(
    {
        "profile",
        "linkedin",
        "connection",
        "invite",
        "message",
        "note",
        "campaign",
        "cadence",
        "lead",
        "contact",
        "person",
        "url",
    },
)
APP_RG_STRING_TERMS: Final[frozenset[str]] = frozenset(
    {"resume", "cv", "skill", "experience", "education", "job posting", "outreach", "candidate", "applicant"},
)
APP_LIC_STRING_TERMS: Final[frozenset[str]] = frozenset(
    {"linkedin", "profile", "connection", "invite", "campaign", "cadence"},
)
VARIABLE_HIT_WEIGHT: Final[float] = 0.5
STRING_HIT_WEIGHT: Final[float] = 0.25
AST_DOMAIN_HIT_THRESHOLD: Final[float] = 2.0
FORBIDDEN_APP_MODULES: Final[frozenset[str]] = frozenset({"apps_rg", "apps_lic"})
POLYGLOT_DOMAIN_SIGNALS: Final[Mapping[str, Mapping[str, Any]]] = {
    "apps_rg": {
        "signal_keywords": APP_RG_STRING_TERMS,
        "match_threshold": 2,
        "extensions": [".yaml", ".yml", ".json"],
    },
    "apps_lic": {
        "signal_keywords": APP_LIC_STRING_TERMS,
        "match_threshold": 2,
        "extensions": [".yaml", ".yml", ".json"],
    },
}
CORE_TERRITORY_KEYWORDS: Final[Mapping[str, Mapping[str, frozenset[str]]]] = {
    "L1_cognition/thought_engine": {
        "primary": frozenset({"think", "reason", "plan", "decompose", "critique", "reflect"}),
    },
    "L2_execution/engine": {"primary": frozenset({"tool", "execute", "call", "registry", "runner"})},
    "L2_execution/mcp": {"primary": frozenset({"mcp", "client", "fetch", "protocol"})},
    "L3_orchestration/engine": {
        "primary": frozenset({"orchestrate", "workflow", "route", "dispatch", "coordinate", "flow"}),
    },
    "L4_state/memory": {"primary": frozenset({"state", "context", "checkpoint", "persist"})},
    "L4_state/ledger": {"primary": frozenset({"ledger", "history", "record", "transaction"})},
    "L5_safety/validators": {
        "primary": frozenset({"validate", "enforce", "check", "guard", "policy", "heal"}),
    },
    "L5_safety/guardrails": {"primary": frozenset({"guardrail", "safety", "membrane", "airlock", "pii"})},
    "L5_safety/gravity": {"primary": frozenset({"gravity", "import", "dependency", "layer"})},
    "config/core": {
        "primary": frozenset({"blueprint", "registry", "sovereign", "canon", "config", "settings"}),
    },
    "schemas/models": {"primary": frozenset({"schema", "model", "type", "message"})},
    "prompt_governance/L3_core": {"primary": frozenset({"render", "registry", "assemble", "govern"})},
    "prompt_governance/L3_templates": {
        "primary": frozenset({"template", "prompt", "persona", "instructional"}),
    },
    "prompt_governance/L3_security": {"primary": frozenset({"security", "injection", "pii", "compliance"})},
    "prompt_governance/L3_integrity": {"primary": frozenset({"validate", "optimize", "test", "quality"})},
    "prompt_governance/L3_utilities": {"primary": frozenset({"script", "middleware", "monitor", "audit"})},
    "observability": {"primary": frozenset({"metric", "trace", "telemetry", "log", "compliance"})},
    "utils": {"primary": frozenset({"util", "helper", "extension", "wrapper"})},
}
LAYER_FORBIDDEN_IMPORTS: Final[Mapping[str, frozenset[str]]] = {
    "L1_cognition": frozenset({"L2_execution", "L3_orchestration", "L4_state", "L5_safety"}),
    "L2_execution": frozenset({"L1_cognition", "L3_orchestration", "L5_safety"}),
    "L3_orchestration": frozenset({"L5_safety"}),
    "apps_shared": frozenset({"apps_rg", "apps_lic"}),
    "apps_rg": frozenset({"apps_lic"}),
    "apps_lic": frozenset({"apps_rg"}),
}
TERRITORY_MISMATCH_THRESHOLD: Final[float] = 2.5
MIN_ALIGNMENT_SCORE: Final[float] = 1.5
DEFAULT_APP_HEALING_TARGET: Final[str] = "apps_rg/engines"
DEFAULT_CORE_HEALING_TERRITORY: Final[str] = "L2_execution/engine"
VIOLATION_SEVERITY: Final[Mapping[str, int]] = {
    "GRAVITY VIOLATION": 10,
    "AST DOMAIN VIOLATION": 9,
    "TERRITORY MISMATCH VIOLATION": 8,
    "APP-SPECIFIC IN CORE VIOLATION": 7,
    "TERRITORY ALIGNMENT WEAK": 5,
}
APP_DOMAIN_PREFIXES: Final[Sequence[str]] = ["Lic", "Campaign", "Outreach"]
_semantic_templates = {
    "node_pattern": {"entity_types": ["Class"], "examples_suffix": ["Node", "ExtractNode", "DraftNode"]},
    "flow_pattern": {
        "entity_types": ["Class"],
        "bases": ["BaseFlow"],
        "examples_suffix": ["Flow", "Pipeline", "Campaign"],
    },
    "engine_pattern": {
        "entity_types": ["Class"],
        "bases": ["BaseEngine"],
        "examples_suffix": ["Engine", "Builder", "Driver"],
    },
    "template_pattern": {
        "entity_types": ["Class", "Dict"],
        "bases": ["BaseTemplate"],
        "examples_suffix": ["Template", "Layout", "Format"],
    },
}
TEST_TYPE_SIGNALS: Final[Mapping[str, Mapping[str, Any]]] = {
    "tests/unit": {
        "description": "Isolated logic tests using mocks and no external I/O.",
        "imports": ["unittest.mock", "MagicMock", "patch", "pytest_mock"],
        "forbidden_imports": ["playwright", "selenium", "requests", "httpx", "psycopg2"],
        "decorators": ["@pytest.mark.unit"],
        "class_patterns": [".*Unit.*", ".*TestBase$"],
        "priority": 1,
    },
    "tests/integration": {
        "description": "Component interaction tests involving DB, API, or Filesystem.",
        "imports": ["fastapi.testclient", "httpx", "requests", "sqlalchemy", "redis"],
        "decorators": ["@pytest.mark.integration", "@pytest.mark.asyncio"],
        "class_patterns": [".*Integration.*", ".*ApiTest.*"],
        "priority": 2,
    },
    "tests/e2e": {
        "description": "Full system simulation using browser automation or real environments.",
        "imports": ["playwright", "selenium", "puppeteer", "subprocess"],
        "decorators": ["@pytest.mark.e2e"],
        "class_patterns": [".*E2E.*", ".*Browser.*", ".*Flow.*"],
        "priority": 3,
    },
}
LEGACY_AST_SIGNALS: Final[Mapping[str, Mapping[str, Any]]] = {
    "archives/legacy_code": {
        "description": "Code explicitly marked as deprecated, legacy, or v1.",
        "decorators": ["@deprecated", "@obsolete"],
        "docstring_markers": ["DEPRECATED", "LEGACY", "DO NOT USE", "MOVED TO"],
        "class_patterns": [".*Legacy.*", ".*Old$", ".*V1$"],
        "function_calls": ["warnings.warn"],
        "variable_markers": ["DEPRECATION_WARNING"],
    },
}
AST_PLACEMENT_SIGNALS: Final[Mapping[str, Mapping[str, Any]]] = {
    "agentic_core/interfaces": {
        "class_patterns": ["^I[A-Z].*Protocol$", "^I[A-Z].*$"],
        "base_classes": ["Protocol", "ABC", "typing.Protocol", "abc.ABC"],
        "function_patterns": [],
        "import_signals": ["typing.Protocol", "abc.ABC", "abc.abstractmethod"],
        "keyword_signals": ["protocol", "interface", "contract", "abstract"],
        "filename_patterns": ["^I[A-Z].*Protocol\\.py$"],
        "decorator_signals": ["@abstractmethod", "@runtime_checkable"],
        "weight": 100,
    },
    "agentic_core/base_agents": {
        "class_patterns": [".*Base$"],
        "base_classes": [
            "SovereignBaseAgent",
            "CanonBaseAgent",
            "L0RoutingBase",
            "L1CognitionBase",
            "L2ExecutionBase",
            "L3OrchestrationBase",
            "L4StateBase",
            "L5SafetyBase",
            "L6ObservabilityBase",
        ],
        "function_patterns": [],
        "import_signals": [],
        "keyword_signals": ["sovereign", "base", "inheritance", "abstract", "foundation"],
        "decorator_signals": [],
        "weight": 100,
    },
    "agentic_core/runtime/types": {
        "class_patterns": [".*Model$", ".*Schema$", ".*DTO$", ".*Types$"],
        "base_classes": ["BaseModel", "pydantic.BaseModel"],
        "import_signals": ["pydantic", "typing", "typing_extensions"],
        "keyword_signals": [
            "field",
            "validator",
            "root_validator",
            "config",
            "TypeAlias",
            "TypedDict",
            "Literal",
            "Union",
            "Optional",
        ],
        "filename_patterns": [".*_types\\.py$"],
        "weight": 10,
    },
    "agentic_core/config": {
        "class_patterns": [".*Config$", ".*Settings$"],
        "base_classes": ["BaseSettings"],
        "import_signals": ["pydantic_settings"],
        "keyword_signals": ["env_file", "secrets", "api_key"],
        "weight": 10,
    },
    "agentic_core/knowledge": {
        "class_patterns": [".*Orchestrator$", ".*Manager$", ".*Loader$", ".*Cache$"],
        "base_classes": ["BaseDocumentLoader"],
        "function_patterns": ["retrieve_.*", "ingest_.*", "index_.*"],
        "import_signals": ["knowledge", "rag", "document_loaders"],
        "keyword_signals": ["rag", "retrieval", "knowledge", "document", "ingest", "orchestrator"],
        "weight": 12,
    },
    "agentic_core/L1_cognition/thought_engine": {
        "class_patterns": [".*Node$", ".*Thought.*", ".*Reason.*", ".*Chain.*", ".*Strategy$"],
        "base_classes": ["BaseNode", "ThoughtNode", "ReActNode", "ReActStrategy"],
        "function_patterns": ["think_.*", "reason_.*", "decompose_.*"],
        "import_signals": ["langchain", "langgraph", "thought_engine"],
        "keyword_signals": ["thought", "reasoning", "decomposition", "chain_of_thought", "react", "strategy"],
        "decorator_signals": ["@thought_node", "@reasoning_step"],
        "weight": 15,
    },
    "agentic_core/L1_cognition/planning": {
        "class_patterns": [".*Planner.*", ".*Strategy.*", ".*Plan.*"],
        "base_classes": ["BasePlanner", "StrategyPlanner"],
        "function_patterns": ["plan_.*", "strategize_.*", "decompose_task.*"],
        "import_signals": ["planning", "strategy"],
        "keyword_signals": ["planner", "strategy", "plan", "goal", "objective"],
        "weight": 15,
    },
    "agentic_core/L2_execution/reasoning": {
        "class_patterns": [".*Agent$", ".*Tool$", ".*Handler$"],
        "base_classes": ["SubAtomicAgent", "BaseTool", "ToolHandler"],
        "function_patterns": ["execute_.*", "run_tool.*", "invoke_.*"],
        "import_signals": ["tool_registry", "SubAtomicAgent"],
        "keyword_signals": ["tool", "execute", "invoke", "action", "handler"],
        "decorator_signals": ["@tool", "@action"],
        "weight": 9,
    },
    "agentic_core/L2_execution/action_handlers": {
        "class_patterns": [".*ActionHandler$", ".*Executor$"],
        "base_classes": ["ActionHandler", "BaseExecutor"],
        "function_patterns": ["handle_action.*", "execute_action.*"],
        "import_signals": ["action_handlers"],
        "keyword_signals": ["action", "handler", "execute", "perform"],
        "weight": 7,
    },
    "agentic_core/L2_execution/enforcement": {
        "class_patterns": [".*MCP.*", ".*Client$", ".*Server$"],
        "base_classes": ["MCPClient", "MCPServer"],
        "function_patterns": ["mcp_.*", "fetch_.*", "connect_.*"],
        "import_signals": ["mcp", "model_context_protocol"],
        "keyword_signals": ["mcp", "model_context_protocol", "fetch", "client", "server"],
        "weight": 9,
    },
    "agentic_core/L3_orchestration/reasoning": {
        "class_patterns": [".*Engine$", ".*Orchestrator$", ".*Controller$", ".*Coordinator$"],
        "base_classes": ["BaseEngine", "WorkflowEngine", "Orchestrator"],
        "function_patterns": ["orchestrate_.*", "coordinate_.*", "run_workflow.*"],
        "import_signals": ["workflow_engines", "orchestration"],
        "keyword_signals": ["orchestrator", "workflow", "engine", "coordinate", "mission", "controller"],
        "decorator_signals": ["@workflow", "@orchestrate"],
        "weight": 16,
    },
    "agentic_core/L3_orchestration/reasoning": {
        "class_patterns": [".*Fission.*", ".*Split.*", ".*Decompose.*"],
        "base_classes": ["FissionEngine", "TaskSplitter"],
        "function_patterns": ["fission_.*", "split_.*", "decompose_.*"],
        "import_signals": ["fission_logic"],
        "keyword_signals": ["fission", "split", "decompose", "parallel", "distribute"],
        "weight": 16,
    },
    "agentic_core/L3_orchestration/meta_learning": {
        "class_patterns": [".*MetaLearn.*", ".*Adaptive.*", ".*SelfImprove.*"],
        "base_classes": ["MetaLearner", "AdaptiveAgent"],
        "function_patterns": ["meta_learn.*", "adapt_.*", "self_improve.*"],
        "import_signals": ["meta_learning"],
        "keyword_signals": ["meta", "learning", "adaptive", "self_improve", "evolve"],
        "weight": 16,
    },
    "agentic_core/L4_state/memory": {
        "class_patterns": [".*Context.*", ".*State.*", ".*Session.*"],
        "base_classes": ["ValidationContext", "StateManager"],
        "function_patterns": ["get_context.*", "set_state.*", "validate_context.*"],
        "import_signals": ["validation_context"],
        "keyword_signals": ["context", "state", "session", "validation"],
        "weight": 14,
    },
    "agentic_core/L4_state/enforcement": {
        "class_patterns": [".*Ledger.*", ".*Audit.*", ".*Log.*", ".*Historian.*"],
        "base_classes": ["BaseLedger", "AuditLog"],
        "function_patterns": ["log_.*", "record_.*", "audit_.*"],
        "import_signals": ["ledger"],
        "keyword_signals": ["ledger", "audit", "log", "record", "Historian", "trail"],
        "weight": 14,
    },
    "agentic_core/L4_state/memory": {
        "class_patterns": [".*Memory.*", ".*cache.*", ".*Store.*", ".*Adapter$"],
        "base_classes": ["MemoryStore", "CacheManager"],
        "function_patterns": ["store_.*", "retrieve_.*", "cache_.*"],
        "import_signals": ["pinecone", "redis", "memory"],
        "keyword_signals": ["memory", "cache", "store", "retrieve", "embedding", "vector", "adapter"],
        "weight": 14,
    },
    "agentic_core/L5_safety/enforcement": {
        "class_patterns": [".*Guardrail.*", ".*Limit.*", ".*Throttle.*", ".*Healer.*"],
        "base_classes": ["BaseGuardrail", "RateLimiter", "CircuitBreaker"],
        "function_patterns": ["guard_.*", "limit_.*", "throttle_.*", "heal_.*"],
        "import_signals": ["guardrails", "safety"],
        "keyword_signals": ["guardrail", "safety", "limit", "throttle", "heal", "circuit", "breaker"],
        "decorator_signals": ["@guardrail", "@rate_limit"],
        "weight": 25,
    },
    "agentic_core/L5_safety/validators": {
        "purpose": "Deterministic safety checks and domain validation",
        "class_patterns": [".*Validator.*", ".*Enforcer.*", ".*Checker.*", ".*Agent$", ".*Deterministic$"],
        "base_classes": ["BaseValidator", "Enforcer"],
        "function_patterns": ["validate_.*", "enforce_.*", "check_.*"],
        "import_signals": ["validators", "compliance"],
        "keyword_signals": [
            "validator",
            "enforce",
            "compliance",
            "check",
            "verify",
            "audit",
            "deterministic",
            "sanitizer",
        ],
        "filename_patterns": [".*_validator\\.py$"],
        "weight": 50,
    },
    "agentic_core/L5_safety/enforcement": {
        "class_patterns": [".*Gravity.*", ".*Import.*", ".*Waterfall.*"],
        "base_classes": ["GravityEnforcer", "ImportValidator"],
        "function_patterns": ["check_gravity.*", "validate_import.*"],
        "import_signals": ["gravity"],
        "keyword_signals": ["gravity", "import", "waterfall", "upstream", "downstream"],
        "weight": 22,
    },
    "agentic_core/L5_safety/reasoning": {
        "class_patterns": [".*RedTeam.*", ".*Adversarial.*", ".*Attack.*"],
        "base_classes": ["RedTeamAgent", "AdversarialTester"],
        "function_patterns": ["attack_.*", "probe_.*", "fuzz_.*"],
        "import_signals": ["red_teaming"],
        "keyword_signals": ["redteam", "adversarial", "attack", "probe", "jailbreak", "exploit"],
        "weight": 20,
    },
    "agentic_core/L5_safety/utils": {
        "class_patterns": [".*Security.*", ".*Control.*", ".*Subprocess.*"],
        "base_classes": [],
        "function_patterns": ["validate_.*", "safe_.*", "security_.*", "create_instance.*"],
        "import_signals": ["L5_safety", "security"],
        "keyword_signals": ["security", "controls", "safe_execute", "subprocess", "injection", "whitelist"],
        "filename_patterns": [".*security.*_util\\.py$", ".*controls.*_util\\.py$"],
        "weight": 26,
    },
    "agentic_core/utils/naming": {
        "class_patterns": [".*Naming.*", ".*Case.*"],
        "base_classes": [],
        "function_patterns": ["to_snake_case.*", "to_pascal_case.*", "validate_name.*"],
        "import_signals": ["naming"],
        "keyword_signals": ["naming", "snake_case", "pascal_case", "case", "convention"],
        "weight": 7,
    },
    "agentic_core/observability/metrics": {
        "class_patterns": [".*Metric.*", ".*Counter.*", ".*Gauge.*"],
        "base_classes": ["MetricCollector"],
        "function_patterns": ["collect_metric.*", "record_.*", "measure_.*"],
        "import_signals": ["prometheus", "metrics"],
        "keyword_signals": ["Metric", "counter", "gauge", "measure", "telemetry"],
        "weight": 7,
    },
    "agentic_core/observability/tracing": {
        "class_patterns": [".*Tracer.*", ".*Span.*"],
        "base_classes": ["Tracer", "SpanContext"],
        "function_patterns": ["trace_.*", "start_span.*"],
        "import_signals": ["opentelemetry", "tracing"],
        "keyword_signals": ["trace", "Span", "opentelemetry", "jaeger"],
        "weight": 7,
    },
    "agentic_core/observability/compliance": {
        "class_patterns": [".*Compliance.*", ".*Report.*"],
        "base_classes": ["ComplianceReporter"],
        "function_patterns": ["report_.*", "generate_compliance.*"],
        "import_signals": ["compliance"],
        "keyword_signals": ["compliance", "report", "audit", "coverage"],
        "weight": 7,
    },
    "agentic_core/prompt_governance/templates": {
        "class_patterns": [".*Template.*", ".*Prompt.*"],
        "base_classes": ["PromptTemplate"],
        "function_patterns": ["render_prompt.*", "format_template.*"],
        "import_signals": ["jinja2", "prompt_governance"],
        "keyword_signals": ["prompt", "template", "jinja", "render"],
        "decorator_signals": ["@registers_prompt"],
        "weight": 15,
    },
    "agentic_core/prompt_governance/meta_prompts": {
        "class_patterns": [".*MetaPrompt.*", ".*SystemPrompt.*"],
        "base_classes": ["MetaPrompt"],
        "function_patterns": ["generate_meta_prompt.*"],
        "import_signals": ["meta_prompts"],
        "keyword_signals": ["meta_prompt", "system_prompt", "persona"],
        "weight": 15,
    },
}
PLACEMENT_CONFIDENCE = {"HIGH": 0.8, "MEDIUM": 0.5, "LOW": 0.3, "REJECT": 0.0}
L2_TO_L1_MAP: Final[Mapping[str, str]] = {
    "reasoning": "CONTEXT_DEPENDENT",
    "enforcement": "CONTEXT_DEPENDENT",
    "validators": "CONTEXT_DEPENDENT",
    "utils": "CONTEXT_DEPENDENT",
    "config": "CONTEXT_DEPENDENT",
    "types": "CONTEXT_DEPENDENT",
    "scripts": "L0_routing",
    "tools": "L2_execution",
    "memory": "L4_state",
    "dashboards": "L6_observability",
    "templates": "prompt_governance",
    "meta_prompts": "prompt_governance",
    "rendering": "prompt_governance",
    "version_registry": "prompt_governance",
    "environments": "config",
    "feature_flags": "config",
    "models": "runtime",
    "messages": "runtime",
}
EXERCISER_REGISTRY: Final[Mapping[str, str]] = {
    "L5_safety": "L5SafetyExerciserAgent",
    "L4_state": "L4StateExerciserAgent",
    "L1_cognition": "L1CognitionExerciserAgent",
    "L2_execution": "GeneralExerciserAgent",
    "L3_orchestration": "GeneralExerciserAgent",
    "L0_routing": "GeneralExerciserAgent",
    "observability": "GeneralExerciserAgent",
    "utils": "GeneralExerciserAgent",
    "config": "GeneralExerciserAgent",
    "prompt_governance": "GeneralExerciserAgent",
    "patterns": "GeneralExerciserAgent",
    "semantic_memory": "GeneralExerciserAgent",
    "knowledge": "GeneralExerciserAgent",
}
AGENT_REGISTRY: Final[Mapping[str, Sequence[Mapping[str, str | int]]]] = {
    "L0": [
        {
            "name": "BootstrapAgent",
            "file": "agentic_core/L5_safety/reasoning/BootstrapAgent.py",
            "methods": 6,
            "fingerprint": "fcfd5e27416abb4c",
        },
    ],
    "L1": [
        {
            "name": "CanonBaseAgent",
            "file": "agentic_core/L1_cognition/thought_engine/CognitionCanonBaseAgent.py",
            "methods": 8,
            "fingerprint": "ea8e7e56381918dc",
        },
        {
            "name": "DependencySentinelAgent",
            "file": "agentic_core/L1_cognition/thought_engine/DependencySentinelAgent.py",
            "methods": 9,
            "fingerprint": "3773a3e6e7e65f7d",
        },
        {
            "name": "GovernanceAgent",
            "file": "agentic_core/L1_cognition/thought_engine/GovernanceAgent.py",
            "methods": 12,
            "fingerprint": "3bab1afa3cbc06ee",
        },
        {
            "name": "MetaLearningAgent",
            "file": "agentic_core/L1_cognition/thought_engine/MetaLearningAgent.py",
            "methods": 6,
            "fingerprint": "da27f331da4c5e37",
        },
        {
            "name": "ReflectionAgent",
            "file": "agentic_core/L1_cognition/thought_engine/ReflectionAgent.py",
            "methods": 9,
            "fingerprint": "c58961965bf91d5c",
        },
    ],
    "L2": [
        {
            "name": "CanonBaseAgent",
            "file": "agentic_core/L2_execution/reasoning/ExecutionCanonBaseAgent.py",
            "methods": 13,
            "fingerprint": "00b4b4376214468b",
        },
        {
            "name": "CodeDeduplicationAgent",
            "file": "agentic_core/L2_execution/reasoning/CodeDeduplicationAgent.py",
            "methods": 11,
            "fingerprint": "1c26bf7b92ef3fb8",
        },
        {
            "name": "CodeJanitorAgent",
            "file": "agentic_core/L2_execution/reasoning/CodeJanitorAgent.py",
            "methods": 12,
            "fingerprint": "ae825674e1abeb55",
        },
        {
            "name": "ContextCuratorAgent",
            "file": "agentic_core/L2_execution/reasoning/ContextCuratorAgent.py",
            "methods": 13,
            "fingerprint": "b55bbeb3cc150054",
        },
        {
            "name": "DependencyDiplomatAgent",
            "file": "agentic_core/L2_execution/reasoning/DependencyDiplomatAgent.py",
            "methods": 11,
            "fingerprint": "15bc567d77279e31",
        },
        {
            "name": "DynamicModelRouterAgent",
            "file": "agentic_core/L2_execution/reasoning/DynamicModelRouterAgent.py",
            "methods": 11,
            "fingerprint": "e6532e4040366631",
        },
        {
            "name": "GitAgent",
            "file": "agentic_core/L2_execution/reasoning/GitAgent.py",
            "methods": 12,
            "fingerprint": "82c9b049e6fd5597",
        },
        {
            "name": "IntegrityGateExecutorAgent",
            "file": "agentic_core/L2_execution/reasoning/IntegrityGateExecutorAgent.py",
            "methods": 8,
            "fingerprint": "cc6465bde4266c9f",
        },
        {
            "name": "SovereignActionPlaneAgent",
            "file": "agentic_core/L2_execution/reasoning/SovereignActionPlaneAgent.py",
            "methods": 11,
            "fingerprint": "91faa15364d0a1a5",
        },
        {
            "name": "StructuralEngineerAgent",
            "file": "agentic_core/L2_execution/reasoning/StructuralEngineerAgent.py",
            "methods": 8,
            "fingerprint": "37d55e1531ee303e",
        },
        {
            "name": "SystemArchitectAgent",
            "file": "agentic_core/L2_execution/reasoning/SystemArchitectAgent.py",
            "methods": 8,
            "fingerprint": "e340d23c73eb4451",
        },
        {
            "name": "ToolsmithAgent",
            "file": "agentic_core/L2_execution/reasoning/ToolsmithAgent.py",
            "methods": 17,
            "fingerprint": "920d8dc7ea2d38d4",
        },
    ],
    "L3": [
        {
            "name": "DagEngineAgent",
            "file": "agentic_core/L3_orchestration/reasoning/DagEngineAgent.py",
            "methods": 14,
            "fingerprint": "e58f4699d9aa84e5",
        },
        {
            "name": "MockAgent",
            "file": "agentic_core/L3_orchestration/reasoning/NervousSystemAgent.py",
            "methods": 2,
            "fingerprint": "b644392cf05e5442",
        },
        {
            "name": "NervousSystemAgent",
            "file": "agentic_core/L3_orchestration/reasoning/NervousSystemAgent.py",
            "methods": 12,
            "fingerprint": "c3a187f4f4fd9eeb",
        },
        {
            "name": "SemanticGatekeeperAgent",
            "file": "agentic_core/L3_orchestration/reasoning/SemanticGatekeeperAgent.py",
            "methods": 6,
            "fingerprint": "40da7e8727c03cdc",
        },
        {
            "name": "SubatomicHopAgent",
            "file": "agentic_core/L3_orchestration/reasoning/SubatomicHopAgent.py",
            "methods": 14,
            "fingerprint": "7c2a442208c79cd7",
        },
        {
            "name": "TestPilotAgent",
            "file": "agentic_core/L3_orchestration/reasoning/TestPilotAgent.py",
            "methods": 15,
            "fingerprint": "5948ee871695c65f",
        },
    ],
    "L4": [
        {
            "name": "AutonomousCheckpointManagerAgent",
            "file": "agentic_core/L4_state/memory/AutonomousCheckpointManagerAgent.py",
            "methods": 13,
            "fingerprint": "41e505612b995ed9",
        },
        {
            "name": "AutonomousStateGuardianAgent",
            "file": "agentic_core/L4_state/memory/AutonomousStateGuardianAgent.py",
            "methods": 10,
            "fingerprint": "5ebb94cbbdf1aa58",
        },
        {
            "name": "RedisSovereignAgent",
            "file": "agentic_core/L4_state/memory/RedisSovereignAgent.py",
            "methods": 6,
            "fingerprint": "b040e351f725cddb",
        },
        {
            "name": "SchemaEvolverAgent",
            "file": "agentic_core/L4_state/memory/SchemaEvolverAgent.py",
            "methods": 14,
            "fingerprint": "895c1f48e33df32e",
        },
        {
            "name": "SubAtomicRegistryAgent",
            "file": "agentic_core/L4_state/memory/SubAtomicRegistryAgent.py",
            "methods": 7,
            "fingerprint": "78801bbc67f74db4",
        },
    ],
    "L5": [
        {
            "name": "AdversarialRedTeamerAgent",
            "file": "agentic_core/L5_safety/enforcement/AdversarialRedTeamerAgent.py",
            "methods": 24,
            "fingerprint": "f7b28e4a681e38f8",
        },
        {
            "name": "AutonomousThreatEvolutionAgent",
            "file": "agentic_core/L5_safety/enforcement/AutonomousThreatEvolutionAgent.py",
            "methods": 11,
            "fingerprint": "c181817ddf232911",
        },
        {
            "name": "DocstringComplianceAgent",
            "file": "agentic_core/L5_safety/validators/DocstringComplianceAgent.py",
            "methods": 3,
            "fingerprint": "667c2361a762cd69",
        },
        {
            "name": "FilenameUniquenessGuardianAgent",
            "file": "agentic_core/L5_safety/validators/FilenameUniquenessGuardianAgent.py",
            "methods": 5,
            "fingerprint": "823711cf0f58b0ff",
        },
        {
            "name": "FilesystemAgent",
            "file": "agentic_core/L5_safety/validators/FilesystemAgent.py",
            "methods": 6,
            "fingerprint": "404bc60482eb1646",
        },
        {
            "name": "GravityLeakRepairAgent",
            "file": "agentic_core/L5_safety/enforcement/GravityLeakRepairAgent.py",
            "methods": 3,
            "fingerprint": "51dbad0a31ea9c72",
        },
        {
            "name": "HallucinationHunterAgent",
            "file": "agentic_core/L5_safety/enforcement/HallucinationHunterAgent.py",
            "methods": 9,
            "fingerprint": "88a8355c3b923aa1",
        },
        {
            "name": "HealerAgent",
            "file": "agentic_core/L5_safety/enforcement/HealerAgent.py",
            "methods": 14,
            "fingerprint": "f7be54e968a04313",
        },
        {
            "name": "HierarchyAgent",
            "file": "agentic_core/L5_safety/validators/HierarchyAgent.py",
            "methods": 14,
            "fingerprint": "c4ba74a74c6e27d2",
        },
        {
            "name": "HygieneGuardianAgent",
            "file": "agentic_core/L5_safety/validators/HygieneGuardianAgent.py",
            "methods": 4,
            "fingerprint": "3aa2327dde094b31",
        },
        {
            "name": "ImportAgent",
            "file": "agentic_core/L5_safety/enforcement/ImportAgent.py",
            "methods": 7,
            "fingerprint": "f1dad62889a51085",
        },
        {
            "name": "InferenceTypeHintAgent",
            "file": "agentic_core/L5_safety/validators/InferenceTypeHintAgent.py",
            "methods": 3,
            "fingerprint": "0fd4fbfb4402be61",
        },
        {
            "name": "L5IntegrityGateExecutorAgent",
            "file": "agentic_core/L5_safety/enforcement/L5IntegrityGateExecutorAgent.py",
            "methods": 17,
            "fingerprint": "790a1b648be58757",
        },
        {
            "name": "LocationAgent",
            "file": "agentic_core/L5_safety/validators/LocationAgent.py",
            "methods": 9,
            "fingerprint": "5e49cfc8aebe839e",
        },
        {
            "name": "NeuralAutoImmuneAgent",
            "file": "agentic_core/L5_safety/enforcement/NeuralAutoImmuneAgent.py",
            "methods": 3,
            "fingerprint": "78dc1bb327996dcf",
        },
        {
            "name": "RedTeamAgent",
            "file": "agentic_core/L5_safety/reasoning/RedTeamAgent.py",
            "methods": 3,
            "fingerprint": "d76f6932c53b7a77",
        },
        {
            "name": "RegressionOracleAgent",
            "file": "agentic_core/L5_safety/validators/RegressionOracleAgent.py",
            "methods": 4,
            "fingerprint": "65c42eea1de011b7",
        },
        {
            "name": "SSOTRefactorAgent",
            "file": "agentic_core/L5_safety/validators/SSOTRefactorAgent.py",
            "methods": 4,
            "fingerprint": "29f31ace7a8982fb",
        },
        {
            "name": "SelfUpdatingSafetyEngineAgent",
            "file": "agentic_core/L5_safety/enforcement/SelfUpdatingSafetyEngineAgent.py",
            "methods": 14,
            "fingerprint": "ce122c5e1c1fe306",
        },
        {
            "name": "TerritoryHealerAgent",
            "file": "agentic_core/L5_safety/enforcement/TerritoryHealerAgent.py",
            "methods": 7,
            "fingerprint": "6fdffa7306e70169",
        },
        {
            "name": "TypeHintEnforcementAgent",
            "file": "agentic_core/L5_safety/validators/TypeHintEnforcementAgent.py",
            "methods": 3,
            "fingerprint": "9bf27471e887b95c",
        },
    ],
    "L6-OBS": [
        {
            "name": "BenchmarkingAgent",
            "file": "agentic_core/observability/metrics/BenchmarkingAgent.py",
            "methods": 14,
            "fingerprint": "aaccf245087d7b9a",
        },
        {
            "name": "CoordinateObservabilityOperationsAgent",
            "file": "agentic_core/observability/metrics/CoordinateObservabilityOperationsAgent.py",
            "methods": 3,
            "fingerprint": "b79b37e264d36fb5",
        },
        {
            "name": "MetricsAgent",
            "file": "agentic_core/observability/metrics/MetricsAgent.py",
            "methods": 14,
            "fingerprint": "c857ceb2e36799b9",
        },
        {
            "name": "PredictiveCostAuditorAgent",
            "file": "agentic_core/observability/metrics/PredictiveCostAuditorAgent.py",
            "methods": 12,
            "fingerprint": "8ef66dd746dd7e50",
        },
        {
            "name": "ReportingAgent",
            "file": "agentic_core/observability/compliance/ReportingAgent.py",
            "methods": 5,
            "fingerprint": "2c9e248f2f70804b",
        },
        {
            "name": "SignatureVerifierAgent",
            "file": "agentic_core/observability/metrics/SignatureVerifierAgent.py",
            "methods": 3,
            "fingerprint": "60824e83630f2650",
        },
        {
            "name": "TelemetryAgent",
            "file": "agentic_core/observability/telemetry/TelemetryAgent.py",
            "methods": 11,
            "fingerprint": "d026b54bad957126",
        },
        {
            "name": "TracingAgent",
            "file": "agentic_core/observability/tracing/TracingAgent.py",
            "methods": 15,
            "fingerprint": "8c951c49ffa5b5ed",
        },
        {
            "name": "TrackObservabilityCostAgent",
            "file": "agentic_core/observability/metrics/TrackObservabilityCostAgent.py",
            "methods": 3,
            "fingerprint": "15b577bc8c1d7075",
        },
    ],
    "UTILS": [
        {
            "name": "NamingAgent",
            "file": "agentic_core/utils/naming/NamingAgent.py",
            "methods": 13,
            "fingerprint": "27645aed97c3aa01",
        },
        {
            "name": "NamingNormalizationAgent",
            "file": "agentic_core/utils/naming/NamingNormalizationAgent.py",
            "methods": 4,
            "fingerprint": "e09b6daa7f5988eb",
        },
    ],
}
semantic_l2_registry: Final[Mapping[str, Any]] = {
    "L5_safety": {
        "base_agents": {
            "purpose": "Constitutional foundation for all agents. Home of SovereignBaseAgent and LayerBaseAgents.",
            "entity_types": ["Class"],
            "keywords": ["base", "sovereign", "foundation", "inheritance", "abstract"],
            "imports": [],
            "bases": ["ABC"],
            "examples": ["SovereignBaseAgent", "L1CognitionBase"],
        },
        "enforcement": {
            "purpose": "Hard safety limits, mutation controls, deletion guards, circuit breakers, rate limits, throttling, and emergency stop mechanisms",
            "entity_types": ["Class"],
            "keywords": [
                "guardrail",
                "safety",
                "limit",
                "constraint",
                "circuit",
                "breaker",
                "throttle",
                "rate",
                "quota",
                "mutate",
                "delete",
                "emergency",
                "stop",
                "block",
                "prevent",
            ],
            "imports": ["agentic_core.L5_safety.enforcement"],
            "bases": ["BaseGuardrail", "SafetyGuardrail", "CircuitBreaker", "RateLimiter"],
            "examples": [
                "MutationGuardrail",
                "DeletionGuardrail",
                "RateLimitGuardrail",
                "EmergencyStopGuardrail",
                "ContentFilterGuardrail",
            ],
        },
        "reasoning": {
            "purpose": "Adversarial testing agents, automated threat simulation, exploit probing, jailbreak attempts, prompt injection testing, and attack vector generation",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "redteam",
                "red_team",
                "adversary",
                "adversarial",
                "attack",
                "exploit",
                "probe",
                "jailbreak",
                "threat",
                "simulate",
                "fuzz",
                "injection",
                "poison",
            ],
            "imports": ["agentic_core.L5_safety.reasoning"],
            "bases": ["RedTeamAgent", "AdversarialAgent", "ThreatSimulator"],
            "examples": [
                "JailbreakProber",
                "PromptInjectionAttacker",
                "ThreatSimulator",
                "AdversarialFuzzer",
                "ExploitGenerator",
            ],
        },
        "validators": {
            "purpose": "Canon constitution validators, structural policy enforcement, naming law validation, runtime compliance auditing, and architectural drift detection",
            "entity_types": ["Class"],
            "keywords": [
                "validator",
                "canon",
                "constitution",
                "rule",
                "policy",
                "enforce",
                "compliance",
                "audit",
                "drift",
                "naming",
                "law",
                "check",
                "verify",
            ],
            "imports": ["agentic_core.L5_safety.validators", "structure_blueprint"],
            "bases": ["CanonBaseAgent", "StructureValidator", "ComplianceAuditor", "DriftDetector"],
            "examples": [
                "NamingLawValidator",
                "DepthValidator",
                "GravityComplianceValidatorAgent",
                "StructuralPolicyValidator",
                "RuntimeComplianceAuditor",
            ],
        },
    },
    "L0_routing": {
        "scripts": {
            "purpose": "Autonomous healing scripts, Checkpoint management, self-updating systems, neural immune agents, and sovereign improvement missions",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "autonomous",
                "heal",
                "repair",
                "Checkpoint",
                "guardian",
                "self_update",
                "immune",
                "mission",
                "surgery",
                "refactor",
                "evolution",
            ],
            "imports": ["agentic_core.L0_routing.scripts", "structure_blueprint"],
            "bases": ["CanonBaseAgent", "AutonomousAgent", "HealingEngine"],
            "examples": [
                "AutonomousCheckpointManager",
                "AutonomousStateGuardian",
                "SelfUpdatingSafetyEngine",
                "NeuralAutoImmuneAgent",
                "SovereignHealingMission",
            ],
        },
        "logs": {
            "purpose": "Structured diagnostic logs, healing operation records, mission transcripts, and maintenance audit trails",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "log",
                "diagnostic",
                "record",
                "transcript",
                "audit",
                "maintenance_log",
                "healing_trace",
                "mission_log",
            ],
            "imports": ["agentic_core.L0_routing.utils", "logging", "json"],
            "bases": ["DiagnosticLogger", "MissionTranscript", "MaintenanceAudit"],
            "examples": [
                "HealingOperationLogger",
                "AutonomousMissionLog",
                "SovereignDiagnosticWriter",
                "MaintenanceTrace",
            ],
        },
        "benchmarks": {
            "purpose": "Performance benchmarking suites, timing profiles, resource usage metrics, and autonomous optimization baselines",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "benchmark",
                "perf",
                "timing",
                "profile",
                "Metric",
                "baseline",
                "optimize",
                "resource",
                "efficiency",
            ],
            "imports": ["agentic_core.L0_routing.benchmarks", "time", "asyncio", "psutil"],
            "bases": ["BenchmarkSuite", "PerformanceProfiler", "ResourceMonitor"],
            "examples": [
                "SovereignBenchmarkRunner",
                "ReasoningSpeedTest",
                "MemoryEfficiencyBenchmark",
                "HealingCycleProfiler",
            ],
        },
    },
    "L1_cognition": {
        "reasoning": {
            "purpose": "Core reasoning primitives, thought nodes, chain-of-thought execution, internal monologue structures, and advanced deliberation patterns",
            "entity_types": ["Class", "Protocol"],
            "keywords": [
                "thought",
                "reason",
                "node",
                "chain",
                "cot",
                "tot",
                "react",
                "monologue",
                "step",
                "decompose",
                "analyze",
                "reflect",
                "critique",
                "socratic",
                "deliberate",
                "ponder",
                "contemplate",
                "self_reflect",
            ],
            "imports": ["agentic_core.L1_cognition.reasoning", "pydantic", "typing"],
            "bases": [
                "ThoughtNode",
                "ReasoningStep",
                "BaseThought",
                "ChainOfThought",
                "TreeOfThoughts",
                "ReActStep",
                "BaseReasoningEngine",
            ],
            "examples": [
                "ReasoningNode",
                "CritiqueStep",
                "ReflectionThought",
                "ChainOfThoughtExecutor",
                "SocraticReasoner",
                "TreeOfThoughtsNode",
                "ReActAgentStep",
            ],
        },
        "planning": {
            "purpose": "Mission decomposition, strategy formulation, step sequencing, dependency mapping, plan validation, and execution roadmap generation",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "plan",
                "strategy",
                "decompose",
                "sequence",
                "step",
                "Task",
                "subtask",
                "dependency",
                "order",
                "validate",
                "breakdown",
                "hierarchy",
                "outline",
                "roadmap",
                "execute_order",
                "priority",
                "milestone",
            ],
            "imports": ["agentic_core.L1_cognition.planning", "networkx", "pydantic", "typing"],
            "bases": [
                "Planner",
                "DecompositionEngine",
                "PlanValidator",
                "StrategyBuilder",
                "BasePlanner",
                "TaskGraph",
            ],
            "examples": [
                "MissionDecomposer",
                "TaskSequencer",
                "DependencyResolver",
                "PlanValidator",
                "StrategicPlannerAgent",
                "StepHierarchyBuilder",
                "PriorityScheduler",
            ],
        },
    },
    "L2_execution": {
        "reasoning": {
            "purpose": "Registration and discovery of external tools, base tool definitions, and tool metadata management",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "tool",
                "registry",
                "register",
                "discover",
                "metadata",
                "available_tools",
                "toolset",
            ],
            "imports": ["agentic_core.L2_execution.reasoning", "pydantic", "typing"],
            "bases": ["BaseTool"],
            "examples": ["register_tool", "AvailableToolsList", "ToolMetadata"],
        },
        "action_handlers": {
            "purpose": "Action dispatch logic, handler mapping, execution routing, and fallback strategies for tool calls",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "action",
                "handler",
                "execute",
                "dispatch",
                "Route",
                "fallback",
                "perform",
                "invoke",
                "call_action",
            ],
            "imports": ["agentic_core.L2_execution.action_handlers"],
            "bases": ["ActionHandler", "BaseActionDispatcher"],
            "examples": [
                "ActionDispatcher",
                "HandlerMap",
                "DefaultActionExecutor",
                "ToolCallRouter",
                "FallbackHandler",
            ],
        },
        "mcp": {
            "purpose": "Multi-Component Protocol clients and tool implementations (figma, fetch, filesystem, semantic_cache, router, marketplace_filter)",
            "entity_types": ["Class"],
            "keywords": [
                "mcp",
                "client",
                "figma",
                "fetch",
                "filesystem",
                "semantic_cache",
                "router",
                "marketplace",
                "filter",
                "protocol",
            ],
            "imports": [
                "agentic_core.L2_execution.enforcement",
                "requests",
                "playwright",
                "selenium",
                "pinecone",
            ],
            "bases": ["BaseTool", "MCPClientBase"],
            "examples": [
                "FigmaClient",
                "FetchClientSovereign",
                "FilesystemMCPClient",
                "SemanticCacheClient",
                "MCPRouter",
                "MarketplaceFilter",
            ],
        },
    },
    "L3_orchestration": {
        "reasoning": {
            "purpose": "High-level agent orchestration, multi-agent workflow engines, Task routing, mission lifecycle management, and coordination primitives",
            "entity_types": ["Class"],
            "keywords": [
                "orchestrator",
                "coordinator",
                "workflow",
                "engine",
                "manager",
                "supervisor",
                "crew",
                "team",
                "mission",
                "lifecycle",
                "Route",
                "dispatch",
                "schedule",
            ],
            "imports": ["agentic_core.L3_orchestration.reasoning", "langgraph", "pydantic"],
            "bases": ["CanonBaseAgent", "WorkflowEngine", "OrchestratorBase", "MissionManager"],
            "examples": [
                "SovereignOrchestrator",
                "MultiAgentWorkflow",
                "TaskRouter",
                "MissionLifecycleManager",
                "AgentSupervisor",
            ],
        },
        "fission_logic": {
            "purpose": "Agent fission mechanics, dynamic sub-agent spawning, division of labor, and recursive self-delegation systems",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "fission",
                "spawn",
                "subagent",
                "divide",
                "delegate",
                "recursive",
                "split",
                "branch",
                "fork",
                "proliferate",
            ],
            "imports": ["agentic_core.L3_orchestration.reasoning"],
            "bases": ["FissionEngine", "SubAgentSpawner", "CanonBaseAgent"],
            "examples": [
                "FissionManagerAgent",
                "DynamicSubAgentCreator",
                "RecursiveDelegator",
                "TaskFissionLogic",
            ],
        },
        "S3_vitality": {
            "purpose": "System vitality monitoring, health checks, self-preservation protocols, anomaly detection, and resilience mechanisms",
            "entity_types": ["Class", "Function"],
            "keywords": [
                "vitality",
                "health",
                "monitor",
                "heartbeat",
                "anomaly",
                "resilience",
                "self_preserve",
                "watchdog",
                "liveness",
                "readiness",
            ],
            "imports": ["agentic_core.L3_orchestration.S3_vitality"],
            "bases": ["VitalityMonitor", "HealthChecker", "CanonBaseAgent"],
            "examples": [
                "VitalityGuardian",
                "SystemHealthMonitor",
                "AnomalyDetector",
                "ResilienceEngine",
                "WatchdogAgent",
            ],
        },
        "mcp": {
            "purpose": "Orchestration-level Multi-Component Protocol components (router, marketplace_filter, coordination logic)",
            "entity_types": ["Class"],
            "keywords": [
                "mcp",
                "router",
                "marketplace",
                "filter",
                "orchestrate",
                "coordinate",
                "gateway",
                "proxy",
            ],
            "imports": ["agentic_core.L3_orchestration.mcp"],
            "bases": ["MCPRouterBase", "MarketplaceFilter", "CanonBaseAgent"],
            "examples": ["MCPRouter", "MarketplaceToolFilter", "OrchestrationGateway", "MCPCoordinator"],
        },
    },
    "L4_state": {
        "reasoning": {
            "purpose": "Runtime validation contexts, state integrity containers, and scoped validation environments",
            "entity_types": ["Class"],
            "keywords": ["validation", "context", "scope", "integrity", "state_check", "validate_in_context"],
            "imports": ["agentic_core.L4_state.memory", "pydantic", "typing"],
            "bases": ["ValidationContext", "BaseStateContext"],
            "examples": ["SovereignValidationContext", "MissionValidationScope", "StateIntegrityContainer"],
        },
        "ledger": {
            "purpose": "Immutable audit ledgers, historical state records, event sourcing, and tamper-evident logs",
            "entity_types": ["Class"],
            "keywords": [
                "ledger",
                "immutable",
                "audit",
                "trail",
                "history",
                "event_source",
                "append_only",
                "commit_log",
            ],
            "imports": ["agentic_core.L4_state.enforcement"],
            "bases": ["ImmutableLedger", "AuditTrail", "EventLedger"],
            "examples": ["SovereignLedger", "MissionHistoryLedger", "StateCommitLog", "TamperEvidentRecord"],
        },
        "filesystem": {
            "purpose": "Sovereign filesystem abstractions, MCP filesystem operations, and persistent file state management",
            "entity_types": ["Class"],
            "keywords": ["filesystem", "mcp", "file", "directory", "path", "persistent", "storage", "disk"],
            "imports": ["agentic_core.L4_state.filesystem", "pathlib"],
            "bases": ["FilesystemMCP", "BaseFilesystemClient", "BaseTool"],
            "examples": ["SovereignFilesystemClient", "PersistentStateStore", "FileLedgerAdapter"],
        },
        "memory": {
            "purpose": "In-memory state stores, session management, ephemeral caches, and short-term memory systems",
            "entity_types": ["Class"],
            "keywords": [
                "memory",
                "session",
                "cache",
                "ephemeral",
                "short_term",
                "in_memory",
                "working_memory",
            ],
            "imports": ["agentic_core.L4_state.memory", "redis", "typing"],
            "bases": ["MemoryStore", "SessionManager", "EphemeralCache"],
            "examples": ["SovereignWorkingMemory", "SessionState", "ShortTermCache", "InMemoryLedger"],
        },
    },
    "config": {
        "core": {
            "purpose": "Core configuration, constants, registries, and settings",
            "entity_types": ["Dict", "Class"],
            "keywords": ["blueprint", "sovereign", "constitution", "registry", "structure", "map", "ssot"],
            "imports": ["agentic_core.config.core"],
            "bases": ["BaseConfiguration", "Constitution"],
            "examples": ["StructureBlueprint", "CanonRegistry", "SovereignConstitution"],
        },
        "environments": {
            "purpose": "Environment-specific configuration loaders, .env parsers, and context switching",
            "entity_types": ["Class", "Function"],
            "keywords": ["env", "config", "loader", "dotenv", "dev", "prod", "staging", "variable"],
            "imports": ["os", "dotenv"],
            "bases": ["ConfigLoader", "EnvironmentContext"],
            "examples": ["EnvLoader", "ProductionConfig", "DevContext", "DotenvParser"],
        },
        "feature_flags": {
            "purpose": "Feature toggle management, rollout controls, and A/B testing switches",
            "entity_types": ["Class"],
            "keywords": ["flag", "feature", "toggle", "rollout", "switch", "beta", "enable", "disable"],
            "imports": ["agentic_core.config.feature_flags"],
            "bases": ["FeatureToggle", "FlagManager"],
            "examples": ["LaunchDarklyAdapter", "FeatureFlagStore", "BetaRolloutSwitch"],
        },
        "secrets_manager": {
            "purpose": "Secure secret retrieval, vault integration, and credential rotation",
            "entity_types": ["Class"],
            "keywords": ["secret", "vault", "key", "credential", "token", "password", "encrypt", "decrypt"],
            "imports": ["agentic_core.config.secrets_manager"],
            "bases": ["SecretsVault", "CredentialProvider"],
            "examples": ["VaultClient", "AWSSystemManager", "SecureTokenStore"],
        },
    },
    "runtime": {
        "shared_runtime": {
            "purpose": "Shared runtime environment setup, void compliance, and global initialization",
            "entity_types": ["Class", "Function"],
            "keywords": ["runtime", "shared", "void", "compliance", "init", "bootstrap", "setup", "global"],
            "imports": ["agentic_core.runtime.shared_runtime"],
            "bases": ["RuntimeContext"],
            "examples": ["VoidComplianceCheck", "runtime_bootstrapper", "GlobalInit"],
        },
        "resource_management": {
            "purpose": "Resource allocation, throttling quotas, thread pool management, and cleanup",
            "entity_types": ["Class"],
            "keywords": ["resource", "throttle", "quota", "cleanup", "pool", "thread", "limit", "allocate"],
            "imports": ["concurrent.futures"],
            "bases": ["ResourceManager", "QuotaEnforcer"],
            "examples": ["ThreadPoolManager", "MemoryQuotaGuard", "ResourceCleaner"],
        },
    },
    "observability": {
        "metrics": {
            "purpose": "Metric collection, counters, gauges, and prometheus exports",
            "entity_types": ["Class"],
            "keywords": ["Metric", "counter", "gauge", "histogram", "prometheus", "stat"],
            "imports": ["prometheus_client"],
            "bases": ["MetricCollector"],
            "examples": ["PerformanceMetrics", "RequestCounter", "SystemGauge"],
        },
        "telemetry": {
            "purpose": "Distributed telemetry, event emission, and structured observability events",
            "entity_types": ["Class"],
            "keywords": ["telemetry", "event", "emit", "signal", "observe"],
            "imports": ["opentelemetry"],
            "bases": ["TelemetryProvider"],
            "examples": ["EventEmitter", "TelemetrySignal", "StructuredObserver"],
        },
        "tracing": {
            "purpose": "Span tracing, context propagation, and distributed trace ids",
            "entity_types": ["Class"],
            "keywords": ["trace", "Span", "context", "propagate", "id", "parent"],
            "imports": ["opentelemetry.trace"],
            "bases": ["TracerBase"],
            "examples": ["SpanContext", "DistributedTracer", "ContextPropagator"],
        },
        "compliance": {
            "purpose": "Compliance reporting, canon drift detection logs, and policy Violation records",
            "entity_types": ["Class", "Function"],
            "keywords": ["compliance", "drift", "report", "canon", "Violation", "audit"],
            "imports": [],
            "bases": ["ComplianceReporter"],
            "examples": ["DriftReportGenerator", "CanonComplianceLog", "ViolationTracker"],
        },
    },
    "utils": {
        "core_extensions": {
            "purpose": "Core Python extensions, polyfills, and monkey-patches",
            "entity_types": ["Function", "Class"],
            "keywords": ["extension", "polyfill", "monkey", "patch", "enhance"],
            "imports": [],
            "bases": [],
            "examples": ["StringExtensions", "DictMergePolyfill", "CoreMonkeyPatch"],
        },
        "wrappers": {
            "purpose": "Decorators, generic wrappers, and function proxies",
            "entity_types": ["Function"],
            "keywords": ["wrapper", "decorator", "retry", "cache", "proxy", "intercept"],
            "imports": ["functools"],
            "bases": [],
            "examples": ["retry_with_backoff", "cached_property_wrapper", "LogExecutionDecorator"],
        },
        "general_helpers": {
            "purpose": "Domain-agnostic helper functions and miscellaneous core utilities",
            "entity_types": ["Function"],
            "keywords": ["helper", "util", "misc", "common", "format"],
            "imports": [],
            "bases": [],
            "examples": ["date_helper", "string_formatter", "generic_util"],
        },
        "naming": {
            "purpose": "Naming law enforcement logic, casing validators, and canon signal checks",
            "entity_types": ["Class", "Function"],
            "keywords": ["naming", "canon", "signal", "law", "case", "snake", "camel"],
            "imports": ["agentic_core.utils.naming", "re"],
            "bases": ["NamingValidator"],
            "examples": ["SnakeCaseValidator", "CanonSignalChecker", "NamingLawEnforcer"],
        },
    },
    "patterns": {
        "agent_roles": {
            "purpose": "Pre-defined agent personas, role templates, and behavioral archetypes",
            "entity_types": ["Class", "Dict"],
            "keywords": ["role", "persona", "agent_type", "Archetype", "behavior"],
            "imports": [],
            "bases": ["CanonBaseAgent"],
            "examples": ["SocraticPersona", "CriticRole", "ArchitectArchetype"],
        },
        "communication_flow": {
            "purpose": "Inter-agent message passing patterns and handoff protocols",
            "entity_types": ["Class"],
            "keywords": ["communication", "message", "flow", "protocol", "handoff", "channel"],
            "imports": [],
            "bases": ["CommunicationProtocol"],
            "examples": ["MessageBusPattern", "HandoffProtocol", "ChannelPattern"],
        },
        "interaction_patterns": {
            "purpose": "Common human-agent and agent-tool interaction patterns (CLI, Chat, etc)",
            "entity_types": ["Class"],
            "keywords": ["interaction", "pattern", "ui", "cli", "chat", "ux"],
            "imports": [],
            "bases": [],
            "examples": ["CliInteractionPattern", "ChatLoopPattern", "ToolUsePattern"],
        },
        "reasoning_patterns": {
            "purpose": "Reusable reasoning strategies (CoT, ToT, ReAct) as abstract patterns",
            "entity_types": ["Class"],
            "keywords": ["reasoning", "strategy", "cot", "tot", "react", "chain", "tree"],
            "imports": ["agentic_core.patterns.reasoning_patterns"],
            "bases": ["BaseReasoningEngine"],
            "examples": ["ChainOfThoughtPattern", "TreeOfThoughtsStrategy", "ReActLoopPattern"],
        },
    },
    "knowledge": {
        "document_loaders": {
            "purpose": "Document ingestion, parsing, and unstructured data loading utilities",
            "entity_types": ["Class"],
            "keywords": ["loader", "ingest", "parse", "document", "pdf", "txt", "html"],
            "imports": ["unstructured", "langchain"],
            "bases": ["BaseLoader"],
            "examples": ["PDFLoader", "TextIngestor", "HTMLParser"],
        },
        "static_index": {
            "purpose": "Hard-coded knowledge bases, static facts, and lookup tables",
            "entity_types": ["Dict", "Class"],
            "keywords": ["static", "index", "facts", "knowledge", "lookup", "table", "constants"],
            "imports": [],
            "bases": [],
            "examples": ["WorldFactsIndex", "ConstantLookup", "StaticKnowledgeBase"],
        },
        "ResearchCache": {
            "purpose": "Cached research results, external knowledge snapshots, and query history",
            "entity_types": ["Class"],
            "keywords": ["research", "cache", "snapshot", "history", "query", "stored"],
            "imports": [],
            "bases": ["CacheStore"],
            "examples": ["ResearchResultCache", "KnowledgeSnapshot", "QueryHistoryLog"],
        },
    },
    "prompt_governance": {
        "templates": {
            "description": "Atomic instructional fragments and Jinja2 partials.",
            "purpose": "Reusable prompt fragments, system instructions, and jinja templates",
            "entity_types": ["Class", "str constant"],
            "keywords": ["prompt", "template", "system", "instruction", "jinja", "partial"],
            "imports": ["jinja2"],
            "bases": [],
            "allowed_extensions": [".jinja", ".txt"],
            "required_content": ["SCHEMA_HEADER"],
            "category": "PARTIAL",
        },
        "meta_prompts": {
            "description": "High-level strategic directives and persona definitions.",
            "purpose": "Strategic prompt orchestration, persona definitions, and meta-level directives",
            "entity_types": ["Class", "str constant"],
            "keywords": ["meta", "persona", "strategy", "directive", "orchestration"],
            "imports": ["jinja2", "yaml"],
            "bases": [],
            "allowed_extensions": [".jinja", ".yaml"],
            "required_content": ["VERSIONED_ENTRY"],
            "category": "STRATEGY",
        },
        "rendering": {
            "purpose": "Dynamic prompt assembly, variable substitution, and rendering logic",
            "entity_types": ["Class", "Function"],
            "keywords": ["render", "assemble", "build", "format", "interpolate"],
            "imports": ["jinja2"],
            "bases": [],
        },
    },
    "semantic_memory": {
        "embeddings": {
            "purpose": "Embedding generation, caching, and dimension management",
            "entity_types": ["Class", "Function"],
            "keywords": ["embedding", "embed", "vectorize", "dimension", "latent"],
            "imports": ["google.genai"],
            "bases": [],
        },
        "retrieval": {
            "purpose": "Semantic search, similarity scoring, and RAG retrieval",
            "entity_types": ["Class", "Function"],
            "keywords": ["retriev", "search", "similarity", "rag", "query", "lookup"],
            "imports": ["pinecone"],
            "bases": [],
        },
    },
    "apps_rg": {
        "core": {
            "purpose": "App-specific base classes, configuration, and exception definitions",
            "entity_types": ["Class"],
            "keywords": ["base", "config", "exception", "settings", "setup"],
            "imports": ["apps_rg.core"],
            "bases": ["BaseConfig", "BaseException"],
        },
        "domain": {
            "purpose": "Pure domain models, type definitions, and business entities",
            "entity_types": ["Class"],
            "keywords": ["model", "type", "entity", "struct", "dataclass"],
            "imports": ["pydantic"],
            "bases": ["BaseModel"],
        },
        "logic_nodes": {
            "purpose": "Business logic nodes for resume extraction, parsing, and section formatting",
            "entity_types": ["Class"],
            "keywords": [
                "resume",
                "cv",
                "node",
                "section",
                "experience",
                "education",
                "skill",
                "extract",
                "format",
                "parse",
            ],
            "imports": ["apps_rg.types", "pydantic"],
            "bases": ["BaseNode", "ResumeNode", "ExtractionNode"],
            "examples": ["ExperienceNode", "SkillExtractNode", "EducationFormatter", "HeaderLogicNode"],
        },
        "asset_library": {
            "purpose": "Static assets, hardcoded strings, action verbs, and skill taxonomies for resumes",
            "entity_types": ["Class", "Dict"],
            "keywords": [
                "asset",
                "string",
                "text",
                "resource",
                "copy",
                "wording",
                "verbs",
                "skills",
                "taxonomy",
            ],
            "imports": [],
            "bases": ["BaseAsset"],
            "examples": ["ResumeAssets", "ActionVerbs", "SkillTaxonomy", "ResumeTemplateStrings"],
        },
        "system_flow": {
            "purpose": "Linear and branching pipelines for the resume generation lifecycle",
            "entity_types": ["Class"],
            "keywords": [
                "flow",
                "pipeline",
                "sequence",
                "generate",
                "create",
                "process",
                "workflow",
                "lifecycle",
            ],
            "imports": ["apps_rg.system_flow"],
            "bases": ["BaseFlow", "ResumeGenerationFlow"],
            "examples": [
                "GenerationFlow",
                "ReviewPipeline",
                "PdfGenerationWorkflow",
                "ContentRefinementFlow",
            ],
        },
        "engines": {
            "purpose": "Core rendering engines for document export (PDF, Docx, HTML)",
            "entity_types": ["Class"],
            "keywords": ["engine", "render", "export", "pdf", "docx", "builder", "latex", "jinja"],
            "imports": ["apps_rg.engines", "jinja2"],
            "bases": ["BaseEngine", "DocumentBuilder"],
            "examples": ["PdfEngine", "DocxBuilder", "HtmlRenderer", "LatexCompiler"],
        },
        "templates": {
            "purpose": "Visual layouts, CSS/Style definitions, and structural blueprints for documents",
            "entity_types": ["Class", "Dict"],
            "keywords": ["template", "layout", "style", "theme", "design", "format", "css", "blueprint"],
            "imports": [],
            "bases": ["BaseTemplate", "ResumeLayout"],
            "examples": ["ModernTemplate", "ClassicLayout", "ExecutiveBlueprint", "MinimalistStyle"],
        },
    },
    "apps_lic": {
        "core": {
            "purpose": "App-specific base classes, configuration, and exception definitions",
            "entity_types": ["Class"],
            "keywords": ["base", "config", "exception", "settings", "setup"],
            "imports": ["apps_lic.core"],
            "bases": ["BaseConfig", "BaseException"],
        },
        "domain": {
            "purpose": "Pure domain models, type definitions, and business entities",
            "entity_types": ["Class"],
            "keywords": ["model", "type", "entity", "struct", "dataclass"],
            "imports": ["pydantic"],
            "bases": ["BaseModel"],
        },
        "logic_nodes": {
            "purpose": "Business logic nodes for profile analysis, connection requests, and message generation",
            "entity_types": ["Class"],
            "keywords": [
                "linkedin",
                "lic",
                "node",
                "message",
                "connect",
                "invite",
                "profile",
                "scrutinize",
                "analyze",
            ],
            "imports": ["apps_lic.types"],
            "bases": ["BaseNode", "LicNode", "MessagingNode"],
            "examples": ["ConnectNode", "MessageDraftNode", "ProfileScrutinyNode", "LeadValidationNode"],
        },
        "asset_library": {
            "purpose": "Outreach scripts, message templates, connection notes, and sequence assets",
            "entity_types": ["Class", "Dict"],
            "keywords": ["asset", "note", "message", "template", "script", "outreach", "sequence", "hook"],
            "imports": [],
            "bases": ["BaseAsset"],
            "examples": ["ConnectionNotes", "FollowUpScripts", "OutreachTemplates", "MessageHooks"],
        },
        "system_flow": {
            "purpose": "Outreach campaign management, multi-step drip sequences, and cadence logic",
            "entity_types": ["Class"],
            "keywords": ["flow", "campaign", "sequence", "cadence", "outreach", "drip", "funnel", "pipeline"],
            "imports": ["apps_lic.system_flow"],
            "bases": ["BaseFlow", "OutreachCampaign"],
            "examples": ["OutreachCampaign", "DailyFlow", "DripSequenceFlow", "FollowUpCadence"],
        },
        "engines": {
            "purpose": "Automated browser drivers for LinkedIn navigation and interaction",
            "entity_types": ["Class"],
            "keywords": [
                "engine",
                "driver",
                "navigate",
                "automate",
                "browser",
                "playwright",
                "selenium",
                "scrape",
            ],
            "imports": ["apps_lic.engines", "playwright", "selenium"],
            "bases": ["BaseEngine", "BrowserDriver"],
            "examples": ["NavigationEngine", "BrowserDriver", "ScrapingEngine", "InteractionDriver"],
        },
        "templates": {
            "purpose": "Message formatting schemas and campaign structural blueprints",
            "entity_types": ["Class"],
            "keywords": ["template", "structure", "format", "blueprint", "schema"],
            "imports": [],
            "bases": ["BaseTemplate", "LicTemplate"],
            "examples": ["CampaignTemplate", "MessageFormat", "OutreachBlueprint"],
        },
    },
    "apps_shared": {
        "core": {
            "purpose": "Abstract base classes, core interfaces, and type contracts shared across all application domains",
            "entity_types": ["Class", "Protocol", "TypeAlias"],
            "keywords": [
                "base",
                "definition",
                "type",
                "shared",
                "interface",
                "abstract",
                "contract",
                "blueprint",
                "abc",
            ],
            "imports": ["abc", "typing"],
            "bases": ["ABC", "Protocol"],
            "examples": ["BaseNode", "BaseFlow", "BaseEngine", "BaseTemplate", "BaseAsset"],
        },
        "utils": {
            "purpose": "Shared application-level utility functions for data manipulation, formatting, and common logic",
            "entity_types": ["Function", "Class"],
            "keywords": [
                "util",
                "common",
                "shared",
                "helper",
                "date",
                "string",
                "collection",
                "formatter",
                "converter",
            ],
            "imports": ["datetime", "re", "json"],
            "bases": [],
            "examples": ["date_utils", "string_helpers", "collection_transformers", "CurrencyFormatter"],
        },
        "components": {
            "purpose": "Reusable architectural widgets and modular components used across multiple app flows",
            "entity_types": ["Class"],
            "keywords": ["component", "module", "widget", "part", "element", "plugin", "extension"],
            "imports": [],
            "bases": ["BaseComponent"],
            "examples": ["LoggerComponent", "ConfigLoader", "NotificationWidget", "AppPluginBase"],
        },
        "agents": {
            "purpose": "Shared application-level agent templates and worker base classes - home for AppBase.py",
            "entity_types": ["Class"],
            "keywords": ["agent", "base_agent", "worker", "bot", "task_executor", "app_worker"],
            "imports": ["agentic_core.L3_orchestration.reasoning", "apps_shared.utils.AppBase"],
            "bases": ["CanonBaseAgent", "AppBase"],
            "examples": ["AppBase", "TaskWorker", "AsyncAppWorker", "StatefulAppAgent"],
            "canonical_files": ["AppBase.py"],
        },
        "models": {
            "purpose": "Shared Pydantic data models, Data Transfer Objects (DTOs), and domain-agnostic schemas",
            "entity_types": ["Class"],
            "keywords": ["model", "dto", "data", "struct", "object", "payload", "contract", "pydantic"],
            "imports": ["pydantic"],
            "bases": ["BaseModel"],
            "examples": ["UserProfile", "TaskResult", "CommonMetadata", "SharedDataPacket"],
        },
        "templates": {
            "purpose": "Shared UI/Text patterns, format schemas, and presentation layers",
            "entity_types": ["Class", "Dict"],
            "keywords": ["template", "format", "schema", "presentation", "layout", "pattern"],
            "imports": [],
            "bases": ["BaseTemplate"],
            "examples": ["CommonLayout", "StandardEmailFormat", "ReportTemplate"],
        },
        "config": {
            "purpose": "Shared configuration files, settings, and environment management",
            "entity_types": ["Class", "Dict", "Function"],
            "keywords": ["config", "settings", "environment", "configuration", "setup", "params"],
            "imports": ["os", "pathlib", "pydantic"],
            "bases": ["BaseSettings", "BaseConfig"],
            "examples": ["AppConfig", "EnvironmentSettings", "SharedParams"],
        },
        "core_components": {
            "purpose": "Core architectural components and foundational building blocks",
            "entity_types": ["Class"],
            "keywords": ["core", "component", "foundation", "building_block", "infrastructure"],
            "imports": [],
            "bases": ["BaseComponent"],
            "examples": ["EmbedJobDescription", "EmbedMessageTemplate", "EmbedRecipientProfile"],
        },
        "data": {
            "purpose": "Shared data structures, data access objects, and data management utilities",
            "entity_types": ["Class", "Function"],
            "keywords": ["data", "dao", "repository", "storage", "persistence", "cache"],
            "imports": ["typing", "pathlib"],
            "bases": ["BaseRepository", "BaseDAO"],
            "examples": ["DataCache", "SharedRepository", "DataAccessLayer"],
        },
        "tools": {
            "purpose": "Shared tooling, utilities, and helper functions for common operations",
            "entity_types": ["Class", "Function"],
            "keywords": ["tool", "utility", "helper", "function", "operation", "service"],
            "imports": [],
            "bases": [],
            "examples": ["FileTools", "StringTools", "DateTools", "ValidationTools"],
        },
        "enforcement": {
            "purpose": "Shared enforcement and policy logic used across applications",
            "entity_types": ["Class", "Function"],
            "keywords": ["enforce", "policy", "rule", "constraint", "guard"],
            "imports": [],
            "bases": [],
            "examples": ["PolicyEnforcer", "RuleEngine"],
        },
        "integration": {
            "purpose": "Integration adapters and connectors shared across applications",
            "entity_types": ["Class"],
            "keywords": ["integration", "adapter", "connector", "bridge", "gateway"],
            "imports": [],
            "bases": [],
            "examples": ["APIAdapter", "ServiceConnector"],
        },
        "llm": {
            "purpose": "Shared LLM interaction utilities and prompt management",
            "entity_types": ["Class", "Function"],
            "keywords": ["llm", "language_model", "prompt", "completion", "inference"],
            "imports": [],
            "bases": [],
            "examples": ["LLMClient", "PromptManager"],
        },
        "mixins": {
            "purpose": "Reusable mixin classes providing cross-cutting capabilities",
            "entity_types": ["Class"],
            "keywords": ["mixin", "trait", "capability", "behavior", "extension"],
            "imports": [],
            "bases": [],
            "examples": ["LoggingMixin", "CacheMixin", "ValidationMixin"],
        },
        "reasoning": {
            "purpose": "Shared reasoning and decision-making logic for application agents",
            "entity_types": ["Class"],
            "keywords": ["reasoning", "decision", "logic", "inference", "strategy"],
            "imports": [],
            "bases": [],
            "examples": ["ReasoningEngine", "DecisionModule"],
        },
        "scripts": {
            "purpose": "Shared utility scripts and automation helpers",
            "entity_types": ["Function"],
            "keywords": ["script", "automation", "runner", "task", "job"],
            "imports": [],
            "bases": [],
            "examples": ["setup_script", "migration_helper"],
        },
        "spine": {
            "purpose": "Core spine infrastructure connecting application layers",
            "entity_types": ["Class"],
            "keywords": ["spine", "core", "backbone", "infrastructure", "foundation"],
            "imports": [],
            "bases": [],
            "examples": ["AppSpine", "CoreSpine"],
        },
        "types": {
            "purpose": "Shared type definitions, TypedDicts, and type aliases",
            "entity_types": ["TypeAlias", "TypedDict", "Protocol"],
            "keywords": ["type", "typedef", "protocol", "alias", "dataclass"],
            "imports": ["typing"],
            "bases": ["TypedDict", "Protocol"],
            "examples": ["AppTypes", "SharedProtocols"],
        },
        "validators": {
            "purpose": "Shared validation logic and validator classes",
            "entity_types": ["Class", "Function"],
            "keywords": ["validator", "validate", "check", "verify", "constraint"],
            "imports": [],
            "bases": [],
            "examples": ["InputValidator", "SchemaValidator"],
        },
    },
}
SEMANTIC_L2_REGISTRY: Final[Mapping[str, Any]] = semantic_l2_registry
