"""Shared limits and defaults for the Redis MCP server."""

from __future__ import annotations

DEFAULT_HOST = "localhost"
DEFAULT_PORT = 6379
DEFAULT_DB = 0
DEFAULT_TIMEOUT_SECONDS = 5.0

MAX_NAMESPACE_TOP_N = 100
MAX_KEY_LIST_LIMIT = 200

NAMESPACE_SCAN_COUNT = 500
NAMESPACE_SCAN_CAP = 50_000

KEY_SCAN_COUNT = 100

MAX_STRING_BYTES = 65_536
MAX_HASH_FIELDS = 500
MAX_SET_MEMBERS = 500
MAX_LIST_ITEMS = 100
MAX_ZSET_ITEMS = 100

FLUSH_SCAN_COUNT = 200
FLUSH_SCAN_CAP = 5_000
FLUSH_SAMPLE_SIZE = 20
DELETE_PIPELINE_BATCH_SIZE = 500

SERVER_NAME = "redis-mcp"
SERVER_DESCRIPTION = "Redis cache/state inspection and bounded invalidation tools."
