"""
apps_shared/rag/hardening/__init__.py
RAG Hardening Modules — Ported from Legacy Resume Gen v61.27

Sovereign Canon — Full 40/40 Protection
"""

from __future__ import annotations

from .signal_quality_pipeline import (
    SourceTier,
    SignalQualityStage,
    PipelineDecision,
    ClaimVerificationMode,
    RetrievedDocument,
    StageResult,
    PipelineResult,
    HyDEConfig,
    SignalQualityConfig,
    SelfCritiqueResult,
    HopRefinementConfig,
    SignalQualityPipeline,
    HopRefinementStrategy,
    create_default_pipeline,
    create_strict_pipeline,
    create_permissive_pipeline,
)

from .validation_gates import (
    GatePolicy,
    GateDecision,
    GateSeverity,
    GateViolation,
    GateResult,
    GateContext,
    ValidationGateConfig,
    ValidationReport,
    ValidationGate,
    SummaryGroundingCheckGate,
    BulletHallucinationCheckGate,
    ThematicUniquenessGate,
    CreativeBriefAdherenceGate,
    HeaderIntegrityCheckGate,
    BulletProvenanceCheckGate,
    RedundancyCheckGate,
    HyphenPreservationGate,
    WordCountBalanceGate,
    BulletPunctuationGate,
    SummaryVoiceTenseGate,
    AgenticOutputValidationGate,
    ValidationGateRegistry,
    generate_validation_report,
    create_default_registry,
    create_strict_registry,
    create_minimal_registry,
)

from .preflight import (
    PreflightTestType,
    PreflightResult,
    PreflightAction,
    PreflightTestResult,
    PreflightReport,
    IterationTest,
    StructuralParseTest,
    FileManifestTest,
    DependencyTest,
    SchemaVersionTest,
    PreflightConfig,
    PreflightValidator,
    CapabilityTest,
    create_default_validator,
    create_strict_validator,
    create_minimal_validator,
    run_preflight_checks,
)

from .creative_brief import (
    VoiceType,
    TenseType,
    ProvenanceType,
    SourcingStrategy,
    WordCountConstraint,
    CharCountConstraint,
    StructureConstraint,
    ForbiddenPatternConstraint,
    VoiceConstraint,
    HeadlineBrief,
    ExecutiveSummaryBrief,
    ExperienceBulletsBrief,
    CompetenciesBrief,
    CoverLetterBrief,
    SkillsListBrief,
    CreativeBrief,
    create_default_brief,
    create_strict_brief,
    create_flexible_brief,
)

from .transaction_manager import (
    TransactionState,
    StepState,
    ExecutionTraceLevel,
    Checkpoint,
    StepResult,
    ExecutionTrace,
    DependencyNode,
    TransactionConfig,
    DependencyGraph,
    TransactionManager,
    WorkflowExecutor,
    create_default_transaction_manager,
    create_strict_transaction_manager,
    create_workflow_executor,
)

from .schema_transform import (
    TransformAction,
    ValidationPolicy,
    TransformResult,
    KeyMapping,
    EnumSpec,
    TransformViolation,
    TransformReport,
    SchemaTransformConfig,
    QASpec,
    SchemaTransformer,
    DataLossPreventionGate,
    ControlledVocabularyValidator,
    SchemaTransformationGate,
    create_default_transformer,
    create_strict_transformer,
    create_transformation_gate,
    RESUME_TRACKER_KEY_MAP,
)

__all__ = [
    # Signal Quality Pipeline
    "SourceTier",
    "SignalQualityStage",
    "PipelineDecision",
    "ClaimVerificationMode",
    "RetrievedDocument",
    "StageResult",
    "PipelineResult",
    "HyDEConfig",
    "SignalQualityConfig",
    "SelfCritiqueResult",
    "HopRefinementConfig",
    "SignalQualityPipeline",
    "HopRefinementStrategy",
    "create_default_pipeline",
    "create_strict_pipeline",
    "create_permissive_pipeline",
    # Validation Gates
    "GatePolicy",
    "GateDecision",
    "GateSeverity",
    "GateViolation",
    "GateResult",
    "GateContext",
    "ValidationGateConfig",
    "ValidationReport",
    "ValidationGate",
    "SummaryGroundingCheckGate",
    "BulletHallucinationCheckGate",
    "ThematicUniquenessGate",
    "CreativeBriefAdherenceGate",
    "HeaderIntegrityCheckGate",
    "BulletProvenanceCheckGate",
    "RedundancyCheckGate",
    "HyphenPreservationGate",
    "WordCountBalanceGate",
    "BulletPunctuationGate",
    "SummaryVoiceTenseGate",
    "AgenticOutputValidationGate",
    "ValidationGateRegistry",
    "generate_validation_report",
    "create_default_registry",
    "create_strict_registry",
    "create_minimal_registry",
    # Pre-Flight Validation
    "PreflightTestType",
    "PreflightResult",
    "PreflightAction",
    "PreflightTestResult",
    "PreflightReport",
    "IterationTest",
    "StructuralParseTest",
    "FileManifestTest",
    "DependencyTest",
    "SchemaVersionTest",
    "PreflightConfig",
    "PreflightValidator",
    "CapabilityTest",
    "create_default_validator",
    "create_strict_validator",
    "create_minimal_validator",
    "run_preflight_checks",
    # Creative Brief
    "VoiceType",
    "TenseType",
    "ProvenanceType",
    "SourcingStrategy",
    "WordCountConstraint",
    "CharCountConstraint",
    "StructureConstraint",
    "ForbiddenPatternConstraint",
    "VoiceConstraint",
    "HeadlineBrief",
    "ExecutiveSummaryBrief",
    "ExperienceBulletsBrief",
    "CompetenciesBrief",
    "CoverLetterBrief",
    "SkillsListBrief",
    "CreativeBrief",
    "create_default_brief",
    "create_strict_brief",
    "create_flexible_brief",
    # Transaction Manager
    "TransactionState",
    "StepState",
    "ExecutionTraceLevel",
    "Checkpoint",
    "StepResult",
    "ExecutionTrace",
    "DependencyNode",
    "TransactionConfig",
    "DependencyGraph",
    "TransactionManager",
    "WorkflowExecutor",
    "create_default_transaction_manager",
    "create_strict_transaction_manager",
    "create_workflow_executor",
    # Schema Transform
    "TransformAction",
    "ValidationPolicy",
    "TransformResult",
    "KeyMapping",
    "EnumSpec",
    "TransformViolation",
    "TransformReport",
    "SchemaTransformConfig",
    "QASpec",
    "SchemaTransformer",
    "DataLossPreventionGate",
    "ControlledVocabularyValidator",
    "SchemaTransformationGate",
    "create_default_transformer",
    "create_strict_transformer",
    "create_transformation_gate",
    "RESUME_TRACKER_KEY_MAP",
]