"""Auto-generated flattened view for design/test_design_validation_dag_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "design/test_design_validation_dag_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import pytest

from agent_orchestration_v10_7 import get_graph_app
from agentic_workflow.workflow_v10_7.dag_spec import (
    CONCEPTUAL_DAG,
    CONCEPTUAL_EDGES,
    all_concrete_nodes,
    conceptual_node_map,
)

EXPECTED_NODES = [
    "SafetyGuardStack",
    "StrategyStack",
    "RAGStack",
    "BulletStack",
    "DraftingStack",
    "QAStack",
    "HILInteractionStack",
]

EXPECTED_EDGES = [
    ("SafetyGuardStack", "StrategyStack"),
    ("StrategyStack", "RAGStack"),
    ("RAGStack", "BulletStack"),
    ("BulletStack", "DraftingStack"),
    ("DraftingStack", "QAStack"),
    ("QAStack", "HILInteractionStack"),
]

EXPECTED_ORDER = [
    "SafetyGuardStack",
    "StrategyStack",
    "RAGStack",
    "BulletStack",
    "DraftingStack",
    "QAStack",
    "HILInteractionStack",
]


@pytest.fixture()
def compiled_workflow(workflow_context):
    workflow_context.config.agent_stacks.enable_hil_stack = True
    workflow = get_graph_app(
        checkpointer=None,
        workflow_context=workflow_context,
        enable_hil=True,
    )
    return workflow


def _runtime_node_names(compiled_workflow):
    return set(compiled_workflow.nodes.keys())


@pytest.mark.design
def test_conceptual_nodes_match_specification_order():
    names = [node.name for node in CONCEPTUAL_DAG]
    assert names == EXPECTED_ORDER, "Conceptual DAG order drifted from spec"


@pytest.mark.design
def test_conceptual_node_names_match_expected_set():
    assert set(node.name for node in CONCEPTUAL_DAG) == set(EXPECTED_NODES), (
        "Conceptual DAG names must match v10.7 design document"
    )


@pytest.mark.design
def test_conceptual_edges_match_design_doc():
    lookup = {name: idx for idx, name in enumerate(EXPECTED_ORDER)}
    for src, dst in EXPECTED_EDGES:
        assert lookup[src] < lookup[dst], f"{src} must precede {dst}"


@pytest.mark.design
def test_conceptual_edge_spec_matches_expected():
    assert CONCEPTUAL_EDGES == EXPECTED_EDGES


@pytest.mark.design
def test_all_conceptual_nodes_have_concrete_mappings():
    for node in CONCEPTUAL_DAG:
        assert node.concrete_nodes, f"Conceptual node {node.name} has no concrete mapping"


@pytest.mark.design
def test_conceptual_nodes_exist_in_runtime(compiled_workflow):
    runtime_nodes = _runtime_node_names(compiled_workflow)
    for node in CONCEPTUAL_DAG:
        missing = set(node.concrete_nodes) - runtime_nodes
        assert not missing, f"{node.name} missing runtime nodes: {sorted(missing)}"


@pytest.mark.design
def test_runtime_nodes_align_with_conceptual_spec(compiled_workflow):
    runtime_nodes = _runtime_node_names(compiled_workflow)
    spec_nodes = all_concrete_nodes()
    missing = spec_nodes - runtime_nodes
    extra = runtime_nodes - spec_nodes
    assert not missing, f"Spec nodes not found in runtime graph: {sorted(missing)}"
    assert not extra, f"Runtime nodes missing from conceptual spec: {sorted(extra)}"


@pytest.mark.design
def test_conceptual_lookup_contains_all_nodes():
    lookup = conceptual_node_map()
    for name in EXPECTED_NODES:
        assert name in lookup, f"Missing conceptual node mapping for {name}"
"""
}

ORIGINAL_MODULE_NAME = "tests.design.test_design_validation_dag_v10_7"
FLAT_MODULE_NAME = "tests_flat.design__test_design_validation_dag_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
