"""Auto-generated flattened view for core/test_runtime_timeout_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "core/test_runtime_timeout_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import asyncio

import pytest

from core_v10_7 import (
    ModelAPIError,
    WorkflowTimeoutError,
    exponential_backoff_retry,
    get_timeout_decorator,
)


@pytest.mark.asyncio
async def test_node_timeout_raises_workflow_timeout_error():
    timeout = get_timeout_decorator(0.01)

    @timeout
    async def slow_node():
        await asyncio.sleep(0.05)

    with pytest.raises(WorkflowTimeoutError):
        await slow_node()


@pytest.mark.asyncio
async def test_exponential_backoff_retry_logs_and_retries(caplog):
    attempts = {"count": 0}

    @exponential_backoff_retry(max_retries=2, initial_delay=0)
    async def flaky_node():
        attempts["count"] += 1
        if attempts["count"] < 3:
            raise ModelAPIError("temporary failure")
        return "ok"

    caplog.set_level("WARNING", logger="core_v10_7")
    result = await flaky_node()

    assert result == "ok"
    assert attempts["count"] == 3
    assert any("failed (Attempt" in rec.message for rec in caplog.records)
"""
}

ORIGINAL_MODULE_NAME = "tests.core.test_runtime_timeout_v10_7"
FLAT_MODULE_NAME = "tests_flat.core__test_runtime_timeout_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
