"""Auto-generated flattened view for integration/test_end_to_end_paths_v10_7.py.

Do not edit this file directly; run tools/flatten_tests.py instead."""
from __future__ import annotations

import sys
import types
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "tests"
OUTPUT_ROOT = REPO_ROOT / "tests_flat"
SOURCE_REL_PATH = "integration/test_end_to_end_paths_v10_7.py"
SOURCE_PATH = REPO_ROOT / SOURCE_REL_PATH

# Embedded canonical source
EMBEDDED_SOURCES = {
    SOURCE_REL_PATH: """import pytest
from workflow.runner import run_workflow

@pytest.mark.parametrize("resume,jd,expect_keys", [
    ("Jane Doe","Chief AI Officer", ["summary"]),
    ("John Smith","Director, AI", ["summary"]),
    ("LowConf","Analyst", ["events"]),
    ("Ambiguous","Unknown", ["events"]),
])
def test_full_run_variants(resume,jd,expect_keys):
    out = run_workflow({"resume": resume, "jd": jd})
    for k in expect_keys: assert k in out

@pytest.mark.parametrize("scenario", ["batch-small","batch-large","parallel-merge","hil-trigger"])
def test_scenarios_collectively(scenario):
    out = run_workflow({"resume": scenario, "jd":"scenario"})
    assert isinstance(out, dict)
"""
}

ORIGINAL_MODULE_NAME = "tests.integration.test_end_to_end_paths_v10_7"
FLAT_MODULE_NAME = "tests_flat.integration__test_end_to_end_paths_v10_7"


def _ensure_import_roots() -> None:
    root = str(REPO_ROOT)
    flat_root = str(OUTPUT_ROOT)
    for candidate in (root, flat_root):
        if candidate not in sys.path:
            sys.path.insert(0, candidate)
    tests_pkg = sys.modules.setdefault("tests", types.ModuleType("tests"))
    tests_pkg.__path__ = list({*(getattr(tests_pkg, "__path__", []) or []), str(SOURCE_ROOT), flat_root})
    tests_flat_pkg = sys.modules.setdefault("tests_flat", types.ModuleType("tests_flat"))
    tests_flat_pkg.__path__ = list({*(getattr(tests_flat_pkg, "__path__", []) or []), flat_root})


def _materialize_module() -> types.ModuleType:
    module = types.ModuleType(ORIGINAL_MODULE_NAME)
    module.__file__ = str(SOURCE_PATH)
    module.__package__ = ORIGINAL_MODULE_NAME.rpartition(".")[0]
    exec(compile(EMBEDDED_SOURCES[SOURCE_REL_PATH], str(SOURCE_PATH), "exec"), module.__dict__)
    sys.modules[ORIGINAL_MODULE_NAME] = module
    sys.modules[FLAT_MODULE_NAME] = module
    return module


_ensure_import_roots()
_embedded_module = _materialize_module()
for _name, _value in list(_embedded_module.__dict__.items()):
    if _name == "__builtins__":
        continue
    globals()[_name] = _value
