"""Semantic type classification maps for ADG edges."""


# Semantic type classification map — maps (edge_kind, relation_type) to
# semantic_type. Edges with semantic_type already set are left untouched.
_SEMANTIC_TYPE_MAP: dict[tuple[str, str], str] = {
    # imports
    ("internal", "imports"): "imports_module",
    ("external", "imports"): "imports_external",
    ("lazy_import", "imports"): "imports_lazy",
    ("optional_import", "imports"): "imports_optional",
    ("import", "imports"): "imports_module",
    ("type_checking_import", "imports"): "imports_type_only",
    ("dead_import", "dead_imports"): "dead_import",
    ("star_import", "imports"): "imports_star",
    # reads / writes
    ("type_annotation", "reads_from"): "reads_type_annotation",
    ("read", "reads_through"): "reads_through",
    ("write", "writes_to"): "writes_variable",
    ("write", "writes_through"): "writes_through",
    ("reads_env", "reads_env"): "reads_environment",
    ("reads_runtime_state", "reads_runtime_state"): "reads_runtime_state",
    ("reads_policy_state", "reads_policy_state"): "reads_policy_state",
    ("reads_secret", "reads_secret"): "reads_secret",
    ("reads_config", "reads_governed_config"): "reads_config",
    ("governed_config_read", "reads_governed_config"): "reads_config",
    # calls / dispatch
    ("call", "calls"): "invokes_function",
    ("call", "routes_through"): "routes_through",
    ("composition", "instantiates"): "instantiates_class",
    ("agent_execution", "dispatches_execution_plan"): "dispatches_execution",
    ("agent_dispatch", "agent_executes_agent"): "dispatches_agent",
    # structure
    ("export", "exports"): "exports_symbol",
    ("decorator", "decorated_by"): "decorator_application",
    ("layer_membership", "belongs_to_layer"): "layer_membership",
    ("unresolved", "implements"): "implements_interface",
    ("external", "implements"): "implements_external",
    # test
    ("test_definition", "defines_test_suite"): "defines_test_suite",
    ("test_definition", "defines_test_case"): "defines_test_case",
    ("test_definition", "defines_invariant"): "defines_invariant",
    ("test_execution", "emits_test_result"): "emits_test_result",
    ("test_execution", "detects_regression"): "detects_regression",
    ("test_execution", "gates_promotion"): "gates_promotion",
    ("test_execution", "links_to_execution_trace"): "links_test_to_trace",
    ("test_execution", "records_validation_outcome"): "records_validation",
    ("import", "covers"): "test_coverage",
    # governance / safety
    ("import", "violates"): "layer_violation",
    ("policy_validation", "policy_verification"): "policy_verification",
    ("safety_plane_validation", "validated_by_safety_plane"): "safety_validation",
    ("guardrail_execution", "applies_guardrail"): "guardrail_enforcement",
    ("execution_trace_record", "records_execution_trace"): "execution_trace",
    ("policy_hash_link", "references_policy_hash"): "policy_hash_reference",
    # state / lineage
    ("state_lineage", "mutation_signature"): "mutation_signature",
    ("state_lineage", "parent_snapshot_hash"): "parent_snapshot",
    ("runtime_state_snapshot", "snapshots_state"): "snapshots_state",
    ("context_pull", "pulls_context"): "pulls_context",
    # determinism / replay
    ("determinism_digest_emit", "emits_determinism_digest"): "determinism_digest",
    # side effects / non-determinism
    ("wall_clock_use", "uses_wall_clock"): "nondeterminism_clock",
    ("uuid_use", "uses_uuid"): "nondeterminism_uuid",
    ("random_use", "uses_random"): "nondeterminism_random",
    ("dynamic_getattr", "invokes_getattr_dynamic"): "dynamic_dispatch",
    ("eval_call", "invokes_eval"): "dynamic_eval",
    ("importlib_call", "invokes_importlib"): "dynamic_import",
    # antipatterns
    ("broad_exception_catch", "antipattern"): "antipattern_broad_except",
    ("retry_without_backoff", "antipattern"): "antipattern_retry",
    ("silent_exception_swallow", "antipattern"): "antipattern_silent_swallow",
    ("return_none_swallow", "antipattern"): "antipattern_return_none",
    ("log_and_swallow", "antipattern"): "antipattern_log_swallow",
    ("global_state_mutation", "antipattern"): "antipattern_global_mutation",
    ("blocking_call_in_async", "antipattern"): "antipattern_blocking_async",
    ("duplicate_method", "antipattern"): "antipattern_duplicate",
    # prompt / learning
    ("prompt_generation", "generates_prompt"): "generates_prompt",
    ("metric_emission", "emits_metric_event"): "emits_metric",
    ("path_route", "routes_path"): "routes_path",
    ("credential_access", "accesses_credential"): "accesses_credential",
    ("unreachable_after_raise", "unreachable_after_raise"): "unreachable_code",
    # orchestration
    ("healing_dispatch", "dispatches_healing_run"): "healing_dispatch",
    ("diff_package", "signs_execution_trace"): "signs_trace",
    ("replay_patch", "emits_replay_key"): "replay_key",
    ("replay_key_emit", "emits_replay_key"): "replay_key",
    ("uwg_termination", "execution_terminates_at_uwg"): "uwg_termination",
    ("sandbox_entry", "enters_sandbox"): "sandbox_entry",
    ("budget_grant", "grants_resource"): "budget_grant",
    ("boundary_accept", "verifies_boundary"): "boundary_verification",
    ("hitl_escalation", "escalates_to_human"): "hitl_escalation",
    ("confidence_gate", "gated_by_confidence"): "confidence_gate",
    ("network", "external_http_call"): "external_http",
    ("http_egress_call", "external_http_call"): "external_http",
    ("io_transcript", "records_io_transcript"): "io_transcript",
    ("io_hard_fail", "hard_fails_io"): "io_hard_fail",
    ("embedding_pipeline", "embeds_into"): "embedding_pipeline",
    ("embedding", "stores_embedding"): "embedding_store",
    ("embedding_store", "stores_embedding"): "embedding_store",
    ("chunking_pipeline", "chunks_into"): "chunking_pipeline",
    ("retrieval_pipeline", "retrieves_via"): "retrieval_pipeline",
    ("llm_gateway_validation", "validated_by_llm_gateway"): "llm_gateway_validation",
    ("registry_validation", "validated_by_registry"): "registry_validation",
    ("registry_check", "checks_agent_registry"): "registry_check",
    ("verification", "verifies_policy"): "policy_verification_check",
    ("authorization", "authorize_and_execute"): "authorization",
    ("execution_authorization", "authorize_and_execute"): "authorization",
    ("routing_commit", "proposal_commits_routing"): "routing_commit",
    ("prompt_template_link", "prompt_template_used_by"): "prompt_template",
    ("prompt_consumption", "prompt_template_used_by"): "prompt_template",
    ("injection_source_link", "instruction_injection_source"): "injection_source",
    ("preference_pair_link", "produces_preference_pair"): "preference_pair",
    ("human_review_gate", "requires_human_review"): "human_review",
    ("trace_prompt_link", "traces_prompt_lineage"): "prompt_trace",
    ("context_freeze", "freezes_context"): "context_freeze",
    ("path_stall", "stalls_path"): "path_stall",
    ("path_safety_reentry", "reenters_path_safely"): "path_safety_reentry",
    ("path_vigilance_reroute", "reroutes_vigilance"): "vigilance_reroute",
    ("determinism", "emits_determinism_digest"): "determinism_digest",
    ("determinism_seed", "seeds_determinism"): "determinism_seed",
    ("antipattern_classification", "classifies_antipattern"): "classifies_antipattern",
    ("proof_comparison", "compares_proof"): "proof_comparison",
    ("test_invariant", "defines_invariant"): "defines_invariant",
    ("optimization_commit", "commits_optimization"): "optimization_commit",
    ("healer_action", "confirms_heal"): "healer_confirm",
    ("capability_token_issue", "issues_capability_token"): "capability_token",
    ("capability_validation", "validates_capability"): "capability_validation",
    ("work_contract_stamp", "stamps_work_contract"): "work_contract",
    ("config_schema_validation", "validates_config_schema"): "config_schema_validation",
    ("dpo_build", "produces_preference_pair"): "dpo_build",
    ("eval_score", "captures_evaluation_metric"): "eval_score",
    ("blast_radius_check", "checks_blast_radius"): "blast_radius",
    ("guardrail", "applies_guardrail"): "guardrail_enforcement",
    ("policy_verification", "verifies_policy"): "policy_verification_check",
    ("workflow_orchestration", "orchestrates_workflow"): "workflow_orchestration",
    ("policy_state_observation", "observes_policy_state"): "policy_observation",
    ("dynamic_exec", "invokes_exec"): "dynamic_exec",
    # last 2 unmapped combos
    ("layer_membership", "belongs_to_layer"): "layer_membership",
    ("import", "violates"): "layer_violation",
    # Phase 3 edge types + W1c module definition edges
    ("module_definition", "decomposes_into"): "module_definition",
    ("decomposition", "decomposes_into"): "block_decomposition",
    ("test_linkage", "tests_execution_of"): "test_execution_linkage",
    ("violation_propagation", "violation_propagates_through"): "violation_trace",
    # Gap-5 closure: explicit semantic mappings for remaining raw-fallback combos
    ("reads_config", "reads_config"): "reads_governed_config",
    ("healing_dispatch", "orchestrates_healing"): "orchestrates_healing",
    ("dpo_build", "builds_dpo_batch"): "dpo_batch_build",
    ("eval_score", "scores_groundedness"): "groundedness_score",
    ("replay_patch", "patches_time"): "replay_time_patch",
    ("replay_patch", "guards_replay"): "replay_guard",
    ("diff_package", "packages_diff"): "diff_packaging",
    ("blast_radius_check", "validates_blast_radius"): "blast_radius_validation",
    ("verification", "policy_verification"): "policy_verification_inline",
    ("embedding_pipeline", "stores_embedding"): "embedding_storage",
    ("network", "invokes_provider"): "provider_invocation",
    ("runtime_state_snapshot", "observes_runtime_state"): "runtime_observation",
    ("determinism_seed", "seeds_rng"): "rng_seed",
    ("io_transcript", "transcripts_response"): "response_transcript",
    ("guardrail", "guardian_gate"): "guardian_gate_check",
    ("io_transcript", "intercepts_io"): "io_interception",
    ("duplicate_method", "duplicate_method"): "antipattern_duplicate_method",
    ("antipattern_classification", "registers_antipattern"): "antipattern_registration",
    ("path_stall", "forces_stall"): "forced_stall",
    ("prompt_consumption", "consumes_prompt"): "prompt_consumption",
    ("path_vigilance_reroute", "vigilance_reroute"): "vigilance_path_reroute",
    ("trace_prompt_link", "triggered_telemetry"): "telemetry_trigger",
    ("boundary_accept", "certifies_envelope"): "envelope_certification",
    ("io_hard_fail", "hard_fails_untranscripted"): "untranscripted_hard_fail",
    ("chunking_pipeline", "chunks_into"): "chunking_pipeline",
    ("confidence_gate", "gated_by_confidence"): "confidence_gate",
    ("config_schema_validation", "validates_config_schema"): "config_schema_validation",
    ("context_pull", "unfreezes_context"): "context_unfreeze",
    ("capability_validation", "validates_agent_capability"): "agent_capability_validation",
    ("dynamic_exec", "invokes_dynamic"): "dynamic_invocation",
}

# Fallback: classify by relation_type alone when (edge_kind, relation_type) not in map
_SEMANTIC_FALLBACK: dict[str, str] = {
    "imports": "imports_module",
    "calls": "invokes_function",
    "reads_from": "reads_data",
    "writes_to": "writes_data",
    "exports": "exports_symbol",
    "implements": "implements_interface",
    "decorated_by": "decorator_application",
    "belongs_to_layer": "layer_membership",
    "covers": "test_coverage",
    "violates": "layer_violation",
    "antipattern": "antipattern_detected",
    "dead_imports": "dead_import",
    "decomposes_into": "block_decomposition",
    "tests_execution_of": "test_execution_linkage",
    "violation_propagates_through": "violation_trace",
    # Add missing relation_type fallbacks to prevent raw edge kind fallbacks
    "reads_runtime_state": "reads_runtime_state",
    "reads_policy_state": "reads_policy_state",
    "reads_secret": "reads_secret",
    "authorization": "authorization",
    "routing_commit": "routing_commit",
    "llm_gateway_validation": "llm_gateway_validation",
    "registry_validation": "registry_validation",
    "prompt_consumption": "prompt_consumption",
    "sandbox_entry": "sandbox_entry",
    "uwg_termination": "uwg_termination",
    "embedding_store": "embedding_store",
    "budget_grant": "budget_grant",
    "hitl_escalation": "hitl_escalation",
    "retrieves_via": "retrieval_pipeline",
    "embeds_into": "embedding_pipeline",
    "authorize_and_execute": "authorization",
    "proposal_commits_routing": "routing_commit",
    "validated_by_llm_gateway": "llm_gateway_validation",
    "validated_by_registry": "registry_validation",
    "consumes_prompt": "prompt_consumption",
    "enters_sandbox": "sandbox_entry",
    "execution_terminates_at_uwg": "uwg_termination",
    "stores_embedding": "embedding_store",
    "grants_resource": "budget_grant",
    "escalates_to_human": "hitl_escalation",
    "chunks_into": "chunking_pipeline",
    "gated_by_confidence": "confidence_gate",
    "validates_config_schema": "config_schema_validation",
}

__all__ = [
    "_SEMANTIC_TYPE_MAP",
    "_SEMANTIC_FALLBACK",
]
