"""Sandbox vs UWG-durable artifact writer for the proof harness.

Per the prompt §4G, every artifact emitted by an apps_* run MUST be classified
as one of:

* ``SANDBOX_OUTPUT``     — runtime evidence; lives under
  ``artifacts/runtime/apps_proof/.../sandbox/``; no system-of-record commit
* ``UWG_DURABLE``        — durable system-of-record state; routed THROUGH a
  UWG facade; contains a commit_request reference
* ``PROOF_ARTIFACT``     — the proof harness's own metadata (packets, traces)

This module exposes two functions used by per-app scenarios:

* :func:`write_sandbox_artifact` — emits a sandbox file and an
  :class:`ArtifactRecord` with classification ``SANDBOX_OUTPUT``
* :func:`request_uwg_commit`     — captures the intent to commit durable state.
  Returns an :class:`ArtifactRecord` with classification ``UWG_DURABLE`` and a
  ``commit_request`` payload — but does NOT bypass the UWG facade. In W6 this
  is a structural placeholder; the real UWG runtime is its own subsystem.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from apps_shared.proof.proof_contracts import (
    CLASSIFICATION_SANDBOX_OUTPUT,
    CLASSIFICATION_UWG_DURABLE,
    ArtifactRecord,
    sha256_of,
    sha256_of_file,
)


@dataclass(frozen=True)
class CommitRequest:
    """A request to commit a durable artifact through UWG.

    Generated by :func:`request_uwg_commit`. The runtime UWG (out of harness
    scope) is responsible for rejecting requests that violate write
    sovereignty. The proof harness only records the request — it does not
    invoke the UWG.
    """

    app_id: str
    run_id: str
    artifact_path: str
    content_hash: str
    write_authority: str
    intent: str

    def to_dict(self) -> dict[str, Any]:
        return {
            "app_id": self.app_id,
            "run_id": self.run_id,
            "artifact_path": self.artifact_path,
            "content_hash": self.content_hash,
            "write_authority": self.write_authority,
            "intent": self.intent,
        }


_SAFE_ARTIFACT_ID_CHARS = frozenset(
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-."
)


def _validate_artifact_id(artifact_id: str) -> str:
    """Reject path-traversal attempts in artifact_id.

    BUG-FIX (2026-04-26 audit pass 2 / #8): pathlib's ``/`` operator
    blindly joins, so ``sandbox_dir / "../../etc/passwd"`` resolves
    outside the sandbox. The current callers pass hardcoded ids, but the
    function signature is public and callers may eventually feed
    request-derived strings. Reject anything that isn't a tight allowlist.
    """
    if not artifact_id:
        raise ValueError("artifact_id must be non-empty")
    if len(artifact_id) > 128:
        raise ValueError(f"artifact_id too long: {len(artifact_id)} > 128")
    if any(ch not in _SAFE_ARTIFACT_ID_CHARS for ch in artifact_id):
        bad = [ch for ch in set(artifact_id) if ch not in _SAFE_ARTIFACT_ID_CHARS]
        raise ValueError(
            f"artifact_id contains forbidden characters: {bad!r}; "
            "allowed: [A-Za-z0-9._-]"
        )
    if artifact_id.startswith(".") or ".." in artifact_id:
        raise ValueError(f"artifact_id may not start with '.' or contain '..': {artifact_id!r}")
    return artifact_id


def write_sandbox_artifact(
    *,
    app_id: str,
    run_id: str,
    trace_id: str,
    producing_span_id: str,
    export_root: Path,
    artifact_id: str,
    payload: Any,
) -> ArtifactRecord:
    """Write a sandbox artifact and return its classified record.

    Sandbox artifacts:
      * Live under ``export_root/sandbox/<app_id>/<artifact_id>.json``
      * Are NEVER routed through UWG
      * Are NEVER part of system-of-record state
      * MUST be classified ``SANDBOX_OUTPUT``
    """
    artifact_id = _validate_artifact_id(artifact_id)
    sandbox_dir = export_root / "sandbox" / app_id
    sandbox_dir.mkdir(parents=True, exist_ok=True)
    path = sandbox_dir / f"{artifact_id}.json"
    body = json.dumps(payload, sort_keys=True, indent=2, default=str)
    path.write_text(body, encoding="utf-8")
    return ArtifactRecord(
        artifact_id=artifact_id,
        app_id=app_id,
        run_id=run_id,
        trace_id=trace_id,
        producing_span_id=producing_span_id,
        classification=CLASSIFICATION_SANDBOX_OUTPUT,
        durable=False,
        path=str(path.relative_to(export_root)).replace("\\", "/"),
        content_hash=sha256_of_file(path),
    )


def request_uwg_commit(
    *,
    app_id: str,
    run_id: str,
    trace_id: str,
    producing_span_id: str,
    export_root: Path,
    artifact_id: str,
    payload: Any,
    intent: str,
    write_authority: str = "PENDING_UWG_APPROVAL",
) -> tuple[ArtifactRecord, CommitRequest]:
    """Record a UWG commit request without performing the commit.

    The proof harness CANNOT commit durable state — that's the runtime UWG's
    responsibility. This function records the *intent* + content hash so that:

      * write sovereignty validators can confirm the intent ROUTED through
        the recorded path (not bypassing UWG)
      * exit gates can verify the request was authorized
      * negative controls can prove tampering with the commit body changes
        the content_hash

    Records a :class:`CommitRequest` to prove that any future durable write
    must route through the documented path.
    """
    artifact_id = _validate_artifact_id(artifact_id)
    pending_dir = export_root / "uwg_pending" / app_id
    pending_dir.mkdir(parents=True, exist_ok=True)
    path = pending_dir / f"{artifact_id}.json"
    body = json.dumps(payload, sort_keys=True, indent=2, default=str)
    path.write_text(body, encoding="utf-8")
    content_hash = sha256_of_file(path)

    record = ArtifactRecord(
        artifact_id=artifact_id,
        app_id=app_id,
        run_id=run_id,
        trace_id=trace_id,
        producing_span_id=producing_span_id,
        classification=CLASSIFICATION_UWG_DURABLE,
        durable=True,
        path=str(path.relative_to(export_root)).replace("\\", "/"),
        content_hash=content_hash,
    )
    commit_request = CommitRequest(
        app_id=app_id,
        run_id=run_id,
        artifact_path=record.path,
        content_hash=content_hash,
        write_authority=write_authority,
        intent=intent,
    )

    # Also write the commit request envelope alongside the artifact so the
    # apps_underwriting_ai-style gate can prove it routes through the
    # documented path.
    request_path = pending_dir / f"{artifact_id}.commit_request.json"
    request_path.write_text(
        json.dumps(commit_request.to_dict(), sort_keys=True, indent=2),
        encoding="utf-8",
    )

    return record, commit_request


__all__ = [
    "CommitRequest",
    "write_sandbox_artifact",
    "request_uwg_commit",
]
